### ISSUE TITLE
[ERROR] sentry.rules: Failed to fetch some GroupRuleStatuses in RuleProcessor

### ISSUE THREAD

**Issue by n0tsaved** [getsentry/self-hosted#1182]
### Version

21.11.0

### Steps to Reproduce

I deployed my customized installation mainly following the docker-compose.yml guidelines but with some replicated services (kafka, postgresql, redis, memcached, relay and *all* of the sentry containers). It seems I mostly did right since everything is up and running, so I wanted to stress-test the installation to get an idea of the load it could handle. 

I launched this script to fire 50 events per second

```
NB_EVENTS=50
export SENTRY_DSN='https://xxxxxxxxxxxxxxxxxxx@xxxxxxxxxxxxxx:443/1'
while true
do
  echo "sending $NB_EVENTS events..."
  for i in {1..$NB_EVENTS}
  do
    sentry-cli send-event -m "[Random-Error] $(echo $RANDOM | md5sum | head -c 20; echo;)" > /dev/null 2>&1 &
  done
  wait
  sleep 1
done
```

### Expected Result

Everything works fine, maybe some events discarded

### Actual Result

Everything looks fine, except lots of these logs in the worker container and lots of missing event from dashboard (but maybe this is normal since many similar events might be discarded)
```
15:39:27 [ERROR] sentry.rules: Failed to fetch some GroupRuleStatuses in RuleProcessor (missing_rule_ids={1} group_id=258)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 46, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/post_process.py", line 342, in post_process_group
    for callback, futures in rp.apply():
  File "/usr/local/lib/python3.8/site-packages/sentry/rules/processor.py", line 245, in apply
    self.apply_rule(rule, rule_statuses[rule.id])
KeyError: 1
15:39:27 [ERROR] celery.app.trace: Task sentry.tasks.post_process.post_process_group[ee00d37e-c123-4229-b81f-58d949ec6b7e] raised unexpected: KeyError(1) (data={'hostname': 'sentry01', 'id': 'ee00d37e-c123-4229-b81f-58d949ec6b7e', 'name': 'sentry.tasks.post_process.post_process_group', 'exc': 'KeyError(1)', 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 46, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/post_process.py", line 342, in post_process_group\n    for callback, futures in rp.apply():\n  File "/usr/local/lib/python3.8/site-packages/sentry/rules/processor.py", line 245, in apply\n    self.apply_rule(rule, rule_statuses[rule.id])\nKeyError: 1\n', 'args': '()', 'kwargs': "{'is_new': True, 'is_regression': False, 'is_new_group_environment': True, 'primary_hash': '2e6c00c421338e5d48fb5582b55b9e8b', 'cache_key': 'e:75ec1f582463405492927166a2eed9ab:1', 'group_id': 258}", 'description': 'raised unexpected', 'internal': False})
```

**Comment by chadwhitacre** [comment]
Love the limits testing. I know there is some sampling but I'm not super-familiar with the specifics and I don't know if it manifests as a `KeyError`, doesn't seem like that would be the design. Can you replicate this result against a stock `self-hosted` install? You might have some component misconfigured in your custom setup.

**Comment by n0tsaved** [comment]
Thanks for the reply. I did run this test against a stock `self-hosted` install and I don't see any Error in the log, while the amount of events showed on the dashboard is very similar.

Any hint of which part of my deployment is misconfigured?

**Comment by chadwhitacre** [comment]
Oof, no idea here. If you figure something out feel free to post back here for posterity.

Good luck! :)

**Comment by n0tsaved** [comment]
Little update.

I think I figured out the cause. As I mentioned earlier I'm using in my setup replicated postgres (1 master and 1 slave).

This is my setup in sentry.conf.py
```
DATABASES = {
    "default": {
        "ENGINE":   "sentry.db.postgres",
        'NAME':     "sentry",
        'USER':     "sentry",
        'PASSWORD': "************",
        "HOST":     "172.25.1.103",
        "PORT":     "5432",
    },
    "replica1": {
        "ENGINE":   "sentry.db.postgres",
        'NAME':     "sentry",
        'USER':     "sentry",
        'PASSWORD': "***********",
        "HOST":     "172.25.1.137",
        "PORT":     "5432",
    },
}

DATABASE_ROUTERS = [ 'Router.PrimaryReplicaRouter' ]
```

I'm using a django router to balance the reads between the 2 instances
```
import random

class PrimaryReplicaRouter(object):
    def db_for_read(self, model, **hints):
        choice_list = [ 
            "default",
            "replica1",
        ]
#        return random.choice(choice_list)
        return 'default'

    def db_for_write(self, model, **hints):
        """
        Writes always go to primary.
        """
        return 'default'

    def allow_relation(self, obj1, obj2, **hints):
        """
        Relations between objects are allowed if both objects are
        in the primary/replica pool.
        """
        db_list = (
            "default",
            "replica1",
        )
        if obj1._state.db in db_list and obj2._state.db in db_list:
            return True
        return None

    def allow_migrate(self, db, app_label, model_name=None, **hints):
        """
        All non-auth models end up in this pool.
        """
        return db == 'default'
```

It turns out that when the read are forwarded to the replica they are not present yet most of the time.
I'll try to tune out replication on my pgsqls or instruct the router to go 'default' if the model is 'sentry_grouprulestatus'.

Any suggestion?
