### ISSUE TITLE
Duplicated auth0 application label for django

### ISSUE THREAD

**Issue by markdensen403** [getsentry/self-hosted#1187]
### Version

21.11.0

### Steps to Reproduce

1. install any build of sentry
2. try to run commands through docker-compose
 > docker-compose run --rm -T -e SENTRY_LOG_LEVEL=CRITICAL web
 2. report and problems that log.

### Expected Result

access to web through docker-compose

### Actual Result

\# docker-compose run --rm -T -e SENTRY_LOG_LEVEL=CRITICAL web
Creating sentry-self-hosted_web_run ... done
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 188, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 28, in inner
    configure()
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 124, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/settings.py", line 153, in configure
    initialize_app(
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py", line 353, in initialize_app
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: auth0
ERROR: 1

**Comment by markdensen403** [comment]
Sorry if this report is poorly made, I rarely use github and use the issues tab.

**Comment by aminvakil** [comment]
How have you installed sentry?

**Comment by markdensen403** [comment]
I haven't even gotten to install sentry, the docker fails to run and doesn't pass the health check, because of this specific error.

**Comment by chadwhitacre** [comment]
Do you have another web container already running?

**Comment by markdensen403** [comment]
Nope, I've completely removed every docker and purged most before reinstalling a few times, seeing if that might help fix things, but it just keeps failing.

**Comment by chadwhitacre** [comment]
@markdensen403 Can you paste debug output of your installation in [a gist](https://gist.github.com/)?

```
DEBUG=1 ./install.sh --no-user-prompt
```

**Comment by markdensen403** [comment]
@chadwhitacre [https://gist.github.com/markdensen403/a1533f42b9cdd4d772087028307d8b15](https://gist.github.com/markdensen403/a1533f42b9cdd4d772087028307d8b15) Just got around to doing a debug installation

**Comment by chadwhitacre** [comment]
Found [this](https://forum.sentry.io/t/sentry-install-fails-with-application-labels-arent-unique-duplicate-auth0/12921/2) by searching for “[sentry "Application labels aren't unique, duplicates: auth0"](https://www.google.com/search?q=sentry+%22Application+labels+aren%27t+unique%2C+duplicates%3A+auth0%22)”:

> you seem to have two separate auth0 plugins installed and they are now conflicting.

Can you try what Mason tried there and see if you get unstuck? Or otherwise look into this possibility that you have two auth0 plugins installed?

> I will clean up and start from scratch and see if I can reproduce it.
