### ISSUE TITLE
Performance data is no longer showing

### ISSUE THREAD

**Issue by brandonhilkert** [getsentry/self-hosted#1249]
### Version

21.12.0

### Steps to Reproduce

1. I set up a new install
2. We started seeing performance data for all projects
3. We overwhelmed the machine with data coming in to the system due to a few very busy projects
4. Performance data stopped showing even though the clients are still sending
5. I attempted to `docker-compose restart` everything but behavior persisted

### Expected Result

Performance data would continue to report in the UI.

### Actual Result

<img width="1272" alt="Screen Shot 2022-01-10 at 11 48 58 AM" src="https://user-images.githubusercontent.com/744212/148829660-b9a85be4-a85e-41a2-8063-2cc9cf507799.png">

`snuba-sessions-consumer` seems normal:
```
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:13:19,290 Completed processing <Batch: 2 messages, open for 0.81 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:13:20,202 Completed processing <Batch: 2 messages, open for 0.91 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:13:21,211 Completed processing <Batch: 2 messages, open for 1.01 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:13:22,230 Completed processing <Batch: 2 messages, open for 1.02 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:13:32,603 Completed processing <Batch: 2 messages, open for 1.01 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:13:39,878 Completed processing <Batch: 2 messages, open for 1.02 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:14:09,096 Completed processing <Batch: 6 messages, open for 1.70 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:14:37,520 Completed processing <Batch: 2 messages, open for 1.01 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:14:41,619 Completed processing <Batch: 2 messages, open for 1.01 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:15:04,690 Completed processing <Batch: 2 messages, open for 1.01 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:16:33,354 Completed processing <Batch: 2 messages, open for 1.01 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:16:36,325 Completed processing <Batch: 2 messages, open for 1.01 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:16:43,794 Completed processing <Batch: 2 messages, open for 1.02 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:16:45,383 Completed processing <Batch: 2 messages, open for 1.01 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:16:53,842 Completed processing <Batch: 2 messages, open for 1.01 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:16:58,304 Completed processing <Batch: 2 messages, open for 1.01 seconds>.
sentry-self-hosted-snuba-sessions-consumer-1  | 2022-01-10 18:17:03,234 Completed processing <Batch: 2 messages, open for 1.01 seconds>.
```

`snuba-transactions-consumer` seems normal:

```
sentry-self-hosted-snuba-transactions-consumer-1  | 2022-01-10 19:44:33,699 Completed processing <Batch: 29 messages, open for 0.77 seconds>.
sentry-self-hosted-snuba-transactions-consumer-1  | 2022-01-10 19:44:34,464 Completed processing <Batch: 75 messages, open for 0.76 seconds>.
sentry-self-hosted-snuba-transactions-consumer-1  | 2022-01-10 19:44:35,262 Completed processing <Batch: 55 messages, open for 0.80 seconds>.
sentry-self-hosted-snuba-transactions-consumer-1  | 2022-01-10 19:44:36,028 Completed processing <Batch: 32 messages, open for 0.77 seconds>.
sentry-self-hosted-snuba-transactions-consumer-1  | 2022-01-10 19:44:36,862 Completed processing <Batch: 36 messages, open for 0.83 seconds>.
sentry-self-hosted-snuba-transactions-consumer-1  | 2022-01-10 19:44:37,652 Completed processing <Batch: 29 messages, open for 0.79 seconds>.
sentry-self-hosted-snuba-transactions-consumer-1  | 2022-01-10 19:44:38,415 Completed processing <Batch: 41 messages, open for 0.76 seconds>.
sentry-self-hosted-snuba-transactions-consumer-1  | 2022-01-10 19:44:39,196 Completed processing <Batch: 38 messages, open for 0.78 seconds>.
sentry-self-hosted-snuba-transactions-consumer-1  | 2022-01-10 19:44:39,969 Completed processing <Batch: 31 messages, open for 0.77 seconds>.
sentry-self-hosted-snuba-transactions-consumer-1  | 2022-01-10 19:44:40,773 Completed processing <Batch: 21 messages, open for 0.80 seconds>.
sentry-self-hosted-snuba-transactions-consumer-1  | 2022-01-10 19:44:41,559 Completed processing <Batch: 22 messages, open for 0.79 seconds>.
```

**Comment by chadwhitacre** [comment]
Did you take any additional steps between (3) and (4)?

In particular, did you restart the system? :)

Also, is this a stock `self-hosted` install?

**Comment by brandonhilkert** [comment]
> Did you take any additional steps between (3) and (4)?

Yes via `docker-compose restart`. No changes.

```NAME                                                            COMMAND                  SERVICE                                    STATUS              PORTS
sentry-self-hosted-clickhouse-1                                 "/entrypoint.sh"         clickhouse                                 running (healthy)   9009/tcp
sentry-self-hosted-cron-1                                       "/etc/sentry/entrypo…"   cron                                       running             9000/tcp
sentry-self-hosted-geoipupdate-1                                "/usr/bin/geoipupdat…"   geoipupdate                                exited (0)
sentry-self-hosted-ingest-consumer-1                            "/etc/sentry/entrypo…"   ingest-consumer                            running             9000/tcp
sentry-self-hosted-kafka-1                                      "/etc/confluent/dock…"   kafka                                      running (healthy)   9092/tcp
sentry-self-hosted-memcached-1                                  "docker-entrypoint.s…"   memcached                                  running (healthy)   11211/tcp
sentry-self-hosted-nginx-1                                      "/docker-entrypoint.…"   nginx                                      running             0.0.0.0:9000->80/tcp, :::9000->80/tcp
sentry-self-hosted-post-process-forwarder-1                     "/etc/sentry/entrypo…"   post-process-forwarder                     running             9000/tcp
sentry-self-hosted-postgres-1                                   "/opt/sentry/postgre…"   postgres                                   running (healthy)   5432/tcp
sentry-self-hosted-redis-1                                      "docker-entrypoint.s…"   redis                                      running (healthy)   6379/tcp
sentry-self-hosted-relay-1                                      "/bin/bash /docker-e…"   relay                                      running             3000/tcp
sentry-self-hosted-sentry-cleanup-1                             "/entrypoint.sh '0 0…"   sentry-cleanup                             running             9000/tcp
sentry-self-hosted-smtp-1                                       "docker-entrypoint.s…"   smtp                                       running             25/tcp
sentry-self-hosted-snuba-api-1                                  "./docker_entrypoint…"   snuba-api                                  running             1218/tcp
sentry-self-hosted-snuba-cleanup-1                              "/entrypoint.sh '*/5…"   snuba-cleanup                              running             1218/tcp
sentry-self-hosted-snuba-consumer-1                             "./docker_entrypoint…"   snuba-consumer                             running             1218/tcp
sentry-self-hosted-snuba-outcomes-consumer-1                    "./docker_entrypoint…"   snuba-outcomes-consumer                    running             1218/tcp
sentry-self-hosted-snuba-replacer-1                             "./docker_entrypoint…"   snuba-replacer                             running             1218/tcp
sentry-self-hosted-snuba-sessions-consumer-1                    "./docker_entrypoint…"   snuba-sessions-consumer                    running             1218/tcp
sentry-self-hosted-snuba-subscription-consumer-events-1         "./docker_entrypoint…"   snuba-subscription-consumer-events         running             1218/tcp
sentry-self-hosted-snuba-subscription-consumer-transactions-1   "./docker_entrypoint…"   snuba-subscription-consumer-transactions   running             1218/tcp
sentry-self-hosted-snuba-transactions-cleanup-1                 "/entrypoint.sh '*/5…"   snuba-transactions-cleanup                 running             1218/tcp
sentry-self-hosted-snuba-transactions-consumer-1                "./docker_entrypoint…"   snuba-transactions-consumer                running             1218/tcp
sentry-self-hosted-subscription-consumer-events-1               "/etc/sentry/entrypo…"   subscription-consumer-events               running             9000/tcp
sentry-self-hosted-subscription-consumer-transactions-1         "/etc/sentry/entrypo…"   subscription-consumer-transactions         running             9000/tcp
sentry-self-hosted-symbolicator-1                               "/bin/bash /docker-e…"   symbolicator                               running             3021/tcp
sentry-self-hosted-symbolicator-cleanup-1                       "/entrypoint.sh '55 …"   symbolicator-cleanup                       running             3021/tcp
sentry-self-hosted-web-1                                        "/etc/sentry/entrypo…"   web                                        running (healthy)   9000/tcp
sentry-self-hosted-worker-1                                     "/etc/sentry/entrypo…"   worker                                     running             9000/tcp
sentry-self-hosted-zookeeper-1                                  "/etc/confluent/dock…"   zookeeper                                  running (healthy)   3888/tcp
```

> Also, is this a stock self-hosted install?

Outside of a few basic config changes (e.g. email host, etc.). Yes.

**Comment by brandonhilkert** [comment]
Sorry, to clarify, I ran `docker-compose restart` after 4. Not in between. It was 1am, so the system was left to itself and I had found that it had stopped 7 hours later.

**Comment by chadwhitacre** [comment]
Are you still seeing exceptions come through? I.e., are all events missing or only performance?

Is the system simply still processing the backlog from the traffic spike?

**Comment by brandonhilkert** [comment]
Yes, exceptions are available. Below you can see where the transactions stopped in the project view:
<img width="490" alt="Screen Shot 2022-01-10 at 12 29 40 PM" src="https://user-images.githubusercontent.com/744212/148834837-268ed430-ae89-44f0-ab0e-1ea44879263b.png">

I haven't seen it make any progress on those transactions in 5 hours. 

Also, it wasn't a spike, it was continued throughput that only stopped 6 hours after the performance data stopped. Happy to dig in to whatever element of the system you think makes sense. I'm just not familiar enough with the components to know where to poke.

**Comment by stefanw** [comment]
I noticed the same thing (self-hosted Sentry 21.12.0 14f603c).
The container `snuba-subscription-consumer-events` keeps restarting with this in the logs:

```
snuba-subscription-consumer-events_1        | 2022-01-10 20:58:41,164 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 203}
snuba-subscription-consumer-events_1        | 2022-01-10 20:58:50,164 Caught KeyError('query'), shutting down...
snuba-subscription-consumer-events_1        | Traceback (most recent call last):
snuba-subscription-consumer-events_1        |   File "/usr/local/bin/snuba", line 33, in <module>
snuba-subscription-consumer-events_1        |     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
snuba-subscription-consumer-events_1        |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
snuba-subscription-consumer-events_1        |     return self.main(*args, **kwargs)
snuba-subscription-consumer-events_1        |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
snuba-subscription-consumer-events_1        |     rv = self.invoke(ctx)
snuba-subscription-consumer-events_1        |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
snuba-subscription-consumer-events_1        |     return _process_result(sub_ctx.command.invoke(sub_ctx))
snuba-subscription-consumer-events_1        |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
snuba-subscription-consumer-events_1        |     return ctx.invoke(self.callback, **ctx.params)
snuba-subscription-consumer-events_1        |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
snuba-subscription-consumer-events_1        |     return callback(*args, **kwargs)
snuba-subscription-consumer-events_1        |   File "/usr/src/snuba/snuba/cli/subscriptions.py", line 269, in subscriptions
snuba-subscription-consumer-events_1        |     batching_consumer.run()
snuba-subscription-consumer-events_1        |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 108, in run
snuba-subscription-consumer-events_1        |     self._run_once()
snuba-subscription-consumer-events_1        |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 146, in _run_once
snuba-subscription-consumer-events_1        |     self.__processing_strategy.submit(self.__message)
snuba-subscription-consumer-events_1        |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/batching.py", line 158, in submit
snuba-subscription-consumer-events_1        |     result = self.__worker.process_message(message)
snuba-subscription-consumer-events_1        |   File "/usr/src/snuba/snuba/subscriptions/worker.py", line 216, in process_message
snuba-subscription-consumer-events_1        |     return [
snuba-subscription-consumer-events_1        |   File "/usr/src/snuba/snuba/subscriptions/worker.py", line 216, in <listcomp>
snuba-subscription-consumer-events_1        |     return [
snuba-subscription-consumer-events_1        |   File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 328, in find
snuba-subscription-consumer-events_1        |     subscriptions = self.__get_subscriptions()
snuba-subscription-consumer-events_1        |   File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 308, in __get_subscriptions
snuba-subscription-consumer-events_1        |     for uuid, data in self.__store.all()
snuba-subscription-consumer-events_1        |   File "/usr/src/snuba/snuba/subscriptions/store.py", line 70, in all
snuba-subscription-consumer-events_1        |     return [
snuba-subscription-consumer-events_1        |   File "/usr/src/snuba/snuba/subscriptions/store.py", line 71, in <listcomp>
snuba-subscription-consumer-events_1        |     (UUID(key.decode("utf-8")), self.codec.decode(val))
snuba-subscription-consumer-events_1        |   File "/usr/src/snuba/snuba/subscriptions/codecs.py", line 35, in decode
snuba-subscription-consumer-events_1        |     return SnQLSubscriptionData.from_dict(data, self.entity_key)
snuba-subscription-consumer-events_1        |   File "/usr/src/snuba/snuba/subscriptions/data.py", line 223, in from_dict
snuba-subscription-consumer-events_1        |     query=data["query"],
snuba-subscription-consumer-events_1        | KeyError: 'query'
```

**Comment by brandonhilkert** [comment]
Our logs for that container are clean:

```
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:09,388 Worker flush took 0ms
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:11,391 Flushing 108 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=7188863, hi=7188971, timestamp=datetime.datetime(2022, 1, 10, 22, 14, 8, 643000))})
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:11,391 Worker flush took 0ms
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:13,393 Flushing 167 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=7188971, hi=7189138, timestamp=datetime.datetime(2022, 1, 10, 22, 14, 11, 10000))})
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:13,393 Worker flush took 0ms
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:15,632 Flushing 210 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=7189138, hi=7189348, timestamp=datetime.datetime(2022, 1, 10, 22, 14, 14, 126000))})
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:15,632 Worker flush took 0ms
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:18,399 Flushing 105 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=7189348, hi=7189453, timestamp=datetime.datetime(2022, 1, 10, 22, 14, 15, 723000))})
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:18,399 Worker flush took 0ms
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:20,401 Flushing 152 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=7189453, hi=7189605, timestamp=datetime.datetime(2022, 1, 10, 22, 14, 18, 43000))})
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:20,402 Worker flush took 0ms
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:22,404 Flushing 176 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=7189605, hi=7189781, timestamp=datetime.datetime(2022, 1, 10, 22, 14, 20, 369000))})
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:22,404 Worker flush took 0ms
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:24,406 Flushing 96 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=7189781, hi=7189877, timestamp=datetime.datetime(2022, 1, 10, 22, 14, 21, 941000))})
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:24,406 Worker flush took 0ms
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:26,408 Flushing 154 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=7189877, hi=7190031, timestamp=datetime.datetime(2022, 1, 10, 22, 14, 24, 279000))})
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:26,408 Worker flush took 0ms
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:28,410 Flushing 123 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=7190031, hi=7190154, timestamp=datetime.datetime(2022, 1, 10, 22, 14, 25, 718000))})
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2022-01-10 22:14:28,411 Worker flush took 0ms
```

**Comment by brandonhilkert** [comment]
I followed [these steps to clear some kafka volumes](https://develop.sentry.dev/self-hosted/troubleshooting/#nuclear-option) and transactions have started coming in again.

**Comment by chadwhitacre** [comment]
Good find @brandonhilkert. Does this help you as well @stefanw?

**Comment by stefanw** [comment]
Yes, performance data is coming in again, the `snuba-subscription-consumer-events` seems unrelated.

**Comment by chadwhitacre** [comment]
@stefanw Nice, glad you're sorted. Thanks for closing the loop @brandonhilkert. 👍
