### ISSUE TITLE
Reprocessing V2 does not work

### ISSUE THREAD

**Issue by dominic-eschbach** [getsentry/self-hosted#1253]
### Version

21.11.0

### Steps to Reproduce

As described in https://docs.sentry.io/product/issues/reprocessing/ we enabled the early adopter program on our self-hosted instance. We are using the Sentry SDK in our macOS application.
* Receive crashes respectively issues from releases without having uploaded the corresponding debug symbol files.
* Upload the corresponding debug symbols afterwards and wait at least a hour.

I was not able to get any information about wether the reprocessing-v2 feature is available at all for the self-hosted version. I would be happy to get any instructions about setting up reprocessing-v2 for macOS applications.

### Expected Result

The reprocessing button should be visible to issues where we uploaded the corresponding debug symbols after the first issues arrived.

### Actual Result

The reprocessing button isn't visible for issues that arrived before we uploaded the debug symbol files for the corresponding release.

**Comment by chadwhitacre** [comment]
> wether the reprocessing-v2 feature is available at all for the self-hosted version

In general the self-hosted version contains all features of Sentry, it should just be a matter of configuration to enable a particular feature. Have you searched the [`sentry`](https://github.com/getsentry/sentry) codebase for "reprocessing"? This might help to discover a config knob that needs to be twiddled.

**Comment by dominic-eschbach** [comment]
That's the error:
`InternalServerError: GET /issues/2/ 500
  at requestPromise(/_static/dist/sentry/chunks/app_actions_navigationActions_tsx-app_actions_organizationActions_tsx-app_bootstrap_initializ-7e3b3e.069a57b4971d3da2541a.js:1:25580)
  at asyncFunctionResume([native code])
  at componentDidUpdate(/_static/dist/sentry/chunks/app_views_organizationGroupDetails_index_tsx.fed469e598ec4d26990a.js:1:28919)
  at bi(/_static/dist/sentry/chunks/vendors-node_modules_echarts_lib_component_markPoint_js-node_modules_focus-trap_dist_focus-tr-0212e0.4cfce74f1581c8fbbff4.js:2:119250)
  at Rl(/_static/dist/sentry/chunks/vendors-node_modules_echarts_lib_component_markPoint_js-node_modules_focus-trap_dist_focus-tr-0212e0.4cfce74f1581c8fbbff4.js:2:137211)
  at Rl([native code])
  at ? (/_static/dist/sentry/chunks/vendors-node_modules_emotion_css_dist_emotion-css_esm_js-node_modules_emotion_react_dist_emot-7a9639.e4f68e6934f33b27863b.js:2:781949)
  at Il(/_static/dist/sentry/chunks/vendors-node_modules_echarts_lib_component_markPoint_js-node_modules_focus-trap_dist_focus-tr-0212e0.4cfce74f1581c8fbbff4.js:2:133911)
  at _l(/_static/dist/sentry/chunks/vendors-node_modules_echarts_lib_component_markPoint_js-node_modules_focus-trap_dist_focus-tr-0212e0.4cfce74f1581c8fbbff4.js:2:129175)
  at _l([native code])
  at ? (/_static/dist/sentry/chunks/vendors-node_modules_echarts_lib_component_markPoint_js-node_modules_focus-trap_dist_focus-tr-0212e0.4cfce74f1581c8fbbff4.js:2:77620)
  at ? (/_static/dist/sentry/chunks/vendors-node_modules_emotion_css_dist_emotion-css_esm_js-node_modules_emotion_react_dist_emot-7a9639.e4f68e6934f33b27863b.js:2:781949)
  at Go(/_static/dist/sentry/chunks/vendors-node_modules_echarts_lib_component_markPoint_js-node_modules_focus-trap_dist_focus-tr-0212e0.4cfce74f1581c8fbbff4.js:2:77566)
  at Qo(/_static/dist/sentry/chunks/vendors-node_modules_echarts_lib_component_markPoint_js-node_modules_focus-trap_dist_focus-tr-0212e0.4cfce74f1581c8fbbff4.js:2:77501)
  at yl(/_static/dist/sentry/chunks/vendors-node_modules_echarts_lib_component_markPoint_js-node_modules_focus-trap_dist_focus-tr-0212e0.4cfce74f1581c8fbbff4.js:2:126275)
  at ju(/_static/dist/sentry/chunks/vendors-node_modules_echarts_lib_component_markPoint_js-node_modules_focus-trap_dist_focus-tr-0212e0.4cfce74f1581c8fbbff4.js:2:97019)
  at ju([native code])
  at n(/_static/dist/sentry/chunks/vendors-node_modules_emotion_css_dist_emotion-css_esm_js-node_modules_emotion_react_dist_emot-7a9639.e4f68e6934f33b27863b.js:2:762400)
  at ? (/_static/dist/sentry/chunks/vendors-node_modules_emotion_css_dist_emotion-css_esm_js-node_modules_emotion_react_dist_emot-7a9639.e4f68e6934f33b27863b.js:2:293306)
  at trigger(/_static/dist/sentry/chunks/vendors-node_modules_emotion_css_dist_emotion-css_esm_js-node_modules_emotion_react_dist_emot-7a9639.e4f68e6934f33b27863b.js:2:762688)
  at onInitializeUrlState(/_static/dist/sentry/chunks/app_utils_analytics_trackAdvancedAnalyticsEvent_tsx-app_utils_discover_eventView_tsx-app_util-bfccf1.edf1e4947cc218b160a4.js:1:245909)
  at onInitializeUrlState([native code])
  at n(/_static/dist/sentry/chunks/vendors-node_modules_emotion_css_dist_emotion-css_esm_js-node_modules_emotion_react_dist_emot-7a9639.e4f68e6934f33b27863b.js:2:762400)
  at ? (/_static/dist/sentry/chunks/vendors-node_modules_emotion_css_dist_emotion-css_esm_js-node_modules_emotion_react_dist_emot-7a9639.e4f68e6934f33b27863b.js:2:292873)
  at trigger(/_static/dist/sentry/chunks/vendors-node_modules_emotion_css_dist_emotion-css_esm_js-node_modules_emotion_react_dist_emot-7a9639.e4f68e6934f33b27863b.js:2:762688)
  at ? (/_static/dist/sentry/chunks/vendors-node_modules_emotion_css_dist_emotion-css_esm_js-node_modules_emotion_react_dist_emot-7a9639.e4f68e6934f33b27863b.js:2:762794)
  at r(/_static/dist/sentry/chunks/vendors-node_modules_emotion_css_dist_emotion-css_esm_js-node_modules_emotion_react_dist_emot-7a9639.e4f68e6934f33b27863b.js:2:53830)`

**Comment by chadwhitacre** [comment]
> I enabled the corresponding feature organizations:reprocessing-v2 and was able to trigger it.

Nice!

> Are the features in general self-contained, so that it's not necessary to look for dependent features?

There might be exceptions but generally they are self-contained.

> Is it also recommended or necessary to always run the install.sh script after changing the available features?

You will need to stop and restart the services (`docker compose down` / `up`) but you do not need to reinstall, no.

> I always get an error "There was an error loading data." after reprocessing an issue. Is this expected or is there still something missing?
> `InternalServerError: GET /issues/2/ 500`

Hmm ... this is the frontend, can you find a corresponding backend error for the 500? In the docker logs, I guess?
