### ISSUE TITLE
Trying to install sentry on Latest Version using external exsiting redis and postgress DB

### ISSUE THREAD

**Issue by Avani231194** [getsentry/self-hosted#1256]
### Version

21.*

### Steps to Reproduce

Getting **_Something went wrong_** after login

### Expected Result

Login to sentry

### Actual Result

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fa5ac3e8c50>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/transport.py", line 326, in send_event_wrapper
    self._send_event(event)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/transport.py", line 234, in _send_event
    headers={"Content-Type": "application/json", "Content-Encoding": "gzip"},
  File "/usr/local/lib/python3.6/site-packages/sentry/utils/sdk.py", line 216, in patched_send_request
    return _send_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/transport.py", line 180, in _send_request
    headers=headers,
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='in-sentry.bookmyshow.com', port=443): Max retries exceeded with url: //api/1/store/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa5ac3e8c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
18:35:58 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk

**Comment by aminvakil** [comment]
I'm not sure if it's supported at all or not, but you can at least share with us how you have configured your sentry to use external redis and postgresdb.
