### ISSUE TITLE
Upgraded Sentry, now "Oops!" and Redis container keeps restarting

### ISSUE THREAD

**Issue by crummy** [getsentry/self-hosted#1280]
### Version

22.1.0

### Steps to Reproduce

Standard install, with legacy Slack integration and Gitlab auth plugin

1. Upgraded from ... ~20.0ish (not sure sorry - can I tell somehow?) to latest onpremise build with `git pull`
2. `./install.sh`, `docker-compose up -d`

### Expected Result

Visit our instance, log in and see everything normal

### Actual Result

Visit our instance, click "Login with Gitlab", see "Oops! Something went wrong". Run `docker ps` and notice Redis container is rebooting every 30s or so.

<details>
<summary>
`ubuntu@localhost:~/sentry/onpremise$ docker logs --tail=26 sentry_onpremise_web_1`
</summary>

```
08:33:08 [ERROR] sentry.errors: Unable to incr internal metric
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 97, in worker
    tsdb.incr(tsdb.models.internal, full_key, count=amount)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 105, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python3.8/site-packages/sentry/tsdb/redissnuba.py", line 83, in method
    return getattr(self.backends[backend], key)(*a, **kw)
  File "/usr/local/lib/python3.8/site-packages/sentry/tsdb/redis.py", line 202, in incr
    self.incr_multi([(model, key)], timestamp, count, environment_id)
  File "/usr/local/lib/python3.8/site-packages/sentry/tsdb/redis.py", line 261, in incr_multi
    client.expireat(hash_key, key_expiries.pop(hash_key))
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 637, in __exit__
    self.mapping_client.join(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 418, in join
    command_buffer.wait_for_responses(self)
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 229, in wait_for_responses
    value = client.parse_response(self.connection, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 477, in read_response
    raise response
redis.exceptions.BusyLoadingError: Redis is loading the dataset in memory
08:33:08 [ERROR] sentry.errors: Unable to incr internal metric
```
</details>

<details>
<summary>
`ubuntu@localhost:~/sentry/onpremise$ docker logs --tail=26 sentry_onpremise_redis_1`
</summary>

```
1:M 28 Jan 2022 08:36:22.804 * Running mode=standalone, port=6379.
1:M 28 Jan 2022 08:36:22.804 # Server initialized
1:M 28 Jan 2022 08:36:22.804 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 28 Jan 2022 08:36:22.805 * Loading RDB produced by version 6.2.4
1:M 28 Jan 2022 08:36:22.805 * RDB age 13484 seconds
1:M 28 Jan 2022 08:36:22.805 * RDB memory usage when created 8692.62 Mb
1:C 28 Jan 2022 08:36:39.836 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 28 Jan 2022 08:36:39.836 # Redis version=6.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 28 Jan 2022 08:36:39.836 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 28 Jan 2022 08:36:39.837 * monotonic clock: POSIX clock_gettime
1:M 28 Jan 2022 08:36:39.838 * Running mode=standalone, port=6379.
1:M 28 Jan 2022 08:36:39.838 # Server initialized
1:M 28 Jan 2022 08:36:39.838 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 28 Jan 2022 08:36:39.840 * Loading RDB produced by version 6.2.4
1:M 28 Jan 2022 08:36:39.840 * RDB age 13501 seconds
1:M 28 Jan 2022 08:36:39.840 * RDB memory usage when created 8692.62 Mb
1:C 28 Jan 2022 08:36:57.054 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 28 Jan 2022 08:36:57.054 # Redis version=6.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 28 Jan 2022 08:36:57.054 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 28 Jan 2022 08:36:57.056 * monotonic clock: POSIX clock_gettime
1:M 28 Jan 2022 08:36:57.058 * Running mode=standalone, port=6379.
1:M 28 Jan 2022 08:36:57.058 # Server initialized
1:M 28 Jan 2022 08:36:57.058 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 28 Jan 2022 08:36:57.060 * Loading RDB produced by version 6.2.4
1:M 28 Jan 2022 08:36:57.060 * RDB age 13519 seconds
1:M 28 Jan 2022 08:36:57.060 * RDB memory usage when created 8692.62 Mb
```
</details>

**Comment by crummy** [comment]
The issue disappeared on its own after ~one day.
