### ISSUE TITLE
Slack integration doesn't work with the new rotating tokens

### ISSUE THREAD

**Issue by ricsipontaz** [getsentry/self-hosted#1296]
### Version

21.12.0

### Steps to Reproduce

* Create a new slack app (with rotating tokens) for Sentry
* Setup it on Sentry

### Expected Result

It should handle the changed token

### Actual Result

It didn't handle it:

08:12:30 [INFO] sentry.integrations.client: integration.http_response (integration='slack' status_string='200')                                                                                               08:12:30 [INFO] sentry.integrations.slack: rule.slack.conversation_info_failed (error='token_expired')                                                                                                        
Traceback (most recent call last):                                                                                                                                                                              File "/usr/local/lib/python3.8/site-packages/sentry/integrations/slack/utils/channel.py", line 85, in validate_channel_id                                                                                       results = client.get("/conversations.info", headers=headers, params=payload)                                                                                                                              
  File "/usr/local/lib/python3.8/site-packages/sentry/shared_integrations/client.py", line 305, in get                                                                                                            return self.request("GET", *args, **kwargs)                                                                                                                                                                 File "/usr/local/lib/python3.8/site-packages/sentry/integrations/slack/client.py", line 83, in request
    raise ApiError(response.get("error", ""))                                                                                                                                                                 sentry.shared_integrations.exceptions.ApiError: token_expired

**Comment by aminvakil** [comment]
I have not used this feature and don't know if it works or not, but here is the appropriate place to open issue:
https://github.com/getsentry/sentry/issues/new?assignees=&labels=Component:%20Integrations&template=bug.yml&title=Slack%20Integration%20Problem

@chadwhitacre If I'm right this can get moved to getsentry/sentry, right?

**Comment by chadwhitacre** [comment]
Yeah, let's move over there so the Ecosystem team can take a look, if it turns out to be self-hosting specific we can move back here. 👍
