### ISSUE TITLE
Sentry sends an error message

### ISSUE THREAD

**Issue by shaojielinux** [getsentry/self-hosted#1313]
### Problem Statement

[ERROR] celery.app.trace: Task sentry.tasks.email.send_email[3fea2e01-d0af-4700-be21-3929ebebe78d] raised unexpected: SMTPServerDisconnected('Connection unexpectedly closed') (data={'hostname': '8fb2a1e1aaf6', 'id': '3fea2e01-d0af-4700-be21-3929ebebe78d', 'name': 'sentry.tasks.email.send_email', 'exc': "SMTPServerDisconnected('Connection unexpectedly closed')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 46, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/email.py", line 73, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/email/send.py", line 18, in send_messages\n    sent: int = connection.send_messages(messages)\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 70, in open\n    self.connection.login(self.username, self.password)\n  File "/usr/local/lib/python3.8/smtplib.py", line 737, in login\n    (code, resp) = self.auth(\n  File "/usr/local/lib/python3.8/smtplib.py", line 640, in auth\n    (code, resp) = self.docmd("AUTH", mechanism + " " + response)\n  File "/usr/local/lib/python3.8/smtplib.py", line 430, in docmd\n    return self.getreply()\n  File "/usr/local/lib/python3.8/smtplib.py", line 403, in getreply\n    raise SMTPServerDisconnected("Connection unexpectedly closed")\nsmtplib.SMTPServerDisconnected: Connection unexpectedly closed\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7fe227d89d60>}", 'description': 'raised unexpected', 'internal': False})
04:21:36 [ERROR] sentry_sdk.errors: Unexpected status code: 502 (body: b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 46, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/email.py", line 73, in send_email
    send_messages([message])
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/email/send.py", line 18, in send_messages
    sent: int = connection.send_messages(messages)
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 70, in open
    self.connection.login(self.username, self.password)
  File "/usr/local/lib/python3.8/smtplib.py", line 737, in login
    (code, resp) = self.auth(
  File "/usr/local/lib/python3.8/smtplib.py", line 640, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/usr/local/lib/python3.8/smtplib.py", line 430, in docmd
    return self.getreply()
  File "/usr/local/lib/python3.8/smtplib.py", line 403, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

**Comment by chadwhitacre** [comment]
Please file [a real problem report](https://github.com/getsentry/self-hosted/issues/new?assignees=&labels=&template=problem-report.yml) if you want help with something.
