### ISSUE TITLE
sentry.models.group.Group.DoesNotExist: Group matching query does not exist

### ISSUE THREAD

**Issue by aamarques** [getsentry/self-hosted#1338]
### Version

21.12.0

### Steps to Reproduce

This happens after an unsuccessful migration to 22.1.0 and I restore a backup of the complete disk before migration.

### Expected Result

Everything running

### Actual Result

in `sentry-cleanup`

```
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 188, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/cleanup.py", line 254, in cleanup
    nodestore.cleanup(cutoff)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 210, in inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/nodestore/django/backend.py", line 60, in cleanup
    BulkDeleteQuery(model=Node, dtfield="timestamp", days=days).execute()
  File "/usr/local/lib/python3.8/site-packages/sentry/db/deletion.py", line 66, in execute
    return self._continuous_query(query)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/deletion.py", line 72, in _continuous_query
    cursor.execute(query)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 500, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 79, in execute
    return self.cursor.execute(sql)
django.db.utils.InternalError: InternalError_('tuple concurrently updated\n')
SQL:
            delete from nodestore_node
            where id = any(array(
                select id
                from nodestore_node
                where "timestamp" < '2022-01-23T00:00:14.372106+00:00'::timestamptz

                limit 10000
            ));

```

in `worker_1`

```
10:24:08 [ERROR] celery.app.trace: Task sentry.tasks.store.save_event[b7429a39-94df-4ed5-952c-3b6cb1e62a07] raised unexpected: DoesNotExist('Group matching query does not exist.') (data={'hostname': '9ad9f23e823b', 'id': 'b7429a39-94df-4ed5-952c-3b6cb1e62a07', 'name': 'sentry.tasks.store.save_event', 'exc': "DoesNotExist('Group matching query does not exist.')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 46, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 763, in save_event\n    _do_save_event(cache_key, data, start_time, event_id, project_id, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 662, in _do_save_event\n    manager.save(\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 210, in inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 439, in save\n    job["group"], job["is_new"], job["is_regression"] = _save_aggregate(\n  File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 1138, in _save_aggregate\n
  group = Group.objects.get(id=existing_grouphash.group_id)\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/models/manager/base.py", line 226, in get\n    model: M = super().get(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n
 File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get\n    raise self.model.DoesNotExist(\nsentry.models.group.Group.DoesNotExist: Group matching query does not exist.\n', 'args': '()', 'kwargs': "{'cache_key': 'e:ab692ad08952431991d494c831821be1:11', 'data': None, 'start_time': 1645525445.0, 'event_id': 'ab692ad08952431991d494c831821be1', 'project_id': 11}", 'description': 'raised unexpected', 'internal': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 46, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 763, in save_event
    _do_save_event(cache_key, data, start_time, event_id, project_id, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 662, in _do_save_event
    manager.save(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 210, in inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 439, in save
    job["group"], job["is_new"], job["is_regression"] = _save_aggregate(
  File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 1138, in _save_aggregate
    group = Group.objects.get(id=existing_grouphash.group_id)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/models/manager/base.py", line 226, in get
    model: M = super().get(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
    raise self.model.DoesNotExist(
sentry.models.group.Group.DoesNotExist: Group matching query does not exist.

````

Any help would be appreciated :)

**Comment by chadwhitacre** [comment]
> This happens after an unsuccessful migration to 22.1.0 and I restore a backup of the complete disk before migration.

These repro steps are pretty thin, @aamarques. I guess your environment is in a corrupted state, but it sounds like you're trying to restore to a known good state? Yes?

**Comment by aamarques** [comment]
Hey @chadwhitacre, I've tried to update from 21.12 to 22.1.0 (related here https://github.com/getsentry/self-hosted/issues/1269). So, after unsuccessfully updating,  I restored a previous disk data and restore the 21.12.0 version. Now I got this scenario.

**Comment by aamarques** [comment]
> Ah, yeah, the index corruption. We never got to the bottom of that one, did we. :-/
No. :-/

> How? What mechanism did you use to back and restore the disk data?
Google Disk snapshot.

**Comment by aminvakil** [comment]
Did it work before upgrading and at the time of backup correctly? Because if you have restored your disk to a working state of sentry, this should have worked, right?

And if it does not, state of backup (or restore) is not correct.

**Comment by aamarques** [comment]
> Did it work before upgrading and at the time of backup correctly? Because if you have restored your disk to a working state of sentry, this should have worked, right?

Yes, work before and after and still working with these errors. I have observed because the disk space increases.

> What I'm trying to say is restoring to a previous full backup should have been like turning off and on the server again and sentry is fine with turning off and on again :)

Sure. I share the same idea. :/

Thanks @aminvakil

**Comment by aamarques** [comment]
Any ideas ? :)

**Comment by aamarques** [comment]
@chadwhitacre and @aminvakil 
I did a node_store reindex. This takes a long time. After this, I could run a cleanup process to remove some days and reduce disk space from 88% to 61%.
Until now, I have no more the previous errors :)

But, the world is a wide place... 

```
postgres_1                                  | ERROR:  duplicate key value violates unique constraint "sentry_eventuser_project_id_1a96e3b719e55f9a_uniq"
postgres_1                                  | DETAIL:  Key (project_id, hash)=(5, 3e1381b8136935403105a500483b8896) already exists.
``` 

Thanks for share your knowledge with me.
