### ISSUE TITLE
Failed migrations during update 20.11.1 -> 22.2.0 

### ISSUE THREAD

**Issue by N1k-3l** [getsentry/self-hosted#1348]
### Version

20.11.1

### Steps to Reproduce

1. Update sentry dir to 22.2.0 using gitlab
2. Copy own _config_ and _env_ files
3. Execute install.sh 

### Expected Result

Update servise to 22.2.0 

### Actual Result

Got error  **Failed to connect to clickhouse:9000** during migration step _**events**_ _0014_backfill_errors_ 
[sentry_install_log-2022-02-22_19-14-16.txt](https://github.com/getsentry/self-hosted/files/8130366/sentry_install_log-2022-02-22_19-14-16.txt)

Migratins list before trying update:
[migrations.txt](https://github.com/getsentry/self-hosted/files/8130341/migrations.txt)

what i am doing wrong?

**Comment by aminvakil** [comment]
Can you please elaborate on how you have updated sentry dir to 22.2.0?

There are lots of files in `.gitignore` which you may have missed if you just downloaded the newer another tarball, extracted it and copy only some files from old sentry to new sentry.

**Comment by aminvakil** [comment]
Sorry, I just saw which version you were (20.11.1) and version you tried to upgrade to (22.2.0) and you have missed 21.5.0 and 21.6.3 hard stops:

https://develop.sentry.dev/self-hosted/releases/#hard-stops

**Comment by N1k-3l** [comment]
[sentry_install_log-2022-03-11_12-45-01.txt](https://github.com/getsentry/self-hosted/files/8231567/sentry_install_log-2022-03-11_12-45-01.txt)
[migrations.txt](https://github.com/getsentry/self-hosted/files/8231579/migrations.txt)

Sorry. But the same error on migrations  while update to sentry:21.5.0

**Comment by chadwhitacre** [comment]
I'm seeing a timeout in the install log (below). Are you overloading your clickhouse instance during the upgrade? Is there some timeout setting you can increase to see if you can allow it to complete?

```
Failed to connect to clickhouse:9000
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 260, in connect
    return self._init_connection(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 226, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 221, in _create_socket
    raise err
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 212, in _create_socket
    sock.connect(sa)
socket.timeout: timed out
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 80, in execute
    result: Sequence[Any] = conn.execute(
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 205, in execute
    self.connection.force_connect()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 180, in force_connect
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 279, in connect
    raise err
clickhouse_driver.errors.SocketTimeoutError: Code: 209. (clickhouse:9000)
```

**Comment by N1k-3l** [comment]
Thanks to all. I tried run migrations with command:
`docker-compose run --rm snuba-api migrations migrate --force docker-compose run --rm snuba-api `
It helped me to avoid error during running _install.sh_

**Comment by chadwhitacre** [comment]
Thanks for posting back @N1k-3l, glad you got it sorted. 👍
