### ISSUE TITLE
Using host machine smtp server

### ISSUE THREAD

**Issue by Enhaloed** [getsentry/self-hosted#1372]
### Version

22.1.0

### Steps to Reproduce

config.yml:
```
mail.backend: 'smtp'
mail.host: 'dockerhost'
mail.port: 25
mail.username: ''
mail.password: ''
mail.use-tls: false
mail.from: 'user@<domainname>.com'
mail.list-namespace: '<domainname>.com'
```
docker-compose.yml:
```
services:
  smtp:
    <<: *restart_policy
    image: tianon/exim4
    hostname: ${SENTRY_MAIL_HOST:-''}
    volumes:
      - "sentry-smtp:/var/spool/exim4"
      - "sentry-smtp-log:/var/log/exim4"
    extra_hosts:
      - "dockerhost:127.0.0.1"
```

I added the extra_hosts entry to the smtp container and attempted to use it as the host for the mail.host

### Expected Result

Emails to be sent from the smtp server on localhost:25 from the container's host.

### Actual Result

docker-compose logs smtp:
```
smtp_1                                      |     9 LOG: MAIN
smtp_1                                      |     9   exim 4.92 daemon started: pid=9, no queue runs, listening for SMTP on port 25 (IPv6 and IPv4)
smtp_1                                      |    11 LOG: MAIN
smtp_1                                      |    11   exim 4.92 daemon started: pid=11, no queue runs, listening for SMTP on port 25 (IPv6 and IPv4)
```
docker-compose logs worker:
```
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
worker_1                                    |     R = retval = fun(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
worker_1                                    |     return self.run(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
worker_1                                    |     reraise(*exc_info)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
worker_1                                    |     raise value
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
worker_1                                    |     return f(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 46, in _wrapped
worker_1                                    |     result = func(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/email.py", line 73, in send_email
worker_1                                    |     send_messages([message])
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/email/send.py", line 18, in send_messages
worker_1                                    |     sent: int = connection.send_messages(messages)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
worker_1                                    |     new_conn_created = self.open()
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 63, in open
worker_1                                    |     self.connection = self.connection_class(self.host, self.port, **connection_params)
worker_1                                    |   File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
worker_1                                    |     (code, msg) = self.connect(host, port)
worker_1                                    |   File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
worker_1                                    |     self.sock = self._get_socket(host, port, self.timeout)
worker_1                                    |   File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
worker_1                                    |     return socket.create_connection((host, port), timeout,
worker_1                                    |   File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
worker_1                                    |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
worker_1                                    |   File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
worker_1                                    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
worker_1                                    | socket.gaierror: [Errno -3] Temporary failure in name resolution
worker_1                                    | 03:43:11 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[b6ae959c-e629-49fa-aa56-f530d9c2271d] raised unexpected: gaierror(-3, 'Temporary failure in name resolution') (data={'hostname': 'ca7ef4976551', 'id': 'b6ae959c-e629-49fa-aa56-f530d9c2271d', 'name': 'sentry.tasks.email.send_email', 'exc': "gaierror(-3, 'Temporary failure in name resolution')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 46, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/email.py", line 73, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/email/send.py", line 18, in send_messages\n    sent: int = connection.send_messages(messages)\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 63, in open\n    self.connection = self.connection_class(self.host, self.port, **connection_params)\n  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__\n    (code, msg) = self.connect(host, port)\n  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect\n    self.sock = self._get_socket(host, port, self.timeout)\n  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket\n    return socket.create_connection((host, port), timeout,\n  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection\n    for res in getaddrinfo(host, port, 0, SOCK_STREAM):\n  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f6fcb50fcd0>}", 'description': 'raised unexpected', 'internal': False})
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 158, in _new_conn
worker_1                                    |     conn = connection.create_connection(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 80, in create_connection
worker_1                                    |     raise err
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 70, in create_connection
worker_1                                    |     sock.connect(sa)
worker_1                                    | ConnectionRefusedError: [Errno 111] Connection refused
worker_1                                    | 
worker_1                                    | During handling of the above exception, another exception occurred:
worker_1                                    | 
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
worker_1                                    |     httplib_response = self._make_request(conn, method, url,
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 343, in _make_request
worker_1                                    |     self._validate_conn(conn)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
worker_1                                    |     conn.connect()
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 301, in connect
worker_1                                    |     conn = self._new_conn()
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 167, in _new_conn
worker_1                                    |     raise NewConnectionError(
worker_1                                    | urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f6fc9619eb0>: Failed to establish a new connection: [Errno 111] Connection refused
worker_1                                    | 
worker_1                                    | During handling of the above exception, another exception occurred:
worker_1                                    | 
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/transport.py", line 453, in send_event_wrapper
worker_1                                    |     self._send_event(event)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/transport.py", line 338, in _send_event
worker_1                                    |     self._send_request(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/sdk.py", line 235, in patched_send_request
worker_1                                    |     return _send_request(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/transport.py", line 230, in _send_request
worker_1                                    |     response = self._pool.request(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 70, in request
worker_1                                    |     return self.request_encode_body(method, url, fields=fields,
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 150, in request_encode_body
worker_1                                    |     return self.urlopen(method, url, **extra_kw)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 324, in urlopen
worker_1                                    |     response = conn.urlopen(method, u.request_uri, **kw)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 663, in urlopen
worker_1                                    |     return self.urlopen(method, url, body, headers, retries,
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 663, in urlopen
worker_1                                    |     return self.urlopen(method, url, body, headers, retries,
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 663, in urlopen
worker_1                                    |     return self.urlopen(method, url, body, headers, retries,
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
worker_1                                    |     retries = retries.increment(method, url, error=e, _pool=self,
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 399, in increment
worker_1                                    |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
worker_1                                    | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='<domainname>.com', port=443): Max retries exceeded with url: /api/1/store/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6fc9619eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
worker_1                                    | 03:43:11 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk
```

How do I go about setting the host to be port 25 of the container's hosts? (Note: replaced \<domainname\> for security reasons)

**Comment by Enhaloed** [comment]
I've looked through both quite a bit @chadwhitacre and haven't found discussions covering specifically this. Do you have a link? Thanks!

**Comment by chadwhitacre** [comment]
> ```
> mail.host: 'dockerhost'
> ```

Where are you getting the name `dockerhost` from? I don't see that it's [any sort of default or convention](https://www.google.com/search?q=dockerhost), and it's not mentioned in `self-hosted`.


> ```
>    hostname: ${SENTRY_MAIL_HOST:-''}
> ```

We just fixed a bug with this in #1365, not sure if it affects you.

**Comment by aminvakil** [comment]
In your container, 127.0.0.1 will be the container itself.

`host-gateway` is set automatically to your container gateway which will be your docker interface on host, it should be something like this:
```
    extra_hosts:
      - "dockerhost:host-gateway"
```

**Comment by Enhaloed** [comment]
Thanks both for your help. I ended up skipping using a local smtp server entirely and used sendgrid instead. Never fully got to the bottom of this but appreciate the help regardless.

**Comment by chadwhitacre** [comment]
Hrm, glad you were able to get sendgrid working @Enhaloed.

Cross-linking with #1312 ...
