### ISSUE TITLE
auth/login/ Oops! Something went wrong

### ISSUE THREAD

**Issue by rockbytem** [getsentry/self-hosted#1391]
### Version

latest

### Steps to Reproduce

docker images

redis                latest              87c26977fd90        39 hours ago        113MB
php                  7.4-apache          91d896afaf11        43 hours ago        452MB
postgres             latest              5cd1494671e9        2 days ago          376MB
sentry               latest              fe6992de61df        2 years ago         869MB

### Expected Result

Login Page should appear

### Actual Result

I am encountering this almost everywhere i try to install it. Azure. localhost. 8gm ram machine. [https://pasteboard.co/rCBW8ob0coND.png](url)
[https://gcdnb.pbrd.co/images/rCBW8ob0coND.png?o=1](url)
 
Docker logs look like this:
```
sentry-base        | 82.76.151.9 - - [19/Mar/2022:20:53:55 +0000] "GET /_static/1647722897/sentry/dist/sentry-pattern.png HTTP/1.1" 200 28417 "http://20.231.16.99:9000/_static/1647722897/sentry/dist/sentry.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
sentry-base        | Traceback (most recent call last):
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
sentry-base        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
sentry-base        |     return self.dispatch(request, *args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
sentry-base        |     return view_func(*args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
sentry-base        |     return self.handle(request, *args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
sentry-base        |     response = view_func(request, *args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
sentry-base        |     return func(*args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 193, in handle
sentry-base        |     return super(AuthLoginView, self).handle(request, *args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 238, in handle
sentry-base        |     return super(BaseView, self).dispatch(request, *args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
sentry-base        |     return handler(request, *args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 211, in get
sentry-base        |     org = Organization.get_default()
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 164, in get_default
sentry-base        |     )[0]
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
sentry-base        |     return list(qs)[0]
sentry-base        | IndexError: list index out of range
sentry-base        | 20:56:11 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest: GET u'/auth/login/'>)
sentry-base        | 82.76.151.9 - - [19/Mar/2022:20:56:11 +0000] "GET /auth/login/ HTTP/1.1" 500 5581 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
sentry-base        | 82.76.151.9 - - [19/Mar/2022:20:56:12 +0000] "GET /_static/1647722897/sentry/dist/app.js.map HTTP/1.1" 200 834000 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
sentry-base        | 82.76.151.9 - - [19/Mar/2022:20:56:12 +0000] "GET /_static/1647722897/sentry/dist/vendor.js.map HTTP/1.1" 200 1245416 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
```

Chrome console logs:

```
GET http://20.231.16.99:9000/auth/login/ 500 (INTERNAL SERVER ERROR)
DevTools failed to load source map: Could not load content for chrome-extension://ljngjbnaijcbncmcnjfhigebomdlkcjo/content-script/browser-polyfill.min.js.map: System error: net::ERR_FILE_NOT_FOUND
20.231.16.99/:1 Error handling response: TypeError: self.processResponse is not a function
    at chrome-extension://cmkdbmfndkfgebldhnkbfhlneefdaaip/js/notification.js:154:10
```

trying to add a user manually. *(Allthough it was asked of me during the docker build to do this.) 
gets me this ;

```
root@sentry-worker:/# sentry createuser
21:21:49 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
21:21:52 [INFO] sentry.plugins.github: apps-not-configured
Email: xxxx@xxxx
Password:
Repeat for confirmation:
Should this user be a superuser? [y/N]: y
User created: xxxx@xxxx
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/createuser.py", line 95, in createuser
    org = Organization.get_default()
  File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 164, in get_default
    )[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
root@sentry-worker:/#
```

**Comment by aminvakil** [comment]
Can you share with us how have you ran this instance of self-hosted?

Can you follow this https://develop.sentry.dev/self-hosted/#getting-started?

**Comment by rockbytem** [comment]
I've used the official sentry docker image


Here are new errors I've tracked down:
```

sentry-base        | 192.168.121.1 - - [20/Mar/2022:14:34:40 +0000] "GET /_static/1647786858/sentry/dist/rubik-regular.woff HTTP/1.1" 200 61975 "http://192.168.121.43:9000/_static/1647786858/sentry/dist/sentry.css" "Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0"
sentry-base        | 192.168.121.1 - - [20/Mar/2022:14:34:40 +0000] "GET /_static/1647786858/sentry/dist/sentry-simple.woff HTTP/1.1" 200 14147 "http://192.168.121.43:9000/_static/1647786858/sentry/dist/sentry.css" "Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0"
sentry-base        | Traceback (most recent call last):
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
sentry-base        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
sentry-base        |     return self.dispatch(request, *args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
sentry-base        |     return view_func(*args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
sentry-base        |     return self.handle(request, *args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
sentry-base        |     response = view_func(request, *args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
sentry-base        |     return func(*args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 193, in handle
sentry-base        |     return super(AuthLoginView, self).handle(request, *args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 238, in handle
sentry-base        |     return super(BaseView, self).dispatch(request, *args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
sentry-base        |     return handler(request, *args, **kwargs)
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 211, in get
sentry-base        |     org = Organization.get_default()
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 164, in get_default
sentry-base        |     )[0]
sentry-base        |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
sentry-base        |     return list(qs)[0]
sentry-base        | IndexError: list index out of range
sentry-base        | 14:36:57 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest: GET u'/auth/login/'>)
sentry-base        | 192.168.121.1 - - [20/Mar/2022:14:36:57 +0000] "GET /auth/login/ HTTP/1.1" 500 5583 "http://192.168.121.43:9000/auth/login/" "Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0"
sentry-redis       | 1:M 20 Mar 2022 14:38:15.086 * 100 changes in 300 seconds. Saving...
sentry-redis       | 1:M 20 Mar 2022 14:38:15.100 * Background saving started by pid 19
sentry-redis       | 19:C 20 Mar 2022 14:38:15.230 * DB saved on disk
sentry-redis       | 19:C 20 Mar 2022 14:38:15.235 * RDB: 0 MB of memory used by copy-on-write
sentry-redis       | 1:M 20 Mar 2022 14:38:15.306 * Background saving terminated with success


```

**Comment by aminvakil** [comment]
How?
Please provide the exact commands.

**Comment by rockbytem** [comment]
Docker Image:
`sentry:latest`
depends_on:
```
- sentry-redis
- sentry-postgres
```
docker-compose run --rm sentry-base upgrade
Service Start
'docker-compose up -d'

It promted me at the beginning for the new user and the pass

**Comment by rockbytem** [comment]
[sentry-worker      | celery@sentry-worker ready.
sentry-worker      | Traceback (most recent call last):
sentry-worker      |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
sentry-worker      |     R = retval = fun(*args, **kwargs)
sentry-worker      |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
sentry-worker      |     return self.run(*args, **kwargs)
sentry-worker      |   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 155, in _inner
sentry-worker      |     reraise(*exc_info)
sentry-worker      |   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 150, in _inner
sentry-worker      |     return f(*args, **kwargs)
sentry-worker      |   File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 54, in _wrapped
sentry-worker      |     result = func(*args, **kwargs)
sentry-worker      |   File "/usr/local/lib/python2.7/site-packages/sentry/tasks/scheduler.py", line 18, in enqueue_scheduled_jobs
sentry-worker      |     with locks.get('scheduler.process', duration=60).acquire():
sentry-worker      |   File "/usr/local/lib/python2.7/site-packages/sentry/utils/locking/lock.py", line 37, in acquire
sentry-worker      |     error
sentry-worker      |   File "/usr/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
sentry-worker      |     raise value
sentry-worker      | UnableToAcquireLock: Unable to acquire <Lock: 'scheduler.process'> due to error: Could not set key: u'l:scheduler.process'
sentry-worker      | 10:00:08 [ERROR] celery.worker.job: Task sentry.tasks.enqueue_scheduled_jobs[9c78834c-5dab-4162-80cb-f7618f0424dd] raised unexpected: UnableToAcquireLock(u"Unable to acquire <Lock: 'scheduler.process'> due to error: Could not set key: u'l:scheduler.process'",) (data={u'hostname': 'celery@sentry-worker', u'name': 'sentry.tasks.enqueue_scheduled_jobs', u'args': '[]', u'internal': False, u'kwargs': '{}', u'id': '9c78834c-5dab-4162-80cb-f7618f0424dd'})](url)

**Comment by aminvakil** [comment]
Sentry is not meant to be run like that.
Please follow https://develop.sentry.dev/self-hosted/#getting-started.
