### ISSUE TITLE
Undefined column `sentry_organizationmember_teams.role` after update to 22.4.0

### ISSUE THREAD

**Issue by ml14tlc** [getsentry/self-hosted#1436]
### Version

22.4.0

### Steps to Reproduce

Running on Ubuntu 20.04 TLS with `docker-compose`.
Since an update from `22.3.0` to `22.4.0` the `internal` projects reports frequent `ProgrammingError` related to an `UndefinedColum`. `Details` are not available (see screenshot)

<img width="1174" alt="Screenshot 2022-05-02 at 11 05 34" src="https://user-images.githubusercontent.com/27334273/166210902-005d6120-a9a3-4145-a4a7-aba2e25eb503.png">

### Expected Result

No such errors are present

### Actual Result

The `web` container reports the following

```
web_1                                       | 08:48:24 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_users.OrganizationUsersEndpoint' response=200 user_id='2' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/dataguard/users/' caller_ip='<redacted>' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.147 Safari/537.36' rate_limited='False' rate_limit_category='user' request_duration_seconds=0.20262932777404785 rate_limit_type='RateLimitType.NOT_LIMITED' concurrent_limit='300' concurrent_requests='1' reset_time='1651481305' limit='370' remaining='368')
web_1                                       | Traceback (most recent call last):
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
web_1                                       |     return func(self, sql, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
web_1                                       |     return self.cursor.execute(sql, clean_bad_params(params))
web_1                                       | psycopg2.errors.UndefinedColumn: column sentry_organizationmember_teams.role does not exist
web_1                                       | LINE 1: ...", "sentry_organizationmember_teams"."is_active", "sentry_or...
web_1                                       |                                                              ^
web_1                                       |
web_1                                       |
web_1                                       | During handling of the above exception, another exception occurred:
web_1                                       |
web_1                                       | Traceback (most recent call last):
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1                                       |     return self.cursor.execute(sql, params)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
web_1                                       |     raise_the_exception(self.db, e)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
web_1                                       |     return func(self, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
web_1                                       |     return func(self, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
web_1                                       |     raise exc_info[0](msg).with_traceback(exc_info[2])
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
web_1                                       |     return func(self, sql, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
web_1                                       |     return self.cursor.execute(sql, clean_bad_params(params))
web_1                                       | psycopg2.errors.UndefinedColumn: UndefinedColumn('column sentry_organizationmember_teams.role does not exist\nLINE 1: ...", "sentry_organizationmember_teams"."is_active", "sentry_or...\n                                                             ^\n')
web_1                                       | SQL: SELECT "sentry_organizationmember_teams"."id", "sentry_organizationmember_teams"."team_id", "sentry_organizationmember_teams"."organizationmember_id", "sentry_organizationmember_teams"."is_active", "sentry_organizationmember_teams"."role", "sentry_team"."id", "sentry_team"."organization_id", "sentry_team"."slug", "sentry_team"."name", "sentry_team"."status", "sentry_team"."actor_id", "sentry_team"."date_added" FROM "sentry_organizationmember_teams" INNER JOIN "sentry_team" ON ("sentry_organizationmember_teams"."team_id" = "sentry_team"."id") WHERE ("sentry_organizationmember_teams"."is_active" = %s AND "sentry_organizationmember_teams"."organizationmember_id" = %s AND "sentry_team"."status" = %s)
web_1                                       |
web_1                                       | The above exception was the direct cause of the following exception:
web_1                                       |
web_1                                       | Traceback (most recent call last):
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 139, in handle_exception
web_1                                       |     response = super().handle_exception(exc)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
web_1                                       |     self.raise_uncaught_exception(exc)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
web_1                                       |     raise exc
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 254, in dispatch
web_1                                       |     response = handler(request, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/api/endpoints/organization_environments.py", line 23, in get
web_1                                       |     project__in=self.get_projects(request, organization)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/api/bases/organization.py", line 207, in get_projects
web_1                                       |     return self._get_projects_by_id(
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/api/bases/organization.py", line 254, in _get_projects_by_id
web_1                                       |     projects = [p for p in qs if func(p)]
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/api/bases/organization.py", line 254, in <listcomp>
web_1                                       |     projects = [p for p in qs if func(p)]
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/auth/access.py", line 212, in has_project_membership
web_1                                       |     return project in self.projects
web_1                                       |   File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
web_1                                       |     val = self.func(instance)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/auth/access.py", line 128, in projects
web_1                                       |     teams = self.teams
web_1                                       |   File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
web_1                                       |     val = self.func(instance)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/auth/access.py", line 122, in teams
web_1                                       |     return frozenset(self._team_memberships.keys())
web_1                                       |   File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
web_1                                       |     val = self.func(instance)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/auth/access.py", line 112, in _team_memberships
web_1                                       |     return {
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
web_1                                       |     self._fetch_all()
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
web_1                                       |     self._result_cache = list(self._iterable_class(self))
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
web_1                                       |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
web_1                                       |     cursor.execute(sql, params)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/__init__.py", line 545, in execute
web_1                                       |     return real_execute(self, sql, params)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
web_1                                       |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
web_1                                       |     return executor(sql, params, many, context)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1                                       |     return self.cursor.execute(sql, params)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
web_1                                       |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1                                       |     return self.cursor.execute(sql, params)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
web_1                                       |     raise_the_exception(self.db, e)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
web_1                                       |     return func(self, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
web_1                                       |     return func(self, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
web_1                                       |     raise exc_info[0](msg).with_traceback(exc_info[2])
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
web_1                                       |     return func(self, sql, *args, **kwargs)
web_1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
web_1                                       |     return self.cursor.execute(sql, clean_bad_params(params))
web_1                                       | django.db.utils.ProgrammingError: UndefinedColumn('column sentry_organizationmember_teams.role does not exist\nLINE 1: ...", "sentry_organizationmember_teams"."is_active", "sentry_or...\n                                                             ^\n')
web_1                                       | SQL: SELECT "sentry_organizationmember_teams"."id", "sentry_organizationmember_teams"."team_id", "sentry_organizationmember_teams"."organizationmember_id", "sentry_organizationmember_teams"."is_active", "sentry_organizationmember_teams"."role", "sentry_team"."id", "sentry_team"."organization_id", "sentry_team"."slug", "sentry_team"."name", "sentry_team"."status", "sentry_team"."actor_id", "sentry_team"."date_added" FROM "sentry_organizationmember_teams" INNER JOIN "sentry_team" ON ("sentry_organizationmember_teams"."team_id" = "sentry_team"."id") WHERE ("sentry_organizationmember_teams"."is_active" = %s AND "sentry_organizationmember_teams"."organizationmember_id" = %s AND "sentry_team"."status" = %s)
web_1                                       | 08:48:24 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_environments.OrganizationEnvironmentsEndpoint' response=500 user_id='2' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/dataguard/environments/' caller_ip='<redacted>' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.147 Safari/537.36' rate_limited='False' rate_limit_category='user' request_duration_seconds=0.11040997505187988 rate_limit_type='RateLimitType.NOT_LIMITED' concurrent_limit='300' concurrent_requests='2' reset_time='1651481305' limit='370' remaining='367')
web_1                                       | 08:48:24 [ERROR] django.request: Internal Server Error: /api/0/organizations/dataguard/environments/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/dataguard/environments/'>)
```

**Comment by aminvakil** [comment]
I'm guessing migrations have not been ran correctly, how have you updated your self-hosted instance? Please provide exact commands.

**Comment by ml14tlc** [comment]
Hi, thanks for the fast reaction.

I followed the [instructions](https://develop.sentry.dev/self-hosted/releases/#upgrading), i.e., 

* checked out the release tag
* shut down all the services, i.e., `docker-compose down --rmi local --remove-orphans`
* ran `./install.sh`

My understanding was that migrations are run as part of the installation procedure, since 

* the documentation says `Before starting the upgrade, we shut down all the services and then run some data migrations`
* I didn't find any mention of the command I should run

**Comment by aminvakil** [comment]
Can you try running `./install.sh` again, and paste the output? Check if your issue has been resolved or not.

**Comment by ml14tlc** [comment]
@aminvakil thanks it worked this time.
