### ISSUE TITLE
ConnectException

### ISSUE THREAD

**Issue by ckrgithub** [getsentry/self-hosted#1540]
### Version

21.9.0

### Steps to Reproduce

Android Project
my code:

        Sentry.captureMessage("testing SDK setup");
        try {
            throw new Exception("This is a test.");
        } catch (Exception e) {
            Sentry.captureException(e);
        }

        <meta-data android:name="io.sentry.dsn" android:value="@string/sentry_dsn" />
        
        <meta-data android:name="io.sentry.debug" android:value="true" />
        
        <meta-data android:name="io.sentry.session-tracking.timeout-interval-millis" android:value="5000" />
        <meta-data android:name="io.sentry.traces.sample-rate" android:value="1.0" />

### Expected Result

Sentry Id is created after capturing events and exceptions, so we expect them to show up on Sentry dashboard.

### Actual Result

2022-06-16 18:08:35.858 Sentry: Envelope submission failed
    java.lang.IllegalStateException: Sending the event failed.
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:274)
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:197)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     **Caused by: java.net.ConnectException: Failed to connect to /127.0.0.1:9000**
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at io.sentry.transport.HttpConnection.createConnection(HttpConnection.java:145)
        at io.sentry.transport.HttpConnection.send(HttpConnection.java:150)
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:236)
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:197) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920)

**Comment by ckrgithub** [comment]
It is my device problem
