### ISSUE TITLE
Error tasks.store.symbolicate_event.symbolication with disabled symbolicator

### ISSUE THREAD

**Issue by n0tsaved** [getsentry/self-hosted#1603]
### Self-Hosted Version

22.7.0

### CPU Architecture

x86_64

### Docker Version

20.10.12

### Docker Compose Version

2.6.0

### Steps to Reproduce

deploy the whole thing without symbolicator in the docker-compose.yml
`symbolicator.enabled: false` in config.yml

### Expected Result

It should work just fine since this service was optional

### Actual Result

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=3021): Max retries exceeded with url: /symbolicate?timeout=10&scope=38 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa9de334d90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/symbolication.py", line 228, in _do_symbolicate_event
    symbolicated_data = symbolication_function(data)
  File "/usr/local/lib/python3.8/site-packages/sentry/lang/native/processing.py", line 374, in process_payload
    response = symbolicator.process_payload(stacktraces=stacktraces, modules=modules, signal=signal)
  File "/usr/local/lib/python3.8/site-packages/sentry/lang/native/symbolicator.py", line 215, in process_payload
    return self._process(
  File "/usr/local/lib/python3.8/site-packages/sentry/lang/native/symbolicator.py", line 174, in _process
    json_response = create_task()
  File "/usr/local/lib/python3.8/site-packages/sentry/lang/native/symbolicator.py", line 216, in <lambda>
    lambda: self.sess.symbolicate_stacktraces(
  File "/usr/local/lib/python3.8/site-packages/sentry/lang/native/symbolicator.py", line 644, in symbolicate_stacktraces
    return self._create_task("symbolicate", json=json)
  File "/usr/local/lib/python3.8/site-packages/sentry/lang/native/symbolicator.py", line 631, in _create_task
    return self._request(method="post", path=path, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/lang/native/symbolicator.py", line 571, in _request
    response = self.session.request(
  File "/usr/local/lib/python3.8/site-packages/sentry/net/http.py", line 154, in request
    response = _Session.request(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3021): Max retries exceeded with url: /symbolicate?timeout=10&scope=38 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa9de334d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
15:18:18 [ERROR] sentry.errors.events: tasks.store.symbolicate_event.symbolication
```
Also it looks like this event is flooding redis

**Comment by ethanhs** [comment]
> It should work just fine since this service was optional

Hm, I'm not sure if this is true, do you have somewhere where we say that the service is optional?
