### ISSUE TITLE
Unable to invite new users (after moving from 22.6.0 to 22.7.0) IntegrityError /auth/login/{organization_slug}

### ISSUE THREAD

**Issue by IgorAlov** [getsentry/self-hosted#1607]
### Self-Hosted Version

22.7.0

### CPU Architecture

x86_64

### Docker Version

20.10.5

### Docker Compose Version

2.6.0

### Steps to Reproduce

Invite  member via web interface or cli (all the same)
I have already created users early in 22.6.0 sentry (and they are works well), but after migration to 22.7.0 i was unable to invite new users. seems to be problem with SQL. also this problem reported in sentry backend.

### Expected Result

create a new user.

### Actual Result

In web, cli, and after run test.sh i getting the similar problem (`IntegrityError /auth/login/{organization_slug}/`):

```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.NotNullViolation: null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (, null, null, test@example.com, , test@example.com, t, t, t, f, null, f, null, 0, null, 2022-07-29 18:47:15.555159+00, 2022-07-29 18:47:15.555168+00, 30).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.NotNullViolation: NotNullViolation('null value in column "id" violates not-null constraint\nDETAIL:  Failing row contains (, null, null, test@example.com, , test@example.com, t, t, t, f, null, f, null, 0, null, 2022-07-29 18:47:15.555159+00, 2022-07-29 18:47:15.555168+00, 30).\n')
SQL: INSERT INTO "auth_user" ("password", "last_login", "username", "first_name", "email", "is_staff", "is_active", "is_superuser", "is_managed", "is_sentry_app", "is_password_expired", "last_password_change", "flags", "session_nonce", "actor_id", "date_joined", "last_active") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING "auth_user"."id"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 187, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/createuser.py", line 104, in createuser
    user = User.objects.create(**fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/sentry/models/user.py", line 211, in save
    return super().save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 780, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 910, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 544, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
django.db.utils.IntegrityError: NotNullViolation('null value in column "id" violates not-null constraint\nDETAIL:  Failing row contains (, null, null, test@example.com, , test@example.com, t, t, t, f, null, f, null, 0, null, 2022-07-29 18:47:15.555159+00, 2022-07-29 18:47:15.555168+00, 30).\n')
SQL: INSERT INTO "auth_user" ("password", "last_login", "username", "first_name", "email", "is_staff", "is_active", "is_superuser", "is_managed", "is_sentry_app", "is_password_expired", "last_password_change", "flags", "session_nonce", "actor_id", "date_joined", "last_active") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING "auth_user"."id"
++ teardown ERR 44
++ '[' 0 -eq 1 ']'
++ DID_TEAR_DOWN=1
++ '[' ERR '!=' EXIT ']'
++ echo 'An error occurred, caught SIGERR on line 44'
An error occurred, caught SIGERR on line 44
++ echo 'Tearing down ...'
Tearing down ...
++ rm /tmp/tmp.hGdGX0rEW4
++ echo Done.
Done.
+ teardown EXIT 1
+ '[' 1 -eq 1 ']'
+ return 0```

**Comment by ethanhs** [comment]
Can you check the install logs and make sure the migrations were run correctly?

**Comment by IgorAlov** [comment]
@ethanhs everything seems good. but, one mystery thing I have: 
```
Running migrations:
  No migrations to apply.
Creating missing DSNs
Correcting Group.num_comments counter
```
This message will show again and again.

**Comment by ethanhs** [comment]
Did it not run migrations when upgrading?

**Comment by IgorAlov** [comment]
@ethanhs i download a new version of self-hosted sentry 22.7.0, replace my existing folder, updated my config, `run docker compose down`, and the run `install.sh` and the run `docker compose up -d`

**Comment by aminvakil** [comment]
Can you elaborate on replacing your existing folder? AFAIK there are some folders and files which gets created during `./install.sh` in the same directory and you can't just `docker-compose down` in a directory, download a new release and unzip it and execute `./install.sh` in it.
Like these files:
```
        geoip/GeoLite2-City.mmdb
        postgres/wal2json/
        relay/config.yml
        relay/credentials.json
        sentry/config.yml
        sentry/requirements.txt
        sentry/sentry.conf.py
        symbolicator/config.yml
```

**Comment by IgorAlov** [comment]
@aminvakil i did like you recommend, but i have got the same error.
also i copy files `.env` and `sentry/config.yml`

**Comment by IgorAlov** [comment]
also I try to solve the problem by using export and import settings, but also no luck. I think i will run ./reset.sh and try to start from the beginning and create new projects.

**Comment by aminvakil** [comment]
Yeah, most probably, thanks for sharing with us!
You can also use `git` to manage tagging, bumping versions, etc. instead of replacing directories every month.

**Comment by IgorAlov** [comment]
@aminvakil Thanks for the hint with git.

**Comment by aminvakil** [comment]
@IgorAlov Can we close this?

**Comment by IgorAlov** [comment]
@aminvakil yes, shure. thanks a lot
