### ISSUE TITLE
The alert was not triggered

### ISSUE THREAD

**Issue by NeroSolomon** [getsentry/self-hosted#1730]
### Self-Hosted Version

22.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

2.4.1

### Steps to Reproduce

1. Create alert, trigger when number of events in an issue is more than 1 in one hour
2. Then create a few events in an issue in 5 minutes

![image](https://user-images.githubusercontent.com/28894970/192933963-2ed746f5-7318-4c78-b5ea-80f7aa4560d2.png)
![image](https://user-images.githubusercontent.com/28894970/192935087-6699d082-79ee-49a7-b525-e940fee9eb5a.png)

### Expected Result

Alert was triggered

### Actual Result

1. Alert was not triggered
2. But alert was triggered before, i don‘t know why it suddenly fail
![image](https://user-images.githubusercontent.com/28894970/192934355-4215bf78-25d1-41f6-a156-baa82d4bf6c1.png)
3. when i input `sentry_install_log-*.txt | tail -1 | xargs cat`
```txt
-----------------------------------------------------------------

You're all done! Run the following command to get Sentry running:

  docker-compose up -d

-----------------------------------------------------------------
```
4. when i input `docker-compose logs`
```txt
sentry-self-hosted-post-process-forwarder-1                    | 06:51:50 [INFO] batching-kafka-consumer: New partitions assigned: [TopicPartition{topic=events,partition=0,offset=-1001,error=None}]
sentry-self-hosted-post-process-forwarder-1                    | /usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:555: DeprecatedSettingWarning: The SENTRY_URL_PREFIX setting is deprecated. Please use SENTRY_OPTIONS['system.url-prefix'] instead.
sentry-self-hosted-post-process-forwarder-1                    |   warnings.warn(DeprecatedSettingWarning(old, "SENTRY_OPTIONS['%s']" % new))
sentry-self-hosted-post-process-forwarder-1                    | Traceback (most recent call last):
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/bin/sentry", line 8, in <module>
sentry-self-hosted-post-process-forwarder-1                    |     sys.exit(main())
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 188, in main
sentry-self-hosted-post-process-forwarder-1                    |     func(**kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
sentry-self-hosted-post-process-forwarder-1                    |     return self.main(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
sentry-self-hosted-post-process-forwarder-1                    |     rv = self.invoke(ctx)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-post-process-forwarder-1                    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-post-process-forwarder-1                    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
sentry-self-hosted-post-process-forwarder-1                    |     return ctx.invoke(self.callback, **ctx.params)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-1                    |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-post-process-forwarder-1                    |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
sentry-self-hosted-post-process-forwarder-1                    |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-1                    |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-post-process-forwarder-1                    |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
sentry-self-hosted-post-process-forwarder-1                    |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-1                    |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 358, in post_process_forwarder
sentry-self-hosted-post-process-forwarder-1                    |     eventstream.run_post_process_forwarder(
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
sentry-self-hosted-post-process-forwarder-1                    |     context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 288, in run_post_process_forwarder
sentry-self-hosted-post-process-forwarder-1                    |     self.run_batched_consumer(
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 273, in run_batched_consumer
sentry-self-hosted-post-process-forwarder-1                    |     consumer.run()
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/batching_kafka_consumer.py", line 323, in run
sentry-self-hosted-post-process-forwarder-1                    |     self._run_once()
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/batching_kafka_consumer.py", line 341, in _run_once
sentry-self-hosted-post-process-forwarder-1                    |     raise Exception(msg.error())
sentry-self-hosted-post-process-forwarder-1                    | Exception: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
sentry-self-hosted-post-process-forwarder-1                    | Updating certificates in /etc/ssl/certs...
sentry-self-hosted-post-process-forwarder-1                    | 0 added, 0 removed; done.
sentry-self-hosted-post-process-forwarder-1                    | Running hooks in /etc/ca-certificates/update.d...
sentry-self-hosted-post-process-forwarder-1                    | done.
sentry-self-hosted-post-process-forwarder-1                    | 06:51:58 [INFO] sentry.plugins.github: apps-not-configured
sentry-self-hosted-post-process-forwarder-1                    | Traceback (most recent call last):
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 123, in setup_once
sentry-self-hosted-post-process-forwarder-1                    |     _patch_rediscluster()
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 88, in _patch_rediscluster
sentry-self-hosted-post-process-forwarder-1                    |     pipeline_cls = rediscluster.ClusterPipeline
sentry-self-hosted-post-process-forwarder-1                    | AttributeError: module 'rediscluster' has no attribute 'ClusterPipeline'
sentry-self-hosted-post-process-forwarder-1                    | 06:51:58 [ERROR] sentry_sdk.errors: Error occurred while patching `rediscluster` library
sentry-self-hosted-post-process-forwarder-1                    | 06:51:58 [INFO] sentry.eventstream.kafka.backend: Starting post process forwarder to consume all messages
sentry-self-hosted-post-process-forwarder-1                    | 06:51:58 [INFO] sentry.eventstream.kafka.postprocessworker: Starting post process forwarder with 1 threads
sentry-self-hosted-post-process-forwarder-1                    | 06:52:35 [INFO] batching-kafka-consumer: New partitions assigned: [TopicPartition{topic=events,partition=0,offset=-1001,error=None}]
sentry-self-hosted-post-process-forwarder-1                    | /usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:555: DeprecatedSettingWarning: The SENTRY_URL_PREFIX setting is deprecated. Please use SENTRY_OPTIONS['system.url-prefix'] instead.
sentry-self-hosted-post-process-forwarder-1                    |   warnings.warn(DeprecatedSettingWarning(old, "SENTRY_OPTIONS['%s']" % new))
sentry-self-hosted-post-process-forwarder-1                    | Traceback (most recent call last):
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/bin/sentry", line 8, in <module>
sentry-self-hosted-post-process-forwarder-1                    |     sys.exit(main())
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 188, in main
sentry-self-hosted-post-process-forwarder-1                    |     func(**kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
sentry-self-hosted-post-process-forwarder-1                    |     return self.main(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
sentry-self-hosted-post-process-forwarder-1                    |     rv = self.invoke(ctx)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-post-process-forwarder-1                    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-post-process-forwarder-1                    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
sentry-self-hosted-post-process-forwarder-1                    |     return ctx.invoke(self.callback, **ctx.params)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-1                    |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-post-process-forwarder-1                    |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
sentry-self-hosted-post-process-forwarder-1                    |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-1                    |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-post-process-forwarder-1                    |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
sentry-self-hosted-post-process-forwarder-1                    |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-1                    |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 358, in post_process_forwarder
sentry-self-hosted-post-process-forwarder-1                    |     eventstream.run_post_process_forwarder(
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
sentry-self-hosted-post-process-forwarder-1                    |     context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 288, in run_post_process_forwarder
sentry-self-hosted-post-process-forwarder-1                    |     self.run_batched_consumer(
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 273, in run_batched_consumer
sentry-self-hosted-post-process-forwarder-1                    |     consumer.run()
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/batching_kafka_consumer.py", line 323, in run
sentry-self-hosted-post-process-forwarder-1                    |     self._run_once()
sentry-self-hosted-post-process-forwarder-1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/batching_kafka_consumer.py", line 341, in _run_once
sentry-self-hosted-post-process-forwarder-1                    |     raise Exception(msg.error())
sentry-self-hosted-post-process-forwarder-1                    | Exception: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
sentry-self-hosted-post-process-forwarder-1                    | Updating certificates in /etc/ssl/certs...
```

**Comment by NeroSolomon** [comment]
the uploading image is：
![image](https://user-images.githubusercontent.com/28894970/192935087-6699d082-79ee-49a7-b525-e940fee9eb5a.png)

**Comment by hubertdeng123** [comment]
Hi there! We actually have seen this error before and have troubleshooting steps here:
https://develop.sentry.dev/self-hosted/troubleshooting/

We're still looking for a more longer term fix but could you let me know if that resolves your issue?

**Comment by NeroSolomon** [comment]
> Hi there! We actually have seen this error before and have troubleshooting steps here: https://develop.sentry.dev/self-hosted/troubleshooting/
> 
> We're still looking for a more longer term fix but could you let me know if that resolves your issue?

Thx! I try first.

**Comment by NeroSolomon** [comment]
The alert can be triggered by finishing this step: https://develop.sentry.dev/self-hosted/troubleshooting/#postgres. Thank you so much!

**Comment by hubertdeng123** [comment]
awesome! glad to hear that
