### ISSUE TITLE
Unable to run Sentry with SSL on the web root. Or just with the SSL at all.

### ISSUE THREAD

**Issue by Matys333** [getsentry/self-hosted#1797]
### Self-Hosted Version

22.11.0.dev0

### CPU Architecture

x86_64

### Docker Version

20.10.20

### Docker Compose Version

1.29.2

### Steps to Reproduce

Trying to change the Sentry from port 9000 to the web root, which is on HTTPS.
I have a Nginx running on the server with SSL, i'd like Sentry to run in HTTPS too, and on the web root (port 443) instead of the 9000.

### Expected Result

A Sentry running on port 443 with SSL, ideally on the root of the web.

### Actual Result

Currently I only could access Sentry via HTTP and port 9000 and not at all after I tried to do what I intend to.
Should I redirect all 9000 Sentry points to another or do it some other way? I was trying to follow [this solved problem](https://github.com/getsentry/self-hosted/issues/1317).

For some reason no matter which privileges I give to the files the nginx does not see the SSL certificates in "/certificates/" folder.
But I believe it's not my only problem. Thanks in advance.

So far what I've done is:
Installed an nginx with SSL certificate on the server.
And changed the following:
1. ~/self-hosted/nginx/nginx.conf
```
user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;


events {
        worker_connections 1024;
}


http {
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        reset_timedout_connection on;

        keepalive_timeout 75s;

        gzip off;
        server_tokens off;

        server_names_hash_bucket_size 64;
        types_hash_max_size 2048;
        types_hash_bucket_size 64;
        client_max_body_size 100m;

        proxy_http_version 1.1;
        proxy_redirect off;
        proxy_buffering off;
        proxy_next_upstream error timeout invalid_header http_502 http_503 non_idempotent;
        proxy_next_upstream_tries 2;

        # Remove the Connection header if the client sends it,
        # it could be "close" to close a keepalive connection
        proxy_set_header Connection '';
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Request-Id $request_id;
        proxy_read_timeout 30s;
        proxy_send_timeout 5s;

        upstream relay {
                server relay:3000;
        }

        upstream sentry {
                server web:9000;
        }

        server {
                listen 80;
                server_name example.cz;
                rewrite ^(.*)$ https://$host$1 permanent;
        }

        server {
                listen 443 ssl;
                server_name example.cz;
                ssl_certificate "/certificates/fullchain.pem"; # The keys generated by certbot and moved to /certificates/ folder.
                ssl_certificate_key "/certificates/privkey.pem";
                ssl_session_timeout 5m;
                ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
                ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
                ssl_prefer_server_ciphers on;

        location /api/store/ {
            proxy_pass http://relay;
        }
        location ~ ^/api/[1-9]\d*/ {
            proxy_pass http://relay;
        }
        location / {
            proxy_pass http://sentry;
    }
  }
}

```

2. ~/self-hosted/docker-compose.yml
```
 nginx:
    <<: *restart_policy
    ports:
      - "80/tcp"
      - "$SENTRY_BIND:443/tcp"
    image: "nginx:1.22.0-alpine"
    volumes:
      - type: bind
        read_only: true
        source: ./nginx
        target: /etc/nginx
      - sentry-nginx-cache:/var/cache/nginx
    depends_on:
      - web
      - relay
```

3. ~/self-hosted/sentry/config.yml

```
system.secret-key: 'my_key'

filestore.backend: 'filesystem'
filestore.options:
  location: '/data/files'
dsym.cache-path: '/data/dsym-cache'
releasefile.cache-path: '/data/releasefile-cache'

system.internal-url-prefix: 'https://example.cz'     # Not sure how this should be really like
system.url-prefix: 'https://example.cz'

symbolicator.enabled: true
symbolicator.options:
  url: "http://symbolicator:3021"

transaction-events.force-disable-internal-project: true
```

4. ~/self-hosted/sentry/sentry.conf.py

```
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
```

nginx_1 logs - problem with the certificate

```
nginx_1                                     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1                                     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1                                     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1                                     | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_1                                     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1                                     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_1                                     | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_1                                     | 2022/11/03 12:03:34 [emerg] 1#1: cannot load certificate "/certificates/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/certificates/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx_1                                     | nginx: [emerg] cannot load certificate "/certificates/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/certificates/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

web_1 log

`web_1  | 11:29:42 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.relay.health_check.RelayHealthCheck' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/live/' caller_ip='172.21.0.17' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.002114534378051758 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')`

worker_1 log

```
worker_1                                    | worker: Warm shutdown (MainProcess)
worker_1                                    | Updating certificates in /etc/ssl/certs...
worker_1                                    | 0 added, 0 removed; done.
worker_1                                    | Running hooks in /etc/ca-certificates/update.d...
worker_1                                    | done.
worker_1                                    | /usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
worker_1                                    |   if key is '':
worker_1                                    | /usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
worker_1                                    |   if key_extra_len is 0:
worker_1                                    | 11:22:24 [INFO] sentry.plugins.github: apps-not-configured
worker_1                                    | 11:22:31 [INFO] sentry.bgtasks: bgtask.spawn (task_name='sentry.bgtasks.clean_dsymcache:clean_dsymcache')
worker_1                                    | 11:22:31 [INFO] sentry.bgtasks: bgtask.spawn (task_name='sentry.bgtasks.clean_releasefilecache:clean_releasefilecache')
worker_1                                    |
worker_1                                    |  -------------- celery@131b883a30a4 v4.4.7 (cliffs)
worker_1                                    | --- ***** -----
worker_1                                    | -- ******* ---- Linux-5.15.0-52-generic-x86_64-with-glibc2.2.5 2022-11-03 11:23:08
worker_1                                    | - *** --- * ---
worker_1                                    | - ** ---------- [config]
worker_1                                    | - ** ---------- .> app:         sentry:0x7f94ff5683d0
worker_1                                    | - ** ---------- .> transport:   redis://redis:6379/0
worker_1                                    | - ** ---------- .> results:     disabled://
worker_1                                    | - *** --- * --- .> concurrency: 2 (prefork)
worker_1                                    | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
worker_1                                    | --- ***** -----
worker_1                                    |  -------------- [queues]
worker_1                                    |                 .> activity.notify  exchange=default(direct) key=activity.notify
worker_1                                    |                 .> alerts           exchange=default(direct) key=alerts
worker_1                                    |                 .> app_platform     exchange=default(direct) key=app_platform
worker_1                                    |                 .> appstoreconnect  exchange=default(direct) key=sentry.tasks.app_store_connect.#
worker_1                                    |                 .> assemble         exchange=default(direct) key=assemble
worker_1                                    |                 .> auth             exchange=default(direct) key=auth
worker_1                                    |                 .> buffers.incr     exchange=default(direct) key=buffers.incr
worker_1                                    |                 .> buffers.process_pending exchange=default(direct) key=buffers.process_pending
worker_1                                    |                 .> cleanup          exchange=default(direct) key=cleanup
worker_1                                    |                 .> code_owners      exchange=default(direct) key=code_owners
worker_1                                    |                 .> commits          exchange=default(direct) key=commits
worker_1                                    |                 .> counters-0       exchange=default(direct) key=counters-0
worker_1                                    |                 .> data_export      exchange=default(direct) key=data_export
worker_1                                    |                 .> default          exchange=default(direct) key=default
worker_1                                    |                 .> digests.delivery exchange=default(direct) key=digests.delivery
worker_1                                    |                 .> digests.scheduling exchange=default(direct) key=digests.scheduling
worker_1                                    |                 .> email            exchange=default(direct) key=email
worker_1                                    |                 .> events.preprocess_event exchange=default(direct) key=events.preprocess_event
worker_1                                    |                 .> events.process_event exchange=default(direct) key=events.process_event
worker_1                                    |                 .> events.reprocess_events exchange=default(direct) key=events.reprocess_events
worker_1                                    |                 .> events.reprocessing.preprocess_event exchange=default(direct) key=events.reprocessing.preprocess_event
worker_1                                    |                 .> events.reprocessing.process_event exchange=default(direct) key=events.reprocessing.process_event
worker_1                                    |                 .> events.reprocessing.symbolicate_event exchange=default(direct) key=events.reprocessing.symbolicate_event
worker_1                                    |                 .> events.reprocessing.symbolicate_event_low_priority exchange=default(direct) key=events.reprocessing.symbolicate_event_low_priority
worker_1                                    |                 .> events.save_event exchange=default(direct) key=events.save_event
worker_1                                    |                 .> events.save_event_attachments exchange=default(direct) key=events.save_event_attachments
worker_1                                    |                 .> events.save_event_transaction exchange=default(direct) key=events.save_event_transaction
worker_1                                    |                 .> events.symbolicate_event exchange=default(direct) key=events.symbolicate_event
worker_1                                    |                 .> events.symbolicate_event_low_priority exchange=default(direct) key=events.symbolicate_event_low_priority
worker_1                                    |                 .> files.delete     exchange=default(direct) key=files.delete
worker_1                                    |                 .> get_suspect_resolutions exchange=default(direct) key=get_suspect_resolutions
worker_1                                    |                 .> get_suspect_resolutions_releases exchange=default(direct) key=get_suspect_resolutions_releases
worker_1                                    |                 .> group_owners.process_commit_context exchange=default(direct) key=group_owners.process_commit_context
worker_1                                    |                 .> group_owners.process_suspect_commits exchange=default(direct) key=group_owners.process_suspect_commits
worker_1                                    |                 .> incident_snapshots exchange=default(direct) key=incident_snapshots
worker_1                                    |                 .> incidents        exchange=default(direct) key=incidents
worker_1                                    |                 .> integrations     exchange=default(direct) key=integrations
worker_1                                    |                 .> merge            exchange=default(direct) key=merge
worker_1                                    |                 .> options          exchange=default(direct) key=options
worker_1                                    |                 .> post_process_errors exchange=default(direct) key=post_process_errors
worker_1                                    |                 .> post_process_transactions exchange=default(direct) key=post_process_transactions
worker_1                                    |                 .> profiles.process exchange=default(direct) key=profiles.process
worker_1                                    |                 .> relay_config     exchange=default(direct) key=relay_config
worker_1                                    |                 .> relay_config_bulk exchange=default(direct) key=relay_config_bulk
worker_1                                    |                 .> release_health.duplex exchange=default(direct) key=release_health.duplex
worker_1                                    |                 .> releasemonitor   exchange=default(direct) key=releasemonitor
worker_1                                    |                 .> replays.delete_replay exchange=default(direct) key=replays.delete_replay
worker_1                                    |                 .> replays.ingest_replay exchange=default(direct) key=replays.ingest_replay
worker_1                                    |                 .> reports.deliver  exchange=default(direct) key=reports.deliver
worker_1                                    |                 .> reports.prepare  exchange=default(direct) key=reports.prepare
worker_1                                    |                 .> search           exchange=default(direct) key=search
worker_1                                    |                 .> sentry_metrics.indexer exchange=default(direct) key=sentry_metrics.indexer
worker_1                                    |                 .> similarity.index exchange=default(direct) key=similarity.index
worker_1                                    |                 .> sleep            exchange=default(direct) key=sleep
worker_1                                    |                 .> stats            exchange=default(direct) key=stats
worker_1                                    |                 .> subscriptions    exchange=default(direct) key=subscriptions
worker_1                                    |                 .> symbolications.compute_low_priority_projects exchange=default(direct) key=symbolications.compute_low_priority_projects
worker_1                                    |                 .> triggers-0       exchange=default(direct) key=triggers-0
worker_1                                    |                 .> unmerge          exchange=default(direct) key=unmerge
worker_1                                    |                 .> update           exchange=default(direct) key=update
worker_1                                    |
worker_1                                    | 11:23:21 [INFO] sentry.tasks.update_user_reports: update_user_reports.records_updated (reports_to_update=0 reports_with_event=0 updated_reports=0)
worker_1                                    | 11:23:22 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
worker_1                                    | 11:26:46 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
worker_1                                    | 11:31:46 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
worker_1                                    | 11:36:46 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
worker_1                                    | 11:36:46 [INFO] sentry.tasks.update_user_reports: update_user_reports.records_updated (reports_to_update=0 reports_with_event=0 updated_reports=0)
worker_1                                    | 11:41:46 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
worker_1                                    | 11:46:46 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
worker_1                                    | 11:51:46 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
worker_1                                    | 11:51:46 [INFO] sentry.tasks.update_user_reports: update_user_reports.records_updated (reports_to_update=0 reports_with_event=0 updated_reports=0)
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
worker_1                                    |     conn = connection.create_connection(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
worker_1                                    |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
worker_1                                    |   File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
worker_1                                    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
worker_1                                    | socket.gaierror: [Errno -2] Name or service not known
worker_1                                    |
worker_1                                    | During handling of the above exception, another exception occurred:
worker_1                                    |
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 700, in urlopen
worker_1                                    |     self._prepare_proxy(conn)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
worker_1                                    |     conn.connect()
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
worker_1                                    |     self.sock = conn = self._new_conn()
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
worker_1                                    |     raise NewConnectionError(
worker_1                                    | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f94fddb1eb0>: Failed to establish a new connection: [Errno -2] Name or service not known
worker_1                                    |
worker_1                                    | During handling of the above exception, another exception occurred:
worker_1                                    |
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
worker_1                                    |     resp = conn.urlopen(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
worker_1                                    |     retries = retries.increment(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
worker_1                                    |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
worker_1                                    | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sentry.io', port=443): Max retries exceeded with url: /remote/beacon/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f94fddb1eb0>: Failed to establish a new connection: [Errno -2] Name or service not known')))
worker_1                                    |
worker_1                                    | During handling of the above exception, another exception occurred:
worker_1                                    |
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/beacon.py", line 92, in send_beacon
worker_1                                    |     request = safe_urlopen(BEACON_URL, json=payload, timeout=5)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/http.py", line 98, in safe_urlopen
worker_1                                    |     response = session.request(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/net/http.py", line 154, in request
worker_1                                    |     response = _Session.request(self, *args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
worker_1                                    |     resp = self.send(prep, **send_kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
worker_1                                    |     r = adapter.send(request, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
worker_1                                    |     raise ProxyError(e, request=request)
worker_1                                    | requests.exceptions.ProxyError: HTTPSConnectionPool(host='sentry.io', port=443): Max retries exceeded with url: /remote/beacon/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f94fddb1eb0>: Failed to establish a new connection: [Errno -2] Name or service not known')))
worker_1                                    | 11:55:54 [WARNING] beacon: beacon.failed (install_id='ab9541ece3b8cc27f2347ef0bb1aaefe39be12bf')
worker_1                                    | 11:56:46 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
worker_1                                    | 12:01:46 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
worker_1                                    | 12:06:46 [INFO] sentry.tasks.update_user_reports: update_user_reports.records_updated (reports_to_update=0 reports_with_event=0 updated_reports=0)
worker_1                                    | 12:06:46 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
worker_1                                    | 12:11:46 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
```

**Comment by hubertdeng123** [comment]
Looks like you'd need to change `SENTRY_BIND` to 443 if you haven't already. Where is the location of your certificates folder?

**Comment by Matys333** [comment]
@hubertdeng123 So I've changed SENTRY_BIND in .env to 443 (should I change it everywhere, like "server web:9000;" in nginx.conf also?), but when I try to do docker-comose up after, it goes into error, that the port is already in use:

`ERROR: for sentry-self-hosted_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint sentry-self-hosted_nginx_1 (bc320be210111f337bb716e735740174b81d977d68046bf149ad7cfb3afe3235): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use`

The certificates folder is in the sentry root, so ~/self-hosted/certificates.

**Comment by hubertdeng123** [comment]
Is there any reason you want to be running the web container on port 443? That's going to create some pain with the nginx as you can see above. You can block connections to access port 9000 from the outside, but allow connections internally to port 9000. In fact, that's something I'd recommend.

Something pretty important I'm noticing is that your `system.internal-url-prefix` doesn't have a port. You should make that the same port as your web service.

**Comment by aminvakil** [comment]
Use a load balancer in front of self-hosted, put your ssl certificate on it easily, configure whatever you like on it, enjoy!

**Comment by NathanQ** [comment]
Just dipping my toes in to the self-hosting and needing https protocol for an integration and notice the productionalizing section could describe at least a basic setup. I used caddy, but I still don't have some things set correctly like static stuff for the favicon or api/1/envelope fails (what does that do? everything seems to work) `Failed to load resource: the server responded with a status of 403 ()` for csrf verification over http web server ip to https webdomain requests. 

Here's what I did:

```yml
# self-hosted/caddy/docker-compose.yml
version: "3.7"

services:
  caddy:
    image: caddy:2.6.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
```

```yml
# self-hosted/caddy/Caddyfile
{
    email myemail@example.com
}

mysite.com {
    reverse_proxy http://web:9000
    # need to get the static stuff maybe that's the relay stuff noted in the nginx files?
}
```

```yml
self-hosted/sentry/config.yml
# system.url-prefix not in here so add it anywhere
system.url-prefix: mysite.com
```

_with any conf changes do `docker compose restart web worker cron sentry-cleanup`_

## to run caddy with sentry:
`docker compose down`
`export COMPOSE_FILE=docker-compose.yml:caddy/docker-compose.yml`
`docker compose up -d`

**Comment by Matys333** [comment]
@NathanQ Thank you! I was able to make it work with Caddy as well. :)

**Comment by Matys333** [comment]
Update: So the problem was that I had `system.url-prefix: https://mysite.com`, which generated the Sentry DSN with HTTPS, which caused the later problems. If i put only mysite.com, the DSN is just an empty string.

It only works, if the Sentry dsn referers to the server IP with HTTP, and the server is still on HTTPS accepting new issues, when I comment out the system.url-prefix.
I now do get an HTTPS warning, that parts of the page aren't secure, but that shouldn't be a problem right?
 
So thanks to all of you, finally got it working. Hope this helps someone too.

**Comment by ethanhs** [comment]
Glad you got it working, do you think we are good to close this @Matys333 ?
