### ISSUE TITLE
Alerts don' work

### ISSUE THREAD

**Issue by luk156** [getsentry/self-hosted#1816]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.17, build 100c701

### Docker Compose Version

1.29.2

### Steps to Reproduce

we have do a fresh install

### Expected Result

we have a lot of issues but the alert below never trigger:

<img width="325" alt="Schermata 2022-11-15 alle 23 53 19" src="https://user-images.githubusercontent.com/1016684/202041803-9d95cfa5-4839-4bad-aa80-6aec678664a2.png">

### Actual Result

no events

**Comment by luk156** [comment]
Also wen we have  a new issue on all project no mail was sent

**Comment by hubertdeng123** [comment]
Sorry to hear that, would you be able to post some logs in your docker containers? snuba in particular?

**Comment by luk156** [comment]
docker logs sentry-self-hosted_snuba-consumer_1

2022-11-17 11:13:23,985 Completed processing <Batch: 1 message, open for 1.03 seconds>.
2022-11-17 11:19:22,216 Completed processing <Batch: 1 message, open for 1.03 seconds>.
2022-11-17 11:26:32,667 Completed processing <Batch: 1 message, open for 1.05 seconds>.
2022-11-17 11:28:41,146 Completed processing <Batch: 1 message, open for 1.03 seconds>.
2022-11-17 11:39:30,071 Completed processing <Batch: 1 message, open for 1.03 seconds>.


docker logs sentry-self-hosted_snuba-api_1

*** Starting uWSGI 2.0.20 (64bit) on [Wed Nov 16 10:35:36 2022] ***
compiled with version: 8.3.1 20190311 (Red Hat 8.3.1-3) on 11 November 2021 18:13:24
os: Linux-5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022
nodename: db11a0d47531
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /usr/src/snuba
detected binary path: /usr/local/bin/python
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 0.0.0.0:1218 fd 3
Python version: 3.8.13 (default, Aug 23 2022, 09:42:19)  [GCC 10.2.1 20210110]
--- Python VM already initialized ---
Python main interpreter initialized at 0x555fecc6b870
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
initialized 38 metrics
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 10, cores: 1)
metrics collector thread started
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x555fecc6b870 pid: 10 (default app)


docker logs sentry-self-hosted_snuba-subscription-consumer-events_1

2022-11-16 10:35:58,508 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_consumer.py", line 126, in poll
    message = self.__consumer.poll(timeout)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 450, in poll
    raise ConsumerError(str(error))
arroyo.errors.ConsumerError: KafkaError{code=COORDINATOR_LOAD_IN_PROGRESS,val=14,str="JoinGroup failed: Broker: Coordinator load in progress"}
2022-11-16 10:36:21,160 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 350450}
%4|1668594981.164|OFFSET|rdkafka#consumer-2| [thrd:main]: snuba-commit-log [0]: offset reset (at offset 350450, broker 1001) to END: fetch failed due to requested offset not available on the broker: Broker: Offset out of range

**Comment by hubertdeng123** [comment]
Seems to be related to https://github.com/getsentry/self-hosted/issues/478.

We have a troubleshooting doc here:
https://develop.sentry.dev/self-hosted/troubleshooting/
