### ISSUE TITLE
Errors in multiple containers after new install 

### ISSUE THREAD

**Issue by darkfallen777** [getsentry/self-hosted#1822]
### Self-Hosted Version

Sentry 22.12.0.dev0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

2.11.1

### Steps to Reproduce

installed the build
corrected config.yaml, added url prefix
one sentry-self-hosted-local "/etc/sentry/entrypo..." container is not coming up.   17 hours ago Restarting (1) 51 seconds ago

### Expected Result

full functionality

### Actual Result

07:28:43 [INFO] sentry.plugins.github: apps-not-configured
07:28:43 [INFO] sentry.eventstream.kafka.backend: Starting post process forwarder to consume None messages
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 373, in post_process_forwarder
    eventstream.run_post_process_forwarder(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 352, in run_post_process_forwarder
    self.run_consumer(
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 302, in run_consumer
    raise ValueError("Invalid entity")
ValueError: Invalid entity
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
07:29:49 [INFO] sentry.plugins.github: apps-not-configured
07:29:49 [INFO] sentry.eventstream.kafka.backend: Starting post process forwarder to consume None messages
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 373, in post_process_forwarder
    eventstream.run_post_process_forwarder(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 352, in run_post_process_forwarder
    self.run_consumer(
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 302, in run_consumer
    raise ValueError("Invalid entity")
ValueError: Invalid entity
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
07:30:55 [INFO] sentry.plugins.github: apps-not-configured
07:30:55 [INFO] sentry.eventstream.kafka.backend: Starting post process forwarder to consume None messages
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 373, in post_process_forwarder
    eventstream.run_post_process_forwarder(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 352, in run_post_process_forwarder
    self.run_consumer(
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 302, in run_consumer
    raise ValueError("Invalid entity")
ValueError: Invalid entity
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
07:32:00 [INFO] sentry.plugins.github: apps-not-configured
07:32:01 [INFO] sentry.eventstream.kafka.backend: Starting post process forwarder to consume None messages
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 373, in post_process_forwarder
    eventstream.run_post_process_forwarder(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 352, in run_post_process_forwarder
    self.run_consumer(
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 302, in run_consumer
    raise ValueError("Invalid entity")
ValueError: Invalid entity

### Event ID

[
    {
        "Id": "63d9f77987a15de54b287f6f0d1223921bd4f3a32e262e7042a7bbc95c4eaed6",
        "Created": "2022-11-16T14:02:31.257698783Z",
        "Path": "/etc/sentry/entrypoint.sh",
        "Args": [
            "run",
            "post-process-forwarder",
            "--commit-batch-size",
            "1"
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2022-11-17T07:30:51.009712214Z",
            "FinishedAt": "2022-11-17T07:30:55.945398453Z"
        },
        "Image": "sha256:37522109e219857057c7e592c9fc011cc105495abb5c95177ce4e3802a3b5f9a",
        "ResolvConfPath": "/var/lib/docker/containers/63d9f77987a15de54b287f6f0d1223921bd4f3a32e262e7042a7bbc95c4eaed6/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/63d9f77987a15de54b287f6f0d1223921bd4f3a32e262e7042a7bbc95c4eaed6/hostname",
        "HostsPath": "/var/lib/docker/containers/63d9f77987a15de54b287f6f0d1223921bd4f3a32e262e7042a7bbc95c4eaed6/hosts",
        "LogPath": "/var/lib/docker/containers/63d9f77987a15de54b287f6f0d1223921bd4f3a32e262e7042a7bbc95c4eaed6/63d9f77987a15de54b287f6f0d1223921bd4f3a32e262e7042a7bbc95c4eaed6-json.log",
        "Name": "/sentry-self-hosted-post-process-forwarder-1",
        "RestartCount": 965,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/storage/sentry_sh/sentry-data:/data:rw",
                "/storage/self-hosted/sentry:/etc/sentry:rw",
                "/storage/self-hosted/geoip:/geoip:ro",
                "/storage/self-hosted/certificates:/usr/local/share/ca-certificates:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "env": "os,customer",
                    "labels": "sentry",
                    "max-file": "3",
                    "max-size": "100k"
                }
            },
            "NetworkMode": "sentry-self-hosted_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/storage/self-hosted/certificates",
                "Destination": "/usr/local/share/ca-certificates",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/storage/sentry_sh/sentry-data",
                "Destination": "/data",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/storage/self-hosted/sentry",
                "Destination": "/etc/sentry",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/storage/self-hosted/geoip",
                "Destination": "/geoip",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "63d9f77987a1",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "9000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "SENTRY_MAIL_HOST",
                "PYTHONUSERBASE=/data/custom-packages",
                "SENTRY_CONF=/etc/sentry",
                "SNUBA=http://snuba-api:1218",
                "DEFAULT_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt",
                "REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt",
                "GRPC_DEFAULT_SSL_ROOTS_FILE_PATH_ENV_VAR=/etc/ssl/certs/ca-certificates.crt",
                "SENTRY_EVENT_RETENTION_DAYS=90",
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.8.13",
                "PYTHON_PIP_VERSION=22.0.4",
                "PYTHON_SETUPTOOLS_VERSION=57.5.0",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5eaac1050023df1f5c98b173b248c260023f2278/public/get-pip.py",
                "PYTHON_GET_PIP_SHA256=5aefe6ade911d997af080b315ebcb7f882212d070465df544e1175ac2be519b4",
                "GOSU_VERSION=1.12",
                "GOSU_SHA256=0f25a21cf64e58078057adc78f38705163c1d564a959ff30a891c31917011a54",
                "TINI_VERSION=0.19.0",
                "TINI_SHA256=93dcc18adc78c65a028a84799ecf8ad40c936fdfc5f2a57b1acda5a8117fa82c",
                "PIP_NO_CACHE_DIR=1",
                "PIP_DISABLE_PIP_VERSION_CHECK=1",
                "UWSGI_PROFILE_OVERRIDE=ssl=false;xml=false;routing=false",
                "UWSGI_NEED_PLUGIN=/var/lib/uwsgi/dogstatsd",
                "GRPC_POLL_STRATEGY=epoll1",
                "SENTRY_BUILD=2df578d19a3c5ad555d6371d13740d40781b5718"
            ],
            "Cmd": [
                "run",
                "post-process-forwarder",
                "--commit-batch-size",
                "1"
            ],
            "Image": "sentry-self-hosted-local",
            "Volumes": {
                "/data": {},
                "/etc/sentry": {},
                "/geoip": {},
                "/usr/local/share/ca-certificates": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/etc/sentry/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "753940d6208016061580bc838e86e362cbd546752fbfca8b26dbd460cc385a90",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "snuba-sessions-consumer:service_started,smtp:service_started,memcached:service_started,snuba-consumer:service_started,kafka:service_healthy,snuba-subscription-consumer-events:service_started,redis:service_healthy,snuba-transactions-consumer:service_started,postgres:service_healthy,snuba-outcomes-consumer:service_started,snuba-subscription-consumer-transactions:service_started,snuba-replacer:service_started,snuba-api:service_started,symbolicator:service_started",
                "com.docker.compose.image": "sha256:37522109e219857057c7e592c9fc011cc105495abb5c95177ce4e3802a3b5f9a",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "sentry-self-hosted",
                "com.docker.compose.project.config_files": "/storage/self-hosted/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/storage/self-hosted",
                "com.docker.compose.service": "post-process-forwarder",
                "com.docker.compose.version": "2.11.1",
                "maintainer": "oss@sentry.io",
                "org.opencontainers.image.authors": "oss@sentry.io",
                "org.opencontainers.image.description": "Sentry runtime image",
                "org.opencontainers.image.documentation": "https://develop.sentry.dev/self-hosted/",
                "org.opencontainers.image.licenses": "https://github.com/getsentry/sentry/blob/2df578d19a3c5ad555d6371d13740d40781b5718/LICENSE",
                "org.opencontainers.image.revision": "2df578d19a3c5ad555d6371d13740d40781b5718",
                "org.opencontainers.image.source": "https://github.com/getsentry/sentry/tree/2df578d19a3c5ad555d6371d13740d40781b5718/",
                "org.opencontainers.image.title": "Sentry",
                "org.opencontainers.image.url": "https://sentry.io/",
                "org.opencontainers.image.vendor": "Functional Software, Inc."
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "f033d2f5ccc8e2d7f22b7e3dac96d8e3ce26035598c53fe181d79273ea2e32a3",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/f033d2f5ccc8",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "sentry-self-hosted_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "sentry-self-hosted-post-process-forwarder-1",
                        "post-process-forwarder",
                        "63d9f77987a1"
                    ],
                    "NetworkID": "a2b816d48e649c6a92b71db28e163f78b775e2ce28f6e086f711e3f414219e00",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by hubertdeng123** [comment]
Is the installer completing succesfully or is it erroring out beforehand? Just to confirm, this is a clean install?

**Comment by darkfallen777** [comment]
это не чистая установка, мною вносятся изменения volume
