### ISSUE TITLE
Container sentry-self-hosted-post-process-forwarder-1 restarting after Kafka issue

### ISSUE THREAD

**Issue by miguelconde91** [getsentry/self-hosted#1863]
### Self-Hosted Version

latest

### CPU Architecture

x64

### Docker Version

20.10.18

### Docker Compose Version

2.3.3

### Steps to Reproduce

I had an issue similar to https://forum.sentry.io/t/kafkaerror-offset-out-of-range-error/14495
Then following the steps I recovered the connection of my Zookeeper and Kafka now is working. Then I executed install.sh script (to recreate the topics required)

### Expected Result

The system working again

### Actual Result

My container sentry-self-hosted-post-process-forwarder-1 is restarting all the time with this error:
```
22:37:25 [INFO] sentry.eventstream.kafka.backend: Starting post process forwarder to consume None messages
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 373, in post_process_forwarder
    eventstream.run_post_process_forwarder(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 363, in run_post_process_forwarder
    self.run_consumer(
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 311, in run_consumer
    raise ValueError("Invalid entity")
ValueError: Invalid entity
```

**Comment by ethanhs** [comment]
> Then following the steps I recovered the connection of my Zookeeper and Kafka now is working. Then I executed install.sh script (to recreate the topics required)

Can you please clarify which sequence of steps you followed?

**Comment by miguelconde91** [comment]
I stopped Kafka and Zookeeper container, removed all the volumes related with Kafka and Zookeeper. I created the volumes and runned the `install.sh` script.

**Comment by ethanhs** [comment]
I believe this may be fixed in the latest release, could you please try updating?

**Comment by miguelconde91** [comment]
I deleted the docker images and download again using the install.sh script and I see the same error but with a variation in the error message:

```
16:49:14 [INFO] sentry.eventstream.kafka.backend: Starting post process forwarder to consume None messages
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 373, in post_process_forwarder
    eventstream.run_post_process_forwarder(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 363, in run_post_process_forwarder
    self.run_consumer(
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 311, in run_consumer
    raise ValueError("Invalid entity")
ValueError: Invalid entity
```
This line is new:
` SyntaxWarning: "is" with a literal. Did you mean "=="?`

**Comment by valbertovc** [comment]
+1 This bug is occurring here too.

**Comment by freedomyiyanxing** [comment]
+1 This bug is occurring here too.

![企业微信截图_16751540393090](https://user-images.githubusercontent.com/26188173/216264353-37dbeb82-f466-4119-8982-1b7a9290a463.png)

**Comment by tsvetomir-ivanov** [comment]
We had the same error when upgrading from version 22.7.0 to 23.1.1 where the culprit line was actually:
```[INFO] sentry.eventstream.kafka.backend: Starting post process forwarder to consume None messages```

After some digging we found a change in the post-process-forwarder deployment made in https://github.com/getsentry/self-hosted/commit/4a02090030fdaaacbac521784919185afc47d88c

In our 22.7.0 configuration, we had a single post-process-forwarder which **did not have** a `--topic` argument. Same deployment did not work with version 23.1.1. After splittling the post-process-forwarder for each topic, and adding the required runtime arguments, which are pointed in the reffered commit, we do not observe this issue anymore.

**Comment by jtraulle** [comment]
@tsvetomir-ivanov thank you for commenting ; I have the same problem but do not understand what exactly you changed to solve it.

**Comment by tsvetomir-ivanov** [comment]
@jtraulle Before the upgrade we had one service named `post-process-forwarder` which ran the docker image `getsentry/sentry` with command `run post-process-forwarder --commit-batch-size 1`.

After the upgrade to Sentry 23.1.1, we deleted the service named `post-process-forwarder` and created two new services, running the same docker image:

1. `post-process-forwarder-errors` with command
```run post-process-forwarder --commit-batch-size 1 --entity errors```
3. `post-process-forwarder-transactions` with command
```run post-process-forwarder --commit-batch-size 1 --entity transactions --commit-log-topic=snuba-transactions-commit-log --synchronize-commit-group transactions_group```

If you are using docker-compose for deployment, you can upgrade to the latest version available at https://github.com/getsentry/self-hosted/blob/master/docker-compose.yml
