### ISSUE TITLE
Sentry With Amazon SES

### ISSUE THREAD

**Issue by swateek** [getsentry/self-hosted#1901]
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

20.10.12

### Docker Compose Version

1.29.2

### Steps to Reproduce

I have made the related changes on - [this link](https://develop.sentry.dev/self-hosted/email/)

Just elaborating to be clear:

1. Created an `.env.custom` file with an entry for `SENTRY_MAIL_HOST=email-smtp.ap-south-1.amazonaws.com` and I use this env file to start my docker eco system.

2. In the `sentry/config.yml` I have these entries
```
mail.backend: 'smtp'
mail.host: 'email-smtp.ap-south-1.amazonaws.com'
mail.port: 587
mail.username: 'myuser'
mail.password: 'mypwd'
mail.use-tls: false
mail.use-ssl: false
mail.from: 'admin@something.com'
```

3. In the `sentry/sentry.conf.py` file, I have commented the sentry options.

Even with all this, I still get **Connection Refused** in the worker docker's logs.

**After bringing up Sentry** invite a new user.

### Expected Result

SES should work with Sentry, any invitation mail to new user must be sent.

### Actual Result

I see this error logs in the worker docker

```
ConnectionRefusedError: [Errno 111] Connection refused
04:41:06 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[a6c8dea1-6a40-4c1a-8443-18c3399020f1] raised unexpected: ConnectionRefusedError(111, 'Connection refused') (data={'hostname': '0952262e66f6', 'id': 'a6c8dea1-6a40-4c1a-8443-18c3399020f1', 'name': 'sentry.tasks.email.send_email', 'exc': "ConnectionRefusedError(111, 'Connection refused')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 64, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/email.py", line 73, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/email/send.py", line 18, in send_messages\n    sent: int = connection.send_messages(messages)\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 63, in open\n    self.connection = self.connection_class(self.host, self.port, **connection_params)\n  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__\n    (code, msg) = self.connect(host, port)\n  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect\n    self.sock = self._get_socket(host, port, self.timeout)\n  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket\n    return socket.create_connection((host, port), timeout,\n  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection\n    raise err\n  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f03a3c099d0>}", 'description': 'raised unexpected', 'internal': False})
```

**Comment by Cave-Johnson** [comment]
Try using port 465 and `mail.use-tls: true`

**Comment by swateek** [comment]
@Cave-Johnson I tried your suggestion, got the same error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 64, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/email.py", line 73, in send_email
    send_messages([message])
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/email/send.py", line 18, in send_messages
    sent: int = connection.send_messages(messages)
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
06:25:23 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[8abdaa60-11bb-4f76-87d4-f1a8a3a0a162] raised unexpected: ConnectionRefusedError(111, 'Connection refused') (data={'hostname': 'ec7f741156d1', 'id': '8abdaa60-11bb-4f76-87d4-f1a8a3a0a162', 'name': 'sentry.tasks.email.send_email', 'exc': "ConnectionRefusedError(111, 'Connection refused')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 64, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/email.py", line 73, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/email/send.py", line 18, in send_messages\n    sent: int = connection.send_messages(messages)\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 63, in open\n    self.connection = self.connection_class(self.host, self.port, **connection_params)\n  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__\n    (code, msg) = self.connect(host, port)\n  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect\n    self.sock = self._get_socket(host, port, self.timeout)\n  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket\n    return socket.create_connection((host, port), timeout,\n  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection\n    raise err\n  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f64162c0c10>}", 'description': 'raised unexpected', 'internal': False})
```

**Comment by ethanhs** [comment]
[Amazon's docs seem to indicate](https://docs.aws.amazon.com/ses/latest/dg/postfix.html) that you should set TLS to true and use port 587.

**Comment by swateek** [comment]
@ethanhs I have tried with the same configuration you mentioned, and still have the error which I posted above.

**Comment by swateek** [comment]
Any help on this one? I seem to have hit a deadend.

**Comment by tony-engineering** [comment]
I confirm you need to enable TLS.

**Comment by swateek** [comment]
I have enabled tls now @tony-engineering , just a slight improvement in the exception message.

```bash
06:54:54 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[32b111d0-f8e1-45fb-887d-f48ee8af12de] raised unexpected: ConnectionRefusedError(111, 'Connection refused') (data={'hostname': 'c070f0e779e8', 'id': '32b111d0-f8e1-45fb-887d-f48ee8af12de', 'name': 'sentry.tasks.email.send_email', 'exc': "ConnectionRefusedError(111, 'Connection refused')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 60, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 64, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/email.py", line 73, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/email/send.py", line 18, in send_messages\n    sent: int = connection.send_messages(messages)\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 63, in open\n    self.connection = self.connection_class(self.host, self.port, **connection_params)\n  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__\n    (code, msg) = self.connect(host, port)\n  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect\n    self.sock = self._get_socket(host, port, self.timeout)\n  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket\n    return socket.create_connection((host, port), timeout,\n  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection\n    raise err\n  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7ff21a4f7400>}", 'description': 'raised unexpected', 'internal': False})
06:54:54 [ERROR] sentry_sdk.errors: Unexpected status code: 502 (body: b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n')
06:54:54 [ERROR] sentry_sdk.errors: Unexpected status code: 502 (body: b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n')
```

I see the **502 Bad Gateway** error.


My config.yml has this configuration

```yaml
###############
# Mail Server #
###############

# mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'email-smtp.ap-south-1.amazonaws.com'
mail.port: 587
mail.username: 'AKIAVESISOMETHNINGSWL5'
mail.password: 'ThisIsASecret+Which/cannotshareWithYou'
mail.use-tls: true
# mail.use-ssl: false
```

**Questions**

1. Is it a problem with the password? Becaue I get that from the SMTP user I create via Terraform.
2. Do I need to expose any other ports?

**Comment by swateek** [comment]
**I finally have this fixed.**

**How did I fix this?**

Followed this [link](https://develop.sentry.dev/self-hosted/email/) to the T.

**More Explanation**

There are three ways to add the mail settings into `config.yml`:

1. If you are using Terraform, update the **mail.*** configurations in the `config.example.yml` before you run the `docker-compose up -d` command. I used `sed` command to replace in the file.
2. If you directly modify the **mail.** configuration in the `config.yml` file after bringing up sentry, then remember to run `docker-compose restart` after the change.
3. On first login, you'll be prompted to input all the SMTP detail, you could do that as well.

**How does my config look**

```yaml
mail.host: 'email-smtp.ap-south-1.amazonaws.com'
mail.port: 587
mail.username: 'AKIAVESOMESECRET'
mail.password: "verysecret+pwd+fromAWS"
mail.use-tls: true
mail.use-ssl: false
```

**Please note the double quote around password**

I used  a hybrid of point 1 and point 2, the password I enter after first login.


Hope this helps.
