### ISSUE TITLE
Alert rules not triggered with KeyError: 'query' in consumer-events

### ISSUE THREAD

**Issue by WVan** [getsentry/self-hosted#1910]
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

20.10.14

### Docker Compose Version

2.3.3

### Steps to Reproduce

1. Trigger an alert rule's conditions.

### Expected Result

Alert rule is triggered and its actions executed.

### Actual Result

Alert rule is not triggered.

I don't know exactly when and why this stopped working, but people only recently noticed it. According to alert history it did work last 44 weeks ago. It might have been an update that broke it, or it might not have. I read some issues about the 'offset our of range' error but that seems not to occur in our case. I did spot this error in the logs for the `snuba-subscription-consumer-events` container:

```
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-01-16 09:21:29,859 Initializing Snuba...
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-01-16 09:21:32,066 Snuba initialization took 2.2070482280105352s
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-01-16 09:21:32,448 Initializing Snuba...
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-01-16 09:21:34,623 Snuba initialization took 2.1751201770384796s
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-01-16 09:21:37,636 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 65027871}
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-01-16 09:21:38,922 Caught exception, shutting down...
sentry-self-hosted-snuba-subscription-consumer-events-1  | Traceback (most recent call last):
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
sentry-self-hosted-snuba-subscription-consumer-events-1  |     self._run_once()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 237, in _run_once
sentry-self-hosted-snuba-subscription-consumer-events-1  |     self.__processing_strategy.submit(message)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 249, in submit
sentry-self-hosted-snuba-subscription-consumer-events-1  |     self.__next_step.submit(message)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 254, in submit
sentry-self-hosted-snuba-subscription-consumer-events-1  |     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 254, in <listcomp>
sentry-self-hosted-snuba-subscription-consumer-events-1  |     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 354, in find
sentry-self-hosted-snuba-subscription-consumer-events-1  |     subscriptions = self.__get_subscriptions()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 333, in __get_subscriptions
sentry-self-hosted-snuba-subscription-consumer-events-1  |     for uuid, data in self.__store.all()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/store.py", line 70, in all
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return [
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/store.py", line 71, in <listcomp>
sentry-self-hosted-snuba-subscription-consumer-events-1  |     (UUID(key.decode("utf-8")), self.codec.decode(val))
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/codecs.py", line 34, in decode
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return SubscriptionData.from_dict(data, self.entity_key)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/data.py", line 194, in from_dict
sentry-self-hosted-snuba-subscription-consumer-events-1  |     query=data["query"],
sentry-self-hosted-snuba-subscription-consumer-events-1  | KeyError: 'query'
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-01-16 09:21:38,924 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7efdd6b10880>...
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-01-16 09:21:38,924 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0)]
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-01-16 09:21:38,925 Processor terminated
sentry-self-hosted-snuba-subscription-consumer-events-1  | Traceback (most recent call last):
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/bin/snuba", line 33, in <module>
sentry-self-hosted-snuba-subscription-consumer-events-1  |     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return self.main(*args, **kwargs)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
sentry-self-hosted-snuba-subscription-consumer-events-1  |     rv = self.invoke(ctx)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return ctx.invoke(self.callback, **ctx.params)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return __callback(*args, **kwargs)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
sentry-self-hosted-snuba-subscription-consumer-events-1  |     processor.run()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
sentry-self-hosted-snuba-subscription-consumer-events-1  |     self._run_once()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 237, in _run_once
sentry-self-hosted-snuba-subscription-consumer-events-1  |     self.__processing_strategy.submit(message)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 249, in submit
sentry-self-hosted-snuba-subscription-consumer-events-1  |     self.__next_step.submit(message)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 254, in submit
sentry-self-hosted-snuba-subscription-consumer-events-1  |     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 254, in <listcomp>
sentry-self-hosted-snuba-subscription-consumer-events-1  |     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 354, in find
sentry-self-hosted-snuba-subscription-consumer-events-1  |     subscriptions = self.__get_subscriptions()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 333, in __get_subscriptions
sentry-self-hosted-snuba-subscription-consumer-events-1  |     for uuid, data in self.__store.all()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/store.py", line 70, in all
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return [
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/store.py", line 71, in <listcomp>
sentry-self-hosted-snuba-subscription-consumer-events-1  |     (UUID(key.decode("utf-8")), self.codec.decode(val))
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/codecs.py", line 34, in decode
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return SubscriptionData.from_dict(data, self.entity_key)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/data.py", line 194, in from_dict
sentry-self-hosted-snuba-subscription-consumer-events-1  |     query=data["query"],
sentry-self-hosted-snuba-subscription-consumer-events-1  | KeyError: 'query'
```

Preferably we'd keep all processed events and statistics etc. But if a solution requires the wiping of some recent events that would be acceptable.

**Comment by hubertdeng123** [comment]
Did you perform an upgrade anytime between now and 44 weeks ago?

**Comment by hubertdeng123** [comment]
Could you post install logs?

**Comment by WVan** [comment]
Yes, updates were done in between. The install logs are attached below:

[sentry_install_log-2022-03-29_19-53-59.txt](https://github.com/getsentry/self-hosted/files/10445480/sentry_install_log-2022-03-29_19-53-59.txt)
[sentry_install_log-2022-03-30_11-16-41.txt](https://github.com/getsentry/self-hosted/files/10445481/sentry_install_log-2022-03-30_11-16-41.txt)
[sentry_install_log-2022-05-17_12-42-17.txt](https://github.com/getsentry/self-hosted/files/10445482/sentry_install_log-2022-05-17_12-42-17.txt)
[sentry_install_log-2023-01-10_14-55-01.txt](https://github.com/getsentry/self-hosted/files/10445483/sentry_install_log-2023-01-10_14-55-01.txt)
[sentry_install_log-2023-01-11_21-48-20.txt](https://github.com/getsentry/self-hosted/files/10445484/sentry_install_log-2023-01-11_21-48-20.txt)
[sentry_install_log-2023-01-11_21-55-27.txt](https://github.com/getsentry/self-hosted/files/10445485/sentry_install_log-2023-01-11_21-55-27.txt)
