### ISSUE TITLE
snuba-subscription-consumer-events: KeyError: 'query'

### ISSUE THREAD

**Issue by failoman23** [getsentry/self-hosted#1913]
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

2.5.0

### Steps to Reproduce

I've reported this error first in may 2022 after upgrading 20.12.1 -> 21.6.3 -> 22.4.0 (see issue #1472). Now after updating from 22.4.0 to 22.12.0 the problem still persists. 

The Problem: 
Container **sentry-self-hosted_snuba-subscription-consumer-events_1** keeps restarting with following error message:

> 2023-01-16 19:02:10,209 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f08d0651070>...
2023-01-16 19:02:10,210 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0)]
2023-01-16 19:02:10,211 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 237, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 249, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 254, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 254, in <listcomp>
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
  File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 354, in find
    subscriptions = self.__get_subscriptions()
  File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 333, in __get_subscriptions
    for uuid, data in self.__store.all()
  File "/usr/src/snuba/snuba/subscriptions/store.py", line 70, in all
    return [
  File "/usr/src/snuba/snuba/subscriptions/store.py", line 71, in <listcomp>
    (UUID(key.decode("utf-8")), self.codec.decode(val))
  File "/usr/src/snuba/snuba/subscriptions/codecs.py", line 34, in decode
    return SubscriptionData.from_dict(data, self.entity_key)
  File "/usr/src/snuba/snuba/subscriptions/data.py", line 194, in from_dict
    query=data["query"],
KeyError: 'query'
2023-01-16 19:02:11,301 Initializing Snuba...
2023-01-16 19:02:13,340 Snuba initialization took 2.0392102636396885s
2023-01-16 19:02:13,753 Initializing Snuba...
2023-01-16 19:02:15,823 Snuba initialization took 2.071133315563202s
2023-01-16 19:02:18,836 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 6305

Here is my sentry_install_log from update 22.4.0 to 22.12.0
[sentry_install_log_2212.log](https://github.com/getsentry/self-hosted/files/10428747/sentry_install_log_2212.log)

### Expected Result

No error

### Actual Result

2023-01-16 19:02:10,209 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f08d0651070>...
2023-01-16 19:02:10,210 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0)]
2023-01-16 19:02:10,211 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 187, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 237, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 249, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 254, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 254, in <listcomp>
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
  File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 354, in find
    subscriptions = self.__get_subscriptions()
  File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 333, in __get_subscriptions
    for uuid, data in self.__store.all()
  File "/usr/src/snuba/snuba/subscriptions/store.py", line 70, in all
    return [
  File "/usr/src/snuba/snuba/subscriptions/store.py", line 71, in <listcomp>
    (UUID(key.decode("utf-8")), self.codec.decode(val))
  File "/usr/src/snuba/snuba/subscriptions/codecs.py", line 34, in decode
    return SubscriptionData.from_dict(data, self.entity_key)
  File "/usr/src/snuba/snuba/subscriptions/data.py", line 194, in from_dict
    query=data["query"],
KeyError: 'query'
2023-01-16 19:02:11,301 Initializing Snuba...
2023-01-16 19:02:13,340 Snuba initialization took 2.0392102636396885s
2023-01-16 19:02:13,753 Initializing Snuba...
2023-01-16 19:02:15,823 Snuba initialization took 2.071133315563202s
2023-01-16 19:02:18,836 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 6305

**Comment by hubertdeng123** [comment]
I'm wondering if this is related to [this](https://github.com/getsentry/self-hosted/issues/1910). Did you resolve the 
```
ls: cannot access '/usr/local/share/ca-certificates/': Operation not permitted
stat: cannot statx '/data': Operation not permitted
```
in the previous issue?

**Comment by failoman23** [comment]
I must have resolved it, otherwise I would not be able to successfully run install.sh. I have the exact same error message as the one in the issue you have linked.
