### ISSUE TITLE
Self-hosted Sentry stops receiving errors

### ISSUE THREAD

**Issue by amirpaia** [getsentry/self-hosted#1930]
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

20.10.14

### Docker Compose Version

1.29.2

### Steps to Reproduce

I installed the latest version of the self-hosted Sentry by going through [these steps](https://develop.sentry.dev/self-hosted/).
But it stops receiving messages (errors, and performance metrics) from time to time. And I have to restart one of the 3 docker services of `subscription-consumer-transactions`, `kafka`, or `relay` to make it work, or sometimes I have to restart all docker services to do so.

In a problematic situation `kafka` logs seem like this:
```
kafka_1                                     | [2023-01-17 07:00:04,972] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-0. (kafka.log.LogCleaner)
kafka_1                                     | [2023-01-17 07:00:04,973] INFO Cleaner 0: Building offset map for __consumer_offsets-0... (kafka.log.LogCleaner)
kafka_1                                     | [2023-01-17 07:00:05,006] INFO Cleaner 0: Building offset map for log __consumer_offsets-0 for 1 segments in offset range [0, 788556). (kafka.log.LogCleaner)
kafka_1                                     | [2023-01-17 07:00:05,945] INFO Cleaner 0: Offset map for log __consumer_offsets-0 complete. (kafka.log.LogCleaner)
kafka_1                                     | [2023-01-17 07:00:05,947] INFO Cleaner 0: Cleaning log __consumer_offsets-0 (cleaning prior to Tue Jan 17 07:00:00 UTC 2023, discarding tombstones prior to Thu Jan 01 00:00:00 UTC 1970)... (kafka.log.LogCleaner)
kafka_1                                     | [2023-01-17 07:00:05,951] INFO Cleaner 0: Cleaning LogSegment(baseOffset=0, size=104857525, lastModifiedTime=1673938800000, largestTime=1673938800955) in log __consumer_offsets-0 into 0 with deletion horizon 0, retaining deletes. (kafka.log.LogCleaner)
kafka_1                                     | [2023-01-17 07:00:06,618] INFO Cleaner 0: Swapping in cleaned segment LogSegment(baseOffset=0, size=7937, lastModifiedTime=1673938800000, largestTime=1673938800955) for segment(s) List(LogSegment(baseOffset=0, size=104857525, lastModifiedTime=1673938800000, largestTime=1673938800955)) in log Log(dir=/var/lib/kafka/data/__consumer_offsets-0, topic=__consumer_offsets, partition=0, highWatermark=788580, lastStableOffset=788580, logStartOffset=0, logEndOffset=788580) (kafka.log.LogCleaner)
kafka_1                                     | [2023-01-17 07:00:06,626] INFO [kafka-log-cleaner-thread-0]: 
kafka_1                                     | 	Log cleaner thread 0 cleaned log __consumer_offsets-0 (dirty section = [0, 0])
kafka_1                                     | 	100.0 MB of log processed in 1.6 seconds (60.6 MB/sec).
kafka_1                                     | 	Indexed 100.0 MB in 1.0 seconds (102.8 Mb/sec, 59.0% of total time)
kafka_1                                     | 	Buffer utilization: 0.0%
kafka_1                                     | 	Cleaned 100.0 MB in 0.7 seconds (147.9 Mb/sec, 41.0% of total time)
kafka_1                                     | 	Start size: 100.0 MB (788,556 messages)
kafka_1                                     | 	End size: 0.0 MB (39 messages)
kafka_1                                     | 	100.0% size reduction (100.0% fewer messages)
kafka_1                                     |  (kafka.log.LogCleaner)
kafka_1                                     | [2023-01-19 14:08:00,069] WARN Client session timed out, have not heard from server in 12045ms for sessionid 0x105cc7f4bb80002 (org.apache.zookeeper.ClientCnxn)
```

And `subscription-consumer-transactions `logs look like this:
```
subscription-consumer-transactions_1        | Updating certificates in /etc/ssl/certs...
subscription-consumer-transactions_1        | 0 added, 0 removed; done.
subscription-consumer-transactions_1        | Running hooks in /etc/ca-certificates/update.d...
subscription-consumer-transactions_1        | done.
subscription-consumer-transactions_1        | 09:24:32 [INFO] sentry.plugins.github: apps-not-configured
subscription-consumer-transactions_1        | %4|1673861072.989|CONFWARN|rdkafka#producer-2| [thrd:app]: Configuration property allow.auto.create.topics is a consumer property and will be ignored by this producer instance
subscription-consumer-transactions_1        | 09:24:35 [INFO] sentry.snuba.query_subscription_consumer: query-subscription-consumer.on_assign (offsets='{0: None}' partitions='[TopicPartition{topic=transactions-subscription-results,partition=0,offset=-1001,error=None}]')
subscription-consumer-transactions_1        | 14:08:00 [INFO] sentry.snuba.query_subscription_consumer: query-subscription-consumer.commit_offsets (offsets='{0: None}' partitions='[0]')
subscription-consumer-transactions_1        | 14:08:00 [INFO] sentry.snuba.query_subscription_consumer: query-subscription-consumer.on_revoke (offsets='{}' partitions='[TopicPartition{topic=transactions-subscription-results,partition=0,offset=-1001,error=None}]')
subscription-consumer-transactions_1        | %4|1674137280.056|SESSTMOUT|rdkafka#consumer-1| [thrd:main]: Consumer group session timed out (in join-state steady) after 6385 ms without a successful response from the group coordinator (broker 1001, last error was Success): revoking assignment and rejoining group
subscription-consumer-transactions_1        | 14:08:00 [INFO] sentry.snuba.query_subscription_consumer: query-subscription-consumer.on_assign (offsets='{0: None}' partitions='[TopicPartition{topic=transactions-subscription-results,partition=0,offset=-1001,error=None}]')
subscription-consumer-transactions_1        | 14:08:03 [INFO] sentry.snuba.query_subscription_consumer: query-subscription-consumer.commit_offsets (offsets='{0: None}' partitions='[0]')
subscription-consumer-transactions_1        | 14:08:03 [INFO] sentry.snuba.query_subscription_consumer: query-subscription-consumer.on_revoke (offsets='{}' partitions='[TopicPartition{topic=transactions-subscription-results,partition=0,offset=-1001,error=None}]')
subscription-consumer-transactions_1        | 14:08:03 [INFO] sentry.snuba.query_subscription_consumer: query-subscription-consumer.on_assign (offsets='{0: None}' partitions='[TopicPartition{topic=transactions-subscription-results,partition=0,offset=-1001,error=None}]')
```
The machine that I installed Sentry on has 16GB of RAM, 8 vCore, and 160GB of storage. Although some other services are running on this machine too, there are at least 10 GB of free memory before running Sentry.

What can I do to handle this problem?

### Expected Result

I expect to see Sentry receiving errors without missing even one

### Actual Result

Sentry stops receiving errors and without restarting some or all services it doesn't work. And I can't even open the dashboard when there is such an issue.

**Comment by ethanhs** [comment]
Hi, sorry you are running into this. Do the zookeeper logs give any clue as to what's going wrong?

**Comment by amirpaia** [comment]
Thanks, Ethan
It's the zookeeper logs:
```
zookeeper_1                                 | ===> Configuring ...
zookeeper_1                                 | ===> Running preflight checks ... 
zookeeper_1                                 | ===> Check if /var/lib/zookeeper/data is writable ...
zookeeper_1                                 | ===> Check if /var/lib/zookeeper/log is writable ...
zookeeper_1                                 | ===> Launching ... 
zookeeper_1                                 | ===> Launching zookeeper ... 
zookeeper_1                                 | [2023-01-13 16:16:35,947] WARN Either no config or no quorum defined in config, running  in standalone mode (org.apache.zookeeper.server.quorum.QuorumPeerMain)
zookeeper_1                                 | [2023-01-13 16:16:36,113] WARN o.e.j.s.ServletContextHandler@4d95d2a2{/,null,UNAVAILABLE} contextPath ends with /* (org.eclipse.jetty.server.handler.ContextHandler)
zookeeper_1                                 | [2023-01-13 16:16:36,113] WARN Empty contextPath (org.eclipse.jetty.server.handler.ContextHandler)
zookeeper_1                                 | [2023-01-19 14:08:00,081] WARN Unable to read additional data from client sessionid 0x105cc7f4bb80002, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn)
```
It seems that Kafka closed the connection with ZooKeeper, but I don't have any idea about the reason :thinking:

**Comment by amirpaia** [comment]
(adding some more information about this issue)
The Sentry running on our server stopped receiving messages two times in recent days (after opening this thread), and this time restarting the `snuba-outcomes-consumer` was the solution to make the application.

Do these logs give you any clue about the source of the issue?

```
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:03.406470587Z 2023-01-29 12:39:03,406 Completed processing <Batch: 4 messages, open for 1.04 seconds>.
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:04.466745547Z 2023-01-29 12:39:04,466 Completed processing <Batch: 4 messages, open for 1.02 seconds>.
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:06.408829109Z 2023-01-29 12:39:06,408 Completed processing <Batch: 5 messages, open for 1.05 seconds>.
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:08.417439350Z 2023-01-29 12:39:08,417 Completed processing <Batch: 5 messages, open for 1.04 seconds>.
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:10.451275817Z 2023-01-29 12:39:10,451 Completed processing <Batch: 4 messages, open for 1.03 seconds>.
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:12.461584666Z 2023-01-29 12:39:12,461 Completed processing <Batch: 4 messages, open for 1.03 seconds>.
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:14.440931921Z 2023-01-29 12:39:14,440 Completed processing <Batch: 4 messages, open for 1.03 seconds>.
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403510595Z 2023-01-29 12:39:19,393 Caught exception, shutting down...
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403545299Z Traceback (most recent call last):
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403553290Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403559804Z     httplib_response = self._make_request(
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403565567Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403586920Z     six.raise_from(e, None)
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403593775Z   File "<string>", line 3, in raise_from
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403599846Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403605376Z     httplib_response = conn.getresponse()
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403610688Z   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 110, in getresponse
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403616345Z     rv = real_getresponse(self, *args, **kwargs)
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403621932Z   File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403627334Z     response.begin()
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403632411Z   File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403637707Z     version, status, reason = self._read_status()
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403642674Z   File "/usr/local/lib/python3.8/http/client.py", line 285, in _read_status
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403648459Z     raise RemoteDisconnected("Remote end closed connection without"
snuba-outcomes-consumer_1                   | 2023-01-29T12:39:19.403654077Z http.client.RemoteDisconnected: Remote end closed connection without response

```

**Comment by PrakashSuthar** [comment]
facing similar issue where the applications error logs are not processed by sentry. This happens very frequently in my case.
I usually disable & enable the project's Client Keys(DSN)  from project settings multiple times before it starts working again. But unable to debug root cause, as `docker-compose logs` does not give any logs in my case

**Comment by PrakashSuthar** [comment]
> facing similar issue where the applications error logs are not processed by sentry. This happens very frequently in my case. I usually disable & enable the project's Client Keys(DSN) from project settings multiple times before it starts working again. But unable to debug root cause, as `docker-compose logs` does not give any logs in my case

After some config changes was able to make logs visible...
For some reason the relay_1 is dropping all the envelopes related to errors( `dropped envelope: internal error`).
Any leads on how I can identify the issue? [Note that Disable followed by Enable Client Keys for this project gets rid of this error for some time.]

Logs for reference:

```
relay_1                                     | 2023-01-31T05:40:11Z [relay_server::actors::project] DEBUG: project 14cb07da8cab4d0bb0de72f70bc05b68 state request amended
relay_1                                     | 2023-01-31T05:40:11Z [relay_server::actors::project] DEBUG: project 14cb07da8cab4d0bb0de72f70bc05b68 state request amended
nginx_1                                     | 172.18.0.1 - - [31/Jan/2023:05:40:11 +0000] "POST /api/5/envelope/ HTTP/1.0" 200 41 "-" "sentry.java.logback" "-"
relay_1                                     | 2023-01-31T05:40:11Z [relay_server::actors::project] DEBUG: project 14cb07da8cab4d0bb0de72f70bc05b68 state request amended
relay_1                                     | 2023-01-31T05:40:11Z [relay_server::actors::project] DEBUG: project 14cb07da8cab4d0bb0de72f70bc05b68 state request amended
relay_1                                     | 2023-01-31T05:40:11Z [relay_server::actors::project] DEBUG: project 14cb07da8cab4d0bb0de72f70bc05b68 state request amended
nginx_1                                     | 172.18.0.1 - - [31/Jan/2023:05:40:11 +0000] "POST /api/5/envelope/ HTTP/1.0" 200 41 "-" "sentry.java.logback" "-"
relay_1                                     | 2023-01-31T05:40:12Z [relay_server::actors::project] DEBUG: project 14cb07da8cab4d0bb0de72f70bc05b68 state request amended
relay_1                                     | 2023-01-31T05:40:12Z [relay_server::actors::project] DEBUG: project 14cb07da8cab4d0bb0de72f70bc05b68 state request amended
nginx_1                                     | 172.18.0.1 - - [31/Jan/2023:05:40:12 +0000] "POST /api/5/envelope/ HTTP/1.0" 200 41 "-" "sentry.java.logback" "-"
relay_1                                     | 2023-01-31T05:40:14Z [relay_server::actors::project] DEBUG: project 14cb07da8cab4d0bb0de72f70bc05b68 state request amended
relay_1                                     | 2023-01-31T05:40:14Z [relay_server::actors::project] DEBUG: project 14cb07da8cab4d0bb0de72f70bc05b68 state request amended
nginx_1                                     | 172.18.0.1 - - [31/Jan/2023:05:40:14 +0000] "POST /api/5/envelope/ HTTP/1.0" 200 41 "-" "sentry.java.logback" "-"
worker_1                                    | 05:40:22 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
web_1                                       | 127.0.0.1 - - [31/Jan/2023:05:40:30 +0000] "GET /_health/ HTTP/1.1" 200 47 "-" "-"
relay_1                                     | 2023-01-31T05:40:51Z [relay_server::actors::upstream] INFO: registering with upstream (http://web:9000/)
relay_1                                     | 2023-01-31T05:40:54Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
relay_1                                     |   caused by: error sending request for url (http://web:9000/api/0/relays/register/challenge/): error trying to connect: operation timed out
relay_1                                     | 2023-01-31T05:40:54Z [relay_server::actors::upstream] DEBUG: scheduling authentication retry in 60 seconds
web_1                                       | 127.0.0.1 - - [31/Jan/2023:05:41:00 +0000] "GET /_health/ HTTP/1.1" 200 47 "-" "-"
relay_1                                     | 2023-01-31T05:41:05Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 60s
web_1                                       | 127.0.0.1 - - [31/Jan/2023:05:41:30 +0000] "GET /_health/ HTTP/1.1" 200 47 "-" "-"
redis_1                                     | 1:M 31 Jan 2023 05:41:37.055 * 100 changes in 300 seconds. Saving...
redis_1                                     | 1:M 31 Jan 2023 05:41:37.055 * Background saving started by pid 11381
redis_1                                     | 11381:C 31 Jan 2023 05:41:37.081 * DB saved on disk
redis_1                                     | 11381:C 31 Jan 2023 05:41:37.082 * RDB: 0 MB of memory used by copy-on-write
redis_1                                     | 1:M 31 Jan 2023 05:41:37.156 * Background saving terminated with success

 SKIPPED SOME REPEATED LOGS

web_1                                       | 127.0.0.1 - - [31/Jan/2023:05:44:31 +0000] "GET /_health/ HTTP/1.1" 200 47 "-" "-"
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::actors::project] ERROR: dropped project with 18 envelopes
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
relay_1                                     | 2023-01-31T05:44:42Z [relay_server::utils::envelope_context] DEBUG: dropped envelope: internal error
clickhouse_1                                | 2023.01.31 05:44:43.523888 [ 2586 ] {3bd44195-bc2b-4b82-afbd-4cddfca65d3f} <Information> executeQuery: Read 17 rows, 936.00 B in 0.008 sec., 2172 rows/sec., 116.82 KiB/sec.
clickhouse_1                                | 2023.01.31 05:44:43.524150 [ 2586 ] {} <Information> HTTPHandler: Done processing query
snuba-outcomes-consumer_1                   | 2023-01-31 05:44:43,528 Completed processing <Batch: 17 messages, open for 1.02 seconds>.
web_1                                       | 127.0.0.1 - - [31/Jan/2023:05:45:01 +0000] "GET /_health/ HTTP/1.1" 200 47 "-" "-"
relay_1                                     | 2023-01-31T05:45:03Z [relay_server::actors::upstream] INFO: registering with upstream (http://web:9000/)
clickhouse_1                                | 2023.01.31 05:45:04.686532 [ 10962 ] {521dcdc6-ace6-4d2c-ba7c-198e520ac852} <Information> executeQuery: Read 1 rows, 491.00 B in 0.002 sec., 437 rows/sec., 209.56 KiB/sec.
clickhouse_1                                | 2023.01.31 05:45:04.687158 [ 10962 ] {} <Information> TCPHandler: Processed in 0.003 sec.
snuba-transactions-cleanup_1                | 2023-01-31 05:45:04,688 Dropped 0 partitions on clickhouse:9000
clickhouse_1                                | 2023.01.31 05:45:04.812188 [ 10962 ] {} <Information> TCPHandler: Done processing connection.
clickhouse_1                                | 2023.01.31 05:45:05.013594 [ 89 ] {b782b49d-a627-4aa4-8a86-3ea658bec5dc} <Information> executeQuery: Read 3 rows, 1.43 KiB in 0.002 sec., 1255 rows/sec., 597.16 KiB/sec.
clickhouse_1                                | 2023.01.31 05:45:05.013943 [ 89 ] {} <Information> TCPHandler: Processed in 0.003 sec.
snuba-cleanup_1                             | 2023-01-31 05:45:05,015 Dropped 0 partitions on clickhouse:9000
clickhouse_1                                | 2023.01.31 05:45:05.135710 [ 89 ] {} <Information> TCPHandler: Done processing connection.
relay_1                                     | 2023-01-31T05:45:06Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
relay_1                                     |   caused by: error sending request for url (http://web:9000/api/0/relays/register/challenge/): error trying to connect: operation timed out
relay_1                                     | 2023-01-31T05:45:06Z [relay_server::actors::upstream] DEBUG: scheduling authentication retry in 60 seconds
relay_1                                     | 2023-01-31T05:45:17Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 60s
worker_1                                    | 05:45:22 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
web_1                                       | 127.0.0.1 - - [31/Jan/2023:05:45:31 +0000] "GET /_health/ HTTP/1.1" 200 47 "-" "-"
```

**Comment by hubertdeng123** [comment]
This is probably because of a network issue
```
relay_1                                     | 2023-01-31T05:45:06Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
relay_1                                     |   caused by: error sending request for url (http://web:9000/api/0/relays/register/challenge/): error trying to connect: operation timed out
relay_1                                     | 2023-01-31T05:45:06Z [relay_server::actors::upstream] DEBUG: scheduling authentication retry in 60 seconds
relay_1                                     | 2023-01-31T05:45:17Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 60s
worker_1                                    | 05:45:22 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
```

Jan gave an answer to this that may be worth reading here: https://github.com/getsentry/self-hosted/issues/1929#issuecomment-1404785112

**Comment by PrakashSuthar** [comment]
Connection to http://web:9000/api/0/relays/register/challenge/ was failing  because of a missed step in sentry installation.
My `~/.docker/config.json` did not have web, relay, sentry under *noProxy* configuration. Such logs stopped after updating the file  and restarting docker service as mentioned in https://develop.sentry.dev/self-hosted/#installing-behind-a-proxy
