### ISSUE TITLE
Nginx needs additional configuration, some request are too large to process

### ISSUE THREAD

**Issue by Sorien** [getsentry/self-hosted#1931]
### Self-Hosted Version

23.1.0

### CPU Architecture

x86_64

### Docker Version

Docker version 20.10.17, build 100c701

### Docker Compose Version

docker-compose version 1.29.2, build 5becea4c

### Steps to Reproduce

After upgrade to 23.1.0 some api call are not processed by internal nginx that results to 502 Bad Gateway errors 

nginx configuration `/nginx/nginx.conf` has to be adjusted with:
```
  proxy_busy_buffers_size 512k;
  proxy_buffers 4 512k;
  proxy_buffer_size 256k
```

### Expected Result

successfully process all requests with default configuration 

### Actual Result

Error: API Request Error
  at b.requestPromise(/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_events_interfaces_utils_tsx-app_components_for-73d130.6c26341e40726a3b4a4c.js:1:34401)
  at g(/_static/dist/sentry/chunks/app_components_events_searchBar_tsx-app_views_performance_transactionSummary_transactionEvent-180114.f9d6f2e0574e44ef9bcb.js:1:16299)
  at children(/_static/dist/sentry/chunks/app_components_events_searchBar_tsx-app_views_performance_transactionSummary_transactionEvent-180114.f9d6f2e0574e44ef9bcb.js:1:17318)
  at h.render(/_static/dist/sentry/chunks/app_components_charts_utils_tsx-app_components_quickTrace_utils_tsx-app_utils_discover_eventV-f49af1.7bdcf946527efdcffb29.js:1:161947)
  at Ja(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:162625)
  at Xa(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:162407)
  at Jl(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:206759)
  at zs(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:190463)
  at Ds(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:190308)
  at Ms(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:190141)
  at Cs(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:186974)
  at ? (/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:135758)
  at M.unstable_runWithPriority(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_node_modules_emotion_memoize_dist_memoize_browser_-5f9918.8a14d4095a0916dd17f0.js:2:707398)
  at Qo(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:135535)
  at Xo(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:135703)
  at Yo(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:135638)
  at _s(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:184305)
  at Object.enqueueSetState(/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-733224.5acaa3e1e55aa433df9e.js:2:139612)
  at _.setState(/_static/dist/sentry/chunks/vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--f36be2.b1c4e2be8d55c190c123.js:2:166289)
  at h.fetchData(/_static/dist/sentry/chunks/app_components_charts_utils_tsx-app_components_quickTrace_utils_tsx-app_utils_discover_eventV-f49af1.7bdcf946527efdcffb29.js:1:161280)
BadGatewayError: GET "/api/0/issues/4285/attachments/?per_page=50&types=event.minidump&event_id=cacdbd0880bf42e38c11e2a2bffacf01&event_id=f83297d4ec354028bd8ed11b4aa4db76&event_id=941f94a4599347aea8c5d6a0d5298ed3&event_id=b5094666dd9f423ab8d541a972b4cc5d&event_id=079...
  at n(/_static/dist/sentry/chunks/app_actionCreators_organization_tsx-app_bootstrap_commonInitialization_tsx-app_bootstrap_init-352097.e76fde19686a3883d9ec.js:18:129036)
  at h.error(/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_events_interfaces_utils_tsx-app_components_for-73d130.6c26341e40726a3b4a4c.js:1:34556)
  at ? (/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_events_interfaces_utils_tsx-app_components_for-73d130.6c26341e40726a3b4a4c.js:1:31824)
  at b.handleRequestError(/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_events_interfaces_utils_tsx-app_components_for-73d130.6c26341e40726a3b4a4c.js:1:32261)
  at p(/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_events_interfaces_utils_tsx-app_components_for-73d130.6c26341e40726a3b4a4c.js:1:33098)
  at ? (/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_events_interfaces_utils_tsx-app_components_for-73d130.6c26341e40726a3b4a4c.js:1:34202)

**Comment by hubertdeng123** [comment]
Seems to be the same issue as reported in https://github.com/getsentry/self-hosted/issues/1927. I'll discuss this with the team and get back. We'll either change the default config or add more documentation around this

**Comment by Sorien** [comment]
yes, it's same, did not notice that another bug report was open, closing as a duplicate of #1927
