### ISSUE TITLE
Delayed transaction after upgrade

### ISSUE THREAD

**Issue by sandratatarevicova** [getsentry/self-hosted#1952]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

We are running Sentry in Kubernetes, not with Docker Compose

### Docker Compose Version

We are running Sentry in Kubernetes, not with Docker Compose

### Steps to Reproduce

After we upgraded Sentry from 22.6.0 to 22.10.0, transactions are being displayed in the UI after more than 12 hours. I have checked logs and found this error in `sentry-snuba-outcomes-consumer`:

```
2023-02-02 08:55:54,402 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 448, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1)"}
2023-02-02 08:55:54,405 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f63bcedd190>...
2023-02-02 08:55:54,405 Partitions revoked: [Partition(topic=Topic(name='outcomes'), index=0)]
2023-02-02 08:55:54,408 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 190, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 150, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in _run_once
    self.__message = self.__consumer.poll(timeout=1.0)
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 448, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1)"}
```

I have tried resetting Kafka topics' offsets (`kafka kafka-consumer-groups.sh --bootstrap-server localhost:9092 --all-groups --all-topics --reset-offsets --to-latest --execute`), but it did not help (and did not solve the error above). We currently have these topics in Kafka:

```
kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --list
snuba-consumers
snuba-post-processor:sync:2ca522d0a2d611edaf35ea78d7abb0d3
ingest-consumer
snuba-post-processor:sync:3160a722a2d611ed9edb2e3a09ff2158
snuba-transactions-subscriptions-consumers
transactions_group
snuba-post-processor
snuba-events-subscriptions-consumers
snuba-replacers
query-subscription-consumer
```

Is it OK that there is not topic `outcomes`? I don't know what it is used for, but I guess it is related to the error in the log.

### Expected Result

-

### Actual Result

-

**Comment by hubertdeng123** [comment]
Have you seen this issue? Perhaps it can help out here:
https://github.com/getsentry/self-hosted/issues/1894

Otherwise, I don't think it's related to your setup for Kubernetes, but just wanted to say that it is not officially supported. We only officially support the docker compose version.
