### ISSUE TITLE
Cannot upgrade to 23.1.1 for Error in db migration

### ISSUE THREAD

**Issue by pietroberaldini** [getsentry/self-hosted#1958]
### Self-Hosted Version

22.5.0

### CPU Architecture

x86_64

### Docker Version

19.03.8

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. git fetch
2. git checkout 23.1.1
3. ./install.sh

### Expected Result

installation successfull

### Actual Result

...
django.db.utils.IntegrityError: UniqueViolation('could not create unique index "sentry_grouprelease_group_id_release_id_envi_044354c8_uniq"\nDETAIL:  Key (group_id, release_id, environment)=(11, 135, docker-prod) is duplicated.\n')
SQL: ALTER TABLE "sentry_grouprelease" ALTER COLUMN "project_id" TYPE bigint USING "project_id"::bigint
1
Error in set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:36
--> set-up-and-migrate-database.sh:source:12

Cleaning up...

**Comment by hubertdeng123** [comment]
You may need to edit your postgres database as the sequence has gotten out of sync somewhere. Can you try this?
https://stackoverflow.com/questions/4448340/postgresql-duplicate-key-violates-unique-constraint

**Comment by pietroberaldini** [comment]
It is not resolving my problem, I am still getting the same error even if I `followed` the commands suggested by your link:

```
postgres=# SELECT MAX(id) FROM sentry_grouprelease;
  max
-------
 24961
(1 row)

postgres=# SELECT nextval('sentry_grouprelease_id_seq');
 nextval
---------
   24964
(1 row)

postgres=# SELECT setval('sentry_grouprelease_id_seq', (SELECT MAX(id) FROM sentry_grouprelease)+1);
 setval
--------
  24962
(1 row)

postgres=#
```

The error that I am getting is the same of before:

```
ls: cannot access '/usr/local/share/ca-certificates/': Operation not permitted
sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image
stat: cannot statx '/data': Operation not permitted
/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:243: DeprecationWarning: `structlog.threadlocal` is deprecated, please use `structlog.contextvars` instead.
  WrappedDictClass = structlog.threadlocal.wrap_dict(dict)
16:16:16 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, replays, sentry, sessions, sites, social_auth
Running migrations:
  Applying sentry.0314_bit_int_for_org_and_project_id...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.UniqueViolation: could not create unique index "sentry_grouprelease_group_id_release_id_envi_044354c8_uniq"
DETAIL:  Key (group_id, release_id, environment)=(11, 135, docker-prod) is duplicated.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.UniqueViolation: UniqueViolation('could not create unique index "sentry_grouprelease_group_id_release_id_envi_044354c8_uniq"\nDETAIL:  Key (group_id, release_id, environment)=(11, 135, docker-prod) is duplicated.\n')
SQL: ALTER TABLE "sentry_grouprelease" ALTER COLUMN "project_id" TYPE bigint USING "project_id"::bigint

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 100, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 51, in _upgrade
    dj_call_command(
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/sentry/new_migrations/monkey/executor.py", line 79, in apply_migration
    return super().apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/sentry/new_migrations/migrations.py", line 22, in apply
    return super().apply(project_state, schema_editor, collect_sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 534, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
    super()._alter_field(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 680, in _alter_field
    self.execute(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 577, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
django.db.utils.IntegrityError: UniqueViolation('could not create unique index "sentry_grouprelease_group_id_release_id_envi_044354c8_uniq"\nDETAIL:  Key (group_id, release_id, environment)=(11, 135, docker-prod) is duplicated.\n')
SQL: ALTER TABLE "sentry_grouprelease" ALTER COLUMN "project_id" TYPE bigint USING "project_id"::bigint
1
Error in set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:33
--> set-up-and-migrate-database.sh:source:12

Cleaning up...
```

**Comment by chocobn69** [comment]
You can try this :

Log in pgsql

```bash
docker exec -ti sentry_onpremise_postgres_1 psql -U postgres
```

Delete duplicate entries

```sql
delete from sentry_eventuser where hash in (select hash from sentry_eventuser group by project_id, hash having count(*) > 1);
```

**Comment by pietroberaldini** [comment]
There are no duplicate entries where you told me:

`sentry_docker]# docker exec -ti sentry-self-hosted_postgres_1 psql -U postgres
psql (9.6.24)
Type "help" for help.

postgres=# delete from sentry_eventuser where hash in (select hash from sentry_eventuser group by project_id, hash having count(*) > 1);
DELETE 0
postgres=#`

**Comment by chocobn69** [comment]
Check what you have in `sentry_grouprelease` table

**Comment by pietroberaldini** [comment]
Sorry, what do you mean? There is no `hash` column in `sentry_grouprelease` table

**Comment by chocobn69** [comment]
You might have a duplicate entry in table `sentry_grouprelease`, check first using this query `select * from sentry_grouprelease` then you can find duplicate entry using a `group by having count(*) > 1`  sql query

**Comment by pietroberaldini** [comment]
Ok thank you, but I don't understand which column inside the `sentry_grouprelease` I have to check

**Comment by pietroberaldini** [comment]
I was able to tun the installer after runnig this command in the postgres DB:

`select group_id, release_id, environment, count(*) as count from sentry_grouprelease group by group_id, release_id, environment HAVING COUNT(*) > 1;`

There was a duplicate record, so I deleted the oldest one and run the installer again
