### ISSUE TITLE
Failed to perform maintenance on digest partition 0 due to error

### ISSUE THREAD

**Issue by rmilesson** [getsentry/self-hosted#1976]
### Self-Hosted Version

23.2.0

### CPU Architecture

x86_64

### Docker Version

20.10.7

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Upgrade to 23.2.0 from 22.10.0 by checking out each release between and running `install.sh`.
2. Start seeing errors

### Expected Result

No internal errors should be reported.

### Actual Result

Error message received:
```
Failed to perform maintenance on digest partition 0 due to error: Error running script (call to f_094f8735408af273da283389ad983f63977831e8): @user_script:11: user_script:11: Attempt to modify a readonly table
```

Logs:
```
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 892, in parse_response
worker_1                                    |     response = connection.read_response()
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 752, in read_response
worker_1                                    |     raise response
worker_1                                    | redis.exceptions.ResponseError: Error running script (call to f_094f8735408af273da283389ad983f63977831e8): @user_script:11: user_script:11: Attempt to modify a readonly table
worker_1                                    | 11:09:56 [ERROR] sentry.digests: Failed to perform scheduling for partition 0 due to error: Error running script (call to f_094f8735408af273da283389ad983f63977831e8): @user_script:11: user_script:11: Attempt to modify a readonly table
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/digests/backends/redis.py", line 181, in maintenance
worker_1                                    |     self.__maintenance_partition(host, deadline, timestamp)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/digests/backends/redis.py", line 169, in __maintenance_partition
worker_1                                    |     return script(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/redis.py", line 390, in call_script
worker_1                                    |     return script[0](keys, args, client)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 4021, in __call__
worker_1                                    |     return client.evalsha(self.sha, len(keys), *args)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3091, in evalsha
worker_1                                    |     return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
worker_1                                    |     return old_execute_command(self, name, *args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 878, in execute_command
worker_1                                    |     return self.parse_response(conn, command_name, **options)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 892, in parse_response
worker_1                                    |     response = connection.read_response()
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 752, in read_response
worker_1                                    |     raise response
worker_1                                    | redis.exceptions.ResponseError: Error running script (call to f_094f8735408af273da283389ad983f63977831e8): @user_script:11: user_script:11: Attempt to modify a readonly table
worker_1                                    | 11:10:26 [ERROR] sentry.digests: Failed to perform maintenance on digest partition 0 due to error: Error running script (call to f_094f8735408af273da283389ad983f63977831e8): @user_script:11: user_script:11: Attempt to modify a readonly table
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/digests/backends/redis.py", line 160, in schedule
worker_1                                    |     for key, timestamp in self.__schedule_partition(host, deadline, timestamp):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/digests/backends/redis.py", line 145, in __schedule_partition
worker_1                                    |     partitions: Iterable[Tuple[bytes, float]] = script(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/redis.py", line 390, in call_script
worker_1                                    |     return script[0](keys, args, client)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 4021, in __call__
worker_1                                    |     return client.evalsha(self.sha, len(keys), *args)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3091, in evalsha
worker_1                                    |     return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
worker_1                                    |     return old_execute_command(self, name, *args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 878, in execute_command
worker_1                                    |     return self.parse_response(conn, command_name, **options)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 892, in parse_response
worker_1                                    |     response = connection.read_response()
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 752, in read_response
worker_1                                    |     raise response
worker_1                                    | redis.exceptions.ResponseError: Error running script (call to f_094f8735408af273da283389ad983f63977831e8): @user_script:11: user_script:11: Attempt to modify a readonly table
worker_1                                    | 11:10:26 [ERROR] sentry.digests: Failed to perform scheduling for partition 0 due to error: Error running script (call to f_094f8735408af273da283389ad983f63977831e8): @user_script:11: user_script:11: Attempt to modify a readonly table
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/digests/backends/redis.py", line 181, in maintenance
worker_1                                    |     self.__maintenance_partition(host, deadline, timestamp)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/digests/backends/redis.py", line 169, in __maintenance_partition
worker_1                                    |     return script(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/redis.py", line 390, in call_script
worker_1                                    |     return script[0](keys, args, client)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 4021, in __call__
worker_1                                    |     return client.evalsha(self.sha, len(keys), *args)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3091, in evalsha
worker_1                                    |     return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
worker_1                                    |     return old_execute_command(self, name, *args, **kwargs)
```

### Event ID

d79d7da7c7aa43c583789bd492f64a72

**Comment by hubertdeng123** [comment]
I'm assuming install script ran smoothly without errors? maybe related: https://github.com/getsentry/sentry/issues/42128

**Comment by rmilesson** [comment]
@hubertdeng123 Sorry for the late reply. Yes, install script ran smoothly.

System specs:
16 cores, 24 gig RAM
