### ISSUE TITLE
Non-working snuba-subscription-consumer-sessions container

### ISSUE THREAD

**Issue by johnbizokk** [getsentry/self-hosted#2022]
### Self-Hosted Version

23.2.0

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

v2.16.0

### Steps to Reproduce

1. Run install script
2. Wait until all containers are running
3. Observe errors in the logs

### Expected Result

All containers running without errors

### Actual Result

Logs from the snuba-subscription-consumer-sessions container

`2023-03-10 20:17:15,936 Initializing Snuba...
2023-03-10 20:17:17,695 Snuba initialization took 1.759857393000857s
2023-03-10 20:17:17,945 Initializing Snuba...
2023-03-10 20:17:19,667 Snuba initialization took 1.722561497001152s
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 110, in subscriptions_scheduler_executor
    assert result_topic_spec is not None
AssertionError
`

Container declaration appeared in the latest commit - https://github.com/getsentry/self-hosted/commit/06662c6cdc8573f81b6a128c7bdb815efd5040ed

**Comment by dereckson** [comment]
I can repro. Here a correctly formatted log:

```
2023-03-12 01:45:24,745 Initializing Snuba...
2023-03-12 01:45:28,878 Snuba initialization took 4.134511881042272s
2023-03-12 01:45:29,411 Initializing Snuba...
2023-03-12 01:45:33,449 Snuba initialization took 4.038913033902645s
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 110, in subscriptions_scheduler_executor
    assert result_topic_spec is not None
AssertionError
```

**Comment by dereckson** [comment]
@johnbizokk Using the last snuba image with nightly tag, the error disappeared:

```
2023-03-12 10:05:41,377 Initializing Snuba...
2023-03-12 10:05:45,618 Snuba initialization took 4.242685459088534s
2023-03-12 10:05:46,174 Initializing Snuba...
2023-03-12 10:05:50,469 Snuba initialization took 4.296280158217996s
2023-03-12 10:05:53,514 New partitions assigned: {Partition(topic=Topic(name='snuba-sessions-commit-log'), index=0): 0}
```

**Comment by hubertdeng123** [comment]
Thanks for chiming in @dereckson . @johnbizokk can you see if that works?
