### ISSUE TITLE
Relay restarting contnuously with error after upgrade from 22.10.0 to 23.3.1

### ISSUE THREAD

**Issue by PrakashSuthar** [getsentry/self-hosted#2040]
### Self-Hosted Version

23.3.1

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

1.29.2

### Steps to Reproduce

Upgrade sentry from 22.10.0 to 23.3.1 using install.sh

### Expected Result

Upgrade succesfull, no errors in containers.

### Actual Result

Relay container keeps restarting non-stop.
Relay container logs output:  :
```
docker-compose logs -f relay
Attaching to sentry-self-hosted_relay_1
relay_1                                     | thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/shutdown.rs:51:21
relay_1                                     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by hubertdeng123** [comment]
Is there a backtrace when you set the variable `RUST_BACKTRACE=1` as recommended?

**Comment by PrakashSuthar** [comment]
did not try setting the variable as wasn't sure how to set it, so, reverted to an older version of relay, which stopped the issue for now.

**Comment by hubertdeng123** [comment]
You should be able to set that variable in your `docker-compose.yml` file. Got it, well if you do upgrade again could you do that? Otherwise I am unable to reproduce

**Comment by hubertdeng123** [comment]
You should be able to set that variable in your `docker-compose.yml` file. Got it, well if you do upgrade again could you do that? Otherwise I am unable to reproduce

**Comment by reneluria** [comment]
I can see the same issue, and here is the backtrace:

```
thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/shutdown.rs:51:21
stack backtrace:
   0:     0x563f28b1b1ba - <unknown>
   1:     0x563f28b40c7e - <unknown>
   2:     0x563f28b14ad5 - <unknown>
   3:     0x563f28b1af85 - <unknown>
   4:     0x563f28b1cabf - <unknown>
   5:     0x563f28b1c7fb - <unknown>
   6:     0x563f28b1d1c9 - <unknown>
   7:     0x563f2884645a - <unknown>
   8:     0x563f2884625c - <unknown>
   9:     0x563f2774167a - <unknown>
  10:     0x563f288595a4 - <unknown>
  11:     0x563f2884a62c - <unknown>
  12:     0x563f278ed54e - <unknown>
  13:     0x563f279170dc - <unknown>
  14:     0x563f278c6229 - <unknown>
  15:     0x563f2789d689 - <unknown>
  16:     0x563f27bc1653 - <unknown>
  17:     0x563f27c32c95 - <unknown>
  18:     0x563f278155bb - <unknown>
  19:     0x563f277deb3c - <unknown>
  20:     0x563f277dc28e - <unknown>
  21:     0x563f277aeaba - <unknown>
  22:     0x563f277af463 - <unknown>
  23:     0x563f277bdf59 - <unknown>
  24:     0x563f28b0dd9c - <unknown>
  25:     0x563f277aeb6c - <unknown>
  26:     0x7f055f8b909b - __libc_start_main
  27:     0x563f2774eb02 - <unknown>
  28:                0x0 - <unknown>
```
