### ISSUE TITLE
BadGatewayError when trying to list a large amount of events

### ISSUE THREAD

**Issue by LordSimal** [getsentry/self-hosted#2045]
### Self-Hosted Version

23.3.0

### CPU Architecture

x86_64

### Docker Version

20.10.23+dfsg1, build 7155243

### Docker Compose Version

1.29.2

### Steps to Reproduce

1) Have a entry with more than 50 events inside sentry
2) Click on in to get on the detail page
3) On the top tab navigation click on `All Events`

### Expected Result

The loading of the events table with the paginator stops after a few seconds

### Actual Result

The loading animation doesn't stop, no error message is being shown and there are 502 Bad Gateway errors present in the JS console

It does work for entries which only have a small amount of events.

36 total events => works
39 total events => Doesn't work anymore

```
Failed to load resource: the server responded with a status of 502 ()
Uncaught (in promise) BadGatewayError: GET "/api/0/issues/{issueId}/?per_page=50&types=event.minidump&event_id=a17bdd3960624b80b7384a661b200c82&event_id=b7886cfbeb454debbb29605b4050d69a&event_id=70f8bce017a44c3594a06876ef1f8496&event_id=936f509ee658447bb40198ae982c832e&event_id=d8e7d2d662ba4694ad5088ec66378abd&event_id=b863d4c43fe9449ca2d6f619f66c8f91&event_id=68bf4d0e8b504326938739d2797b58b0&event_id=3ae79fe1deac4c9fb9aa655f91dc75b6&event_id=ae2ea7d537eb4987b1e66faeb38ffb49&event_id=fa624ba46749497fa8e31e01c1c8d475&event_id=3583651d3f3849c787595fe75db4b78d&event_id=940a81a9b03945fabb8548067cbd75d9&event_id=a11d7c6b29e447849d7612930d9d3525&event_id=c39ca507d33e4f7d8d84efe1432fb483&event_id=f3fa39ab27bb4b8a91956cd8804b8196&event_id=d42ea5662145476f9c19e3ce845275c8&event_id=af258f0fc1cb43b4a321d72262a9dee5&event_id=5c69ce247c82430ba3e7afa8a2024496&event_id=5655bfbf466b4cde840c124c59960ac1&event_id=adc33e504206469281ad54266e68de12&event_id=0739e42adc7248b4819a50db32e7ce1c&event_id=3bd4e72d9cb84d1b85a7cfe7a200a6f7&event_id=4f5dec79c4d14c2bac958d19ab9c2862&event_id=2442e688d5914838a1bae6ca6296245c&event_id=2d82fe2abf414b769e90460ffe41e12f&event_id=4b1b0bea021f4f30845b0e9ebfbad1ac&event_id=57ab121ef77941158959184e0950aeae&event_id=8422f44582db40b78c406e189d6f82ed&event_id=0eaac8a6c6c14554b6ccac69ea123b91&event_id=e9a76cfc15ed4251b701946ad6a13596&event_id=857e9511f68149cdb3f280beb58d6ab4&event_id=fa859a0fa75c447a95bfe1b13032ec5f&event_id=9a383064f67846eab0aed8a217126258&event_id=0f22809fed7e446083942d06b373d493&event_id=f925a378bf4b4bc8ab21a7726b4fe2a9&event_id=b49349a5a112466f96661909bcc48f2d&event_id=28d015f87a3b444c8316a8f2fa42dd50&event_id=a2319f9c3ecd4e6a8b4415b625f0819d&event_id=77718683d6164fab9ae1755f45e85589&event_id=29af07e793694e6ba9922fdd3549bdc7&event_id=ef910d4b6048405a82fcabb300efc16d&event_id=34e1446b6a0e47a4bf9ca3497c540479&event_id=8fb16a74e95d46a0a62f22bade8507b8&event_id=ae49ff5cdaae48db9abe80ed49bf495f&event_id=071acb807cda48b099f5b55084cf5bc1&event_id=0e533885c60a45fb884025129cdcd8bc&event_id=464798aad2744b1eb77288ef8391d9c6&event_id=16c77f8a59f04e16bfed87741ad06df4&event_id=78b3faa8d9ff4ce39ff9f0c4fefbaa85&event_id=0c30d59d1cd440a89001c5f7e1ff5aee" 502
    at n (createRequestError.tsx:32:15)
    at h.error (api.tsx:558:36)
    at api.tsx:281:20
    at b.handleRequestError (api.tsx:328:5)
    at p (api.tsx:399:12)
    at api.tsx:511:13
```
[sentry_install_log.txt](https://github.com/getsentry/self-hosted/files/11071255/sentry_install_log.txt)

[docker_compose.log.zip](https://github.com/getsentry/self-hosted/files/11071259/docker_compose.log.zip)

**Comment by LordSimal** [comment]
Refs: Refs: https://github.com/getsentry/self-hosted/issues/1927

**Comment by LordSimal** [comment]
Sorry, it was the NGINX reverse proxy on our side which also needed the 
```
proxy_buffer_size          128k;
proxy_buffers              4 256k;
proxy_busy_buffers_size    256k;
```
config to fix this issue 🙈
