### ISSUE TITLE
Non fatal Kafka errors during upgrade 22.6->23.3.1

### ISSUE THREAD

**Issue by Apollon77** [getsentry/self-hosted#2062]
### Self-Hosted Version

22.61

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

1.29.2

### Steps to Reproduce

checkout 23.3.1 branch and run install.sh

### Expected Result

no errors

### Actual Result

a lot error slike
```
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/utils/manage_topics.py", line 31, in create_topics
    future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/confluent_kafka/admin/__init__.py", line 89, in _make_topics_result
    result = f.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=_TIMED_OUT,val=-185,str="Failed while waiting for response from broker: Local: Timed out"}
2023-03-31 08:46:46,969 Failed to create topic event-replacements
Traceback (most recent call last):
```

... starting line 936 in the logfile

[Gesicherte Terminal-Ausgabe.txt](https://github.com/getsentry/self-hosted/files/11120125/Gesicherte.Terminal-Ausgabe.txt)

**Comment by hubertdeng123** [comment]
Can you check to see if those kafka topics were created if the install script finished succesfully?

**Comment by Apollon77** [comment]
Can you give me instructions on how to do that? From CLI or such? (in fact so far I can see anything works, btw)

**Comment by hubertdeng123** [comment]
Sure, you can run this:
`docker-compose run --rm kafka kafka-topics --bootstrap-server kafka:9092 --list`

**Comment by Apollon77** [comment]
Ok, here is the result:

```
Creating sentry-self-hosted_kafka_run ... done
__consumer_offsets
cdc
errors-replacements
event-replacements
event-replacements-legacy
events
events-subscription-results
generic-events
generic-metrics-counters-subscription-results
generic-metrics-distributions-subscription-results
generic-metrics-sets-subscription-results
ingest-attachments
ingest-events
ingest-metrics
ingest-replay-events
ingest-replay-recordings
ingest-sessions
ingest-transactions
metrics-subscription-results
outcomes
processed-profiles
profiles-call-tree
scheduled-subscriptions-events
scheduled-subscriptions-generic-metrics-counters
scheduled-subscriptions-generic-metrics-distributions
scheduled-subscriptions-generic-metrics-sets
scheduled-subscriptions-metrics
scheduled-subscriptions-sessions
scheduled-subscriptions-transactions
sessions-subscription-results
snuba-attribution
snuba-commit-log
snuba-dead-letter-generic-events
snuba-dead-letter-generic-metrics
snuba-dead-letter-inserts
snuba-dead-letter-metrics
snuba-dead-letter-replays
snuba-dead-letter-sessions
snuba-generic-events-commit-log
snuba-generic-metrics
snuba-generic-metrics-counters-commit-log
snuba-generic-metrics-distributions-commit-log
snuba-generic-metrics-sets-commit-log
snuba-metrics
snuba-metrics-commit-log
snuba-queries
snuba-sessions-commit-log
snuba-transactions-commit-log
transactions
transactions-subscription-results
```

I checked some of the names from log and found all in that list ... so they seems to be there

**Comment by hubertdeng123** [comment]
Well in that case, I don't think the errors you saw during install are indicative of an actual problem

**Comment by hubertdeng123** [comment]
Wondering if these errors are common during install, but should be harmless

**Comment by Apollon77** [comment]
I brought it up because they could be common ... i could tell you when I upgade t nxt version :-) maybe something is not waiting long enough for kafka being fully reachable
