### ISSUE TITLE
'Number of Errors' alert rules not triggering

### ISSUE THREAD

**Issue by WVan** [getsentry/self-hosted#2067]
### Self-Hosted Version

23.3.1

### CPU Architecture

x86_64

### Docker Version

23.0.3

### Docker Compose Version

2.3.3

### Steps to Reproduce

1. Trigger 'Number of Errors' condition for alert rule.

### Expected Result

Alert rule is triggered and its actions executed.

### Actual Result

Alert rule is not triggered. 'Issues' alerts do seem to work fine though. 

I don't know exactly when and why this stopped working, but people only recently noticed it. It might have been an update that broke it, or it might not have. I read some issues about the 'offset our of range' error but that seems not to occur in our case. I did spot this error in the logs for the snuba-subscription-consumer-events container:

```
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-04-05 14:35:04,129 Initializing Snuba...
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-04-05 14:35:07,457 Snuba initialization took 3.329675873999804s
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-04-05 14:35:07,885 Initializing Snuba...
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-04-05 14:35:11,197 Snuba initialization took 3.313476281000021s
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-04-05 14:35:14,216 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 69089981}
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-04-05 14:35:18,012 Caught exception, shutting down...
sentry-self-hosted-snuba-subscription-consumer-events-1  | Traceback (most recent call last):
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 181, in run
sentry-self-hosted-snuba-subscription-consumer-events-1  |     self._run_once()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 231, in _run_once
sentry-self-hosted-snuba-subscription-consumer-events-1  |     self.__processing_strategy.submit(message)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
sentry-self-hosted-snuba-subscription-consumer-events-1  |     self.__next_step.submit(message)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
sentry-self-hosted-snuba-subscription-consumer-events-1  |     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in <listcomp>
sentry-self-hosted-snuba-subscription-consumer-events-1  |     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 405, in find
sentry-self-hosted-snuba-subscription-consumer-events-1  |     subscriptions = self.__get_subscriptions()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 378, in __get_subscriptions
sentry-self-hosted-snuba-subscription-consumer-events-1  |     for uuid, data in self.__store.all()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/store.py", line 70, in all
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return [
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/store.py", line 71, in <listcomp>
sentry-self-hosted-snuba-subscription-consumer-events-1  |     (UUID(key.decode("utf-8")), self.codec.decode(val))
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/codecs.py", line 34, in decode
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return SubscriptionData.from_dict(data, self.entity_key)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/data.py", line 200, in from_dict
sentry-self-hosted-snuba-subscription-consumer-events-1  |     query=data["query"],
sentry-self-hosted-snuba-subscription-consumer-events-1  | KeyError: 'query'
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-04-05 14:35:18,014 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f176de1e3a0>...
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-04-05 14:35:18,015 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0)]
sentry-self-hosted-snuba-subscription-consumer-events-1  | 2023-04-05 14:35:18,016 Processor terminated
sentry-self-hosted-snuba-subscription-consumer-events-1  | Traceback (most recent call last):
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/bin/snuba", line 33, in <module>
sentry-self-hosted-snuba-subscription-consumer-events-1  |     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return self.main(*args, **kwargs)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
sentry-self-hosted-snuba-subscription-consumer-events-1  |     rv = self.invoke(ctx)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return ctx.invoke(self.callback, **ctx.params)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return __callback(*args, **kwargs)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 141, in subscriptions_scheduler_executor
sentry-self-hosted-snuba-subscription-consumer-events-1  |     processor.run()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 181, in run
sentry-self-hosted-snuba-subscription-consumer-events-1  |     self._run_once()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 231, in _run_once
sentry-self-hosted-snuba-subscription-consumer-events-1  |     self.__processing_strategy.submit(message)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
sentry-self-hosted-snuba-subscription-consumer-events-1  |     self.__next_step.submit(message)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
sentry-self-hosted-snuba-subscription-consumer-events-1  |     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in <listcomp>
sentry-self-hosted-snuba-subscription-consumer-events-1  |     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 405, in find
sentry-self-hosted-snuba-subscription-consumer-events-1  |     subscriptions = self.__get_subscriptions()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 378, in __get_subscriptions
sentry-self-hosted-snuba-subscription-consumer-events-1  |     for uuid, data in self.__store.all()
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/store.py", line 70, in all
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return [
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/store.py", line 71, in <listcomp>
sentry-self-hosted-snuba-subscription-consumer-events-1  |     (UUID(key.decode("utf-8")), self.codec.decode(val))
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/codecs.py", line 34, in decode
sentry-self-hosted-snuba-subscription-consumer-events-1  |     return SubscriptionData.from_dict(data, self.entity_key)
sentry-self-hosted-snuba-subscription-consumer-events-1  |   File "/usr/src/snuba/snuba/subscriptions/data.py", line 200, in from_dict
sentry-self-hosted-snuba-subscription-consumer-events-1  |     query=data["query"],
sentry-self-hosted-snuba-subscription-consumer-events-1  | KeyError: 'query'
sentry-self-hosted-snuba-subscription-consumer-events-1 exited with code 0
```

And it seems this container is continuously starting, failing and restarting again.

Here are the most recent install logs: 

[sentry_install_log-2022-03-29_19-53-59.txt](https://github.com/getsentry/self-hosted/files/11160163/sentry_install_log-2022-03-29_19-53-59.txt)
[sentry_install_log-2022-03-30_11-16-41.txt](https://github.com/getsentry/self-hosted/files/11160166/sentry_install_log-2022-03-30_11-16-41.txt)
[sentry_install_log-2022-05-17_12-42-17.txt](https://github.com/getsentry/self-hosted/files/11160169/sentry_install_log-2022-05-17_12-42-17.txt)
[sentry_install_log-2023-01-10_14-55-01.txt](https://github.com/getsentry/self-hosted/files/11160170/sentry_install_log-2023-01-10_14-55-01.txt)
[sentry_install_log-2023-01-11_21-48-20.txt](https://github.com/getsentry/self-hosted/files/11160172/sentry_install_log-2023-01-11_21-48-20.txt)
[sentry_install_log-2023-01-11_21-55-27.txt](https://github.com/getsentry/self-hosted/files/11160174/sentry_install_log-2023-01-11_21-55-27.txt)
[sentry_install_log-2023-04-05_13-50-48.txt](https://github.com/getsentry/self-hosted/files/11160175/sentry_install_log-2023-04-05_13-50-48.txt)

**Comment by hubertdeng123** [comment]
I wonder if a migration has failed. I don't think I saw an error in the logs you posted during the migration step though. Is this crash only happening during the Trigger 'Number of Errors' condition for alert rule?

**Comment by WVan** [comment]
I don't remember any migrations having failed. Is there a way to check this other than the install logs?

This crash seems to happen continuously, the container starts, initialises, crashes with that stacktrace and is restarted by docker immediately to do just the same over and over.

What data would be causing this crash (and should maybe have been migrated)? And would there be a way to clear/reset it?

**Comment by hubertdeng123** [comment]
Hmm, not quite familiar with this. Maybe @lynnagara can chime in here for context

**Comment by hubertdeng123** [comment]
Talked with Lyn, we advise you to clear the messages out of the `events-subscriptions-result` topic. There appears to be bad data in that topic which could cause you to miss a few alerts but they're probably old anyways.

**Comment by WVan** [comment]
I was unsure how to clear those messages. But some Googling found me a method to do so by setting the retention for that topic to a short time, waiting that time and then setting the retention back to the original value.

After doing so I still get the same error and container restarts for snuba-subscription-consumer-events.

**Comment by WVan** [comment]
> To be clear I executed `docker compose run --rm kafka kafka-configs --bootstrap-server kafka:9092 --topic events-subscription-results --alter --add-config retention.ms=10000` and then the same with the original retention value. Is this the correct method to clear it? If not how should I do it?
> 
> And if it was it does not seem to solve the problem with the alerts, do you have any other suggestions perhaps?

@hubertdeng123 Did I correctly clear those messages with my method? If not how should I do it instead? And if it was correct it does not seem to work. Do you have any other suggestions I could try?

**Comment by hubertdeng123** [comment]
We would recommend you to reset the offset or delete and remake the topic if that doesn't work.

**Comment by knaperek** [comment]
Had the same problem after upgrade (21.4.1 -> 21.6.3 -> 23.5.0).
Deleted all Alerts in web UI and it seems to have fixed the issue (`snuba-subscription-consumer-transactions` and `snuba-subscription-consumer-events` containers already running for 14 hours without crash).

**Comment by eugen-korentsov** [comment]
Have similar issue, after upgrade to 23.6.1:

`2023-07-26 12:20:01,014 Initializing Snuba...
2023-07-26 12:20:12,731 Snuba initialization took 11.726379256695509s
2023-07-26 12:20:15,786 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 108393}
2023-07-26 12:20:15,793 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 381, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 7
2023-07-26 12:20:15,797 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f56d1c3ad60>...
2023-07-26 12:20:15,797 Partitions to revoke: [Partition(topic=Topic(name='snuba-commit-log'), index=0)]
2023-07-26 12:20:15,798 Partition revocation complete.
2023-07-26 12:20:15,810 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 141, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 381, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 240, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 246, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 7
`

removing of alerts didn't help.

**Comment by WVan** [comment]
Yesterday I updated to 23.8.0 and this problem still persists. If recreating the topic is the solution indeed, how would I do this? I have no knowledge of Kafka or Snuba at all. I did find a way to list some of those offsets, does this help?

```
root@svc-sentry:/mnt/svc-sentry-data/getsentry-self-hosted# docker compose run --rm kafka kafka-consumer-groups --bootstrap-server kafka:9092 --all-groups -describe
[+] Running 1/0
 ✔ Container sentry-self-hosted-zookeeper-1  Running                                                                                                                                                                                                                     0.0s

GROUP                TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
generic_events_group generic-events  0          -               0               -               rdkafka-a4d75033-67ac-47b9-a3a8-89bbdcb0eba3 /192.168.4.16   rdkafka

GROUP           TOPIC               PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
ingest-consumer ingest-attachments  0          -               0               -               rdkafka-dae24630-2cbc-42c1-a79e-3f18a2d86e82 /192.168.4.37   rdkafka
ingest-consumer ingest-events       0          300213736       300213741       5               rdkafka-f5e264a8-a6d5-4da7-a6d4-f1efebfcd167 /192.168.4.33   rdkafka
ingest-consumer ingest-transactions 0          21336459        21336459        0               rdkafka-5fe094d1-fbda-489b-9d7d-ea3d7ce58410 /192.168.4.36   rdkafka

GROUP              TOPIC              PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
ingest-occurrences ingest-occurrences 0          -               0               -               rdkafka-5ace5fd5-afeb-41f8-b588-d2d348e90b20 /192.168.4.32   rdkafka

GROUP           TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
ingest-profiles profiles        0          -               0               -               rdkafka-8ea24309-81e5-46cc-b741-e47a3393a3d1 /192.168.4.34   rdkafka

GROUP                    TOPIC                    PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
ingest-replay-recordings ingest-replay-recordings 0          -               0               -               rdkafka-3487805f-78da-46d7-a4b2-14af5a106c3f /192.168.4.38   rdkafka

GROUP                  TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
post-process-forwarder events          0          346044869       346044898       29              rdkafka-2a4920fd-096d-46f1-a38d-5e61ec3011bf /192.168.4.26   rdkafka
post-process-forwarder generic-events  0          -               0               -               rdkafka-6771f6e2-4dc1-40ca-9640-2bc852601374 /192.168.4.31   rdkafka
post-process-forwarder transactions    0          8969941         8969942         1               rdkafka-cd550c80-3bad-4cc4-b55a-a9659576fa33 /192.168.4.30   rdkafka

GROUP                       TOPIC                             PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
query-subscription-consumer events-subscription-results       0          351082          351082          0               rdkafka-e5f33504-ccfd-40f2-b998-34e51d70a343 /192.168.4.35   rdkafka
query-subscription-consumer transactions-subscription-results 0          -               0               -               rdkafka-21ba9079-a8e2-48c4-8b24-aa3bdcfe07e2 /192.168.4.24   rdkafka

GROUP                                              TOPIC                         PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
sentry-commit-log-84d8101e56f111ee9e970242c0a8041e snuba-transactions-commit-log 0          -               5991775         -               rdkafka-05ba2b5a-f76f-4866-9f16-64db3e3ad8b9 /192.168.4.30   rdkafka

GROUP                                              TOPIC            PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
sentry-commit-log-84ec687a56f111eeb8a20242c0a8041a snuba-commit-log 0          -               79242800        -               rdkafka-3a48d167-b1e6-425f-991b-84107f6b1279 /192.168.4.26   rdkafka

GROUP                                              TOPIC                           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
sentry-commit-log-84f8edac56f111eebf010242c0a8041f snuba-generic-events-commit-log 0          -               0               -               rdkafka-19234862-d8df-4622-bf78-b1fc76839fe2 /192.168.4.31   rdkafka

GROUP           TOPIC                PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
snuba-consumers ingest-sessions      0          876416921       876416939       18              rdkafka-92311e4c-8ecd-4fc8-b281-eba8cd65c862 /192.168.4.18   rdkafka
snuba-consumers profiles-call-tree   0          -               0               -               rdkafka-e125ad93-718e-4ec5-876e-d1166235e713 /192.168.4.17   rdkafka
snuba-consumers processed-profiles   0          -               0               -               rdkafka-ebafac65-cf03-47dd-aa70-ff53b1b775fd /192.168.4.20   rdkafka
snuba-consumers ingest-replay-events 0          -               0               -               rdkafka-1eba4484-a155-4ff8-9415-086568dd7dea /192.168.4.22   rdkafka
snuba-consumers outcomes             0          388671644       388671652       8               rdkafka-3059be15-b36a-4e83-b0dd-8bd6325d75fe /192.168.4.19   rdkafka
snuba-consumers events               0          346044890       346044898       8               rdkafka-4212f3c2-a167-4bf9-8d3e-baab44f1110b /192.168.4.12   rdkafka

Consumer group 'snuba-post-processor' has no active members.

GROUP                TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID     HOST            CLIENT-ID
snuba-post-processor events          0          345755671       346044898       289227          -               -               -
snuba-post-processor transactions    0          8947512         8969942         22430           -               -               -

GROUP           TOPIC              PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
snuba-replacers event-replacements 0          3768            3768            0               rdkafka-2275e907-57c2-4228-b4d7-c2b418957971 /192.168.4.13   rdkafka

GROUP                                  TOPIC                     PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
snuba-sessions-subscriptions-consumers snuba-sessions-commit-log 0          -               16419176        -               rdkafka-fb718b3f-fe77-426a-980e-bd0bb2dd40b9 /192.168.4.23   rdkafka

GROUP                                      TOPIC                         PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
snuba-transactions-subscriptions-consumers snuba-transactions-commit-log 0          -               5991775         -               rdkafka-3cae26be-ef2b-4f85-8202-78c7345dc451 /192.168.4.15   rdkafka

GROUP              TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
transactions_group transactions    0          8969942         8969942         0               rdkafka-41275518-da6f-4d5c-a47c-25e43b8ead5c /192.168.4.14   rdkafka
```

**Comment by hubertdeng123** [comment]
You'll be able to do that with
```
kafka-topics --bootstrap-server kafka:9092 --delete --topic events-subscription-results
kafka-topics --bootstrap-server kafka:9092 --create --topic events-subscription-results
```
