### ISSUE TITLE
Alerts not triggered, and the [New issue] tag is missing

### ISSUE THREAD

**Issue by gongpeione** [getsentry/self-hosted#2095]
### Self-Hosted Version

23.5.0.dev0

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

2.16.0

### Steps to Reproduce

I recently installed Sentry Self-Hosted and initially, everything seemed to be working fine. However, after two days, I started experiencing unexpected behavior with the Alert system, like new issue alert not triggered. And the [New issue] tag is no longer appearing on any issues.

I noticed some errors in the following containers:

[sentry-self-hosted-post-process-forwarder-errors-1]
```
sentry-self-hosted-post-process-forwarder-errors-1             | 03:35:32 [INFO] arroyo.processing.processor: Processor terminated
sentry-self-hosted-post-process-forwarder-errors-1             | Traceback (most recent call last):
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/bin/sentry", line 8, in <module>
sentry-self-hosted-post-process-forwarder-errors-1             |     sys.exit(main())
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
sentry-self-hosted-post-process-forwarder-errors-1             |     func(**kwargs)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
sentry-self-hosted-post-process-forwarder-errors-1             |     return self.main(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
sentry-self-hosted-post-process-forwarder-errors-1             |     rv = self.invoke(ctx)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-post-process-forwarder-errors-1             |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-post-process-forwarder-errors-1             |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
sentry-self-hosted-post-process-forwarder-errors-1             |     return ctx.invoke(self.callback, **ctx.params)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-errors-1             |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-post-process-forwarder-errors-1             |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
sentry-self-hosted-post-process-forwarder-errors-1             |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-errors-1             |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-post-process-forwarder-errors-1             |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
sentry-self-hosted-post-process-forwarder-errors-1             |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-errors-1             |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 427, in post_process_forwarder
sentry-self-hosted-post-process-forwarder-errors-1             |     eventstream.run_post_process_forwarder(
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
sentry-self-hosted-post-process-forwarder-errors-1             |     context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 314, in run_post_process_forwarder
sentry-self-hosted-post-process-forwarder-errors-1             |     consumer.run()
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 194, in run
sentry-self-hosted-post-process-forwarder-errors-1             |     self._run_once()
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 225, in _run_once
sentry-self-hosted-post-process-forwarder-errors-1             |     self.__message = self.__consumer.poll(timeout=1.0)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/synchronized.py", line 248, in poll
sentry-self-hosted-post-process-forwarder-errors-1             |     message = self.__consumer.poll(timeout)
sentry-self-hosted-post-process-forwarder-errors-1             |   File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 407, in poll
sentry-self-hosted-post-process-forwarder-errors-1             |     raise OffsetOutOfRange(str(error))
sentry-self-hosted-post-process-forwarder-errors-1             | arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker:
 Broker: Offset out of range (broker 1001)"}
```

[sentry-self-hosted-post-process-forwarder-transactions-1 ]
```
sentry-self-hosted-post-process-forwarder-transactions-1       | 03:34:51 [INFO] arroyo.processing.processor: Processor terminated
sentry-self-hosted-post-process-forwarder-transactions-1       | Traceback (most recent call last):
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/bin/sentry", line 8, in <module>
sentry-self-hosted-post-process-forwarder-transactions-1       |     sys.exit(main())
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
sentry-self-hosted-post-process-forwarder-transactions-1       |     func(**kwargs)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
sentry-self-hosted-post-process-forwarder-transactions-1       |     return self.main(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
sentry-self-hosted-post-process-forwarder-transactions-1       |     rv = self.invoke(ctx)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-post-process-forwarder-transactions-1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-post-process-forwarder-transactions-1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
sentry-self-hosted-post-process-forwarder-transactions-1       |     return ctx.invoke(self.callback, **ctx.params)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-transactions-1       |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-post-process-forwarder-transactions-1       |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
sentry-self-hosted-post-process-forwarder-transactions-1       |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-transactions-1       |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-post-process-forwarder-transactions-1       |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
sentry-self-hosted-post-process-forwarder-transactions-1       |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-transactions-1       |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 427, in post_process_forwarder
sentry-self-hosted-post-process-forwarder-transactions-1       |     eventstream.run_post_process_forwarder(
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
sentry-self-hosted-post-process-forwarder-transactions-1       |     context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 314, in run_post_process_forwarder
sentry-self-hosted-post-process-forwarder-transactions-1       |     consumer.run()
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 194, in run
sentry-self-hosted-post-process-forwarder-transactions-1       |     self._run_once()
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 225, in _run_once
sentry-self-hosted-post-process-forwarder-transactions-1       |     self.__message = self.__consumer.poll(timeout=1.0)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/synchronized.py", line 248, in poll
sentry-self-hosted-post-process-forwarder-transactions-1       |     message = self.__consumer.poll(timeout)
sentry-self-hosted-post-process-forwarder-transactions-1       |   File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 407, in poll
sentry-self-hosted-post-process-forwarder-transactions-1       |     raise OffsetOutOfRange(str(error))
sentry-self-hosted-post-process-forwarder-transactions-1       | arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
```

[sentry-self-hosted-kafka-1]
```
sentry-self-hosted-kafka-1                                     | [2023-04-12 10:02:52,450] ERROR Unable to resolve address: zookeeper:2181 (org.apache.zookeeper.client.StaticHostProvider)
sentry-self-hosted-kafka-1                                     | java.net.UnknownHostException: zookeeper
sentry-self-hosted-kafka-1                                     | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
sentry-self-hosted-kafka-1                                     | 	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
sentry-self-hosted-kafka-1                                     | 	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
sentry-self-hosted-kafka-1                                     | 	at org.apache.zookeeper.client.StaticHostProvider$1.getAllByName(StaticHostProvider.java:92)
sentry-self-hosted-kafka-1                                     | 	at org.apache.zookeeper.client.StaticHostProvider.resolve(StaticHostProvider.java:147)
sentry-self-hosted-kafka-1                                     | 	at org.apache.zookeeper.client.StaticHostProvider.next(StaticHostProvider.java:375)
sentry-self-hosted-kafka-1                                     | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1137)
```
But when I enter the Kafka container and execute ping zookeeper, the command works as expected.

And after I remove Kafka and Zookeeper's volume and reinstall it, everything back to normal.

I would appreciate any guidance or suggestions for resolving this issue. Thank you!

### Expected Result

Alerts system and issue tags works as expected. 

### Actual Result

Experiencing unexpected behavior with the Alert system, like new issue alert not triggered. And the [New issue] tag is no longer appearing on any issues

**Comment by hubertdeng123** [comment]
This is actually a known issue documented here:
https://github.com/getsentry/self-hosted/issues/1982

As such, I'm going to close this as a duplicate
