### ISSUE TITLE
Build fails with redis 127.0.0.1:6379 Connection refused

### ISSUE THREAD

**Issue by blodone** [getsentry/self-hosted#2112]
### Self-Hosted Version

23.4.0

### CPU Architecture

x86_64

### Docker Version

23.0.4

### Docker Compose Version

2.17.2

### Steps to Reproduce

try to use another postgres instance

### Expected Result

all ok

### Actual Result

```
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Starting
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-snuba-replacer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Starting
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-snuba-api-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-sessions-consumer-1  Starting
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Starting
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-snuba-transactions-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-consumer-1  Starting
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Started
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Started
 Container sentry-self-hosted-snuba-replacer-1  Started
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Started
 Container sentry-self-hosted-snuba-sessions-consumer-1  Started
 Container sentry-self-hosted-snuba-api-1  Started
 Container sentry-self-hosted-snuba-transactions-consumer-1  Started
 Container sentry-self-hosted-snuba-consumer-1  Started
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image
07:15:21 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 552, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 609, in _connect
    raise err
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 597, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/buffer/redis.py", line 65, in validate
    client.ping()
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1351, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 170, in sentry_patched_execute_command
    return old_execute_command(self, name, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 488, in execute_command
    buf = self._get_command_buffer(host_id, args[0])
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 355, in _get_command_buffer
    buf = CommandBuffer(host_id, connect, self.auto_batch)
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 91, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 107, in connect
    self.connection = self._connect_func()
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 353, in connect
    return self.connection_pool.get_connection(command_name, shard_hint=host_id)
  File "/usr/local/lib/python3.8/site-packages/rb/clients.py", line 254, in get_connection
    con = real_pool.get_connection(command_name)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1185, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 557, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 192, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 28, in inner
    configure()
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 128, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/settings.py", line 154, in configure
    initialize_app(
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py", line 393, in initialize_app
    setup_services(validate=not skip_service_validation)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py", line 436, in setup_services
    service.validate()
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python3.8/site-packages/sentry/buffer/redis.py", line 69, in validate
    raise InvalidConfiguration(str(e))
sentry.exceptions.InvalidConfiguration: Error 111 connecting to 127.0.0.1:6379. Connection refused.
Error in install/set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:34
--> install/set-up-and-migrate-database.sh:source:12

Cleaning up...
```

**Comment by hubertdeng123** [comment]
How are you setting up your connection to your own postgres db? You may need to change the `docker-compose.yml` file and `sentry.conf.py` if you haven't already
