### ISSUE TITLE
DB error during upgrade

### ISSUE THREAD

**Issue by lynomet** [getsentry/self-hosted#2158]
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

24.0

### Docker Compose Version

1.28.5

### Steps to Reproduce

sudo ./install.sh

### Expected Result

complete the upgrade ok

### Actual Result

During the upgrade i get this error
`▶ Setting up / migrating database ...
 Container sentry-self-hosted-postgres-1  Creating
 Container sentry-self-hosted-smtp-1  Creating
 Container sentry-self-hosted-symbolicator-1  Creating
 Container sentry-self-hosted-redis-1  Running
 Container sentry-self-hosted-zookeeper-1  Running
 Container sentry-self-hosted-kafka-1  Running
 Container sentry-self-hosted-memcached-1  Creating
 Container sentry-self-hosted-clickhouse-1  Running
 Container sentry-self-hosted-snuba-api-1  Creating
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Creating
 Container sentry-self-hosted-snuba-transactions-consumer-1  Creating
 Container sentry-self-hosted-snuba-replacer-1  Creating
 Container sentry-self-hosted-snuba-consumer-1  Creating
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Creating
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Creating
 Container sentry-self-hosted-snuba-sessions-consumer-1  Creating
 Container sentry-self-hosted-smtp-1  Created
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Created
 Container sentry-self-hosted-snuba-consumer-1  Created
 Container sentry-self-hosted-snuba-sessions-consumer-1  Created
 Container sentry-self-hosted-symbolicator-1  Created
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Created
 Container sentry-self-hosted-memcached-1  Created
 Container sentry-self-hosted-snuba-replacer-1  Created
 Container sentry-self-hosted-snuba-transactions-consumer-1  Created
 Container sentry-self-hosted-snuba-api-1  Created
 Container sentry-self-hosted-postgres-1  Created
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Created
 Container sentry-self-hosted-symbolicator-1  Starting
 Container sentry-self-hosted-memcached-1  Starting
 Container sentry-self-hosted-postgres-1  Starting
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-smtp-1  Starting
 Container sentry-self-hosted-smtp-1  Started
 Container sentry-self-hosted-symbolicator-1  Started
 Container sentry-self-hosted-zookeeper-1  Healthy
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-memcached-1  Started
 Container sentry-self-hosted-postgres-1  Started
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-transactions-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-replacer-1  Starting
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Starting
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-snuba-api-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Starting
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-snuba-sessions-consumer-1  Starting
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-snuba-consumer-1  Starting
 Container sentry-self-hosted-snuba-replacer-1  Started
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Started
 Container sentry-self-hosted-snuba-transactions-consumer-1  Started
 Container sentry-self-hosted-snuba-api-1  Started
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Started
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Started
 Container sentry-self-hosted-snuba-sessions-consumer-1  Started
 Container sentry-self-hosted-snuba-consumer-1  Started
sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image
12:13:37 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, replays, sentry, sessions, sites, social_auth
Running migrations:
  Applying sentry.0296_alertrule_type_not_null...* Unknown config option found: 'slack.legacy-app'
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 99, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 50, in _upgrade
    dj_call_command(
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/sentry/new_migrations/monkey/executor.py", line 79, in apply_migration
    return super().apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/sentry/new_migrations/migrations.py", line 22, in apply
    return super().apply(project_state, schema_editor, collect_sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/schema.py", line 52, in inner
    func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 534, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
    super()._alter_field(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 661, in _alter_field
    fragment = self._alter_column_null_sql(model, old_field, new_field)
  File "/usr/local/lib/python3.8/site-packages/django_zero_downtime_migrations/backends/postgres/schema.py", line 592, in _alter_column_null_sql
    return self._alter_column_set_not_null(model, new_field)
  File "/usr/local/lib/python3.8/site-packages/django_zero_downtime_migrations/backends/postgres/schema.py", line 536, in _alter_column_set_not_null
    raise UnsafeOperationException(Unsafe.ALTER_COLUMN_NOT_NULL)
django_zero_downtime_migrations.backends.postgres.schema.UnsafeOperationException: ALTER COLUMN NOT NULL is unsafe operation
See details for safe alternative https://github.com/tbicr/django-pg-zero-downtime-migrations#dealing-with-not-null-constraint
Error in set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:33
--> set-up-and-migrate-database.sh:source:12

Cleaning up...
`

any idea how to fix this?

**Comment by hubertdeng123** [comment]
What version are you upgrading from? Have you attempted any of the solutions in the link provided?

**Comment by lynomet** [comment]
@hubertdeng123  i upgrade from Sentry 21.12.0,
 yes i have tried to apply the constraint changes but nothing worked.
i end-up just slowly upgrading to 22.1.0 and from there to 23.5.0, eventually it start doing the db migration 
and it worked.

**Comment by hubertdeng123** [comment]
Glad you were able to figure it out. Were the issues all related to db migrations?

**Comment by lynomet** [comment]
partly to the db migration and partly to the install.sh
