### ISSUE TITLE
Sentry 21.6.3 - Unable to process events

### ISSUE THREAD

**Issue by amitseth7** [getsentry/self-hosted#2175]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Sentry 21.6.3 - [relay_server::utils::kafka] ERROR: failed to produce message to Kafka (delivery callback): Message production error: MessageTimedOut

After upgrade using hardstops. 

### Expected Result

Events should be processed. 

### Actual Result

```
nginx_1                                     | 17.93.111.70 - - [29/May/2023:16:18:12 +0000] "POST /api/19/envelope/ HTTP/1.1" 200 41 "-" "sentry.python/0.19.5" "-"
relay_1                                     | 2023-05-29T16:18:12Z [relay_server::utils::kafka] ERROR: failed to produce message to Kafka (delivery callback): Message production error: MessageTimedOut (Local: Message timed out)
relay_1                                     | 2023-05-29T16:18:12Z [relay_server::utils::kafka] ERROR: failed to produce message to Kafka (delivery callback): Message production error: MessageTimedOut (Local: Message timed out)
nginx_1                                     | 17.91.247.70 - - [29/May/2023:16:18:12 +0000] "POST /api/19/envelope/ HTTP/1.1" 200 41 "-" "sentry.python/0.19.5" "-"
```

### Product Area

Issues

### Version

21.6.3

**Comment by hubertdeng123** [comment]
Hi there, what has been your upgrade path so far? Did you perform the hard stop at 21.5.0 and 9.1.2?

**Comment by amitseth7** [comment]
Yes that is correct.. I followed the upgrade path .. followed by 
-> deleting the Kafka and zookeeper volumes as mentioned by https://develop.sentry.dev/self-hosted/troubleshooting/#nuclear-option

-> things look good , but the logs are deceptive.. and still donot see events being created . Clickhouse is having issues.. I believe . 


```
snuba-transactions-consumer_1               | 2023-05-31 22:30:08,920 Completed processing <Batch: 19 messages, open for 1.02 seconds>.
clickhouse_1                                | 2023.05.31 22:30:09.224247 [ 115 ] {b1511753-bf34-41a9-bc38-cdbf4bc58e46} <Information> executeQuery: Read 2 rows, 232.00 B in 0.059 sec., 33 rows/sec., 3.81 KiB/sec.
clickhouse_1                                | 2023.05.31 22:30:09.225420 [ 115 ] {} <Information> HTTPHandler: Done processing query
snuba-sessions-consumer_1                   | 2023-05-31 22:30:09,274 Completed processing <Batch: 2 messages, open for 1.12 seconds>.
nginx_1                                     | 17.222.104.25 - - [31/May/2023:22:30:09 +0000] "POST /api/19/envelope/ HTTP/1.1" 200 41 "-" "sentry.python/0.19.5" "-"
ingest-consumer_1                           | 22:30:09 [INFO] batching-kafka-consumer: Flushing 5 items (from {('ingest-transactions', 0): [1599151, 1599155]}): forced:False size:False time:True
clickhouse_1                                | 2023.05.31 22:30:09.662360 [ 121 ] {85e45712-509e-4913-ac34-18d17daa289f} <Information> executeQuery: Read 48 rows, 2.69 KiB in 0.025 sec., 1951 rows/sec., 109.35 KiB/sec.
clickhouse_1                                | 2023.05.31 22:30:09.662713 [ 121 ] {} <Information> HTTPHandler: Done processing query
ingest-consumer_1                           | 22:30:09 [INFO] batching-kafka-consumer: Worker flush took 168ms
nginx_1                                     | 17.26.239.70 - - [31/May/2023:22:30:09 +0000] "POST /api/19/envelope/ HTTP/1.1" 200 41 "-" "sentry.python/0.19.5" "-"
snuba-outcomes-consumer_1                   | 2023-05-31 22:30:09,674 Completed processing <Batch: 48 messages, open for 0.82 seconds>.
clickhouse_1                                | 2023.05.31 22:30:09.745668 [ 114 ] {beffc926-5e46-4381-ad00-eb936c93f7a4} <Information> executeQuery: Read 55 rows, 69.71 KiB in 0.049 sec., 1130 rows/sec., 1.40 MiB/sec.
clickhouse_1                                | 2023.05.31 22:30:09.748152 [ 114 ] {} <Information> HTTPHandler: Done processing query
clickhouse_1                                | 2023.05.31 22:30:29.846196 [ 121 ] {9b4e5c7b-bf09-4365-a92f-64941b6b707e} <Error> executeQuery: Code: 60, e.displayText() = DB::Exception: Table default.sentry_local doesn't exist. (version 20.3.9.70 (official build)) (from 192.168.80.18:60292) (in query: INSERT INTO default.sentry_local   FORMAT JSONEachRow ), Stack trace (when copying this message, always include the lines below):
clickhouse_1                                |
clickhouse_1                                | 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x105351b0 in /usr/bin/clickhouse
clickhouse_1                                | 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f4172d in /usr/bin/clickhouse
clickhouse_1                                | 2. DB::Context::getTableImpl(DB::StorageID const&, std::__1::optional<DB::Exception>*) const @ 0xcfe2a24 in /usr/bin/clickhouse
clickhouse_1                                | 3. DB::Context::getTable(DB::StorageID const&) const @ 0xcfe2bbb in /usr/bin/clickhouse
clickhouse_1                                | 4. DB::Context::getTable(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xcfe2c7d in /usr/bin/clickhouse
clickhouse_1                                | 5. DB::InterpreterInsertQuery::getTable(DB::ASTInsertQuery&) @ 0xd0bb313 in /usr/bin/clickhouse
clickhouse_1                                | 6. DB::InterpreterInsertQuery::execute() @ 0xd0bba62 in /usr/bin/clickhouse
clickhouse_1                                | 7. ? @ 0xd550808 in /usr/bin/clickhouse
clickhouse_1                                | 8. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xd553789 in /usr/bin/clickhouse
clickhouse_1                                | 9. DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x8fed706 in /usr/bin/clickhouse
clickhouse_1                                | 10. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x8ff0bc3 in /usr/bin/clickhouse
clickhouse_1                                | 11. Poco::Net::HTTPServerConnection::run() @ 0xe37c6f4 in /usr/bin/clickhouse
clickhouse_1                                | 12. Poco::Net::TCPServerConnection::start() @ 0xe3ac69b in /usr/bin/clickhouse
clickhouse_1                                | 13. Poco::Net::TCPServerDispatcher::run() @ 0xe3acb1d in /usr/bin/clickhouse
clickhouse_1                                | 14. Poco::PooledThread::run() @ 0x105c3317 in /usr/bin/clickhouse
clickhouse_1                                | 15. Poco::ThreadImpl::runnableEntry(void*) @ 0x105bf11c in /usr/bin/clickhouse
clickhouse_1                                | 16. ? @ 0x105c0abd in /usr/bin/clickhouse
clickhouse_1                                | 17. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
clickhouse_1                                | 18. clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
clickhouse_1                                |
clickhouse_1                                | 2023.05.31 22:30:29.855754 [ 121 ] {} <Error> HTTPHandler: Code: 60, e.displayText() = DB::Exception: Table default.sentry_local doesn't exist., Stack trace (when copying this message, always include the lines below):
clickhouse_1                                |
clickhouse_1                                | 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x105351b0 in /usr/bin/clickhouse
clickhouse_1                                | 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f4172d in /usr/bin/clickhouse
clickhouse_1                                | 2. DB::Context::getTableImpl(DB::StorageID const&, std::__1::optional<DB::Exception>*) const @ 0xcfe2a24 in /usr/bin/clickhouse
clickhouse_1                                | 3. DB::Context::getTable(DB::StorageID const&) const @ 0xcfe2bbb in /usr/bin/clickhouse
clickhouse_1                                | 4. DB::Context::getTable(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xcfe2c7d in /usr/bin/clickhouse
clickhouse_1                                | 5. DB::InterpreterInsertQuery::getTable(DB::ASTInsertQuery&) @ 0xd0bb313 in /usr/bin/clickhouse
clickhouse_1                                | 6. DB::InterpreterInsertQuery::execute() @ 0xd0bba62 in /usr/bin/clickhouse
clickhouse_1                                | 7. ? @ 0xd550808 in /usr/bin/clickhouse
clickhouse_1                                | 8. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xd553789 in /usr/bin/clickhouse
clickhouse_1                                | 9. DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x8fed706 in /usr/bin/clickhouse
clickhouse_1                                | 10. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x8ff0bc3 in /usr/bin/clickhouse
clickhouse_1                                | 11. Poco::Net::HTTPServerConnection::run() @ 0xe37c6f4 in /usr/bin/clickhouse
clickhouse_1                                | 12. Poco::Net::TCPServerConnection::start() @ 0xe3ac69b in /usr/bin/clickhouse
clickhouse_1                                | 13. Poco::Net::TCPServerDispatcher::run() @ 0xe3acb1d in /usr/bin/clickhouse
clickhouse_1                                | 14. Poco::PooledThread::run() @ 0x105c3317 in /usr/bin/clickhouse
clickhouse_1                                | 15. Poco::ThreadImpl::runnableEntry(void*) @ 0x105bf11c in /usr/bin/clickhouse
clickhouse_1                                | 16. ? @ 0x105c0abd in /usr/bin/clickhouse
clickhouse_1                                | 17. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
clickhouse_1                                | 18. clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
clickhouse_1                                |  (version 20.3.9.70 (official build))
snuba-consumer_1                            | 2023-05-31 22:30:29,861 Caught ClickhouseWriterError(code=60, message="Table default.sentry_local doesn't exist. (version 20.3.9.70 (official build))", row=None), shutting down...
snuba-sessions-consumer_1                   | 2023-05-31 22:30:29,869 Partitions revoked: [Partition(topic=Topic(name='ingest-sessions'), index=0)]
snuba-consumer_1                            | Traceback (most recent call last):
snuba-consumer_1                            |   File "/usr/local/bin/snuba", line 33, in <module>
snuba-consumer_1                            |     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
snuba-consumer_1                            |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
snuba-consumer_1                            |     return self.main(*args, **kwargs)
snuba-consumer_1                            |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
snuba-consumer_1                            |     rv = self.invoke(ctx)
snuba-consumer_1                            |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
snuba-consumer_1                            |     return _process_result(sub_ctx.command.invoke(sub_ctx))
snuba-consumer_1                            |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
snuba-consumer_1                            |     return ctx.invoke(self.callback, **ctx.params)
snuba-consumer_1                            |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
snuba-consumer_1                            |     return callback(*args, **kwargs)
snuba-consumer_1                            |   File "/usr/src/snuba/snuba/cli/consumer.py", line 172, in consumer
snuba-consumer_1                            |     consumer.run()
snuba-consumer_1                            |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 108, in run
snuba-consumer_1                            |     self._run_once()
snuba-consumer_1                            |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 143, in _run_once
snuba-consumer_1                            |     self.__processing_strategy.poll()
snuba-consumer_1                            |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/transform.py", line 58, in poll
snuba-consumer_1                            |     self.__next_step.poll()
snuba-consumer_1                            |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 119, in poll
snuba-consumer_1                            |     self.__close_and_reset_batch()
snuba-consumer_1                            |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 101, in __close_and_reset_batch
snuba-consumer_1                            |     self.__batch.close()
snuba-consumer_1                            |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/streaming/collect.py", line 61, in close
snuba-consumer_1                            |     self.__step.close()
snuba-consumer_1                            |   File "/usr/src/snuba/snuba/consumers/consumer.py", line 222, in close
snuba-consumer_1                            |     self.__insert_batch_writer.close()
snuba-consumer_1                            |   File "/usr/src/snuba/snuba/consumers/consumer.py", line 87, in close
snuba-consumer_1                            |     self.__writer.write(
snuba-consumer_1                            |   File "/usr/src/snuba/snuba/clickhouse/http.py", line 245, in write
snuba-consumer_1                            |     batch.join()
snuba-consumer_1                            |   File "/usr/src/snuba/snuba/clickhouse/http.py", line 193, in join
snuba-consumer_1                            |     raise ClickhouseWriterError(code, message, row)
snuba-consumer_1                            | snuba.clickhouse.errors.ClickhouseWriterError: [60] Table default.sentry_local doesn't exist. (version 20.3.9.70 (official build))
clickhouse_1                                | 2023.05.31 22:30:29.891209 [ 113 ] {76583bf4-2943-47dd-bacb-c0f89ed81b3a} <Information> executeQuery: Read 2 rows, 229.00 B in 0.020 sec., 101 rows/sec., 11.34 KiB/sec.
clickhouse_1                                | 2023.05.31 22:30:29.891499 [ 113 ] {} <Information> HTTPHandler: Done processing query
snuba-sessions-consumer_1                   | 2023-05-31 22:30:29,899 Completed processing <Batch: 2 messages, open for 0.64 seconds>.
nginx_1                                     | 17.28.175.70 - - [31/May/2023:22:30:30 +0000] "POST /api/19/envelope/ HTTP/1.1" 200 41 "-" "sentry.python/0.19.5" "-"


```

**Comment by amitseth7** [comment]
I see data , coming in .. but no issues are showing up 
<img width="1258" alt="Screen Shot 2023-06-01 at 11 33 20 AM" src="https://github.com/getsentry/self-hosted/assets/13052615/9bff3266-a8a7-4f61-9759-115054ddb1f5">

**Comment by amitseth7** [comment]
<img width="1587" alt="Screen Shot 2023-06-01 at 11 36 03 AM" src="https://github.com/getsentry/self-hosted/assets/13052615/bb36aaaf-5862-4150-99e8-7908a0e34b1a">

**Comment by RedShiba** [comment]
@amitseth7 hi, recheck --storage key in snuba-consumer command if you use own docker-compose.yaml. Key should be `--storage errors ` not `events`

**Comment by amitseth7** [comment]
Awesome that fixed the issue . Thank you very much @RedShiba
