### ISSUE TITLE
Upgrade failed - ModuleNotFoundError: No module named 'snuba.settings.settings_self_hosted'

### ISSUE THREAD

**Issue by ryan-marshall-evident** [getsentry/self-hosted#2204]
### Self-Hosted Version

23.2.0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

1.29.2

### Steps to Reproduce

From release 23.2.0
git checkout tags/23.5.2 -b 23.5.2
./install.sh

### Expected Result

Installation should be successful.

### Actual Result

▶ Bootstrapping and migrating Snuba ...
Creating network "sentry-self-hosted_default" with the default driver
Creating sentry-self-hosted_clickhouse_1 ...
Creating sentry-self-hosted_zookeeper_1  ...
Creating sentry-self-hosted_redis_1      ...
Creating sentry-self-hosted_clickhouse_1 ... done
Creating sentry-self-hosted_redis_1      ... done
Creating sentry-self-hosted_zookeeper_1  ... done
Creating sentry-self-hosted_kafka_1      ...
Creating sentry-self-hosted_kafka_1      ... done
Creating sentry-self-hosted_snuba-api_run ...
Creating sentry-self-hosted_snuba-api_run ... done
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/bin/snuba", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/snuba/snuba/cli/__init__.py", line 13, in <module>
    from snuba.environment import metrics as environment_metrics
  File "/usr/src/snuba/snuba/environment.py", line 17, in <module>
    from snuba import settings
  File "/usr/src/snuba/snuba/settings/__init__.py", line 418, in <module>
    _load_settings()
  File "/usr/src/snuba/snuba/settings/__init__.py", line 409, in _load_settings
    settings_module = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'snuba.settings.settings_self_hosted'
1
Error in install/bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:31
--> install/bootstrap-snuba.sh:source:3

Cleaning up...

**Comment by hubertdeng123** [comment]
Can you check your .env file make sure that you're using the appropriate snuba image? I have a feeling that your self-hosted instance is using `SNUBA_SETTINGS: self_hosted` but your snuba image is not up to date.

**Comment by ryan-marshall-evident** [comment]
Hi @hubertdeng123, thanks for your quick reply. I upgraded the Snuba version in the .env.custom and the upgrade was successful.
