### ISSUE TITLE
Web still starting and in terminal say "Error" and nginx and relay container only created

### ISSUE THREAD

**Issue by grulicht** [getsentry/self-hosted#2215]
### Self-Hosted Version

23.4.0

### CPU Architecture

x86_64 and 6 CPU

### Docker Version

24.0.1

### Docker Compose Version

v2.18.1

### Steps to Reproduce

.

### Expected Result

I do not know where is a problem, but other container is running.

### Actual Result

logs in sentry web is:

06:04:13 [INFO] sentry.plugins.github: apps-not-configured

*** Starting uWSGI 2.0.20 (64bit) on [Tue Jun 20 06:04:14 2023] ***

compiled with version: 8.3.1 20190311 (Red Hat 8.3.1-3) on 11 November 2021 18:13:24

os: Linux-5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13)

nodename: e84f2e86b48a

machine: x86_64

clock source: unix

pcre jit disabled

detected number of CPU cores: 6

current working directory: /

detected binary path: /usr/local/bin/python

your memory page size is 4096 bytes

detected max file descriptor number: 1048576

lock engine: pthread robust mutexes

thunder lock: enabled

uWSGI http bound on 0.0.0.0:9000 fd 4

uwsgi socket 0 bound to TCP address 127.0.0.1:42839 (port auto-assigned) fd 3

Python version: 3.8.16 (default, Apr 12 2023, 07:03:02)  [GCC 10.2.1 20210110]

--- Python VM already initialized ---

Python main interpreter initialized at 0x55867eb6f880

python threads support enabled

your server socket listen backlog is limited to 100 connections

your mercy for graceful operations on workers is 60 seconds

setting request body buffering size to 65536 bytes

mapped 1924224 bytes (1879 KB) for 12 cores

*** Operational MODE: preforking+threaded ***

spawned uWSGI master process (pid: 686)

spawned uWSGI worker 1 (pid: 688, cores: 4)

spawned uWSGI worker 2 (pid: 689, cores: 4)

spawned uWSGI worker 3 (pid: 690, cores: 4)

spawned uWSGI http 1 (pid: 691)

06:04:19 [INFO] sentry.plugins.github: apps-not-configured

06:04:19 [INFO] sentry.plugins.github: apps-not-configured

06:04:19 [INFO] sentry.plugins.github: apps-not-configured

* Unknown config option found: 'slack.legacy-app'

* Unknown config option found: 'slack.legacy-app'

* Unknown config option found: 'slack.legacy-app'

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/sentry/wsgi.py", line 46, in <module>

    application = FileWrapperWSGIHandler()

  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 135, in __init__

    self.load_middleware()

  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/middleware.py", line 66, in sentry_patched_load_middleware

    return old_load_middleware(*args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 35, in load_middleware

    middleware = import_string(middleware_path)

  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/middleware.py", line 51, in sentry_patched_import_string

    rv = old_import_string(dotted_path)

  File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string

    module = import_module(module_path)

  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

ModuleNotFoundError: No module named 'csp'

unable to load app 0 (mountpoint='') (callable not found or import error)

*** no app loaded. GAME OVER ***

SIGINT/SIGTERM received...killing workers...

Exception ignored in: <module 'threading' from '/usr/local/lib/python3.8/threading.py'>

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/threading.py", line 1355, in _shutdown

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/serializer.py", line 218, in _serialize_node

    return _serialize_node_impl(

  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/serializer.py", line 278, in _serialize_node_impl

    if obj is None or isinstance(obj, (bool, number_types)):

KeyboardInterrupt

06:04:19 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk

    def _shutdown():

Traceback (most recent call last):

KeyboardInterrupt: 

  File "/usr/local/lib/python3.8/site-packages/sentry/wsgi.py", line 46, in <module>

    application = FileWrapperWSGIHandler()

  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 135, in __init__

    self.load_middleware()

  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/middleware.py", line 66, in sentry_patched_load_middleware

    return old_load_middleware(*args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 35, in load_middleware

    middleware = import_string(middleware_path)

  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/middleware.py", line 51, in sentry_patched_import_string

    rv = old_import_string(dotted_path)

  File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string

    module = import_module(module_path)

  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

ModuleNotFoundError: No module named 'csp'

unable to load app 0 (mountpoint='') (callable not found or import error)

*** no app loaded. GAME OVER ***

gateway "uWSGI http 1" has been buried (pid: 691)

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/sentry/wsgi.py", line 46, in <module>

    application = FileWrapperWSGIHandler()

  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 135, in __init__

    self.load_middleware()

  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/middleware.py", line 66, in sentry_patched_load_middleware

    return old_load_middleware(*args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 35, in load_middleware

    middleware = import_string(middleware_path)

  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/middleware.py", line 51, in sentry_patched_import_string

    rv = old_import_string(dotted_path)

  File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string

    module = import_module(module_path)

  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 839, in exec_module

  File "<frozen importlib._bootstrap_external>", line 934, in get_code

  File "<frozen importlib._bootstrap_external>", line 1033, in get_data

KeyboardInterrupt

unable to load app 0 (mountpoint='') (callable not found or import error)

*** no app loaded. GAME OVER ***

thread panicked while processing panic. aborting.

thread panicked while processing panic. aborting.

thread panicked while processing panic. aborting.

worker 1 buried after 1 seconds

worker 2 buried after 1 seconds

worker 3 buried after 1 seconds

goodbye to uWSGI.

Updating certificates in /etc/ssl/certs...

0 added, 0 removed; done.

Running hooks in /etc/ca-certificates/update.d...

done.

**Comment by hubertdeng123** [comment]
Thanks for writing in! 
Did you receive this error after a clean upgrade? Wondering if you have this option defined in your config file `slack.legacy-app` which is causing this issue

**Comment by DzianisMatveyeu** [comment]
I have the same error, after updating from 21.6.3 to 23.4.0 
[Logs](https://pastebin.com/Bk4qBt0g)

**Comment by tm1000** [comment]
This is a duplicate of #2163

**Comment by tm1000** [comment]
@hubertdeng123 so my mistake. I have a .env.custom and I forgot to update it. As a result I was running older images!
