### ISSUE TITLE
No module named 'snuba.settings.settings_self_hosted'

### ISSUE THREAD

**Issue by ProFire** [getsentry/self-hosted#2218]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Install 23.3.1
2. Download 23.5.2
3. tar -xvzf 23.5.2.tar.gz
4. cp -rf self-hosted-23.5.2/* sentryio/
5. Install 23.5.2

### Expected Result

Smooth installation with no errors

### Actual Result

I got 

```
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/bin/snuba", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/snuba/snuba/cli/__init__.py", line 13, in <module>
    from snuba.environment import metrics as environment_metrics
  File "/usr/src/snuba/snuba/environment.py", line 17, in <module>
    from snuba import settings
  File "/usr/src/snuba/snuba/settings/__init__.py", line 410, in <module>
    _load_settings()
  File "/usr/src/snuba/snuba/settings/__init__.py", line 401, in _load_settings
    settings_module = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'snuba.settings.settings_self_hosted'
Error in install/bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:31
--> install/bootstrap-snuba.sh:source:3
```

When I edit the following line in docker-compose.yml, it works:

```
SNUBA_SETTINGS: docker
```

I'm quite sure I'm suppose to edit/copy some settings, but I can't figure out where I should go.

### Product Area

Settings

### Version

23.5.2

**Comment by hubertdeng123** [comment]
Hi there, can you ensure you're using a more recent snuba image? Do you have a custom env file that may be overriding the default version?

**Comment by hubertdeng123** [comment]
The snuba image that adds the self-hosted settings was released in 23.4.0. If I were to guess, your snuba image is still on 23.3.1 which is declared in your `.env` file.

**Comment by ProFire** [comment]
Oh, I think I understand the issue. I see in the .env file the following:

```
SENTRY_IMAGE=getsentry/sentry:23.1.1
SNUBA_IMAGE=getsentry/snuba:23.1.1
RELAY_IMAGE=getsentry/relay:23.1.1
SYMBOLICATOR_IMAGE=getsentry/symbolicator:0.6.0
```

Should I change all the 23.1.1 to 23.5.2?

**Comment by hubertdeng123** [comment]
@ProFire Yes, you should.

**Comment by ProFire** [comment]
Yes, it worked. After I updated the values and run ./install.sh, I don't encounter the error anymore.

I guess I'll do this additional step from now on. I wish this was documented somewhere. If it already is, I wish it was a bit more obvious.

**Comment by hubertdeng123** [comment]
The .env file in 23.5.2 release should come with the images tagged with the appropriate versions. My guess is you’re not overwriting the file when upgrading. Are you using custom env variables? Perhaps we can better document this during the upgrade process

**Comment by ProFire** [comment]
I'm definitely not using any custom .env file. When I edited the .env file and run `./install.sh`, it worked.
My guess that the command `cp -rf self-hosted-23.5.2 sentryio` failed to copy dotfiles over.

**Comment by hubertdeng123** [comment]
Got it, thanks for the info. Going to close this since it seems to be resolved now
