### ISSUE TITLE
InconsistentMigrationHistory

### ISSUE THREAD

**Issue by justsomexanda** [getsentry/self-hosted#2229]
### Self-Hosted Version

23.6.1

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.2, build cb74dfc

### Docker Compose Version

Docker Compose version v2.18.1 (docker-compose-plugin)

### Steps to Reproduce

1. git clone https://github.com/getsentry/self-hosted sentry
2. cd sentry
3. ./install

### Expected Result

Migration ran successfully

### Actual Result

```
...
▶ Setting up / migrating database ...
 Container sentry-self-hosted-memcached-1  Creating
 Container sentry-self-hosted-symbolicator-1  Creating
 Container sentry-self-hosted-postgres-1  Creating
 Container sentry-self-hosted-smtp-1  Creating
 Container sentry-self-hosted-clickhouse-1  Running
 Container sentry-self-hosted-redis-1  Running
 Container sentry-self-hosted-zookeeper-1  Running
 Container sentry-self-hosted-kafka-1  Running
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Creating
 Container sentry-self-hosted-vroom-1  Creating
 Container sentry-self-hosted-snuba-consumer-1  Creating
 Container sentry-self-hosted-snuba-api-1  Creating
 Container sentry-self-hosted-snuba-transactions-consumer-1  Creating
 Container sentry-self-hosted-snuba-replacer-1  Creating
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Creating
 Container sentry-self-hosted-snuba-sessions-consumer-1  Creating
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Creating
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Created
 Container sentry-self-hosted-snuba-api-1  Created
 Container sentry-self-hosted-snuba-transactions-consumer-1  Created
 Container sentry-self-hosted-snuba-consumer-1  Created
 Container sentry-self-hosted-snuba-sessions-consumer-1  Created
 Container sentry-self-hosted-snuba-replacer-1  Created
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Created
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Created
 Container sentry-self-hosted-vroom-1  Created
 Container sentry-self-hosted-symbolicator-1  Created
 Container sentry-self-hosted-memcached-1  Created
 Container sentry-self-hosted-smtp-1  Created
 Container sentry-self-hosted-postgres-1  Created
 Container sentry-self-hosted-smtp-1  Starting
 Container sentry-self-hosted-postgres-1  Starting
 Container sentry-self-hosted-symbolicator-1  Starting
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-memcached-1  Starting
 Container sentry-self-hosted-zookeeper-1  Healthy
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-symbolicator-1  Started
 Container sentry-self-hosted-smtp-1  Started
 Container sentry-self-hosted-memcached-1  Started
 Container sentry-self-hosted-postgres-1  Started
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-snuba-replacer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-vroom-1  Starting
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Starting
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-snuba-api-1  Starting
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-snuba-sessions-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-snuba-consumer-1  Starting
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-snuba-transactions-consumer-1  Starting
 Container sentry-self-hosted-snuba-replacer-1  Started
 Container sentry-self-hosted-vroom-1  Started
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Started
 Container sentry-self-hosted-snuba-api-1  Started
 Container sentry-self-hosted-snuba-sessions-consumer-1  Started
 Container sentry-self-hosted-snuba-consumer-1  Started
 Container sentry-self-hosted-snuba-transactions-consumer-1  Started
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Started
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Started
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image
07:57:34 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb
07:57:35 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb
Running migrations for default
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 99, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 50, in _upgrade
    dj_call_command(
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 90, in handle
    executor.loader.check_consistent_history(connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 295, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency sentry.0001_squashed_0200_release_indices on database 'default'.
Error in install/set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:34
--> install/set-up-and-migrate-database.sh:source:12

Looks like you've already sent this error to us, we're on it :)
```

**Comment by hubertdeng123** [comment]
Is this a fresh install? Are you upgrading from an older version of Sentry to 23.6.1?

**Comment by justsomexanda** [comment]
> Is this a fresh install? Are you upgrading from an older version of Sentry to 23.6.1?

Fresh install on Ubuntu latest LTS. I try once every couple of months, but same error. Docker volumes are always dropped after I finish my failed attempt (docker-compose down -v).

If I run this on my machine I work on, it works just fine, which is also Ubuntu but desktop version.

**Comment by hubertdeng123** [comment]
> Fresh install on Ubuntu latest LTS. I try once every couple of months, but same error. Docker volumes are always dropped after I finish my failed attempt (docker-compose down -v).

Interesting, so you installed from scratch? I did a quick search and it looks like some people have experienced this in the past with v21.7.0, so maybe this would be helpful for you?
https://github.com/getsentry/self-hosted/issues/1114

**Comment by justsomexanda** [comment]
I tried and followed suggested steps (once again).

I tried this before and it also didn't work, but after upgrading to docker compose v2 it doesn't work even more (because "docker compose" instead of "docker-compose"). Before upgrading compose to v2 I tried with different sentry versions as well.

```
 File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 99, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 50, in _upgrade
    dj_call_command(
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 90, in handle
    executor.loader.check_consistent_history(connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 295, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration sentry.0201_semver_package is applied before its dependency sentry.0001_squashed_0200_release_indices on database 'default'.
Error in install/set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:34
--> install/set-up-and-migrate-database.sh:source:12

Looks like you've already sent this error to us, we're on it :)
> ✘  server  /s/sentry  ➦ f8a7fa7    git checkout 21.6.3
Previous HEAD position was f8a7fa7 release: 23.6.1
HEAD is now at 4da1069 release: 21.6.3
> server  /s/sentry  ➦ 4da1069    ./install.sh
▶ Parsing command line ...

▶ Setting up error handling ...

▶ Checking minimum requirements ...
check-minimum-requirements.sh: line 11: docker-compose: command not found
An error occurred, caught SIGERR on line 11
Cleaning up...
```

**Comment by hubertdeng123** [comment]
That's all I got then 🥲. You may need to start from scratch and rerun the migrations on an empty Postgres database if all else fails

**Comment by justsomexanda** [comment]
Thats a bummer :/
As far as I know I am starting from scratch every attempt. I am commanding "docker down -v" which should reset everything, right? Is Sentry using a bare-metal installation of Postgres, which I am not aware of?

I would be totally fine with starting over from the start, that was my plan anyway, so is sentry persisting somewhere else outside of the docker environment?

**Comment by aldy505** [comment]
I’m going to close this for now, since this appears to be tied to an older install / migration state rather than a current self-hosted issue we can act on directly.
 
Self-hosted has changed a lot since 2023, and if someone is still on an older version, the right path would be to upgrade first. If this still reproduces on a current release, please open a new issue with the exact version, upgrade path, and any migration/database details, that would help us investigate it in a more actionable way.
