### ISSUE TITLE
UnsafeOperationException

### ISSUE THREAD

**Issue by LuckyType** [getsentry/self-hosted#2232]
### Self-Hosted Version

23.5.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

2.12.2

### Steps to Reproduce

I had a running installation of Sentry 23.4.0.dev0 aac2452 and ran  ./install.sh
Also tried with
```
SENTRY_IMAGE=getsentry/sentry:latest ./install.sh
SENTRY_IMAGE=getsentry/sentry:23.6.0 ./install.sh
SENTRY_IMAGE=getsentry/sentry:23.5.0 ./install.sh
```
in that order.

Trying to go back to 23.4.0 results in the same error.

### Expected Result

The install.sh completes successfully. upgrading to the latest nightly

### Actual Result
```

▶ Setting up / migrating database ...
Container sentry-self-hosted-symbolicator-1  Creating
Container sentry-self-hosted-memcached-1  Creating
Container sentry-self-hosted-postgres-1  Creating
Container sentry-self-hosted-smtp-1  Creating
Container sentry-self-hosted-zookeeper-1  Running
Container sentry-self-hosted-kafka-1  Running
Container sentry-self-hosted-redis-1  Running
Container sentry-self-hosted-clickhouse-1  Running
Container sentry-self-hosted-snuba-replacer-1  Creating
Container sentry-self-hosted-snuba-transactions-consumer-1  Creating
Container sentry-self-hosted-snuba-subscription-consumer-events-1  Creating
Container sentry-self-hosted-snuba-outcomes-consumer-1  Creating
Container sentry-self-hosted-snuba-sessions-consumer-1  Creating
Container sentry-self-hosted-snuba-consumer-1  Creating
Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Creating
Container sentry-self-hosted-snuba-api-1  Creating
Container sentry-self-hosted-snuba-subscription-consumer-events-1  Created
Container sentry-self-hosted-symbolicator-1  Created
Container sentry-self-hosted-snuba-transactions-consumer-1  Created
Container sentry-self-hosted-snuba-sessions-consumer-1  Created
Container sentry-self-hosted-snuba-api-1  Created
Container sentry-self-hosted-memcached-1  Created
Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Created
Container sentry-self-hosted-postgres-1  Created
Container sentry-self-hosted-smtp-1  Created
Container sentry-self-hosted-snuba-replacer-1  Created
Container sentry-self-hosted-snuba-outcomes-consumer-1  Created
Container sentry-self-hosted-snuba-consumer-1  Created
Container sentry-self-hosted-symbolicator-1  Starting
Container sentry-self-hosted-smtp-1  Starting
Container sentry-self-hosted-memcached-1  Starting
Container sentry-self-hosted-postgres-1  Starting
Container sentry-self-hosted-zookeeper-1  Waiting
Container sentry-self-hosted-zookeeper-1  Healthy
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-snuba-transactions-consumer-1  Starting
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Starting
Container sentry-self-hosted-snuba-subscription-consumer-events-1  Starting
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-snuba-sessions-consumer-1  Starting
Container sentry-self-hosted-snuba-consumer-1  Starting
Container sentry-self-hosted-snuba-api-1  Starting
Container sentry-self-hosted-snuba-outcomes-consumer-1  Starting
Container sentry-self-hosted-snuba-replacer-1  Starting
Container sentry-self-hosted-symbolicator-1  Started
Container sentry-self-hosted-memcached-1  Started
Container sentry-self-hosted-smtp-1  Started
Container sentry-self-hosted-postgres-1  Started
Container sentry-self-hosted-snuba-transactions-consumer-1  Started
Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Started
Container sentry-self-hosted-snuba-subscription-consumer-events-1  Started
Container sentry-self-hosted-snuba-sessions-consumer-1  Started
Container sentry-self-hosted-snuba-api-1  Started
Container sentry-self-hosted-snuba-consumer-1  Started
Container sentry-self-hosted-snuba-outcomes-consumer-1  Started
Container sentry-self-hosted-snuba-replacer-1  Started
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image
13:47:37 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, replays, sentry, sessions, sites, social_auth
Running migrations:
  Applying sentry.0419_add_null_constraint_for_org_integration_denorm...Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 99, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 50, in _upgrade
    dj_call_command(
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/sentry/new_migrations/monkey/executor.py", line 79, in apply_migration
    return super().apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/sentry/new_migrations/migrations.py", line 22, in apply
    return super().apply(project_state, schema_editor, collect_sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/schema.py", line 52, in inner
    func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 534, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
    super()._alter_field(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 661, in _alter_field
    fragment = self._alter_column_null_sql(model, old_field, new_field)
  File "/usr/local/lib/python3.8/site-packages/django_zero_downtime_migrations/backends/postgres/schema.py", line 592, in _alter_column_null_sql
    return self._alter_column_set_not_null(model, new_field)
  File "/usr/local/lib/python3.8/site-packages/django_zero_downtime_migrations/backends/postgres/schema.py", line 536, in _alter_column_set_not_null
    raise UnsafeOperationException(Unsafe.ALTER_COLUMN_NOT_NULL)
django_zero_downtime_migrations.backends.postgres.schema.UnsafeOperationException: ALTER COLUMN NOT NULL is unsafe operation
See details for safe alternative https://github.com/tbicr/django-pg-zero-downtime-migrations#dealing-with-not-null-constraint
Error in install/set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1

```

**Comment by LuckyType** [comment]
SENTRY_IMAGE=getsentry/sentry:23.4.0 ./install.sh threw as i've said the same error.

I just tried again with the previously running SHA aac2452 and got my instance atleast running again.
aac2452 is 23.4.0.dev0

**Comment by LuckyType** [comment]
As expected, even though the services are up and running, the Django migrations has been run and now i've got:
```

sentry-self-hosted-web-1  | 14:08:53 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_users.OrganizationUsersEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/hatraco-gmbh/users/' caller_ip='84.46.80.142' user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 OPR/100.0.0.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.38374876976013184 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-web-1  | Traceback (most recent call last):
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
sentry-self-hosted-web-1  |     return func(self, sql, *args, **kwargs)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
sentry-self-hosted-web-1  |     return self.cursor.execute(sql, clean_bad_params(params))
sentry-self-hosted-web-1  | psycopg2.errors.UndefinedColumn: column sentry_groupsnooze.until_escalating does not exist
sentry-self-hosted-web-1  | LINE 1: ...snooze"."state", "sentry_groupsnooze"."actor_id", "sentry_gr...
sentry-self-hosted-web-1  |                                                              ^
sentry-self-hosted-web-1  | 
sentry-self-hosted-web-1  | 
sentry-self-hosted-web-1  | During handling of the above exception, another exception occurred:
sentry-self-hosted-web-1  | 
sentry-self-hosted-web-1  | Traceback (most recent call last):
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
sentry-self-hosted-web-1  |     return self.cursor.execute(sql, params)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
sentry-self-hosted-web-1  |     raise_the_exception(self.db, e)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
sentry-self-hosted-web-1  |     return func(self, *args, **kwargs)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
sentry-self-hosted-web-1  |     return func(self, *args, **kwargs)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
sentry-self-hosted-web-1  |     raise exc_info[0](msg).with_traceback(exc_info[2])
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
sentry-self-hosted-web-1  |     return func(self, sql, *args, **kwargs)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
sentry-self-hosted-web-1  |     return self.cursor.execute(sql, clean_bad_params(params))
sentry-self-hosted-web-1  | psycopg2.errors.UndefinedColumn: UndefinedColumn('column sentry_groupsnooze.until_escalating does not exist\nLINE 1: ...snooze"."state", "sentry_groupsnooze"."actor_id", "sentry_gr...\n                                                             ^\n')
sentry-self-hosted-web-1  | SQL: SELECT "sentry_groupsnooze"."id", "sentry_groupsnooze"."group_id", "sentry_groupsnooze"."until", "sentry_groupsnooze"."count", "sentry_groupsnooze"."window", "sentry_groupsnooze"."user_count", "sentry_groupsnooze"."user_window", "sentry_groupsnooze"."state", "sentry_groupsnooze"."actor_id", "sentry_groupsnooze"."until_escalating" FROM "sentry_groupsnooze" WHERE "sentry_groupsnooze"."group_id" IN (%s, %s, %s, %s, %s)
sentry-self-hosted-web-1  | 
sentry-self-hosted-web-1  | The above exception was the direct cause of the following exception:
sentry-self-hosted-web-1  | 
sentry-self-hosted-web-1  | Traceback (most recent call last):
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 188, in handle_exception
sentry-self-hosted-web-1  |     response = super().handle_exception(exc)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
sentry-self-hosted-web-1  |     self.raise_uncaught_exception(exc)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
sentry-self-hosted-web-1  |     raise exc
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 305, in dispatch
sentry-self-hosted-web-1  |     response = handler(request, *args, **kwargs)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/api/helpers/group_index/index.py", line 128, in wrapper
sentry-self-hosted-web-1  |     response = function(request, *args, **kwargs)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/api/endpoints/organization_group_index.py", line 334, in get
sentry-self-hosted-web-1  |     context = serialize(
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/base.py", line 78, in serialize
sentry-self-hosted-web-1  |     attrs = serializer.get_attrs(
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/group_stream.py", line 207, in get_attrs
sentry-self-hosted-web-1  |     attrs = super().get_attrs(item_list, user)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/group.py", line 235, in get_attrs
sentry-self-hosted-web-1  |     ignore_items = {g.group_id: g for g in GroupSnooze.objects.filter(group__in=item_list)}
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
sentry-self-hosted-web-1  |     self._fetch_all()
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
sentry-self-hosted-web-1  |     self._result_cache = list(self._iterable_class(self))
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
sentry-self-hosted-web-1  |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
sentry-self-hosted-web-1  |     cursor.execute(sql, params)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/__init__.py", line 582, in execute
sentry-self-hosted-web-1  |     return real_execute(self, sql, params)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
sentry-self-hosted-web-1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
sentry-self-hosted-web-1  |     return executor(sql, params, many, context)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
sentry-self-hosted-web-1  |     return self.cursor.execute(sql, params)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
sentry-self-hosted-web-1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
sentry-self-hosted-web-1  |     return self.cursor.execute(sql, params)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
sentry-self-hosted-web-1  |     raise_the_exception(self.db, e)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
sentry-self-hosted-web-1  |     return func(self, *args, **kwargs)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
sentry-self-hosted-web-1  |     return func(self, *args, **kwargs)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
sentry-self-hosted-web-1  |     raise exc_info[0](msg).with_traceback(exc_info[2])
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
sentry-self-hosted-web-1  |     return func(self, sql, *args, **kwargs)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
sentry-self-hosted-web-1  |     return self.cursor.execute(sql, clean_bad_params(params))
sentry-self-hosted-web-1  | django.db.utils.ProgrammingError: UndefinedColumn('column sentry_groupsnooze.until_escalating does not exist\nLINE 1: ...snooze"."state", "sentry_groupsnooze"."actor_id", "sentry_gr...\n                                                             ^\n')
sentry-self-hosted-web-1  | SQL: SELECT "sentry_groupsnooze"."id", "sentry_groupsnooze"."group_id", "sentry_groupsnooze"."until", "sentry_groupsnooze"."count", "sentry_groupsnooze"."window", "sentry_groupsnooze"."user_count", "sentry_groupsnooze"."user_window", "sentry_groupsnooze"."state", "sentry_groupsnooze"."actor_id", "sentry_groupsnooze"."until_escalating" FROM "sentry_groupsnooze" WHERE "sentry_groupsnooze"."group_id" IN (%s, %s, %s, %s, %s)

```

**Comment by LuckyType** [comment]
I wanted to check the migration file and checked the [file history of the migration](https://github.com/getsentry/sentry/commits/47a464dbc942a0748a00104a9c245239e89df439/src/sentry/migrations/0419_add_null_constraint_for_org_integration_denorm.py) and found the change to the `is_dangerous = True`.

I just used the [previous SHA](https://github.com/getsentry/sentry/commit/ee0b94c7da80d0cdc8d089f330ef13b90cbfce1a) where it still was False and ran:
`SENTRY_IMAGE=getsentry/sentry:ee0b94c ./install.sh`

The migration for sentry.0419_add_null_constraint_for_org_integration_denorm ran through.
I followed up by
`SENTRY_IMAGE=getsentry/sentry:latest ./install.sh`
to run the other migrations which completed as expected.

Everything seems to be okay now.
