### ISSUE TITLE
Unable to update Alert in Sentry

### ISSUE THREAD

**Issue by manikandan300** [getsentry/self-hosted#2268]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Hi Team,
Unable to update Alerts , Everytime I have to delete alert and create new if there is update in alert

See the Error Message Below 

<img width="1217" alt="image" src="https://github.com/getsentry/sentry/assets/213221/425a8768-d50b-434e-bfc1-c987f363841c">

### Expected Result

Alert should be updated

### Actual Result

<img width="1217" alt="image" src="https://github.com/getsentry/sentry/assets/213221/fe0f7042-44f3-491c-a7a2-502f357d1d64">

Error mesage
uring handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    raise exc_info[0](msg).with_traceback(exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.UniqueViolation: UniqueViolation('duplicate key value violates unique constraint "sentry_alertrule_organization_id_12c48b37_uniq"\nDETAIL:  Key (organization_id, name)=(1, Test) already exists.\n')
SQL: INSERT INTO "sentry_alertrule" ("organization_id", "snuba_query_id", "owner_id", "name", "status", "include_all_projects", "threshold_type", "resolve_threshold", "threshold_period", "comparison_delta", "date_modified", "date_added") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING "sentry_alertrule"."id"

### Product Area

Alerts

### Version

22.10.0

**Comment by azaslavsky** [comment]
Is there any chance you've restored from a backup recently?
