### ISSUE TITLE
snuba-sessions-consumer

### ISSUE THREAD

**Issue by roock** [getsentry/self-hosted#2271]
### Self-Hosted Version

23.6.2

### CPU Architecture

x86_64

### Docker Version

24.0.4

### Docker Compose Version

2.17.0

### Steps to Reproduce

I'm seeing the following error in container `sentry-self-hosted-snuba-sessions-consumer-1`

```
2023-07-17 12:30:51,221 No validator configured for topic
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 559, in process_message
    raise Exception("No validator configured for topic")
Exception: No validator configured for topic
2023-07-17 12:30:52,404 No validator configured for topic
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 559, in process_message
    raise Exception("No validator configured for topic")
Exception: No validator configured for topic
2023-07-17 12:30:53,669 No validator configured for topic
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 559, in process_message
    raise Exception("No validator configured for topic")
Exception: No validator configured for topic
```

The error is repeated almost every second or even more often. I think the error start when upgrading from 23.5.2 to 23.6.2. Otherwise everything else seems to be working fine.

### Expected Result

No errors are shown on the `sentry-self-hosted-snuba-sessions-consumer-1`

### Actual Result

Logs of `sentry-self-hosted-snuba-sessions-consumer-1` are flooded with error messages.

**Comment by azaslavsky** [comment]
We see this on our production instance too. We are planning to [deprecate sessions](https://github.com/getsentry/self-hosted/issues/2200) in the near future, at which point this service, and therefore this issue, should go away.
