### ISSUE TITLE
Pydantic validation error when accessing trace

### ISSUE THREAD

**Issue by pboers1988** [getsentry/self-hosted#2289]
### Self-Hosted Version

23.6.1

### CPU Architecture

x86_64

### Docker Version

24.0.4

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Go to the page https://<your url here>/organizations/sentry/performance/trace/<trace_id>/?statsPeriod=7d
2. This is the result
<img width="1466" alt="Screenshot 2023-07-21 at 14 54 21" src="https://github.com/getsentry/self-hosted/assets/3235585/dd1e7203-76b0-4a0d-ba31-ccacbb0cbd80">

3. Http request result ```{"detail":"Internal error. Your query failed to run."}```

We are running a stock install of sentry where the config only has custom slack configuration and mail configuration.

### Expected Result

The trace page, so we can correlate data accross all services

### Actual Result

logs output of the web page:

```bash
12:49:15 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_events_trace.OrganizationEventsTraceMetaEndpoint' response=500 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/events-trace-meta/3c7004ec1bac40e7bb425c9770e3f7a4/' caller_ip='145.90.231.141' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.23001456260681152 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
12:49:15 [ERROR] django.request: Internal Server Error: /api/0/organizations/sentry/events-trace-meta/3c7004ec1bac40e7bb425c9770e3f7a4/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/sentry/events-trace-meta/3c7004ec1bac40e7bb425c9770e3f7a4/?project=-1&query=&statsPeriod=7d'>)
NoneType: None
12:49:23 [WARNING] sentry.services.hybrid_cloud: Pydantic type validation error
NoneType: None
12:49:23 [WARNING] sentry.services.hybrid_cloud: Pydantic type validation error
12:49:23 [INFO] sentry.access.api: api.access (method='GET' view='sentry.web.frontend.react_page.ReactPageView' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/organizations/sentry/performance/trace/3c7004ec1bac40e7bb425c9770e3f7a4/' caller_ip='145.90.231.141' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.05277872085571289 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
```

Schreenshot as shared above.

If you need more information, please feel free to reach out.

**Comment by azaslavsky** [comment]
Hmm, this looks like a bug on our end. It seems like it might be related to the work in https://github.com/getsentry/sentry/pull/50846. We are currently having some migration issues with 23.7.0 ([more info](https://github.com/getsentry/self-hosted/issues/2281)), but will release 23.7.1 on Monday, which will include the change linked above. Once we do, would you be willing to upgrade and post the (hopefully) newly available stack trace produced by this error?

**Comment by jahands** [comment]
I am getting this issue as well on 23.6.1

**Comment by damon-kwok** [comment]
I am getting this issue as well on 23.6.1 (same http response)
Here are the logs when I refresh the `projects` page:
```
10:44:09 [INFO] sentry.superuser: superuser.request (url='http://192.168.1.220:30080/api/1/envelope/?sentry_key=e4f849b6b87146888ed50ebf361ec0cd&sentry_version=7&sentry_client=sentry.javascript.react%2F7.53.1' method='POST' ip_address='192.168.1.119' user_id=3)
NoneType: None
10:44:09 [ERROR] root: CSRF failure for staff or superuser
10:44:09 [INFO] sentry.superuser: superuser.request (url='http://192.168.1.220:30080/api/1/envelope/?sentry_key=e4f849b6b87146888ed50ebf361ec0cd&sentry_version=7&sentry_client=sentry.javascript.react%2F7.53.1' method='POST' ip_address='192.168.1.119' user_id=3)
NoneType: None
10:44:09 [ERROR] root: CSRF failure for staff or superuser
10:44:09 [INFO] sentry.superuser: superuser.request (url='http://192.168.1.220:30080/api/0/organizations/sentry/user-teams/' method='GET' ip_address='192.168.1.119' user_id=3)
10:44:09 [INFO] sentry.superuser: superuser.superuser_access (superuser_token_id='mHBbvGIOlwwf' user_id=3 user_email='guowangwei@fuyao.com' su_org_accessed='sentry')
10:44:09 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_user_teams.OrganizationUserTeamsEndpoint' response=200 user_id='3' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/user-teams/' caller_ip='192.168.1.119' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.09173345565795898 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
NoneType: None
10:44:09 [WARNING] sentry.services.hybrid_cloud: Pydantic type validation error
NoneType: None
10:44:09 [WARNING] sentry.services.hybrid_cloud: Pydantic type validation error
10:44:09 [WARNING] django.security.csrf: Forbidden (CSRF token missing or incorrect.): /api/1/envelope/ (status_code=403 request=<WSGIRequest: POST '/api/1/envelope/?sentry_key=e4f849b6b87146888ed50ebf361ec0cd&sentry_version=7&sentry_client=sentry.javascript.react%2F7.53.1'>)
10:44:09 [INFO] sentry.access.api: api.access (method='POST' view='django.views.generic.base.RedirectView' response=403 user_id='3' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/api/1/envelope/' caller_ip='192.168.1.119' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.19309210777282715 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
NoneType: None
10:44:09 [WARNING] sentry.services.hybrid_cloud: Pydantic type validation error
NoneType: None
10:44:09 [WARNING] sentry.services.hybrid_cloud: Pydantic type validation error
10:44:09 [WARNING] django.security.csrf: Forbidden (CSRF token missing or incorrect.): /api/1/envelope/ (status_code=403 request=<WSGIRequest: POST '/api/1/envelope/?sentry_key=e4f849b6b87146888ed50ebf361ec0cd&sentry_version=7&sentry_client=sentry.javascript.react%2F7.53.1'>)
10:44:09 [INFO] sentry.access.api: api.access (method='POST' view='django.views.generic.base.RedirectView' response=403 user_id='3' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/api/1/envelope/' caller_ip='192.168.1.119' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.22109556198120117 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
10:44:09 [INFO] sentry.superuser: superuser.request (url='http://192.168.1.220:30080/api/0/organizations/sentry/projects/?query=id%3A1%20id%3A2&sessionStats=1&statsPeriod=24h&transactionStats=1' method='GET' ip_address='192.168.1.119' user_id=3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 222, in handle_exception
    response = super().handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 345, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/drainage.py", line 156, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/endpoints/organization_projects.py", line 145, in get
    return self.paginate(
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 455, in paginate
    results = on_results(cursor_result.results)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/endpoints/organization_projects.py", line 143, in serialize_on_result
    return serialize(result, request.user, serializer)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/base.py", line 78, in serialize
    attrs = serializer.get_attrs(
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/project.py", line 667, in get_attrs
    attrs = super().get_attrs(item_list, user)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/project.py", line 554, in get_attrs
    attrs = super().get_attrs(item_list, user)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/project.py", line 319, in get_attrs
    stats = self.get_stats(project_ids, "!event.type:transaction")
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/project.py", line 394, in get_stats
    stats = discover.top_events_timeseries(
  File "/usr/local/lib/python3.8/site-packages/sentry/snuba/discover.py", line 477, in top_events_timeseries
    result = top_events_builder.run_query(referrer)
  File "/usr/local/lib/python3.8/site-packages/sentry/search/events/builder/discover.py", line 1675, in run_query
    return raw_snql_query(self.get_snql_query(), referrer, use_cache)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/snuba.py", line 797, in raw_snql_query
    return _apply_cache_and_build_results([params], referrer=referrer, use_cache=use_cache)[0]
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/snuba.py", line 872, in _apply_cache_and_build_results
    query_results = _bulk_snuba_query([item[1] for item in to_query], headers)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/snuba.py", line 955, in _bulk_snuba_query
    raise clickhouse_error_codes_map.get(error["code"], QueryExecutionError)(
sentry.utils.snuba.QueryExecutionError: DB::Exception: Table default.errors_dist doesn't exist. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8febd9a in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x9102da3 in /usr/bin/clickhouse
2. void std::__1::__optional_storage_base<DB::Exception, false>::__construct<int const&, char const (&) [23], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int const&, char const (&) [23], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x1010cfb1 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const @ 0x100ff04a in /usr/bin/clickhouse
4. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const @ 0x10105708 in /usr/bin/clickhouse
5. DB::JoinedTables::getLeftTableStorage() @ 0x10692c5c in /usr/bin/clickhouse
6. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x1047ac7c in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x1047a25e in /usr/bin/clickhouse
8. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context const>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x106571fa in /usr/bin/clickhouse
9. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x10265837 in /usr/bin/clickhouse
10. ? @ 0x1081bc66 in /usr/bin/clickhouse
11. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1081a5a3 in /usr/bin/clickhouse
12. DB::TCPHandler::runImpl() @ 0x110c08be in /usr/bin/clickhouse
13. DB::TCPHandler::run() @ 0x110d3859 in /usr/bin/clickhouse
14. Poco::Net::TCPServerConnection::start() @ 0x13c4ca2f in /usr/bin/clickhouse
15. Poco::Net::TCPServerDispatcher::run() @ 0x13c4e4ba in /usr/bin/clickhouse
16. Poco::PooledThread::run() @ 0x13d80739 in /usr/bin/clickhouse
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x13d7c9ca in /usr/bin/clickhouse
18. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
19. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

10:44:09 [INFO] sentry.superuser: superuser.superuser_access (superuser_token_id='mHBbvGIOlwwf' user_id=3 user_email='guowangwei@fuyao.com' su_org_accessed='sentry')
10:44:09 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_projects.OrganizationProjectsEndpoint' response=500 user_id='3' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/projects/' caller_ip='192.168.1.119' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.19248580932617188 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
10:44:09 [ERROR] django.request: Internal Server Error: /api/0/organizations/sentry/projects/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/sentry/projects/?query=id%3A1%20id%3A2&sessionStats=1&statsPeriod=24h&transactionStats=1'>)


```

**Comment by azaslavsky** [comment]
@damon-kwok this seems like a different issue (Snuba vs Hybrid Cloud). Would you mind opening a separate bug so that we can route to the correct location?
