### ISSUE TITLE
Enhance script doesn't work anymore

### ISSUE THREAD

**Issue by devag-al** [getsentry/self-hosted#2334]
### Self-Hosted Version

23.7.2

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.20.2

### Steps to Reproduce

1. Create script `sentry/enhance-image.sh` and put `apt update` in it
2. Run `./install.sh`
3. Will crash trying to `apt update`

I've also put `id` in that script and as shown in the actual result below, script is ran as `root`.

### Expected Result

Script execute as normal (which used to work properly before (not sure which version, but around last March/April, it was working properly)

### Actual Result

```
#6 [web 2/4] COPY . /usr/src/sentry
#6 DONE 0.0s

#7 [web 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#7 0.262 uid=0(root) gid=0(root) groups=0(root)
#7 0.265 mkdir: cannot create directory ‘/var/lib/apt/lists/partial’: Permission denied
#7 0.277 Reading package lists...
#7 0.277 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#7 0.277 
#7 0.284 
#7 0.287 E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
#7 0.292 
#7 0.293 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#7 0.293 
#7 0.296 E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
#7 0.297 E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
#7 0.869 Defaulting to user installation because normal site-packages is not writeable
#7 0.951 ERROR: Exception:
#7 0.951 Traceback (most recent call last):
#7 0.951   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
#7 0.951     status = run_func(*args)
#7 0.951   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
#7 0.951     return func(self, options, args)
#7 0.951   File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 294, in run
#7 0.951     wheel_cache = WheelCache(options.cache_dir, options.format_control)
#7 0.951   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cache.py", line 219, in __init__
#7 0.951     self._ephem_cache = EphemWheelCache(format_control)
#7 0.951   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cache.py", line 191, in __init__
#7 0.951     self._temp_dir = TempDirectory(
#7 0.951   File "/usr/local/lib/python3.8/site-packages/pip/_internal/utils/temp_dir.py", line 125, in __init__
#7 0.951     path = self._create(kind)
#7 0.951   File "/usr/local/lib/python3.8/site-packages/pip/_internal/utils/temp_dir.py", line 164, in _create
#7 0.951     path = os.path.realpath(tempfile.mkdtemp(prefix=f"pip-{kind}-"))
#7 0.951   File "/usr/local/lib/python3.8/tempfile.py", line 347, in mkdtemp
#7 0.951     prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
#7 0.951   File "/usr/local/lib/python3.8/tempfile.py", line 117, in _sanitize_params
#7 0.951     dir = gettempdir()
#7 0.951   File "/usr/local/lib/python3.8/tempfile.py", line 286, in gettempdir
#7 0.951     tempdir = _get_default_tempdir()
#7 0.951   File "/usr/local/lib/python3.8/tempfile.py", line 218, in _get_default_tempdir
#7 0.951     raise FileNotFoundError(_errno.ENOENT,
#7 0.951 FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
#7 ERROR: executor failed running [/bin/sh -c if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi]: exit code: 2
------
 > [web 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi:
0.951     path = os.path.realpath(tempfile.mkdtemp(prefix=f"pip-{kind}-"))
0.951   File "/usr/local/lib/python3.8/tempfile.py", line 347, in mkdtemp
0.951     prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
0.951   File "/usr/local/lib/python3.8/tempfile.py", line 117, in _sanitize_params
0.951     dir = gettempdir()
0.951   File "/usr/local/lib/python3.8/tempfile.py", line 286, in gettempdir
0.951     tempdir = _get_default_tempdir()
0.951   File "/usr/local/lib/python3.8/tempfile.py", line 218, in _get_default_tempdir
0.951     raise FileNotFoundError(_errno.ENOENT,
0.951 FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
------
failed to solve: executor failed running [/bin/sh -c if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi]: exit code: 2
Error in install/build-docker-images.sh:6.
'$dcb --force-rm web' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:6
```

**Comment by hubertdeng123** [comment]
I don't think this is something particularly wrong with the enhance script, it seems to be another issue that you may be having. Perhaps the image is being built on a non-root user, and you may need to specify root permissions to bypass this error.

**Comment by devag-al** [comment]
Well, the error is coming from the Docker image, and so this is during the image build process, where the build user is `root` as shown by my `id` line in the `enhance-image.sh` :

```
#7 [web 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#7 0.262 uid=0(root) gid=0(root) groups=0(root)
```

It shows as `uid=0`.  If I don't put anything in the `enhance-image.sh` file and run those same commands with an `exec` on the `web` and `worker` containers once the environment is built, it works properly.

So something funky is going on during the build process.

I'm running Docker Compose as a user having the `docker` group, for I did test as `root` before posting just in case, and I had the same issue.

Just to make sure, the error is coming from inside the Docker environment, not from my OS.  Those command are Debian-related and my OS is not, so the error has to come from the container building process.

**Comment by hubertdeng123** [comment]
Interesting, thanks for the additional info. Let me see if I can reproduce

**Comment by hubertdeng123** [comment]
I am unable to reproduce this locally :/

Not sure what is going on for you

**Comment by alegag** [comment]
I'm not able to confirm if this is the reason, but on my system, the `/usr` partition is read-only.

So the latest version of `docker-compose` is under my user's home folder in `~/.local/bin/docker-compose`.

My user has `docker` group.  That file is assigned to my user's uid+gid tho', not the docker's group.

Maybe this is what makes it not behave as supposed ???

I've compared the SELinux parms of the `docker-compose` under `/usr` and that one and it is the same.

**Comment by hubertdeng123** [comment]
Thanks for chiming in! Let us know what you find
