### ISSUE TITLE
Strange Errors in Workers about invalid value

### ISSUE THREAD

**Issue by tm1000** [getsentry/self-hosted#2348]
### Self-Hosted Version

23.7.2

### CPU Architecture

x86_64

### Docker Version

20.10.17, build 100c701

### Docker Compose Version

2.20.0

### Steps to Reproduce

Starting up sentry self-hosted, the workers crash with the following: `ValueError: The `socket.timeout.ms` configuration key is not supported.`

### Expected Result

Shouldnt crash.

If I remove the following configuration option: https://github.com/getsentry/self-hosted/blob/8c294f577bab901272d536c35a082879d6417331/sentry/sentry.conf.example.py#L129

Then the error isnt there anymore

### Actual Result

```
ValueError: The `socket.timeout.ms` configuration key is not supported.
20:26:24 [ERROR] celery.app.trace: Task sentry.tasks.store.save_event_transaction[c61423e1-c0ea-4522-b175-68606293073b] raised unexpected: ValueError('The `socket.timeout.ms` configuration key is not supported.') (data={'hostname': '31d697c2100c', 'id': 'c61423e1-c0ea-4522-b175-68606293073b', 'name': 'sentry.tasks.store.save_event_transaction', 'exc': "ValueError('The `socket.timeout.ms` configuration key is not supported.')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 60, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 270, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 114, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 831, in save_event_transaction\n    _do_save_event(cache_key, data, start_time, event_id, project_id, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 707, in _do_save_event\n    manager.save(\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 199, in inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 437, in save\n    jobs = save_transaction_events([job], projects)\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 199, in inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 2460, in save_transaction_events\n    _send_occurrence_to_platform(jobs, projects)\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 199, in inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 2424, in _send_occurrence_to_platform\n    produce_occurrence_to_kafka(occurrence)\n  File "/usr/local/lib/python3.8/site-packages/sentry/issues/producer.py", line 50, in produce_occurrence_to_kafka\n    _occurrence_producer.produce(Topic(settings.KAFKA_INGEST_OCCURRENCES), payload)\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/arroyo_producer.py", line 35, in produce\n    future = self._get().produce(topic, payload)\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/arroyo_producer.py", line 40, in _get\n    self._producer = self._factory()\n  File "/usr/local/lib/python3.8/site-packages/sentry/issues/producer.py", line 20, in _get_occurrence_producer\n    return KafkaProducer(build_kafka_configuration(default_config=producer_config))\n  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/configuration.py", line 63, in build_kafka_configuration\n    raise ValueError(\nValueError: The `socket.timeout.ms` configuration key is not supported.\n', 'args': '()', 'kwargs': "{'cache_key': 'e:5f9f62d4d93f4a9492befe0ea78d595a:39', 'data': None, 'start_time': 1692215753.0, 'event_id': '5f9f62d4d93f4a9492befe0ea78d595a', 'project_id': 39}", 'description': 'raised unexpected', 'internal': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 270, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 114, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 831, in save_event_transaction
    _do_save_event(cache_key, data, start_time, event_id, project_id, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 707, in _do_save_event
    manager.save(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 199, in inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 437, in save
    jobs = save_transaction_events([job], projects)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 199, in inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 2460, in save_transaction_events
    _send_occurrence_to_platform(jobs, projects)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 199, in inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 2424, in _send_occurrence_to_platform
    produce_occurrence_to_kafka(occurrence)
  File "/usr/local/lib/python3.8/site-packages/sentry/issues/producer.py", line 50, in produce_occurrence_to_kafka
    _occurrence_producer.produce(Topic(settings.KAFKA_INGEST_OCCURRENCES), payload)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/arroyo_producer.py", line 35, in produce
    future = self._get().produce(topic, payload)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/arroyo_producer.py", line 40, in _get
    self._producer = self._factory()
  File "/usr/local/lib/python3.8/site-packages/sentry/issues/producer.py", line 20, in _get_occurrence_producer
    return KafkaProducer(build_kafka_configuration(default_config=producer_config))
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/configuration.py", line 63, in build_kafka_configuration
    raise ValueError(
```

**Comment by hubertdeng123** [comment]
@tm1000 Which version of self-hosted are you using? This should no longer be an issue, since we've updated one of our libraries to support this option.

https://github.com/getsentry/arroyo/pull/275

**Comment by tm1000** [comment]
@hubertdeng123 23.7.2 (sorry about that I typo'd it in the initial)

**Comment by tm1000** [comment]
...and you release 23.8.0 yesterday.

I suspect the fix is in there?

**Comment by hubertdeng123** [comment]
Yep, it should be. Are you trying to enable issue platform on 23.7.2 yourself? That could be why things are failing on your side.

**Comment by tm1000** [comment]
@hubertdeng123 nope not trying to enable that. I usually review the example conf file when I do upgrades

**Comment by hubertdeng123** [comment]
Hmmmm ok. That's weird then. Either way, your temporary workaround should be fine and 23.8.0 should fix this.
