### ISSUE TITLE
Database migration issue when upgrading from 22.1 to 23.6.2

### ISSUE THREAD

**Issue by structurefall** [getsentry/self-hosted#2392]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

* Have existing data in self-hosted 22.1 with Postgres 9.6 DB
* Pull self-hosted 23.6.2 tag, run install.sh

### Expected Result

Successful upgrade

### Actual Result

Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, replays, sentry, sessions, sites, social_auth
Running migrations:
  Applying sentry.0385_service_hook_hc_fk...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/schema.py", line 52, in inner
    func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 534, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
    super()._alter_field(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 638, in _alter_field
    fragment, other_actions = self._alter_column_type_sql(model, old_field, new_field, new_type)
  File "/usr/local/lib/python3.8/site-packages/django_zero_downtime_migrations/backends/postgres/schema.py", line 625, in _alter_column_type_sql
    raise UnsafeOperationException(Unsafe.ALTER_COLUMN_TYPE)
django_zero_downtime_migrations.backends.postgres.schema.UnsafeOperationException: ALTER COLUMN TYPE is unsafe operation
See details for safe alternative https://github.com/tbicr/django-pg-zero-downtime-migrations#dealing-with-alter-table-alter-column-type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 117, in upgrade
    _upgrade(
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/upgrade.py", line 52, in _upgrade
    dj_call_command(
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/sentry/new_migrations/monkey/executor.py", line 79, in apply_migration
    return super().apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/sentry/new_migrations/migrations.py", line 22, in apply
    return super().apply(project_state, schema_editor, collect_sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/schema.py", line 60, in inner
    raise UnsafeOperationException(exc_str.format(*formatted_args))
django_zero_downtime_migrations.backends.postgres.schema.UnsafeOperationException: Altering the type of column ServiceHook.installation_id in this way is unsafe
More info here: https://develop.sentry.dev/database-migrations/#altering-column-types

### Product Area

Other

### Version

23.6.2

**Comment by hubertdeng123** [comment]
Were you able to upgrade from postgres 9.6 -> 14 successfully? Something there might've gone wrong

**Comment by hubertdeng123** [comment]
The script for that lives in `install/upgrade-postgres.sh`. Although, that might not be the case here as the migration itself doesn't look that dangerous to me.

https://github.com/getsentry/sentry/blob/master/src/sentry/migrations/0385_service_hook_hc_fk.py

**Comment by structurefall** [comment]
That part went on without incident, although I wouldn’t be surprised if it was related.

I’ll post details later, but I did actually get through this by running:

```
sentry django migrate sentry 0385 --fake
``` 

…from the web instance, then running install.sh again. This probably isn’t safe, however the table that this migration hits was empty in our db and we were getting desperate so I decided to risk it. So far it’s looking okay.

**Comment by structurefall** [comment]
Here are some additional details, including our complete not-so-great resolution and some additional questions.

As @hubertdeng123 notes above, the Postgres upgrade happened during the initial `install.sh` run and appears to have gone smoothly. The existing data was accessible from the Postgres 14.5 container and no errors occurred during that phase of the upgrade.

In order to isolate the problem, I tried spinning up just the Postgres and "web" containers, and used `docker exec` to shell into web. From there I was able to replicate the issue with `sentry upgrade`, and manipulate the migrations directly with `sentry django`.

I was hoping to get the SQL query that the migration was trying to run this way and possibly try it myself, but using `sentry django sqlmigrate sentry 0385` just gave me the same error message. Eventually I found this:

https://github.com/getsentry/sentry/pull/45656#issuecomment-1469480253

I found that the `sentry_servicehook` table in my database was empty, so I figured it was worth the risk to just run the query, which failed because the constraint being dropped apparently already didn't exist.

At this point I had people breathing down my neck to get the service back up, and my other option was to roll back to a pre-migration backup, so I ran `sentry django migrate sentry 0385 --fake` to update the migration table without actually trying to perform the migration. That command succeeded, so I went back and ran `install.sh` _again_ and it completed successfully, and my installation came back up looking healthy.

So that's all great, however I'm concerned that the table in question may now be in a weird state, and I might have issues with some future migration as a result. If there's some way to check that, I'd love to know about it!

**Comment by structurefall** [comment]
Update: I tried to upgrade to Sentry 23.8.0.

`install.sh` now ends with:

```sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image
Error: It looks like you've skipped a hard stop in our upgrade process. Please follow the upgrade process here: https://develop.sentry.dev/self-hosted/releases/#hard-stops
Error in install/set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:34
--> install/set-up-and-migrate-database.sh:source:12
```

I tried logging into web and running `sentry upgrade` gives me the same error. I also tried this:

```
root@6c25ae2ca64c:/# sentry django migrate sentry
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/django.py", line 14, in django
    execute_from_command_line(argv=[ctx.command_path] + list(management_args))
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 95, in handle
    executor.loader.check_consistent_history(connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 306, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration social_auth.0001_initial is applied before its dependency sentry.0001_squashed_0484_break_org_member_user_fk on database 'default'.
```

It seems like that might be the issue. Is there some sort of repair process I can run to get the DB back where it should be without losing data?

**Comment by structurefall** [comment]
Another update: I tried bumping just to 23.7.2, and got the same "skipped a hard stop" error. I guess I can try 23.7.1, but that seems like an extraordinarily unlikely fix and your docs explicitly say not to use 23.7.0. I'm at an impasse here, any help would be much appreciated.

**Comment by hubertdeng123** [comment]
I don't think going to 23.7.1 would help your problem. You can take a look at the code here that throws the error:
https://github.com/getsentry/sentry/blob/master/src/sentry/runner/commands/upgrade.py#L36. 

> It seems like that might be the issue. Is there some sort of repair process I can run to get the DB back where it should be without losing data?

I'm afraid not, you'd need a backup of your database to do so

**Comment by hubertdeng123** [comment]
The reason why 23.6.2 is a hard stop is because it includes a squash of migrations. I believe you're getting an issue there because somehow it wasn't applied cleanly, resulting in issues when trying to upgrade further.

**Comment by structurefall** [comment]
That makes sense, considering that as described above, my upgrade to 23.6.2 was _not_ applied cleanly. What can I do from here?

**Comment by hubertdeng123** [comment]
There may not be a clean way to approach this. You may need to wipe your database.
