### ISSUE TITLE
Upgrading to 23.9.1 causes performance issues

### ISSUE THREAD

**Issue by thelazyoxymoron** [getsentry/self-hosted#2415]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

20.10.22

### Docker Compose Version

2.14.1

### Steps to Reproduce

1. Checkout the latest release branch
2. Run `./install.sh`
3. Observe the performance in htop

### Expected Result

System should consume reasonable resources.

### Actual Result

All the CPU cores are running at 100% capacity and the memory also gets exhausted. Disabling session replay doesn't help either.

System details:
4 Cores, 8GB Memory

**Comment by hubertdeng123** [comment]
Unfortunately I'm not too surprised, given that we've added a lot more containers for 23.9.1 🥲. For now, there's no solution to this besides adding more CPU/RAM.

**Comment by thelazyoxymoron** [comment]
That's a shame, but understandable. Should the recommended system requirements in README be updated?

**Comment by hubertdeng123** [comment]
Yeah, they should be updated then. I'll have to investigate what this CPU/RAM should be. Do you have any datapoints for me to use?

**Comment by maperz** [comment]
We faced similar issues with a 4vCore, 8GB RAM machine. The Kafka image seems to restart every 3-8 minutes as we run out of memory.  After reverting to release `v23.8.0` htop shows `6.55G/7.79G` of usage which might not be ideal but keeps working for our circumstances. Curious if there is any way of reliably configuring the Java processes to keep running Sentry in future versions under the 8GB budget. Our use case is very minimal and keeping existing infrastructure would be great.

Nevertheless, a big thank you for the great effort behind Sentry, very much appreciated👍 .

**Comment by shadowlmd** [comment]
I'd recommend to check logs for exceptions because more images added doesn't mean rapid increase of resource usage. Maybe you are experiencing #2436.

**Comment by ybinnenwegin2ip** [comment]
> I'd recommend to check logs for exceptions because more images added doesn't mean rapid increase of resource usage. Maybe you are experiencing #2436.

We are experiencing excessive resource usage from Sentry self-hosted as well and I'm seeing the same messages as the issue you linked:

```
sentry-self-hosted-snuba-api-1                                     | 2023-10-02 07:40:00,441 Allocation policy failed to update quota balance, this is a bug, fix it
sentry-self-hosted-snuba-api-1                                     | Traceback (most recent call last):
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/__init__.py", line 745, in update_quota_balance
sentry-self-hosted-snuba-api-1                                     |     return self._update_quota_balance(tenant_ids, query_id, result_or_error)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 217, in _update_quota_balance
sentry-self-hosted-snuba-api-1                                     |     rate_limit_params, _ = self._get_rate_limit_params(tenant_ids)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 179, in _get_rate_limit_params
sentry-self-hosted-snuba-api-1                                     |     tenant_key, tenant_value = self._get_tenant_key_and_value(tenant_ids)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 172, in _get_tenant_key_and_value
sentry-self-hosted-snuba-api-1                                     |     raise AllocationPolicyViolation(
sentry-self-hosted-snuba-api-1                                     | snuba.query.allocation_policies.AllocationPolicyViolation: Queries must have a project id or organization id, explanation: {}
```

We are running Sentry on 4 vCPU's and 8GB of RAM, SSD storage.

**Comment by azaslavsky** [comment]
I agree that this is a Snuba issue - similar to https://github.com/getsentry/self-hosted/issues/2436. I've moved it over to that repository for triage.
