### ISSUE TITLE
Snuba API - Allocation policy failed to get quota allowance, this is a bug, fix it

### ISSUE THREAD

**Issue by rojinebrahimi** [getsentry/self-hosted#2417]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

K8s

### Docker Compose Version

K8s

### Steps to Reproduce

Hi!
I have upgraded the Sentry to its latest version using Helm Charts (from 21.1.0). When I want to login to my account, I encounter this issue. But I see no problems logging in via Admin account.
![Screenshot 2023-09-21 at 14 47 01](https://github.com/getsentry/self-hosted/assets/44529498/242c1b75-c8c7-41c0-9b9d-74a8ac153b69)

### Expected Result

I have migrated both ClickHouse and PSQL databases. Is there anything else that I need to check? Thanks in advance.

### Actual Result

![Screenshot 2023-09-21 at 14 44 17](https://github.com/getsentry/self-hosted/assets/44529498/e17e9b4a-cafc-4d17-a134-0e80b0d13bfc)

**Comment by hubertdeng123** [comment]
This may have something to do with your helm charts setup. Unfortunately, only the docker compose version of self-hosted is supported here. I haven't seen this error before so not sure what might be causing this.

**Comment by afaianswq** [comment]
I am running a canonical self-hosted installation and upgraded from 23.5.1 to 23.6.2 and then to 23.9.1. Right after upgrade, I noticed this message in the UI:

```
Background workers haven't checked in recently. It seems that you have a backlog of 371 tasks. Either your workers aren't running or you need more capacity.
```

I checked logs and found some kafka related issues:
```
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:38.918185934Z /usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:38.918193289Z   if key is '':
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:38.918197972Z /usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:38.918208243Z   if key_extra_len is 0:
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641161999Z Traceback (most recent call last):
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641201453Z   File "/usr/local/bin/sentry", line 8, in <module>
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641208133Z     sys.exit(main())
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641212742Z   File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641217301Z     func(**kwargs)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641238446Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641243495Z     return self.main(*args, **kwargs)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641247589Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641252355Z     rv = self.invoke(ctx)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641256053Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641260141Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641263994Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641268528Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641272699Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641276974Z     return ctx.invoke(self.callback, **ctx.params)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641280769Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641284674Z     return __callback(*args, **kwargs)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641288956Z   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641293829Z     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641297676Z   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641302347Z     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641306417Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641310785Z     return __callback(*args, **kwargs)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641314700Z   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641319443Z     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641323933Z   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641327835Z     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641331719Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641336028Z     return __callback(*args, **kwargs)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641339817Z   File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 746, in basic_consumer
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641344476Z     run_processor_with_signals(processor)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641350861Z   File "/usr/local/lib/python3.8/site-packages/sentry/utils/kafka.py", line 13, in run_processor_with_signals
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641355238Z     processor.run()
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641359040Z   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641363249Z     self._run_once()
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641372021Z   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 356, in _run_once
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641376855Z     self.__message = self.__consumer.poll(timeout=1.0)
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641380761Z   File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 414, in poll
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641385098Z     raise OffsetOutOfRange(str(error))
sentry-self-hosted-transactions-consumer-1  | 2023-09-29T08:21:41.641389158Z arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
```

I have fixed these issues by running the script:
```bash
docker compose down
docker compose up -d zookeeper kafka
sleep 60
docker compose exec -it kafka kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --all-groups --all-topics --reset-offsets --to-latest --execute
sleep 10
docker compose down
docker compose up
```

Error message in the UI didn't go, so I checked logs again and found this:
```
sentry-self-hosted-snuba-api-1                                     | 2023-09-29 08:43:48,430 Allocation policy failed to get quota allowance, this is a bug, fix it
sentry-self-hosted-snuba-api-1                                     | Traceback (most recent call last):
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/__init__.py", line 701, in get_quota_allowance
sentry-self-hosted-snuba-api-1                                     |     allowance = self._get_quota_allowance(tenant_ids, query_id)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 205, in _get_quota_allowance
sentry-self-hosted-snuba-api-1                                     |     rate_limit_params, overrides = self._get_rate_limit_params(tenant_ids)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 179, in _get_rate_limit_params
sentry-self-hosted-snuba-api-1                                     |     tenant_key, tenant_value = self._get_tenant_key_and_value(tenant_ids)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 172, in _get_tenant_key_and_value
sentry-self-hosted-snuba-api-1                                     |     raise AllocationPolicyViolation(
sentry-self-hosted-snuba-api-1                                     | snuba.query.allocation_policies.AllocationPolicyViolation: Queries must have a project id or organization id, explanation: {}
sentry-self-hosted-snuba-api-1                                     | 2023-09-29 08:43:48,513 Allocation policy failed to update quota balance, this is a bug, fix it
sentry-self-hosted-snuba-api-1                                     | Traceback (most recent call last):
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/__init__.py", line 745, in update_quota_balance
sentry-self-hosted-snuba-api-1                                     |     return self._update_quota_balance(tenant_ids, query_id, result_or_error)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 217, in _update_quota_balance
sentry-self-hosted-snuba-api-1                                     |     rate_limit_params, _ = self._get_rate_limit_params(tenant_ids)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 179, in _get_rate_limit_params
sentry-self-hosted-snuba-api-1                                     |     tenant_key, tenant_value = self._get_tenant_key_and_value(tenant_ids)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 172, in _get_tenant_key_and_value
sentry-self-hosted-snuba-api-1                                     |     raise AllocationPolicyViolation(
sentry-self-hosted-snuba-api-1                                     | snuba.query.allocation_policies.AllocationPolicyViolation: Queries must have a project id or organization id, explanation: {}
sentry-self-hosted-snuba-api-1                                     | 2023-09-29 08:44:04,969 Allocation policy failed to get quota allowance, this is a bug, fix it
sentry-self-hosted-snuba-api-1                                     | Traceback (most recent call last):
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/__init__.py", line 701, in get_quota_allowance
sentry-self-hosted-snuba-api-1                                     |     allowance = self._get_quota_allowance(tenant_ids, query_id)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 205, in _get_quota_allowance
sentry-self-hosted-snuba-api-1                                     |     rate_limit_params, overrides = self._get_rate_limit_params(tenant_ids)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 179, in _get_rate_limit_params
sentry-self-hosted-snuba-api-1                                     |     tenant_key, tenant_value = self._get_tenant_key_and_value(tenant_ids)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 172, in _get_tenant_key_and_value
sentry-self-hosted-snuba-api-1                                     |     raise AllocationPolicyViolation(
sentry-self-hosted-snuba-api-1                                     | snuba.query.allocation_policies.AllocationPolicyViolation: Queries must have a project id or organization id, explanation: {}
sentry-self-hosted-snuba-api-1                                     | 2023-09-29 08:44:04,997 Allocation policy failed to update quota balance, this is a bug, fix it
sentry-self-hosted-snuba-api-1                                     | Traceback (most recent call last):
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/__init__.py", line 745, in update_quota_balance
sentry-self-hosted-snuba-api-1                                     |     return self._update_quota_balance(tenant_ids, query_id, result_or_error)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 217, in _update_quota_balance
sentry-self-hosted-snuba-api-1                                     |     rate_limit_params, _ = self._get_rate_limit_params(tenant_ids)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 179, in _get_rate_limit_params
sentry-self-hosted-snuba-api-1                                     |     tenant_key, tenant_value = self._get_tenant_key_and_value(tenant_ids)
sentry-self-hosted-snuba-api-1                                     |   File "/usr/src/snuba/./snuba/query/allocation_policies/concurrent_rate_limit.py", line 172, in _get_tenant_key_and_value
sentry-self-hosted-snuba-api-1                                     |     raise AllocationPolicyViolation(
sentry-self-hosted-snuba-api-1                                     | snuba.query.allocation_policies.AllocationPolicyViolation: Queries must have a project id or organization id, explanation: {}
```

**Comment by afaianswq** [comment]
Since this bug report is closed, I reported a new one: 2436

**Comment by afaianswq** [comment]
> Hi! I had the same issue with background workers and I realized that I had not started the cron worker properly. The issue of background workers got fixed after I enabled it.

That's not the case here. All containers are running and healthy.
