### ISSUE TITLE
I can't update beyond version 21.5.1, I get a posgres error.

### ISSUE THREAD

**Issue by Shedyk** [getsentry/self-hosted#2422]
### Self-Hosted Version

21.5.1

### CPU Architecture

x86_

### Docker Version

19.03.13

### Docker Compose Version

1.27.4

### Steps to Reproduce

I was updating sentry from 20.11.1 following the hard-stop defined in the self-hosted release guide.
`<your.sentry.version> -> 21.5.0 -> 21.6.3 -> 23.6.2 -> latest`
First I encountered an issue with docker build #2413 due to Ubuntu Stretch being no longer supported. Fortunately there is a fix for that and I was able to proceed but could not complete the upgrade. Going directly to 21.5.0 resulted in the error below.
```
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known
```
So I opted to go do few releases back.. 21.1.0 > 21.3.1 > 21.4.1 > 21.5.0 > 21.5.1 which managed to get me past 21.5.0 where initial error occurred to 21.5.1 but not 21.5.1 to  21.6.0 or  21.6.3 is stuck on same error

Steps
1. Unzip respective version to installation folder
2. Run ./install.sh

### Expected Result

Successful upgrade to latest version

### Actual Result

logs at version when upgrading to 21.5.1
Sentry runs successfully when I execute docker-compose up -d and I can login
```
Creating sentry_onpremise_snuba-api_1                                ... done
Creating sentry_onpremise_web_run                                    ... 
Creating sentry_onpremise_web_run                                    ... done
05:31:15 [INFO] sentry.plugins.github: apps-not-configured
* Unknown config option found: 'slack.legacy-app'
[36;1mOperations to perform:[0m
[1m  Apply all migrations: [0madmin, auth, contenttypes, jira_ac, nodestore, sentry, sessions, sites, social_auth
[36;1mRunning migrations:[0m
  No migrations to apply.
Creating missing DSNs
Correcting Group.num_comments counter

▶ Migrating file storage ...

▶ Generating Relay credentials ...
../relay/config.yml already exists, skipped creation.

▶ Setting up GeoIP integration ...
Setting up IP address geolocation ...
IP address geolocation database already exists.
IP address geolocation is not configured for updates.
See https://develop.sentry.dev/self-hosted/geolocation/ for instructions.
Error setting up IP address geolocation.


-----------------------------------------------------------------

You're all done! Run the following command to get Sentry running:

  docker-compose up -d

-----------------------------------------------------------------
```
logs at attempting to upgrade to 21.6.0

```
Creating sentry_onpremise_snuba-replacer_1                           ... done
Creating sentry_onpremise_web_run                                    ... 
Creating sentry_onpremise_web_run                                    ... done
05:00:24 [INFO] sentry.plugins.github: apps-not-configured
* Unknown config option found: 'slack.legacy-app'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/__init__.py", line 196, in main
    func(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 171, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 118, in _upgrade
    _migrate_from_south(verbosity)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 90, in _migrate_from_south
    if not _has_south_history(connection):
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 75, in _has_south_history
    cursor = connection.cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 96, in _cursor
    return super()._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known

An error occurred, caught SIGERR on line 12
```

**Comment by hubertdeng123** [comment]
Seems like potentially a config mismatch? Do you have a custom postgres setup where you've changed settings around in your docker-compose.yml file?

**Comment by Shedyk** [comment]
> Seems like potentially a config mismatch? Do you have a custom postgres setup where you've changed settings around in your docker-compose.yml file?

No, I did not change any settings in the docker-compose.yml file and I don't have a custom postgres installation either

**Comment by hubertdeng123** [comment]
Looks like there used to be some issues with wal2json in the past.
https://forum.sentry.io/t/could-not-translate-host-name-postgres-to-address-name-or-service-not-known/14292

Hopefully that gives you some more info to go off of
