### ISSUE TITLE
Fresh install of self hosted version got 'NoneType' object has no attribute 'id' inside worker container

### ISSUE THREAD

**Issue by manaclan** [getsentry/self-hosted#2444]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

2.22.0

### Steps to Reproduce

1. Fresh install by cloning the repo and run ./install.sh
2. Integration our front end with the web UI installation instruction
3. Send log to Sentry
4. docker log the worker container and the errors appear

### Expected Result

no error 

### Actual Result

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 280, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 99, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 126, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/auto_ongoing_issues.py", line 44, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/auto_ongoing_issues.py", line 136, in schedule_auto_transition_issues_new_to_ongoing
    "most_recent_group_first_seen_seven_days_ago": most_recent_group_first_seen_seven_days_ago.id,
AttributeError: 'NoneType' object has no attribute 'id'
08:34:00 [ERROR] celery.app.trace: Task sentry.tasks.schedule_auto_transition_issues_new_to_ongoing[4191b626-350f-4001-a2af-9c2779f25714] raised unexpected: AttributeError("'NoneType' object has no attribute 'id'") (data={'hostname': '41058e66047c', 'id': '4191b626-350f-4001-a2af-9c2779f25714', 'name': 'sentry.tasks.schedule_auto_transition_issues_new_to_ongoing', 'exc': 'AttributeError("\'NoneType\' object has no attribute \'id\'")', 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 280, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 99, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override\n    return original_method(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 126, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 163, in wrapped\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/auto_ongoing_issues.py", line 44, in wrapped\n    func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/auto_ongoing_issues.py", line 136, in schedule_auto_transition_issues_new_to_ongoing\n    "most_recent_group_first_seen_seven_days_ago": most_recent_group_first_seen_seven_days_ago.id,\nAttributeError: \'NoneType\' object has no attribute \'id\'\n', 'args': '()', 'kwargs': "{'first_seen_lte': 1695717240, 'expires': datetime.datetime(2023, 10, 3, 9, 34, 0, 22780, tzinfo=datetime.timezone.utc), '__start_time': 1696322040.022792}", 'description': 'raised unexpected', 'internal': False})
```

**Comment by azaslavsky** [comment]
I think this is a duplicate of this bug? https://github.com/getsentry/sentry/issues/57581

**Comment by manaclan** [comment]
@azaslavsky Actually there were something wrong with my self-hosted-web container that send None id to the worker container. Please have a look at my docker-compose logs:
```
sentry-self-hosted-web-1                                           | 07:20:53 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='192.168.128.51' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.005914449691772461 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-cron-1                                          | 07:20:58 [WARNING] sentry_sdk.errors: Intervals shorter than one minute are not supported by Sentry Crons. Monitor 'sync-options-control' has an interval of 10 seconds. Use the `exclude_beat_tasks` option in the celery integration to exclude it.
sentry-self-hosted-worker-1                                        | Traceback (most recent call last):
sentry-self-hosted-worker-1                                        |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
sentry-self-hosted-worker-1                                        |     R = retval = fun(*args, **kwargs)
sentry-self-hosted-worker-1                                        |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 280, in _inner
sentry-self-hosted-worker-1                                        |     reraise(*exc_info)
sentry-self-hosted-worker-1                                        |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 99, in reraise
sentry-self-hosted-worker-1                                        |     raise value
sentry-self-hosted-worker-1                                        |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner
sentry-self-hosted-worker-1                                        |     return f(*args, **kwargs)
sentry-self-hosted-worker-1                                        |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
sentry-self-hosted-worker-1                                        |     return self.run(*args, **kwargs)
sentry-self-hosted-worker-1                                        |   File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override
sentry-self-hosted-worker-1                                        |     return original_method(*args, **kwargs)
sentry-self-hosted-worker-1                                        |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 126, in _wrapped
sentry-self-hosted-worker-1                                        |     result = func(*args, **kwargs)
sentry-self-hosted-worker-1                                        |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 163, in wrapped
sentry-self-hosted-worker-1                                        |     return func(*args, **kwargs)
sentry-self-hosted-worker-1                                        |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/auto_ongoing_issues.py", line 44, in wrapped
sentry-self-hosted-worker-1                                        |     func(*args, **kwargs)
sentry-self-hosted-worker-1                                        |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/auto_ongoing_issues.py", line 136, in schedule_auto_transition_issues_new_to_ongoing
sentry-self-hosted-worker-1                                        |     "most_recent_group_first_seen_seven_days_ago": most_recent_group_first_seen_seven_days_ago.id,
sentry-self-hosted-worker-1                                        | AttributeError: 'NoneType' object has no attribute 'id'
sentry-self-hosted-worker-1                                        | 07:21:00 [ERROR] celery.app.trace: Task sentry.tasks.schedule_auto_transition_issues_new_to_ongoing[dc5be2c9-48a9-4fd0-af1a-02416a1eceeb] raised unexpected: AttributeError("'NoneType' object has no attribute 'id'") (data={'hostname': '3aa91158a789', 'id': 'dc5be2c9-48a9-4fd0-af1a-02416a1eceeb', 'name': 'sentry.tasks.schedule_auto_transition_issues_new_to_ongoing', 'exc': 'AttributeError("\'NoneType\' object has no attribute \'id\'")', 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 280, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 99, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override\n    return original_method(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 126, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 163, in wrapped\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/auto_ongoing_issues.py", line 44, in wrapped\n    func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/auto_ongoing_issues.py", line 136, in schedule_auto_transition_issues_new_to_ongoing\n    "most_recent_group_first_seen_seven_days_ago": most_recent_group_first_seen_seven_days_ago.id,\nAttributeError: \'NoneType\' object has no attribute \'id\'\n', 'args': '()', 'kwargs': "{'first_seen_lte': 1695972060, 'expires': datetime.datetime(2023, 10, 6, 8, 21, 0, 67224, tzinfo=datetime.timezone.utc), '__start_time': 1696576860.06724}", 'description': 'raised unexpected', 'internal': False})
```
