### ISSUE TITLE
Reprocessing does not work

### ISSUE THREAD

**Issue by lndmnn** [getsentry/self-hosted#2451]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

If an iOS SDK Problem is reported to sentry and the dSYM is missing, sentry offers the option to reprocess the task (if activated). In my case, sentry just shows an error when checking the logs.

### Expected Result

Reprocess the Event with dSYM File

### Actual Result

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 280, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 99, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 126, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/reprocessing.py", line 33, in reprocess_events
    insert_data_to_database_legacy(raw_event.data.data, from_reprocessing=True)
  File "/usr/local/lib/python3.8/site-packages/sentry/coreapi.py", line 61, in insert_data_to_database_legacy
    cache_key = event_processing_store.store(data)
  File "/usr/local/lib/python3.8/site-packages/sentry/eventstore/processing/base.py", line 38, in store
    key = cache_key_for_event(event)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/cache.py", line 43, in cache_key_for_event
    return "e:{}:{}".format(data["event_id"], data["project"])
KeyError: 'event_id'
12:19:18 [ERROR] celery.app.trace: Task sentry.tasks.reprocess_events[9f41ad6f-bfaa-49cb-9901-0cb427652a6b] raised unexpected: KeyError('event_id') (data={'hostname': '3c1681163871', 'id': '9f41ad6f-bfaa-49cb-9901-0cb427652a6b', 'name': 'sentry.tasks.reprocess_events', 'exc': "KeyError('event_id')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 280, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 99, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 275, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override\n    return original_method(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 126, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/reprocessing.py", line 33, in reprocess_events\n    insert_data_to_database_legacy(raw_event.data.data, from_reprocessing=True)\n  File "/usr/local/lib/python3.8/site-packages/sentry/coreapi.py", line 61, in insert_data_to_database_legacy\n    cache_key = event_processing_store.store(data)\n  File "/usr/local/lib/python3.8/site-packages/sentry/eventstore/processing/base.py", line 38, in store\n    key = cache_key_for_event(event)\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/cache.py", line 43, in cache_key_for_event\n    return "e:{}:{}".format(data["event_id"], data["project"])\nKeyError: \'event_id\'\n', 'args': '()', 'kwargs': "{'project_id': 5, '__start_time': 1696508358.090607}", 'description': 'raised unexpected', 'internal': False})

### Product Area

Issues

### Version

23.9.1

**Comment by hubertdeng123** [comment]
Hi there, what version of self-hosted Sentry are you using?
