### ISSUE TITLE
Unable to fetch all project stats after update to 23.10.0

### ISSUE THREAD

**Issue by marbon87** [getsentry/self-hosted#2487]
### Self-Hosted Version

23.10.0

### CPU Architecture

x64_64

### Docker Version

24.0.5

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Update existing project to latest version
2. Start sentry
3. Open projects page

### Expected Result

No error

### Actual Result

After updating from sentry 23.5.0 to 23.9.0 and then to 23.10.0  i get the following error when i open the project overview page:
![image](https://github.com/getsentry/self-hosted/assets/2949525/a11a97ee-2f1b-4839-83ec-a58e34584e49)

The web-container contains the following exception:

```
07:40:30 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_user_teams.OrganizationUserTeamsEndpoint' response=200 user_id='2' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/lvm/user-teams/' caller_ip='10.234.141.109' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.06595349311828613 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 257, in handle_exception
    response = super().handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/sentry/../rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/sentry/../rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 381, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/endpoints/organization_projects.py", line 172, in get
    return self.paginate(
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 491, in paginate
    results = on_results(cursor_result.results)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/endpoints/organization_projects.py", line 170, in serialize_on_result
    return serialize(result, request.user, serializer)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/base.py", line 69, in serialize
    attrs = serializer.get_attrs(
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/project.py", line 716, in get_attrs
    attrs = super().get_attrs(item_list, user)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/project.py", line 603, in get_attrs
    attrs = super().get_attrs(item_list, user)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/project.py", line 358, in get_attrs
    transaction_stats = self.get_stats(project_ids, "event.type:transaction")
  File "/usr/local/lib/python3.8/site-packages/sentry/api/serializers/models/project.py", line 443, in get_stats
    stats = self.dataset.top_events_timeseries(
  File "/usr/local/lib/python3.8/site-packages/sentry/snuba/metrics_enhanced_performance.py", line 222, in top_events_timeseries
    raise error
  File "/usr/local/lib/python3.8/site-packages/sentry/snuba/metrics_enhanced_performance.py", line 197, in top_events_timeseries
    return metrics_top_events_timeseries(
  File "/usr/local/lib/python3.8/site-packages/sentry/snuba/metrics_performance.py", line 321, in top_events_timeseries
    result = top_events_builder.run_query(referrer)
  File "/usr/local/lib/python3.8/site-packages/sentry/search/events/builder/metrics.py", line 1485, in run_query
    results = bulk_snql_query(queries, referrer, use_cache)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/snuba.py", line 827, in bulk_snql_query
    return _apply_cache_and_build_results(params, referrer=referrer, use_cache=use_cache)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/snuba.py", line 880, in _apply_cache_and_build_results
    query_results = _bulk_snuba_query([item[1] for item in to_query], headers)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/snuba.py", line 963, in _bulk_snuba_query
    raise clickhouse_error_codes_map.get(error["code"], QueryExecutionError)(
sentry.utils.snuba.QueryExecutionError: DB::Exception: Type mismatch in IN or VALUES section. Expected: UInt64. Got: String. Stack trace:
```

Any idea how i can fix that?

**Comment by khs123** [comment]
i also got this error

**Comment by marbon87** [comment]
Also occurs on a complete new installation without data migration.

**Comment by hasielhassan** [comment]
Got the same exact problem
