### ISSUE TITLE
Migrated from 23.8.0 to 23.9.1 

### ISSUE THREAD

**Issue by ngatti-tmm** [getsentry/self-hosted#2513]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

24.0.6

### Steps to Reproduce

git checkout 23.9.1
./install.sh --no-report-self-hosted-issues 
docker compose up

### Expected Result

sentry GUI working ok

### Actual Result

After upgrading to 23.9.1, nginx replies with a 502 error. The sentry self-hosted-web container fails with the following log:

```
15:21:10 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.18.0.53' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.024573564529418945 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')

15:21:18 [INFO] sentry_sdk.errors: event processor (<function DedupeIntegration.setup_once.<locals>.processor at 0x7f82f529a9d0>) dropped event

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner  response = get_response(request)

  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
 response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/django/views.py", line 84, in
sentry_wrapped_callback
    return callback(request, *args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/sentry/web/frontend/base.py", line 409, in dispatch
    return self.handle(request, *args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/sentry/web/frontend/react_page.py", line 117, in handle
    return self.handle_react(request)

  File "/usr/local/lib/python3.8/site-packages/sentry/web/frontend/react_page.py", line 92, in handle_react
    response = render_to_response("sentry/base-react.html", context=context, request=request)

  File "/usr/local/lib/python3.8/site-packages/sentry/web/helpers.py", line 42, in render_to_response
    response = HttpResponse(render_to_string(template, context, request))

  File "/usr/local/lib/python3.8/site-packages/sentry/web/helpers.py", line 29, in render_to_string
    rendered = loader.render_to_string(template, context=context, request=request)

  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)

  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)

  File "/usr/local/lib/python3.8/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)

  File "/usr/local/lib/python3.8/site-packages/sentry/templatetags/sentry_helpers.py", line 210, in get_sentry_version
    latest = options.get("sentry:latest_version") or current

  File "/usr/local/lib/python3.8/site-packages/sentry/options/manager.py", line 285, in get
    result = self.store.get(opt, silent=silent)

  File "/usr/local/lib/python3.8/site-packages/sentry/options/store.py", line 97, in get
    result = self.get_store(key, silent=silent)

  File "/usr/local/lib/python3.8/site-packages/sentry/options/store.py", line 193, in get_store
    value = self.model.objects.get(key=key.name).value

  File "/usr/local/lib/python3.8/site-packages/sentry/db/models/manager/base.py", line 260, in get
    return super().get(*args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
sentry.models.options.option.MultipleObjectsReturned: get() returned more than one Option -- it returned 3!
```

**Comment by azaslavsky** [comment]
It seems like you have multiple options set - I'm not sure how this would have occurred. You may need to remove these manually.

I'm curious how many duplicated option keys you have. Do you mind running the following:
```
docker compose exec postgres bash
psql -U postgres
select key,count(1) from sentry_option_ group by key having count(1) > 1;
```

Can you report back with how many keys are duplicated in this manner. Please do not reply with any values, only keys, as the values contain sensitive information (ex: API secrets and the like).

**Comment by ngatti-tmm** [comment]
Thanks for the reply. Here is the requested information:

```
sentry_postgres=# select key,count(1) from sentry_option group by key having count(1) > 1;
            key             | count
----------------------------+-------
 system.url-prefix          |     3
 sentry:version-configured  |     3
 sentry:last_worker_ping    |     4
 system.admin-email         |     3
 auth.allow-registration    |     3
 sentry:last_worker_version |     4
 sentry:install-id          |     3
 sentry:latest_version      |     3
```

I see many of them are duplicate. Should I remove the duplicates? Maybe that also explains an other strange issue that I have once in a while, where after login I am redirected to the initial setup wizard (to configure smtp settings).

About how this could happend, this is a self-hosted sentry that have been migrated from the old deprecated docker version (version 7 if I recall correctly). It has suffered a lot of migrations and upgrades.

**Comment by ngatti-tmm** [comment]
Update: I removed duplicated with
```
DELETE FROM sentry_option a
WHERE a.ctid <> (SELECT min(b.ctid)
                 FROM   sentry_option b
                 WHERE  a.key = b.key);
```

and it started to work ok! Thanks @azaslavsky  for your support.

**Comment by azaslavsky** [comment]
Hmm yeah, it seems like this instance has gotten into a weird state - we generally check for duplicate options and overwrite existing ones, but as you say, upgrading from a very old version could have caused unexpected problems.

In any case, glad this worked and got things back into shape!
