### ISSUE TITLE
zookeeper broke my environment

### ISSUE THREAD

**Issue by outductor** [getsentry/self-hosted#2530]
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

After applying updates that include https://github.com/getsentry/self-hosted/pull/2500, my environment cannot be booted

### Expected Result

Kafka should run with KRaft

### Actual Result

```
sentry-self-hosted-zookeeper-1  | [2023-10-28 05:52:22,401] ERROR Unexpected exception, exiting abnormally (org.apache.zookeeper.server.ZooKeeperServerMain)
sentry-self-hosted-zookeeper-1  | java.io.IOException: No snapshot found, but there are log entries. Something is broken!
sentry-self-hosted-zookeeper-1  | 	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.restore(FileTxnSnapLog.java:240)
sentry-self-hosted-zookeeper-1  | 	at org.apache.zookeeper.server.ZKDatabase.loadDataBase(ZKDatabase.java:240)
sentry-self-hosted-zookeeper-1  | 	at org.apache.zookeeper.server.ZooKeeperServer.loadData(ZooKeeperServer.java:305)
sentry-self-hosted-zookeeper-1  | 	at org.apache.zookeeper.server.ZooKeeperServer.startdata(ZooKeeperServer.java:465)
sentry-self-hosted-zookeeper-1  | 	at org.apache.zookeeper.server.NIOServerCnxnFactory.startup(NIOServerCnxnFactory.java:764)
sentry-self-hosted-zookeeper-1  | 	at org.apache.zookeeper.server.ServerCnxnFactory.startup(ServerCnxnFactory.java:98)
sentry-self-hosted-zookeeper-1  | 	at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:145)
sentry-self-hosted-zookeeper-1  | 	at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:107)
sentry-self-hosted-zookeeper-1  | 	at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:65)
sentry-self-hosted-zookeeper-1  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:128)
sentry-self-hosted-zookeeper-1  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
```

**Comment by hubertdeng123** [comment]
Unfortunately that is part of the reason we reverted this change. You'll be able to get your instance up and running if you remake your kafka and zookeeper volumes. Note that this may lead to data loss if there is unprocessed data.

**Comment by outductor** [comment]
@hubertdeng123 
after removing kafka and zookeeper volumes, I still get the following error in the phase where `snuma bootstrap` is executed.

```
sentry-self-hosted-zookeeper-1   | [2023-11-05 11:16:40,888] ERROR Unexpected exception, exiting abnormally (org.apache.zookeeper.server.ZooKeeperServerMain)
sentry-self-hosted-zookeeper-1   | java.io.IOException: No snapshot found, but there are log entries. Something is broken!
sentry-self-hosted-zookeeper-1   | 	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.restore(FileTxnSnapLog.java:240)
sentry-self-hosted-zookeeper-1   | 	at org.apache.zookeeper.server.ZKDatabase.loadDataBase(ZKDatabase.java:240)
sentry-self-hosted-zookeeper-1   | 	at org.apache.zookeeper.server.ZooKeeperServer.loadData(ZooKeeperServer.java:305)
sentry-self-hosted-zookeeper-1   | 	at org.apache.zookeeper.server.ZooKeeperServer.startdata(ZooKeeperServer.java:465)
sentry-self-hosted-zookeeper-1   | 	at org.apache.zookeeper.server.NIOServerCnxnFactory.startup(NIOServerCnxnFactory.java:764)
sentry-self-hosted-zookeeper-1   | 	at org.apache.zookeeper.server.ServerCnxnFactory.startup(ServerCnxnFactory.java:98)
sentry-self-hosted-zookeeper-1   | 	at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:145)
sentry-self-hosted-zookeeper-1   | 	at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:107)
sentry-self-hosted-zookeeper-1   | 	at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:65)
sentry-self-hosted-zookeeper-1   | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:128)
sentry-self-hosted-zookeeper-1   | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
```

**Comment by hubertdeng123** [comment]
@outductor have you remade your zookeeper log volume?
