### ISSUE TITLE
Problem running ./restore.sh - Unknown internal error occurred: get() returned more than one UserIP -- it returned 2!

### ISSUE THREAD

**Issue by Hugo-Persson** [getsentry/self-hosted#2571]
### Self-Hosted Version

23.10.2

### CPU Architecture

x86_64

### Docker Version

docker

### Docker Compose Version

20.10.20

### Steps to Reproduce

1. Run ./scripts/backup.sh
2. `docker compose down`
3. `docker volume prune`
4. clone repo again in new dir
5. copy backup.json
6. run `./install.sh` 
7. run `./scripts/restore.sh`

### Expected Result

No errors and exit code 0

### Actual Result

I get and error, see logs
```
./scripts/restore.sh
▶ Initializing Docker Compose ...

▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Setting up error handling ...
#2 [internal] load .dockerignore
#2 sha256:65263a64a585b16e72a23f4d3efb70098ad2d38bfecc21cb702f294165014ecc
#2 transferring context: 2B done
#2 DONE 0.0s

#1 [internal] load build definition from Dockerfile
#1 sha256:895fa7ece5b7e068c230c0acb38d4007cd9c6714db12050e877d30b7a167da80
#1 transferring dockerfile: 298B done
#1 DONE 0.0s

#3 [internal] load metadata for docker.io/library/debian:bullseye-slim
#3 sha256:934609b8daae60945272376631143418e3455bd8f42cec3f0749895e255e3083
#3 DONE 0.7s

#5 [1/2] FROM docker.io/library/debian:bullseye-slim@sha256:19664a5752dddba7f59bb460410a0e1887af346e21877fa7cec78bfd3cb77da5
#5 sha256:ac11ef32a7a72ca627f7b5096796994c8ca3b7f8def957e79ad749c55584ea75
#5 DONE 0.0s

#4 [2/2] RUN set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*
#4 sha256:11c998242bde3466d28b1456af9abf6141eda68f1f001c47d1133fa63db7e637
#4 CACHED

#6 exporting to image
#6 sha256:b62e9b5086f788750069f68c5bac917af6b495bac0f580ce3f49e8dd891f8899
#6 exporting layers done
#6 writing image sha256:8d347568af4f61fc26c7ff777c70e6da185dc2083bdae5d9f41ba1f1eba84aaa done
#6 naming to docker.io/library/sentry-self-hosted-jq-local:latest done
#6 DONE 0.0s

Hey, so ... we would love to automatically find out about issues with your
Sentry instance so that we can improve the product. Turns out there is an app
for that, called Sentry. Would you be willing to let us automatically send data
about your instance upstream to Sentry for development and debugging purposes?

  y / yes / 1
  n / no / 0

(Btw, we send this to our own self-hosted Sentry instance, not to Sentry SaaS,
so that we can be in this together.)

Here's the info we may collect:

  - OS username
  - IP address
  - install log
  - runtime errors
  - performance data

Thirty (30) day retention. No marketing. Privacy policy at sentry.io/privacy.

y or n? n

Understood. To avoid this prompt in the future, use one of these flags:

  --report-self-hosted-issues
  --no-report-self-hosted-issues

or set the REPORT_SELF_HOSTED_ISSUES environment variable:

  REPORT_SELF_HOSTED_ISSUES=1 to send data
  REPORT_SELF_HOSTED_ISSUES=0 to not send data


 Container sentry-self-hosted-redis-1  Created
 Container sentry-self-hosted-clickhouse-1  Created
 Container sentry-self-hosted-symbolicator-1  Created
 Container sentry-self-hosted-smtp-1  Created
 Container sentry-self-hosted-postgres-1  Created
 Container sentry-self-hosted-memcached-1  Created
 Container sentry-self-hosted-zookeeper-1  Created
 Container sentry-self-hosted-kafka-1  Created
 Container sentry-self-hosted-vroom-1  Created
 Container sentry-self-hosted-snuba-transactions-consumer-1  Created
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Created
 Container sentry-self-hosted-snuba-replacer-1  Created
 Container sentry-self-hosted-snuba-consumer-1  Created
 Container sentry-self-hosted-snuba-api-1  Created
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Created
 Container sentry-self-hosted-snuba-sessions-consumer-1  Created
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Created
 Container sentry-self-hosted-memcached-1  Starting
 Container sentry-self-hosted-clickhouse-1  Starting
 Container sentry-self-hosted-smtp-1  Starting
 Container sentry-self-hosted-symbolicator-1  Starting
 Container sentry-self-hosted-postgres-1  Starting
 Container sentry-self-hosted-zookeeper-1  Starting
 Container sentry-self-hosted-redis-1  Starting
 Container sentry-self-hosted-symbolicator-1  Started
 Container sentry-self-hosted-memcached-1  Started
 Container sentry-self-hosted-redis-1  Started
 Container sentry-self-hosted-clickhouse-1  Started
 Container sentry-self-hosted-smtp-1  Started
 Container sentry-self-hosted-postgres-1  Started
 Container sentry-self-hosted-zookeeper-1  Started
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-zookeeper-1  Healthy
 Container sentry-self-hosted-kafka-1  Starting
 Container sentry-self-hosted-kafka-1  Started
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-replacer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-transactions-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-sessions-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-consumer-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-vroom-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-api-1  Starting
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Starting
 Container sentry-self-hosted-snuba-replacer-1  Started
 Container sentry-self-hosted-snuba-outcomes-consumer-1  Started
 Container sentry-self-hosted-snuba-transactions-consumer-1  Started
 Container sentry-self-hosted-snuba-sessions-consumer-1  Started
 Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Started
 Container sentry-self-hosted-snuba-api-1  Started
 Container sentry-self-hosted-snuba-consumer-1  Started
 Container sentry-self-hosted-snuba-subscription-consumer-events-1  Started
 Container sentry-self-hosted-vroom-1  Started
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
RpcImportError(
	kind: Unknown,
	on: InstanceID(model: 'sentry.userip'),
	reason: Unknown internal error occurred: get() returned more than one UserIP -- it returned 2!
)
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 195, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/backup.py", line 241, in import_global
    import_in_global_scope(
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 355, in import_in_global_scope
    return _import(
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 238, in _import
    do_writes(pk_map)
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 233, in do_writes
    do_write(pk_map, model_name, json_data)
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 220, in do_write
    raise ImportingError(result)
sentry.backup.imports.ImportingError: is_err=True kind='Unknown' on=InstanceID(model='sentry.userip', ordinal=None) left_pk=None right_pk=None reason='Unknown internal error occurred: get() returned more than one UserIP -- it returned 2!'
Error in scripts/_lib.sh:69.
'$dc run --rm -T web import global /etc/sentry/backup.json' exited with status 1
-> ./scripts/restore.sh:main:4
--> scripts/_lib.sh:restore:69

Cleaning up...
```

**Comment by Hugo-Persson** [comment]
I tried to delete all instances of UserIP from the backup.json, now I get the following error:

```
RpcImportError(
	kind: Unknown,
	on: InstanceID(model: 'sentry.useremail'),
	reason: Unknown internal error occurred: UserEmail matching query does not exist.
)
```

**Comment by hubertdeng123** [comment]
This is a duplicate of https://github.com/getsentry/self-hosted/issues/2468

This should hopefully be fixed now, could you chime in there if you have issues?

**Comment by azaslavsky** [comment]
To create a "sanitized" copy of your export, take the `backup.json` file, manually reduce it to only the entries that contain `"model": "sentry.useremail`, then paste (or upload, if its very large) that entry here. If you only include the `sentry.useremail` models, there should be no PII, but just in case, make sure to scrub (ie, replace with random values) any emails in your JSON!

**Comment by Hugo-Persson** [comment]
Here is the useremails, I have changed the real email
[clean.json](https://github.com/getsentry/self-hosted/files/13368815/clean.json)

**Comment by azaslavsky** [comment]
Thank you, this helps a lot! I'll see if I can replicate locally, then I'll try to push out a fix.

**Comment by Hugo-Persson** [comment]
Ok let me know if you need anything else @azaslavsky 👍

**Comment by Hugo-Persson** [comment]
Any progress @azaslavsky ? Is there anything I can do to help?

**Comment by azaslavsky** [comment]
@Hugo-Persson I just landed what I believe to be a fix for this on self-hostd `main` HEAD. Would you mind giving that a try.

I'll also be cutting a release later today (23.11.1) that should have this fix included.
