### ISSUE TITLE
sentry-snuba-metrics-consumer keeps crashing since update

### ISSUE THREAD

**Issue by michaelniemand** [getsentry/self-hosted#2601]
### Self-Hosted Version

23.11.0

### CPU Architecture

x86_64

### Docker Version

containerd on k8s 1.23.17-eks

### Docker Compose Version

kubernetes 1.23

### Steps to Reproduce

After updating to the latest version 2 days ago, the sentry-snuba-metrics-consumer service is in a CrashLoop. The sentry-sessions-consumer has also lots of crashes.

### Expected Result

no crashes

### Actual Result

```
2023-11-23 08:21:57,062 Consumer Starting
2023-11-23 08:21:57,062 Checking Clickhouse connections...
2023-11-23 08:21:57,075 Successfully connected to Clickhouse: cluster_name=sentry-clickhouse
2023-11-23 08:21:57,076 librdkafka log level: 6
2023-11-23 08:21:57,098 New partitions assigned: {Partition(topic=Topic(name='snuba-metrics'), index=0): 5607793}
2023-11-23 08:21:58,550 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 294, in run self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 380, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/reduce.py", line 153, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 107, in poll
    result = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
    File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 124, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 324, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 160, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 355, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 282, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Method write is not supported by storage Distributed with more than one shard and no sharding key provided (version 21.8.13.6 (official build))
2023-11-23 08:21:58,556 Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f8d4007f4f0>...
2023-11-23 08:21:58,557 Partitions to revoke: [Partition(topic=Topic(name='snuba-metrics'), index=0)]
2023-11-23 08:21:58,558 Partition revocation complete.
2023-11-23 08:21:58,561 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
  sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 283, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 294, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 380, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 101, in poll
    self.__inner_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 37, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/reduce.py", line 153, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task_in_threads.py", line 107, in poll
    result = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 124, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 324, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 160, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 355, in write
    batch.join(timeout=batch_join_timeout)
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 282, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Method write is not supported by storage Distributed with more than one shard and no sharding key provided (version 21.8.13.6 (official build))
```

**Comment by mrouhi13** [comment]
Same here.

**Comment by mrouhi13** [comment]
There are already some open issues for that error:

https://github.com/sentry-kubernetes/charts/issues/1042#issuecomment-1814347637

https://github.com/getsentry/snuba/issues/4897

**Comment by michaelniemand** [comment]
> There are already some open issues for that error:
> 
> [sentry-kubernetes/charts#1042 (comment)](https://github.com/sentry-kubernetes/charts/issues/1042#issuecomment-1814347637)
> 
> [getsentry/snuba#4897](https://github.com/getsentry/snuba/issues/4897)

thanks a lot, I tried searching first but to no avail. I will try the solution(s) in those issues and update this issue here accordingly afterwards.

**Comment by mrouhi13** [comment]
> > There are already some open issues for that error:
> > [sentry-kubernetes/charts#1042 (comment)](https://github.com/sentry-kubernetes/charts/issues/1042#issuecomment-1814347637)
> > [getsentry/snuba#4897](https://github.com/getsentry/snuba/issues/4897)
> 
> thanks a lot, I tried searching first but to no avail. I will try the solution(s) in those issues and update this issue here accordingly afterwards.

This one worked for me: https://github.com/sentry-kubernetes/charts/issues/1042#issuecomment-1814347637

**Comment by michaelniemand** [comment]
worked for me, too. Closing this issue.
Just one FYI: to find out your cluster name (which is required for the query in the linked issue) run:

`SELECT * FROM system.clusters LIMIT 2 FORMAT Vertical;` in clickhouse-client
