### ISSUE TITLE
Unable to login after upgrade to 23.11.2: relation "sentry_artifactbundleflatfileindex" does not exist

### ISSUE THREAD

**Issue by pva** [getsentry/self-hosted#2612]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

23.0.3

### Docker Compose Version

v2.17.2

### Steps to Reproduce

I had version 23.6.2 when I noticed that I was not able to log in: got  `Oops! Something went wrong` message after entering login/password. I found in logs the following problem #2330. Since the issue was closed, I decided to upgrade. After the upgrade, I'm still unable to log in yet the error message in the logs changed:

```
sentry-self-hosted-postgres-1 | 2023-11-29 21:14:29.138 UTC [9006] ERROR:  column auth_user.is_unclaimed does not exist at character 952
```

### Expected Result

I expect to be able to log in.

### Actual Result

I'm receiving "Oops! Something went wrong" message and the following trace I have in logs:
```
sentry-self-hosted-postgres-1 | 2023-11-29 21:14:29.138 UTC [9006] ERROR:  column auth_user.is_unclaimed does not exist at character 952
sentry-self-hosted-postgres-1 | 2023-11-29 21:14:29.138 UTC [9006] STATEMENT:  SELECT (select array_agg(permission) from sentry_userpermission where user_id=auth_user.id) AS "permissions", (
sentry-self-hosted-postgres-1 | 	                        SELECT array_agg(permissions)
sentry-self-hosted-postgres-1 | 	                        FROM sentry_userrole
sentry-self-hosted-postgres-1 | 	                        JOIN sentry_userrole_users
sentry-self-hosted-postgres-1 | 	                          ON sentry_userrole_users.role_id=sentry_userrole.id
sentry-self-hosted-postgres-1 | 	                       WHERE user_id=auth_user.id) AS "roles", (select array_agg(row_to_json(sentry_useremail)) from sentry_useremail where user_id=auth_user.id) AS "useremails", (SELECT array_agg(row_to_json(auth_authenticator)) FROM auth_authenticator WHERE user_id=auth_user.id) AS "authenticators", (SELECT array_agg(row_to_json(sentry_useravatar)) FROM sentry_useravatar WHERE user_id = auth_user.id) AS "useravatar", "auth_user"."password", "auth_user"."last_login", "auth_user"."id", "auth_user"."username", "auth_user"."first_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."is_unclaimed", "auth_user"."is_superuser", "auth_user"."is_managed", "auth_user"."is_sentry_app", "auth_user"."is_password_expired", "auth_user"."last_password_change", "auth_user"."flags", "auth_user"."session_nonce", "auth_user"."date_joined", "auth_user"."last_active", "auth_user"."avatar_type", "auth_user"."avatar_url" FROM "auth_user" WHERE "auth_user"."id" IN (1)
sentry-self-hosted-worker-1   | Traceback (most recent call last):
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
sentry-self-hosted-worker-1   |     return func(self, sql, *args, **kwargs)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
sentry-self-hosted-worker-1   |     return self.cursor.execute(sql, clean_bad_params(params))
sentry-self-hosted-worker-1   | psycopg2.errors.UndefinedColumn: column auth_user.is_unclaimed does not exist
sentry-self-hosted-worker-1   | LINE 6: ... "auth_user"."is_staff", "auth_user"."is_active", "auth_user...
sentry-self-hosted-worker-1   |                                                              ^
sentry-self-hosted-worker-1   | 
sentry-self-hosted-worker-1   | 
sentry-self-hosted-worker-1   | During handling of the above exception, another exception occurred:
sentry-self-hosted-worker-1   | 
sentry-self-hosted-worker-1   | Traceback (most recent call last):
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
sentry-self-hosted-worker-1   |     return self.cursor.execute(sql, params)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
sentry-self-hosted-worker-1   |     raise_the_exception(self.db, e)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
sentry-self-hosted-worker-1   |     return func(self, *args, **kwargs)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
sentry-self-hosted-worker-1   |     return func(self, *args, **kwargs)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
sentry-self-hosted-worker-1   |     raise exc_info[0](msg).with_traceback(exc_info[2])
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
sentry-self-hosted-worker-1   |     return func(self, sql, *args, **kwargs)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
sentry-self-hosted-worker-1   |     return self.cursor.execute(sql, clean_bad_params(params))
sentry-self-hosted-worker-1   | psycopg2.errors.UndefinedColumn: UndefinedColumn('column auth_user.is_unclaimed does not exist\nLINE 6: ... "auth_user"."is_staff", "auth_user"."is_active", "auth_user...\n                                                             ^\n')
sentry-self-hosted-worker-1   | SQL: SELECT (select array_agg(permission) from sentry_userpermission where user_id=auth_user.id) AS "permissions", (
sentry-self-hosted-worker-1   |                         SELECT array_agg(permissions)
sentry-self-hosted-worker-1   |                         FROM sentry_userrole
sentry-self-hosted-worker-1   |                         JOIN sentry_userrole_users
sentry-self-hosted-worker-1   |                           ON sentry_userrole_users.role_id=sentry_userrole.id
sentry-self-hosted-worker-1   |                        WHERE user_id=auth_user.id) AS "roles", (select array_agg(row_to_json(sentry_useremail)) from sentry_useremail where user_id=auth_user.id) AS "useremails", (SELECT array_agg(row_to_json(auth_authenticator)) FROM auth_authenticator WHERE user_id=auth_user.id) AS "authenticators", (SELECT array_agg(row_to_json(sentry_useravatar)) FROM sentry_useravatar WHERE user_id = auth_user.id) AS "useravatar", "auth_user"."password", "auth_user"."last_login", "auth_user"."id", "auth_user"."username", "auth_user"."first_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."is_unclaimed", "auth_user"."is_superuser", "auth_user"."is_managed", "auth_user"."is_sentry_app", "auth_user"."is_password_expired", "auth_user"."last_password_change", "auth_user"."flags", "auth_user"."session_nonce", "auth_user"."date_joined", "auth_user"."last_active", "auth_user"."avatar_type", "auth_user"."avatar_url" FROM "auth_user" WHERE "auth_user"."id" IN (%s)
sentry-self-hosted-worker-1   | 
sentry-self-hosted-worker-1   | The above exception was the direct cause of the following exception:
sentry-self-hosted-worker-1   | 
sentry-self-hosted-worker-1   | Traceback (most recent call last):
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/signals.py", line 93, in send_robust
sentry-self-hosted-worker-1   |     response = receiver(signal=self, sender=sender, **named)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/receivers/onboarding.py", line 409, in record_event_with_first_minified_stack_trace_for_project
sentry-self-hosted-worker-1   |     user: RpcUser = Organization.objects.get(id=project.organization_id).get_default_owner()
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/models/organization.py", line 325, in get_default_owner
sentry-self-hosted-worker-1   |     self._default_owner = self.get_owners()[0]
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/models/organization.py", line 321, in get_owners
sentry-self-hosted-worker-1   |     return user_service.get_many(filter={"user_ids": list(owners)})
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/services/hybrid_cloud/user/impl.py", line 57, in get_many
sentry-self-hosted-worker-1   |     return self._FQ.get_many(filter)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/services/hybrid_cloud/filter_query.py", line 131, in get_many
sentry-self-hosted-worker-1   |     return [self.serialize_rpc(o) for o in self._query_many(filter=filter)]
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
sentry-self-hosted-worker-1   |     self._fetch_all()
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
sentry-self-hosted-worker-1   |     self._result_cache = list(self._iterable_class(self))
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
sentry-self-hosted-worker-1   |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
sentry-self-hosted-worker-1   |     cursor.execute(sql, params)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 641, in execute
sentry-self-hosted-worker-1   |     return real_execute(self, sql, params)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
sentry-self-hosted-worker-1   |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
sentry-self-hosted-worker-1   |     return executor(sql, params, many, context)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
sentry-self-hosted-worker-1   |     return self.cursor.execute(sql, params)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
sentry-self-hosted-worker-1   |     raise dj_exc_value.with_traceback(traceback) from exc_value
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
sentry-self-hosted-worker-1   |     return self.cursor.execute(sql, params)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
sentry-self-hosted-worker-1   |     raise_the_exception(self.db, e)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
sentry-self-hosted-worker-1   |     return func(self, *args, **kwargs)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
sentry-self-hosted-worker-1   |     return func(self, *args, **kwargs)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
sentry-self-hosted-worker-1   |     raise exc_info[0](msg).with_traceback(exc_info[2])
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
sentry-self-hosted-worker-1   |     return func(self, sql, *args, **kwargs)
sentry-self-hosted-worker-1   |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
sentry-self-hosted-worker-1   |     return self.cursor.execute(sql, clean_bad_params(params))
sentry-self-hosted-worker-1   | django.db.utils.ProgrammingError: UndefinedColumn('column auth_user.is_unclaimed does not exist\nLINE 6: ... "auth_user"."is_staff", "auth_user"."is_active", "auth_user...\n                                                             ^\n')
sentry-self-hosted-worker-1   | SQL: SELECT (select array_agg(permission) from sentry_userpermission where user_id=auth_user.id) AS "permissions", (
sentry-self-hosted-worker-1   |                         SELECT array_agg(permissions)
sentry-self-hosted-worker-1   |                         FROM sentry_userrole
sentry-self-hosted-worker-1   |                         JOIN sentry_userrole_users
sentry-self-hosted-worker-1   |                           ON sentry_userrole_users.role_id=sentry_userrole.id
sentry-self-hosted-worker-1   |                        WHERE user_id=auth_user.id) AS "roles", (select array_agg(row_to_json(sentry_useremail)) from sentry_useremail where user_id=auth_user.id) AS "useremails", (SELECT array_agg(row_to_json(auth_authenticator)) FROM auth_authenticator WHERE user_id=auth_user.id) AS "authenticators", (SELECT array_agg(row_to_json(sentry_useravatar)) FROM sentry_useravatar WHERE user_id = auth_user.id) AS "useravatar", "auth_user"."password", "auth_user"."last_login", "auth_user"."id", "auth_user"."username", "auth_user"."first_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."is_unclaimed", "auth_user"."is_superuser", "auth_user"."is_managed", "auth_user"."is_sentry_app", "auth_user"."is_password_expired", "auth_user"."last_password_change", "auth_user"."flags", "auth_user"."session_nonce", "auth_user"."date_joined", "auth_user"."last_active", "auth_user"."avatar_type", "auth_user"."avatar_url" FROM "auth_user" WHERE "auth_user"."id" IN (%s)
sentry-self-hosted-worker-1   | 21:14:29 [ERROR] root: signal.failure (receiver='<function record_event_with_first_minified_stack_trace_for_project at 0x7f12bb7b1040>')
```

### Event ID

I've opted in, but I don't see event id anywhere.

**Comment by pva** [comment]
Also, here is the upgrade output:

[sentry-upgrade.txt](https://github.com/getsentry/self-hosted/files/13505599/sentry-upgrade.txt)

**Comment by azaslavsky** [comment]
Hmm, based on those logs it seems like your snuba migrations ran, but not your postgres migrations.

Can you try the following (do a [full volume backup](https://develop.sentry.dev/self-hosted/backup/#full-backup) before you do this - seriously!):

```shell
./senty-admin.sh upgrade
```
