### ISSUE TITLE
Sentry woker tasks.store.preprocessors.error

### ISSUE THREAD

**Issue by zKoz210** [getsentry/self-hosted#2628]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.5, build ced0996

### Docker Compose Version

Docker Compose version v2.20.2

### Steps to Reproduce

1. Run Sentry self-hosted (docker compose up -d)
2. Send transactions & errors from iOS, Android, Laravel (PHP)

### Expected Result

We expect that no errors will occur and everything will be processed correctly. We are getting a lot of errors with this.

### Actual Result

```
docker logs -f -n 200 sentry-self-hosted-worker-1
```

```
08:54:36 [ERROR] sentry.errors.events: tasks.store.preprocessors.error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 422, in do_process_event
    result = processor(data)
  File "/usr/local/lib/python3.8/site-packages/sentry/lang/java/processing.py", line 16, in deobfuscate_exception_value
    re.escape(raw_method_name), deobfuscated_method_name, exception["value"]
KeyError: 'value'
```

**Comment by hubertdeng123** [comment]
Is this a fresh install of Sentry? Or have you upgraded from a previous version. What SDK and version are you using?

**Comment by zKoz210** [comment]
Upgraded from 23.11.0 -> 23.11.1 -> 23.11.2

I noticed that this error occurs when the Android application starts sending data to Sentry

https://github.com/getsentry/sentry-java/releases/tag/6.31.0
