### ISSUE TITLE
ingest-consumer-events Stops ingesting events

### ISSUE THREAD

**Issue by fayak** [getsentry/self-hosted#2671]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Pod `sentry-ingest-consumer-events` stopped working and new events were not ingested.
It stopped without apparent reasons or actions

Here are the logs of the pod before it stopped ingesting. Can it be scaled to multiple instance safely also ?
```11:49:03 [INFO] arroyo.processing.processor: Partitions to revoke: [Partition(topic=Topic(name='ingest-events'), index=0)]
11:49:03 [INFO] arroyo.processing.processor: Closing <arroyo.processing.strategies.guard.StrategyGuard object at 0x7fef02fe3e20>...
11:49:03 [INFO] arroyo.processing.processor: Waiting for <arroyo.processing.strategies.guard.StrategyGuard object at 0x7fef02fe3e20> to exit...
11:49:03 [INFO] arroyo.processing.processor: <arroyo.processing.strategies.guard.StrategyGuard object at 0x7fef02fe3e20> exited successfully, releasing assignment.
11:49:03 [INFO] arroyo.processing.processor: Partition revocation complete.
11:49:22 [INFO] arroyo.processing.processor: New partitions assigned: {Partition(topic=Topic(name='ingest-events'), index=0): 1834400}
%4|1703078960.922|MAXPOLL|rdkafka#consumer-1| [thrd:main]: Application maximum poll interval (30000ms) exceeded by 3542ms (adjust max.poll.interval.ms for long-running message processing): leaving group
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 291, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 386, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 82, in submit
    self.__inner_strategy.submit(message)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 52, in submit
    self.__next_step.submit(Message(value))
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 34, in submit
    self.__next_step.submit(message)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 82, in submit
    self.__inner_strategy.submit(message)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 52, in submit
    self.__next_step.submit(Message(value))
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/guard.py", line 34, in submit
    self.__next_step.submit(message)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/commit.py", line 23, in submit
    self.__commit(message.committable)
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 277, in __commit
    self.__consumer.commit_offsets()
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 609, in commit_offsets
    return self.__commit_retry_policy.call(self.__commit)
  File "/usr/local/lib/python3.8/site-packages/arroyo/utils/retries.py", line 88, in call
    return callable()
  File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 567, in __commit
    result = self.__consumer.commit(
cimpl.KafkaException: KafkaError{code=UNKNOWN_MEMBER_ID,val=25,str="Commit failed: Broker: Unknown member"}
13:29:21 [ERROR] arroyo.processing.processor: Caught exception, shutting down...
13:29:21 [INFO] arroyo.processing.processor: Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7fef02fd96a0>...
13:29:21 [INFO] arroyo.processing.processor: Partitions to revoke: [Partition(topic=Topic(name='ingest-events'), index=0)]
13:29:21 [INFO] arroyo.processing.processor: Partition revocation complete.
13:29:21 [WARNING] arroyo.backends.kafka.consumer: Dropping staged offset for revoked partition (Partition(topic=Topic(name='ingest-events'), index=0))!
```

### Expected Result

auto restart of the pod in case of a failure, or auto recover.

Easy fix I did was to kill the pod manually

### Actual Result

Pod is stuck and new events are not ingested

### Product Area

Issues

### Version

23.10.1 (88c7f2d)

**Comment by hubertdeng123** [comment]
Looks like you're not using the docker compose version of self-hosted, so I'm afraid you're using an unsupported version of Sentry here. I'd advise you to ensure that your consumers are subscribed to the right topics
