### ISSUE TITLE
Stats page not showing any accepted transactions or profiles since upgrade from 21.8.0 to 23.6.2

### ISSUE THREAD

**Issue by roganartu** [getsentry/self-hosted#2672]
### Self-Hosted Version

23.6.2

### CPU Architecture

x86_64

### Docker Version

19.03.13, build 4484c46d9d

### Docker Compose Version

N/A

### Steps to Reproduce

Unsure how exactly to repro as we don't run Sentry in the docker stack, and instead run a cluster of hosts with systemd units that mirror the docker images. I have gone through both our Salt configuration as well as the actual units running on machines several times, comparing to the commands in the docker-compose, and everything appears to be correct (though it's certainly possible I missed something).

Other perhaps interesting aspects of our environment are that we run Redpanda instead of Kafka, but since Redpanda just exposes the Kafka API and that's all Sentry uses here and this used to work pre-upgrade I'm not sure it matters in practice.

### Expected Result

Stats page shows correct accepted, dropped, and filtered counts for Errors, Transactions, Attachments, and Profiles.

### Actual Result

Only Errors stats appear correct. Transactions and Profiles both only show Dropped and Filtered, though afaict both are still being processed correctly (they appear in other views).

Errors, working correctly:
![image](https://github.com/getsentry/self-hosted/assets/1133705/04dd954c-08a2-4bcc-8746-12871bb03da4)

Transactions, only showing Dropped and Filtered:
![image](https://github.com/getsentry/self-hosted/assets/1133705/a8f340a7-a88a-4a12-9b4e-7c90c67e618e)

Profiles, only showing Dropped:
![image](https://github.com/getsentry/self-hosted/assets/1133705/05ff8b2b-18fe-437c-bd21-2e469fca4735)

We don't use attachments, so those are just always zero.

This used to work fine on v21.8.0 before we upgraded about 5 months ago.

Perhaps related, we see perpetually increasing lag on several groups:
- `snuba-transactions-subscriptions-consumers` (no partitions are processed, all offsets remain perpetually at 0)
- `snuba-events-subscriptions-consumers` (some partitions are processed, most offset remain perpetually at 0)

Example of this perpetual lag (this is very soon after we nuked the Kafka cluster data, hence the low offsets):
```
❯ rpk group describe snuba-transactions-subscriptions-consumers
GROUP        snuba-transactions-subscriptions-consumers
COORDINATOR  3
STATE        Stable
BALANCER     range
MEMBERS      12
TOTAL-LAG    78616

TOPIC                          PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG    MEMBER-ID                                     CLIENT-ID  HOST
snuba-transactions-commit-log  0          0               0               -      rdkafka-4054075a-039f-4724-941a-b72c70e00a07  rdkafka    10.16.97.179
snuba-transactions-commit-log  1          0               3936            3936   rdkafka-4054075a-039f-4724-941a-b72c70e00a07  rdkafka    10.16.97.179
snuba-transactions-commit-log  2          0               0               -      rdkafka-5dc23c89-2f67-4a11-9959-9cb88d4c5c46  rdkafka    10.16.88.140
snuba-transactions-commit-log  3          0               3935            3935   rdkafka-5dc23c89-2f67-4a11-9959-9cb88d4c5c46  rdkafka    10.16.88.140
snuba-transactions-commit-log  4          0               0               -      rdkafka-608e914a-0f7c-4321-a30f-c3e924142402  rdkafka    10.16.97.179
snuba-transactions-commit-log  5          0               3939            3939   rdkafka-608e914a-0f7c-4321-a30f-c3e924142402  rdkafka    10.16.97.179
snuba-transactions-commit-log  6          0               0               -      rdkafka-6aff0b2a-0d92-419b-b21a-a895af8251af  rdkafka    10.16.104.153
snuba-transactions-commit-log  7          0               0               -      rdkafka-6aff0b2a-0d92-419b-b21a-a895af8251af  rdkafka    10.16.104.153
snuba-transactions-commit-log  8          0               3924            3924   rdkafka-7ec74dae-c692-4d8c-8a3d-6c4803b92699  rdkafka    10.16.88.140
snuba-transactions-commit-log  9          0               3939            3939   rdkafka-7ec74dae-c692-4d8c-8a3d-6c4803b92699  rdkafka    10.16.88.140
snuba-transactions-commit-log  10         0               3941            3941   rdkafka-80bd5a41-4c88-4e21-b0a7-17867045d5f4  rdkafka    10.16.88.140
snuba-transactions-commit-log  11         0               3931            3931   rdkafka-80bd5a41-4c88-4e21-b0a7-17867045d5f4  rdkafka    10.16.88.140
snuba-transactions-commit-log  12         0               7856            7856   rdkafka-93ed3f3c-9315-4750-a4a7-896f4686e172  rdkafka    10.16.97.179
snuba-transactions-commit-log  13         0               7846            7846   rdkafka-93ed3f3c-9315-4750-a4a7-896f4686e172  rdkafka    10.16.97.179
snuba-transactions-commit-log  14         0               0               -      rdkafka-b32c0397-c0be-47e0-bb9b-7d43b06f1de1  rdkafka    10.16.88.140
snuba-transactions-commit-log  15         0               3933            3933   rdkafka-b32c0397-c0be-47e0-bb9b-7d43b06f1de1  rdkafka    10.16.88.140
snuba-transactions-commit-log  16         0               7873            7873   rdkafka-b75064d7-8da6-4cae-b5fa-9572b2a40a07  rdkafka    10.16.104.153
snuba-transactions-commit-log  17         0               0               -      rdkafka-bdfdf287-01eb-4cec-8d87-1043f62bc19f  rdkafka    10.16.104.153
snuba-transactions-commit-log  18         0               15703           15703  rdkafka-c0c17be2-9acc-482f-8c79-64124b0f97f5  rdkafka    10.16.104.153
snuba-transactions-commit-log  19         0               7860            7860   rdkafka-f6981507-3282-4273-8144-a0ec8feb1495  rdkafka    10.16.97.179
```

The consumer that the docker-compose associates with this group (`snuba-subscription-consumer-transactions`) has a small number of the following error in its logs, but it has always done this even before we upgraded to 23.6.2:
```
Dec 22 15:27:27 shasentry1 docker[71824]: 2023-12-22 20:27:27,880 Could not construct valid interval between MessageDetails(offset=28978, orig_message_ts=datetime.datetime(2023, 12, 22, 20, 27, 26, 863000)) and MessageDetails(offset=28986, orig_message_ts=datetime.datetime(2023, 12, 22, 20, 27, 26, 846000))!                                                                                                                                                                        
Dec 22 15:27:27 shasentry1 docker[71824]: Traceback (most recent call last):
Dec 22 15:27:27 shasentry1 docker[71824]:   File "/usr/src/snuba/snuba/subscriptions/scheduler_consumer.py", line 148, in poll
Dec 22 15:27:27 shasentry1 docker[71824]:     time_interval = Interval(
Dec 22 15:27:27 shasentry1 docker[71824]:   File "<string>", line 5, in __init__
Dec 22 15:27:27 shasentry1 docker[71824]:   File "/usr/src/snuba/snuba/utils/types.py", line 64, in __post_init__
Dec 22 15:27:27 shasentry1 docker[71824]:     raise InvalidRangeError(self.lower, self.upper)
Dec 22 15:27:27 shasentry1 docker[71824]: snuba.utils.types.InvalidRangeError: (datetime.datetime(2023, 12, 22, 20, 27, 26, 863000), datetime.datetime(2023, 12, 22, 20, 27, 26, 846000))
```
When I say "small amount", we process thousands of transactions a minute, and get around 5 of the above error in the logs every 10 mins or so. If it's relevant to this particular error, the machines that run Redpanda/Kafka are running in Eastern Time, while all the Sentry containers run in docker and hence are UTC.

Initially we thought the lack of stats was related to a group joining timeout error we were experiencing as there were `snuba-commit-log-<random string>` groups that kept perpetually getting added and never cleaned up (to the point there were at least thousands if not more) and an older version of redpanda didn't handle this well. However we recently upgraded Redpanda and cleared all data from the cluster in the process, fixing the group join timeouts, and this stats issue persists.

I understand our setup is not really the blessed path here and that it's entirely possible we're holding something wrong here, but we've exhausted all debugging paths we can by reading source with relatively limited understanding of the components, so any tips on what else we could look into would be appreciated. I can provide any logs or command outputs that might be useful.

**Comment by hubertdeng123** [comment]
I myself am not familiar with this area of the product, so I will transfer this over to the `sentry` repo where folks can be of more help. However, note that since your setup is not officially supported and highly customized, I'm not sure how much help we can be.
