### ISSUE TITLE
Error upgrdeing from 23.8.0

### ISSUE THREAD

**Issue by kevinwincott** [getsentry/self-hosted#2680]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. git clone any version greater than 23.8.0
2. run./install.sh

### Expected Result

install and runs

### Actual Result

Running migrations for default
Operations to perform:
  Apply all migrations: auth, contenttypes, feedback, hybridcloud, nodestore, replays, sentry, sessions, sites, social_auth
Running migrations:
Rules:   7% |###                                               | ETA:   0:00:00Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py", line 173, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'project'

__fake__.Project.DoesNotExist: Project matching query does not exist.
Error in install/set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:34
--> install/set-up-and-migrate-database.sh:source:12

**Comment by hubertdeng123** [comment]
Not entirely sure why this is happening. Maybe try and clear your cache and retry the upgrade?

**Comment by kevinwincott** [comment]
> Not entirely sure why this is happening. Maybe try and clear your cache and retry the upgrade?

have done, even on a fresh build doesnt work

**Comment by hubertdeng123** [comment]
Unfortunately, if it's not working on a fresh install for you, I'm not sure what could be going wrong. Have you attempted to recreate your docker volumes before installing?
