### ISSUE TITLE
Upgrading to 23.12.1 or newest dev version fails due to hanging snuba migration

### ISSUE THREAD

**Issue by evolvoltd** [getsentry/self-hosted#2710]
### Self-Hosted Version

23.12.1

### CPU Architecture

x86-64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

git pull origin master or git fetch; git checkout  23.12.1
./install.sh

### Expected Result

Installation completes successfully

### Actual Result

Docker images built.

▶ Downloading and installing wal2json ...

▶ Bootstrapping and migrating Snuba ...
 Network sentry-self-hosted_default  Creating
 Network sentry-self-hosted_default  Created
 Container sentry-self-hosted-redis-1  Creating
 Container sentry-self-hosted-zookeeper-1  Creating
 Container sentry-self-hosted-clickhouse-1  Creating
 Container sentry-self-hosted-clickhouse-1  Created
 Container sentry-self-hosted-redis-1  Created
 Container sentry-self-hosted-zookeeper-1  Created
 Container sentry-self-hosted-kafka-1  Creating
 Container sentry-self-hosted-kafka-1  Created
 Container sentry-self-hosted-redis-1  Starting
 Container sentry-self-hosted-zookeeper-1  Starting
 Container sentry-self-hosted-clickhouse-1  Starting
 Container sentry-self-hosted-zookeeper-1  Started
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-redis-1  Started
 Container sentry-self-hosted-clickhouse-1  Started
 Container sentry-self-hosted-zookeeper-1  Healthy
 Container sentry-self-hosted-kafka-1  Starting
 Container sentry-self-hosted-kafka-1  Started
2024-01-16 13:05:22,504 Initializing Snuba...
2024-01-16 13:05:30,400 Snuba initialization took 7.8977684415876865s
2024-01-16 13:05:31,773 Initializing Snuba...
2024-01-16 13:05:39,993 Snuba initialization took 8.22258822992444s
2024-01-16 13:05:39,998 Attempting to connect to Kafka (attempt 0)...
2024-01-16 13:05:40,024 Connected to Kafka on attempt 0
2024-01-16 13:05:40,028 Creating Kafka topics...
 Container sentry-self-hosted-redis-1  Running
 Container sentry-self-hosted-zookeeper-1  Running
 Container sentry-self-hosted-kafka-1  Running
 Container sentry-self-hosted-clickhouse-1  Running
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-zookeeper-1  Healthy
2024-01-16 13:05:44,534 Initializing Snuba...
2024-01-16 13:05:53,180 Snuba initialization took 8.64770570769906s
2024-01-16 13:05:54,442 Initializing Snuba...
2024-01-16 13:06:03,098 Snuba initialization took 8.658086821436882s
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 99, in migrate
    runner.run_all(
  File "/usr/src/snuba/snuba/migrations/runner.py", line 178, in run_all
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 410, in _get_pending_migrations
    group_migrations = self._get_pending_migrations_for_group(group)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 433, in _get_pending_migrations_for_group
    raise MigrationInProgress(str(migration_key))
snuba.migrations.errors.MigrationInProgress: outcomes: 0002_outcomes_remove_size_and_bytes
Error in install/bootstrap-snuba.sh:4.
'$dcr snuba-api migrations migrate --force' exited with status 1
-> ./install.sh:main:31
--> install/bootstrap-snuba.sh:source:4

**Comment by hubertdeng123** [comment]
Looks like your migration may not have been terminated correctly in the middle. You may need to do some manual work to force a migration or remove pending migrations in order to get this upgrade through.

**Comment by evolvoltd** [comment]
Is there a documentation of Available snuba api database commands?  Or do I need to login to database directly in to database? If so, it would be easier to reinstall everything.

**Comment by azaslavsky** [comment]
If you want to keep the basic structure of the instance (users, orgs, projects, teams, rules, etc) after a reinstall, you can use `backup.sh` to back all of that up, then `restore.sh` post re-install. More info [here](https://develop.sentry.dev/self-hosted/backup/). I would recommend doing a [full volume backup](https://develop.sentry.dev/self-hosted/backup/#full-backup) as well to be extra safe.

**Comment by evolvoltd** [comment]
Thank you can close now.
