### ISSUE TITLE
Unable to fetch all project stats due to AssertionError

### ISSUE THREAD

**Issue by fdaugs** [getsentry/self-hosted#2736]
### Self-Hosted Version

24.1.0

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

2.18.1

### Steps to Reproduce

When opening the "Projects"-page, no stats are shown and "Unable to fetch all project stats" error is shown. Alle stats on the project Details page work as expected.

This is the error log from the web container:

```
sentry-self-hosted-web-1  | Traceback (most recent call last):
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/api/base.py", line 231, in handle_exception
sentry-self-hosted-web-1  |     response = super().handle_exception(exc)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
sentry-self-hosted-web-1  |     self.raise_uncaught_exception(exc)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
sentry-self-hosted-web-1  |     raise exc
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/api/base.py", line 355, in dispatch
sentry-self-hosted-web-1  |     response = handler(request, *args, **kwargs)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
sentry-self-hosted-web-1  |     return method(self, request, *args, **kwargs)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/api/endpoints/organization_projects.py", line 172, in get
sentry-self-hosted-web-1  |     return self.paginate(
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/api/base.py", line 465, in paginate
sentry-self-hosted-web-1  |     results = on_results(cursor_result.results)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/api/endpoints/organization_projects.py", line 170, in serialize_on_result
sentry-self-hosted-web-1  |     return serialize(result, request.user, serializer)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/api/serializers/base.py", line 69, in serialize
sentry-self-hosted-web-1  |     attrs = serializer.get_attrs(
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/api/serializers/models/project.py", line 660, in get_attrs
sentry-self-hosted-web-1  |     attrs = super().get_attrs(item_list, user)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/api/serializers/models/project.py", line 547, in get_attrs
sentry-self-hosted-web-1  |     attrs = super().get_attrs(item_list, user)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/api/serializers/models/project.py", line 334, in get_attrs
sentry-self-hosted-web-1  |     session_stats = self.get_session_stats(project_ids)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/api/serializers/models/project.py", line 419, in get_session_stats
sentry-self-hosted-web-1  |     project_health_data_dict = release_health.backend.get_current_and_previous_crash_free_rates(
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/release_health/metrics.py", line 205, in get_current_and_previous_crash_free_rates
sentry-self-hosted-web-1  |     previous = self._get_crash_free_rate_data(
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/release_health/metrics.py", line 173, in _get_crash_free_rate_data
sentry-self-hosted-web-1  |     assert totals is not None
sentry-self-hosted-web-1  | AssertionError
sentry-self-hosted-web-1  | 22:17:32 [ERROR] django.request: Internal Server Error: /api/0/organizations/applysia/projects/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/applysia/projects/?dataset=metricsEnhanced&query=id%3A5%20id%3A3%20id%3A4%20id%3A1&sessionStats=1&statsPeriod=24h&transactionStats=1'>)
```

Looks like `totals` is `None` here: https://github.com/getsentry/sentry/blob/f41be40ac7c60809d2a9cd12eb3a3584aa75c932/src/sentry/release_health/metrics.py#L187

This happen after the Upgrade to 24.1.0

### Expected Result

Should show me projects stats.

### Actual Result

see above

**Comment by fdaugs** [comment]
Nevermind. Fixed itself over night :D
