### ISSUE TITLE
Update fails with '$dcr snuba-api snuba bootstrap --no-migrate --force' exited with status 1

### ISSUE THREAD

**Issue by adminZebralog** [getsentry/self-hosted#2744]
### Self-Hosted Version

23.11.0.dev0

### CPU Architecture

x86_64

### Docker Version

25.0.1

### Docker Compose Version

2.24.2

### Steps to Reproduce

1. git fetch
2. git checkout 24.1.1 - but every version I tried gave the same error
3. ./install.sh --report-self-hosted-issues

OS is Debian 12 Bookworm headless

### Expected Result

Installer is upgrading Sentry

### Actual Result

Installer fails with '$dcr snuba-api snuba bootstrap --no-migrate --force' exited with status 1 error message.

```
[...]
Docker images built.

▶ Downloading and installing wal2json ...

▶ Bootstrapping and migrating Snuba ...
 Network sentry-self-hosted_default  Creating
 Network sentry-self-hosted_default  Created
 Volume "sentry-self-hosted_sentry-zookeeper-log"  Creating
 Volume "sentry-self-hosted_sentry-zookeeper-log"  Created
 Container sentry-self-hosted-redis-1  Creating
 Container sentry-self-hosted-zookeeper-1  Creating
 Container sentry-self-hosted-clickhouse-1  Creating
 Container sentry-self-hosted-clickhouse-1  Created
 Container sentry-self-hosted-redis-1  Created
 Container sentry-self-hosted-zookeeper-1  Created
 Container sentry-self-hosted-kafka-1  Creating
 Container sentry-self-hosted-kafka-1  Created
 Container sentry-self-hosted-clickhouse-1  Starting
 Container sentry-self-hosted-zookeeper-1  Starting
 Container sentry-self-hosted-redis-1  Starting
 Container sentry-self-hosted-redis-1  Started
 Container sentry-self-hosted-zookeeper-1  Started
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Started
 Container sentry-self-hosted-zookeeper-1  Healthy
 Container sentry-self-hosted-kafka-1  Starting
 Container sentry-self-hosted-kafka-1  Started
dependency failed to start: container sentry-self-hosted-kafka-1 is unhealthy
Error in install/bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:31
--> install/bootstrap-snuba.sh:source:3

install/error-handling.sh: line 81: /usr/bin/docker: Argument list too long

```

**Comment by adminZebralog** [comment]
Kafka looks ready

```
kafka-1  | 2024-01-29T16:03:56.091830566Z ===> User
kafka-1  | 2024-01-29T16:03:56.092139458Z uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
kafka-1  | 2024-01-29T16:03:56.092149136Z ===> Configuring ...
kafka-1  | 2024-01-29T16:03:56.092156800Z Running in KRaft mode...
kafka-1  | 2024-01-29T16:04:03.241190905Z ===> Running preflight checks ... 
kafka-1  | 2024-01-29T16:04:03.241224849Z ===> Check if /var/lib/kafka/data is writable ...
kafka-1  | 2024-01-29T16:04:05.963415740Z ===> Running in KRaft mode, skipping Zookeeper health check...
kafka-1  | 2024-01-29T16:04:05.963441329Z ===> Using provided cluster id MkU3OEVBNTcwNTJENDM2Qk ...
kafka-1  | 2024-01-29T16:04:21.647385639Z Log directory /var/lib/kafka/data is already formatted. Use --ignore-formatted to ignore this directory and format the others.
kafka-1  | 2024-01-29T16:04:21.647432848Z ===> Launching ... 
kafka-1  | 2024-01-29T16:04:21.647443688Z ===> Launching kafka ... 
kafka-1  | 2024-01-29T16:04:29.235206961Z [2024-01-29 16:04:29,231] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka-1  | 2024-01-29T16:04:44.796218301Z [2024-01-29 16:04:44,796] INFO Updated connection-accept-rate max connection creation rate to 2147483647 (kafka.network.ConnectionQuotas)
kafka-1  | 2024-01-29T16:04:45.380681924Z [2024-01-29 16:04:45,380] INFO [SocketServer listenerType=CONTROLLER, nodeId=1] Created data-plane acceptor and processors for endpoint : ListenerName(CONTROLLER) (kafka.network.SocketServer)
kafka-1  | 2024-01-29T16:05:05.380320597Z [2024-01-29 16:05:05,380] INFO Initialized snapshots with IDs SortedSet(OffsetAndEpoch(offset=16883373, epoch=29), OffsetAndEpoch(offset=16890563, epoch=29), OffsetAndEpoch(offset=16897762, epoch=29), OffsetAndEpoch(offset=16904952, epoch=29), OffsetAndEpoch(offset=16912151, epoch=29), OffsetAndEpoch(offset=16919341, epoch=29), OffsetAndEpoch(offset=16926540, epoch=29), OffsetAndEpoch(offset=16933730, epoch=29), OffsetAndEpoch(offset=16940929, epoch=29), OffsetAndEpoch(offset=16948119, epoch=29), OffsetAndEpoch(offset=16955318, epoch=29), OffsetAndEpoch(offset=16962508, epoch=29), OffsetAndEpoch(offset=16969708, epoch=29), OffsetAndEpoch(offset=16976899, epoch=29), OffsetAndEpoch(offset=16984099, epoch=29), OffsetAndEpoch(offset=16991289, epoch=29), OffsetAndEpoch(offset=16998488, epoch=29), OffsetAndEpoch(offset=17005678, epoch=29), OffsetAndEpoch(offset=17012877, epoch=29), OffsetAndEpoch(offset=17020067, epoch=29), OffsetAndEpoch(offset=17027266, epoch=29), OffsetAndEpoch(offset=17034456, epoch=29), OffsetAndEpoch(offset=17041655, epoch=29), OffsetAndEpoch(offset=17048845, epoch=29), OffsetAndEpoch(offset=17056044, epoch=29), OffsetAndEpoch(offset=17063234, epoch=29), OffsetAndEpoch(offset=17070433, epoch=29), OffsetAndEpoch(offset=17077623, epoch=29), OffsetAndEpoch(offset=17084822, epoch=29), OffsetAndEpoch(offset=17092012, epoch=29), OffsetAndEpoch(offset=17099211, epoch=29), OffsetAndEpoch(offset=17106401, epoch=29), OffsetAndEpoch(offset=17113600, epoch=29), OffsetAndEpoch(offset=17120790, epoch=29), OffsetAndEpoch(offset=17127989, epoch=29), OffsetAndEpoch(offset=17135179, epoch=29), OffsetAndEpoch(offset=17142378, epoch=29), OffsetAndEpoch(offset=17149568, epoch=29), OffsetAndEpoch(offset=17156767, epoch=29), OffsetAndEpoch(offset=17163957, epoch=29), OffsetAndEpoch(offset=17171156, epoch=29), OffsetAndEpoch(offset=17178347, epoch=29), OffsetAndEpoch(offset=17185546, epoch=29), OffsetAndEpoch(offset=17192736, epoch=29), OffsetAndEpoch(offset=17199935, epoch=29), OffsetAndEpoch(offset=17207124, epoch=29), OffsetAndEpoch(offset=17214323, epoch=29), OffsetAndEpoch(offset=17221513, epoch=29), OffsetAndEpoch(offset=17228712, epoch=29), OffsetAndEpoch(offset=17235902, epoch=29), OffsetAndEpoch(offset=17243101, epoch=29), OffsetAndEpoch(offset=17250291, epoch=29), OffsetAndEpoch(offset=17257490, epoch=29), OffsetAndEpoch(offset=17264680, epoch=29), OffsetAndEpoch(offset=17271880, epoch=29), OffsetAndEpoch(offset=17279070, epoch=29), OffsetAndEpoch(offset=17286269, epoch=29), OffsetAndEpoch(offset=17293468, epoch=29), OffsetAndEpoch(offset=17300668, epoch=29), OffsetAndEpoch(offset=17307858, epoch=29), OffsetAndEpoch(offset=17315057, epoch=29), OffsetAndEpoch(offset=17322246, epoch=29), OffsetAndEpoch(offset=17329445, epoch=29), OffsetAndEpoch(offset=17336635, epoch=29), OffsetAndEpoch(offset=17343834, epoch=29), OffsetAndEpoch(offset=17351024, epoch=29), OffsetAndEpoch(offset=17358224, epoch=29), OffsetAndEpoch(offset=17365414, epoch=29), OffsetAndEpoch(offset=17372613, epoch=29), OffsetAndEpoch(offset=17379803, epoch=29), OffsetAndEpoch(offset=17387002, epoch=29), OffsetAndEpoch(offset=17394192, epoch=29), OffsetAndEpoch(offset=17401391, epoch=29), OffsetAndEpoch(offset=17408581, epoch=29), OffsetAndEpoch(offset=17415780, epoch=29)) from /var/lib/kafka/data/__cluster_metadata-0 (kafka.raft.KafkaMetadataLog$)
kafka-1  | 2024-01-29T16:05:05.416999666Z [2024-01-29 16:05:05,415] INFO [raft-expiration-reaper]: Starting (kafka.raft.TimingWheelExpirationService$ExpiredOperationReaper)
kafka-1  | 2024-01-29T16:05:05.683398507Z [2024-01-29 16:05:05,669] INFO [kafka-1-raft-outbound-request-thread]: Starting (kafka.raft.RaftSendThread)
kafka-1  | 2024-01-29T16:05:05.712389772Z [2024-01-29 16:05:05,712] INFO [kafka-1-raft-io-thread]: Starting (kafka.raft.KafkaRaftManager$RaftIoThread)
kafka-1  | 2024-01-29T16:05:06.052491450Z [2024-01-29 16:05:06,050] INFO [SocketServer listenerType=CONTROLLER, nodeId=1] Enabling request processing. (kafka.network.SocketServer)
kafka-1  | 2024-01-29T16:05:06.060336438Z [2024-01-29 16:05:06,060] INFO Awaiting socket connections on 0.0.0.0:29093. (kafka.network.DataPlaneAcceptor)
kafka-1  | 2024-01-29T16:05:06.341414182Z [2024-01-29 16:05:06,341] INFO Updated connection-accept-rate max connection creation rate to 2147483647 (kafka.network.ConnectionQuotas)
kafka-1  | 2024-01-29T16:05:06.408193435Z [2024-01-29 16:05:06,408] INFO [SocketServer listenerType=BROKER, nodeId=1] Created data-plane acceptor and processors for endpoint : ListenerName(PLAINTEXT) (kafka.network.SocketServer)
kafka-1  | 2024-01-29T16:05:06.408578401Z [2024-01-29 16:05:06,408] INFO Updated connection-accept-rate max connection creation rate to 2147483647 (kafka.network.ConnectionQuotas)
kafka-1  | 2024-01-29T16:05:06.412543811Z [2024-01-29 16:05:06,412] INFO [SocketServer listenerType=BROKER, nodeId=1] Created data-plane acceptor and processors for endpoint : ListenerName(INTERNAL) (kafka.network.SocketServer)
kafka-1  | 2024-01-29T16:05:06.414565369Z [2024-01-29 16:05:06,414] INFO Updated connection-accept-rate max connection creation rate to 2147483647 (kafka.network.ConnectionQuotas)
kafka-1  | 2024-01-29T16:05:06.426274909Z [2024-01-29 16:05:06,426] INFO [SocketServer listenerType=BROKER, nodeId=1] Created data-plane acceptor and processors for endpoint : ListenerName(EXTERNAL) (kafka.network.SocketServer)
kafka-1  | 2024-01-29T16:05:07.679190989Z [2024-01-29 16:05:07,666] INFO Starting the log cleaner (kafka.log.LogCleaner)
kafka-1  | 2024-01-29T16:05:19.801763599Z [2024-01-29 16:05:19,801] INFO [SocketServer listenerType=BROKER, nodeId=1] Enabling request processing. (kafka.network.SocketServer)
kafka-1  | 2024-01-29T16:05:19.802275273Z [2024-01-29 16:05:19,802] INFO Awaiting socket connections on 0.0.0.0:9093. (kafka.network.DataPlaneAcceptor)
kafka-1  | 2024-01-29T16:05:19.802820661Z [2024-01-29 16:05:19,802] INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.DataPlaneAcceptor)
kafka-1  | 2024-01-29T16:05:19.803348395Z [2024-01-29 16:05:19,803] INFO Awaiting socket connections on 0.0.0.0:29092. (kafka.network.DataPlaneAcceptor)

```

**Comment by adminZebralog** [comment]
Ok we have the next error:
```
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:34
--> install/set-up-and-migrate-database.sh:source:12

install/error-handling.sh: line 81: /usr/bin/docker: Argument list too long
```
What I did:
I restored a working snapshot after failed upgrade yesterday to get the sentry logs I tried to do the update again but now I get this new error.

```
[...]
  Applying sentry.0628_better_menv_latest_index... OK
  Applying sentry.0629_eventattachment_index... OK
  Applying sentry.0630_better_monitor_latest_index... OK
  Applying sentry.0631_add_priority_columns_to_groupedmessage... OK
Api Tokens: N/A% |                                             | ETA:  --:--:--Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'django.core.cache.backends.memcached' has no attribute 'MemcachedCache'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/cache/__init__.py", line 47, in create_connection
    backend_cls = import_string(backend)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/options/store.py", line 119, in get_cache
    value = self.cache.get(cache_key)
            ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/caching.py", line 108, in sentry_create_connection
    cache = original_create_connection(self, alias)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/cache/__init__.py", line 49, in create_connection
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django.core.cache.backends.memcached.MemcachedCache': Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class
07:41:35 [WARNING] sentry: Unable to fetch option cache for apitoken.auto-add-last-chars (key='apitoken.auto-add-last-chars')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'django.core.cache.backends.memcached' has no attribute 'MemcachedCache'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/cache/__init__.py", line 47, in create_connection
    backend_cls = import_string(backend)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/options/store.py", line 262, in set_cache
    self.cache.set(cache_key, value, self.ttl)
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/caching.py", line 108, in sentry_create_connection
    cache = original_create_connection(self, alias)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/cache/__init__.py", line 49, in create_connection
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django.core.cache.backends.memcached.MemcachedCache': Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class
07:41:35 [WARNING] sentry: Unable to update option cache for apitoken.auto-add-last-chars (key='apitoken.auto-add-last-chars')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'django.core.cache.backends.memcached' has no attribute 'MemcachedCache'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/cache/__init__.py", line 47, in create_connection
    backend_cls = import_string(backend)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/options/store.py", line 119, in get_cache
    value = self.cache.get(cache_key)
            ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/caching.py", line 108, in sentry_create_connection
    cache = original_create_connection(self, alias)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/cache/__init__.py", line 49, in create_connection
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django.core.cache.backends.memcached.MemcachedCache': Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class
07:41:35 [WARNING] sentry: Unable to fetch option cache for transaction-events.force-disable-internal-project (key='transaction-events.force-disable-internal-project')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'django.core.cache.backends.memcached' has no attribute 'MemcachedCache'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/cache/__init__.py", line 47, in create_connection
    backend_cls = import_string(backend)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/options/store.py", line 262, in set_cache
    self.cache.set(cache_key, value, self.ttl)
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/caching.py", line 108, in sentry_create_connection
    cache = original_create_connection(self, alias)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/cache/__init__.py", line 49, in create_connection
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django.core.cache.backends.memcached.MemcachedCache': Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class
07:41:35 [WARNING] sentry: Unable to update option cache for transaction-events.force-disable-internal-project (key='transaction-events.force-disable-internal-project')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'django.core.cache.backends.memcached' has no attribute 'MemcachedCache'. Did you mean: 'PyMemcacheCache'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/cache/__init__.py", line 47, in create_connection
    backend_cls = import_string(backend)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/runner/__init__.py", line 190, in main
    func(**kwargs)
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/runner/commands/upgrade.py", line 117, in upgrade
    _upgrade(
  File "/usr/local/lib/python3.11/site-packages/sentry/runner/commands/upgrade.py", line 52, in _upgrade
    dj_call_command(
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/new_migrations/monkey/executor.py", line 140, in apply_migration
    return super().apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/new_migrations/migrations.py", line 22, in apply
    return super().apply(project_state, schema_editor, collect_sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/local/lib/python3.11/site-packages/sentry/migrations/0632_apitoken_backfill_last_chars.py", line 16, in backfill_last_token_characters
    api_token.save()
  File "/usr/local/lib/python3.11/site-packages/sentry/silo/base.py", line 145, in override
    return original_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/models/apitoken.py", line 66, in save
    return super().save(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/db/models/outboxes.py", line 258, in save
    super().save(*args, **kwds)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.11/site-packages/sentry/silo/base.py", line 145, in override
    return original_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/db/models/manager/base.py", line 181, in __post_save
    cache.set(
    ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/caching.py", line 108, in sentry_create_connection
    cache = original_create_connection(self, alias)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/cache/__init__.py", line 49, in create_connection
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django.core.cache.backends.memcached.MemcachedCache': Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class
Error in install/set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:34
--> install/set-up-and-migrate-database.sh:source:12

install/error-handling.sh: line 81: /usr/bin/docker: Argument list too long

```

**Comment by aldy505** [comment]
At this point, you must update your sentry/sentry.conf.py file. There's an update to the Memcached problem.

**Comment by adminZebralog** [comment]
How could I miss that note...
https://github.com/getsentry/self-hosted/pull/2722/files
helped here

Thanks
