### ISSUE TITLE
The sentry-self-hosted-post-process-forwarder-errors-1 keeps restarting

### ISSUE THREAD

**Issue by kecsot** [getsentry/self-hosted#2795]
### Self-Hosted Version

24.1.2

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

2.21

### Steps to Reproduce

docker ps

### Expected Result

sentry-self-hosted-post-process-forwarder-errors-1 should not restarting in every 8 seconds.

### Actual Result

My sentry-self-hosted-post-process-forwarder-errors-1 container is always restarting. After restarting, it uses 80-90% of my CPU. It dies again after 8 seconds.

docker compose logs post-process-forwarder-errors

```

sentry-self-hosted-post-process-forwarder-errors-1  | arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
sentry-self-hosted-post-process-forwarder-errors-1  | 09:39:35 [ERROR] arroyo.processing.processor: Caught exception, shutting down...
sentry-self-hosted-post-process-forwarder-errors-1  | 09:39:35 [INFO] arroyo.processing.processor: Closing <sentry.consumers.synchronized.SynchronizedConsumer object at 0x7f680983e210>...
sentry-self-hosted-post-process-forwarder-errors-1  | 09:39:35 [INFO] arroyo.processing.processor: Partitions to revoke: [Partition(topic=Topic(name='events'), index=0)]
sentry-self-hosted-post-process-forwarder-errors-1  | 09:39:35 [INFO] arroyo.processing.processor: Partition revocation complete.
sentry-self-hosted-post-process-forwarder-errors-1  | 09:39:35 [INFO] arroyo.processing.processor: Processor terminated
sentry-self-hosted-post-process-forwarder-errors-1  | Traceback (most recent call last):
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/bin/sentry", line 8, in <module>
sentry-self-hosted-post-process-forwarder-errors-1  |     sys.exit(main())
sentry-self-hosted-post-process-forwarder-errors-1  |              ^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/sentry/runner/__init__.py", line 190, in main
sentry-self-hosted-post-process-forwarder-errors-1  |     func(**kwargs)
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
sentry-self-hosted-post-process-forwarder-errors-1  |     return self.main(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
sentry-self-hosted-post-process-forwarder-errors-1  |     rv = self.invoke(ctx)
sentry-self-hosted-post-process-forwarder-errors-1  |          ^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
sentry-self-hosted-post-process-forwarder-errors-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-post-process-forwarder-errors-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
sentry-self-hosted-post-process-forwarder-errors-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-post-process-forwarder-errors-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
sentry-self-hosted-post-process-forwarder-errors-1  |     return ctx.invoke(self.callback, **ctx.params)
sentry-self-hosted-post-process-forwarder-errors-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
sentry-self-hosted-post-process-forwarder-errors-1  |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
sentry-self-hosted-post-process-forwarder-errors-1  |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/sentry/runner/decorators.py", line 69, in inner
sentry-self-hosted-post-process-forwarder-errors-1  |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
sentry-self-hosted-post-process-forwarder-errors-1  |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
sentry-self-hosted-post-process-forwarder-errors-1  |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/sentry/runner/decorators.py", line 29, in inner
sentry-self-hosted-post-process-forwarder-errors-1  |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
sentry-self-hosted-post-process-forwarder-errors-1  |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/sentry/runner/commands/run.py", line 557, in basic_consumer
sentry-self-hosted-post-process-forwarder-errors-1  |     run_processor_with_signals(processor, consumer_name)
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/sentry/utils/kafka.py", line 46, in run_processor_with_signals
sentry-self-hosted-post-process-forwarder-errors-1  |     processor.run()
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 319, in run
sentry-self-hosted-post-process-forwarder-errors-1  |     self._run_once()
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 381, in _run_once
sentry-self-hosted-post-process-forwarder-errors-1  |     self.__message = self.__consumer.poll(timeout=1.0)
sentry-self-hosted-post-process-forwarder-errors-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/sentry/consumers/synchronized.py", line 235, in poll
sentry-self-hosted-post-process-forwarder-errors-1  |     message = self.__consumer.poll(timeout)
sentry-self-hosted-post-process-forwarder-errors-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-post-process-forwarder-errors-1  |   File "/usr/local/lib/python3.11/site-packages/arroyo/backends/kafka/consumer.py", line 414, in poll
sentry-self-hosted-post-process-forwarder-errors-1  |     raise OffsetOutOfRange(str(error))
sentry-self-hosted-post-process-forwarder-errors-1  | arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
```

**Comment by hubertdeng123** [comment]
How much CPU/RAM is on your server? Perhaps you'll need to add more CPU or RAM

**Comment by roock** [comment]
@kecsot Looks like your Kafka data is corrupted. Try the steps from the troubleshooting guide: https://develop.sentry.dev/self-hosted/troubleshooting/#kafka

**Comment by kecsot** [comment]
Thank you! @roock
