### ISSUE TITLE
Profiles Function Regression & Improvement now working after changing vroom storage

### ISSUE THREAD

**Issue by DarkByteZero** [getsentry/self-hosted#2800]
### Self-Hosted Version

24.1.1

### CPU Architecture

x86_64

### Docker Version

25.0.1

### Docker Compose Version

2.24.2

### Steps to Reproduce

1. change vroom bucket to google cloud storage
 SENTRY_BUCKET_PROFILES: gs://sense-sentry-profiles

### Expected Result

Everything should work:
- Profiles ingestion,
- Profiles view
- Profiles Function Worst, Best, Regression

### Actual Result

Profiles ingestion & view works, but the regression and worst functions dont work anymore.

Web Container Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7efd5bec1600>: Failed to establish a new connection: [Errno 111] Connection refused
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sentry/api/base.py", line 231, in handle_exception
    response = super().handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/sentry/api/base.py", line 355, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/api/endpoints/organization_profiling_functions.py", line 200, in get
    trending_functions = get_trends_data(stats_data)
  File "/usr/local/lib/python3.10/site-packages/sentry/api/endpoints/organization_profiling_functions.py", line 187, in get_trends_data
    return detect_breakpoints(trends_request)["data"]
  File "/usr/local/lib/python3.10/site-packages/sentry/seer/utils.py", line 40, in detect_breakpoints
    response = seer_connection_pool.urlopen(
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/sentry/../urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9091): Max retries exceeded with url: /trends/breakpoint-detector (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd5bec1600>: Failed to establish a new connection: [Errno 111] Connection refused'))
20:15:08 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_profiling_functions.OrganizationProfilingFunctionTrendsEndpoint' response=500 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sense-ai-tion/profiling/function-trends/' caller_ip='84.188.31.51' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=1.9635026454925537 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
20:15:08 [ERROR] django.request: Internal Server Error: /api/0/organizations/sense-ai-tion/profiling/function-trends/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/sense-ai-tion/profiling/function-trends/?function=p95%28%29&per_page=3&query=is_application%3A1&statsPeriod=24h&trend=improvement'>)
```

**Comment by aldy505** [comment]
The connection error was coming from this line of code: https://github.com/getsentry/sentry/blob/4d2e2f71b8396527cb1c7def30c51d184f77b642/src/sentry/seer/utils.py#L48-L55

The `ANOMALY_DETECTION_SERVICE` is defined as "http://127.0.0.1:9091": https://github.com/getsentry/sentry/blob/4d2e2f71b8396527cb1c7def30c51d184f77b642/src/sentry/conf/server.py#L3720

I don't know what service is this, and it's not configured on self-hosted's `sentry/sentry.conf.py` file.

/cc @hubertdeng123 @azaslavsky Can you guys ask this internally?

**Comment by azaslavsky** [comment]
Will just transfer this into the vroom repo, since they'd know the most about how to configure this.
