### ISSUE TITLE
Upgrade 23.6.2 to 24.2.0 fails on migration

### ISSUE THREAD

**Issue by ZVilusinsky** [getsentry/self-hosted#2805]
### Self-Hosted Version

23.6.2

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.20.2

### Steps to Reproduce

Not sure if reproducible ? I have tried to update our long running sentry instance (started as major 8) to 24.2.0 from 23.6.2 (documentation does not mention any force step after 23.6.2) Previous upgrade went smoothly from 21.9.0, but this one fails with 
```
ValueError: Found wrong number (2) of indexes for sentry_groupedmessage(project_id, id).
Error in install/set-up-and-migrate-database.sh:15.
```
entire log follows. Just to pre-emptively answer obvious - we have not done any manual database manipulation other then vacuum full. 

### Expected Result

Successful upgrade to latest version.

### Actual Result

[sentry_install_log-2024-02-19_16-06-02.txt](https://github.com/getsentry/self-hosted/files/14334066/sentry_install_log-2024-02-19_16-06-02.txt)

**Comment by ZVilusinsky** [comment]
Hm, honestly, not sure what hit me here, after trying to recover from manual backup of volumes, the stack will start up, but can't login into the Sentry and log is full of 
```
psycopg2.errors.UndefinedColumn: UndefinedColumn('column sentry_projectdsymfile.date_accessed does not exist\nLINE 1: ...file"."code_id", "sentry_projectdsymfile"."data", "sentry_pr...\n                                                             ^\n')
SQL: SELECT "sentry_projectdsymfile"."id", "sentry_projectdsymfile"."file_id", "sentry_projectdsymfile"."checksum", "sentry_projectdsymfile"."object_name", "sentry_projectdsymfile"."cpu_name", "sentry_projectdsymfile"."project_id", "sentry_projectdsymfile"."uuid", "sentry_projectdsymfile"."code_id", "sentry_projectdsymfile"."data", "sentry_projectdsymfile"."date_accessed", "sentry_file"."id", "sentry_file"."name", "sentry_file"."type", "sentry_file"."timestamp", "sentry_file"."headers", "sentry_file"."size", "sentry_file"."checksum", "sentry_file"."blob_id", "sentry_file"."path" FROM "sentry_projectdsymfile" INNER JOIN "sentry_file" ON ("sentry_projectdsymfile"."file_id" = "sentry_file"."id") WHERE ("sentry_projectdsymfile"."uuid" = %s AND "sentry_projectdsymfile"."project_id" = %s) ORDER BY "sentry_projectdsymfile"."id" DESC LIMIT 21

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/api/base.py", line 273, in handle_exception
    response = super().handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/sentry/api/base.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/api/endpoints/debug_files.py", line 299, in get
    return self.paginate(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/api/base.py", line 487, in paginate
    cursor_result = paginator.get_result(
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/api/paginator.py", line 275, in get_result
    results = list(queryset[offset:stop])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/sentry/../sentry_sdk/integrations/django/__init__.py", line 641, in execute
    result = real_execute(self, sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python3.11/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/db/postgres/decorators.py", line 93, in inner
    raise type(e)(f"{e!r}\nSQL: {sql}").with_traceback(e.__traceback__)
  File "/usr/local/lib/python3.11/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/db/postgres/base.py", line 84, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           
```
seems like the first update did not end well and we just did not notice :-/

**Comment by ZVilusinsky** [comment]
We managed to recover using a backup of whole VM and I've tried to upgrade again - with the same result of error in migration. 

Seems like either there is a hard stop missing in documentation, or our data(base) are somehow corrupted, despite running and ingesting events.
