### ISSUE TITLE
Login failed cause by Coloumn not found

### ISSUE THREAD

**Issue by binooetomo** [getsentry/self-hosted#2843]
### Self-Hosted Version

unknown (how to check it?)

### CPU Architecture

x86_64

### Docker Version

19.03.13

### Docker Compose Version

1.27.4

### Steps to Reproduce

do a web login

### Expected Result

loged in

### Actual Result

![Screenshot_2024-02-29_10-12-48](https://github.com/getsentry/self-hosted/assets/28727621/9306fb7b-fd15-4deb-97e9-a0848d2a287e)

Logs:
```
File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 76, in execute
   return self.cursor.execute(sql, clean_bad_params(params))
psycopg2.errors.UndefinedColumn: UndefinedColumn('column auth_user.actor_id does not exist\nLINE 1: …"auth_user"."flags", "auth_user"."session_nonce", "auth_user…\n                                                             ^\n',)
SQL: SELECT "auth_user"."password", "auth_user"."last_login", "auth_user"."id", "auth_user"."username", "auth_user"."first_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."is_superuser", "auth_user"."is_managed", "auth_user"."is_sentry_app", "auth_user"."is_password_expired", "auth_user"."last_password_change", "auth_user"."flags", "auth_user"."session_nonce", "auth_user"."actor_id", "auth_user"."date_joined", "auth_user"."last_active" FROM "auth_user" WHERE (NOT ("auth_user"."password" = %s) AND UPPER("auth_user"."username"::text) = UPPER(%s))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
   response = get_response(request)
 File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
   response = self.process_exception_by_middleware(e, request)
 File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/local/lib/python3.6/site-packages/sentry/../sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
   return callback(request, *args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
   return self.dispatch(request, *args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
   return view_func(*args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/sentry/web/frontend/base.py", line 228, in dispatch
   return self.handle(request, *args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
   response = view_func(request, *args, **kwargs)
 File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
   return func(*args, **kwds)
 File "/usr/local/lib/python3.6/site-packages/sentry/web/frontend/auth_organization_login.py", line 68, in handle
   response = self.handle_basic_auth(request, organization=organization)
 File "/usr/local/lib/python3.6/site-packages/sentry/web/frontend/auth_login.py", line 199, in handle_basic_auth
   elif login_form.is_valid():
 File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
   return self.is_bound and not self.errors
 File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
   self.full_clean()
 File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 382, in full_clean
   self._clean_form()
 File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 409, in _clean_form
   cleaned_data = self.clean()
 File "/usr/local/lib/python3.6/site-packages/sentry/web/forms/accounts.py", line 129, in clean
   self.user_cache = authenticate(username=username, password=password)
 File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
   user = backend.authenticate(request, **credentials)
 File "/usr/local/lib/python3.6/site-packages/sentry/utils/auth.py", line 277, in authenticate
   users = find_users(username)
 File "/usr/local/lib/python3.6/site-packages/sentry/utils/auth.py", line 162, in find_users
   user = qs.get(username__iexact=username)
 File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
   num = len(clone)
 File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
   self._fetch_all()
 File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
   self._result_cache = list(self._iterable_class(self))
 File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
   results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
 File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
   cursor.execute(sql, params)
 File "/usr/local/lib/python3.6/site-packages/sentry/../sentry_sdk/integrations/django/__init__.py", line 500, in execute
   return real_execute(self, sql, params)
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
   return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
   return executor(sql, params, many, context)
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
   return self.cursor.execute(sql, params)
 File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
   raise dj_exc_value.with_traceback(traceback) from exc_value
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
   return self.cursor.execute(sql, params)
 File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
   raise_the_exception(self.db, e)
 File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
   return func(self, *args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
   return func(self, *args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
   raise exc_info[0](msg).with_traceback(exc_info[2])
 File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
   return func(self, sql, *args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 76, in execute
   return self.cursor.execute(sql, clean_bad_params(params))
django.db.utils.ProgrammingError: UndefinedColumn('column auth_user.actor_id does not exist\nLINE 1: …"auth_user"."flags", "auth_user"."session_nonce", "auth_user…\n                                                             ^\n',)
SQL: SELECT "auth_user"."password", "auth_user"."last_login", "auth_user"."id", "auth_user"."username", "auth_user"."first_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."is_superuser", "auth_user"."is_managed", "auth_user"."is_sentry_app", "auth_user"."is_password_expired", "auth_user"."last_password_change", "auth_user"."flags", "auth_user"."session_nonce", "auth_user"."actor_id", "auth_user"."date_joined", "auth_user"."last_active" FROM "auth_user" WHERE (NOT ("auth_user"."password" = %s) AND UPPER("auth_user"."username"::text) = UPPER(%s))
01:47:23 [ERROR] django.request: Internal Server Error: /auth/login/sentry/ (status_code=500 request=)
```

**Comment by aldy505** [comment]
Hi.

How did you install your Sentry? Can you describe your steps?

**Comment by binooetomo** [comment]
> Hi.
> 
> How did you install your Sentry? Can you describe your steps?

well .. it's not me that do the installation.
After I talk to my boss, he decide to do new installation.

I thankyou for your response.

**Comment by hubertdeng123** [comment]
Is the new installation working now?
