### ISSUE TITLE
iOS symbolization problem

### ISSUE THREAD

**Issue by barisyild** [getsentry/self-hosted#2875]
### Self-Hosted Version

24.1.0

### CPU Architecture

x86_64

### Docker Version

Docker version 25.0.3, build 4debf41

### Docker Compose Version

Docker Compose version v2.24.6

### Steps to Reproduce

I'm not sure exactly how it will be produced.

### Expected Result

Sentry Cloud

![image](https://github.com/getsentry/self-hosted/assets/25794892/9bd33766-42ae-42b5-a2fe-06585a876940)
![image](https://github.com/getsentry/self-hosted/assets/25794892/8629dc9d-52b4-4b1c-8e6f-7a8a718733a8)

Sentry Self-Hosted

![image](https://github.com/getsentry/self-hosted/assets/25794892/89ea4b56-477f-4416-86e9-b725cce2deb8)

In the 2 report, the dSYM file does not exist, even if dSYM already exists, self-hosted definitely does not work.

It was working at first but suddenly this problem started, I suspect it started after the upgrade below.

https://github.com/getsentry/self-hosted/issues/2545#issuecomment-1840020025

### Actual Result

```
worker-1                                    |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
worker-1                                        |     resp = conn.urlopen(
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
worker-1                                        |     retries = retries.increment(
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
worker-1                                        |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
worker-1                                        | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='symbolicator', port=3021): Max retries exceeded with url: /symbolicate?timeout=5&scope=5 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f02314cd900>: Failed to resolve 'symbolicator' ([Errno -3] Temporary failure in name resolution)"))
worker-1                                        | 
worker-1                                        | During handling of the above exception, another exception occurred:
worker-1                                        | 
worker-1                                        | Traceback (most recent call last):
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/sentry/lang/native/symbolicator.py", line 293, in _request
worker-1                                        |     response = self.session.request(method, url, timeout=self.timeout + 1, **kwargs)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/sentry/net/http.py", line 189, in request
worker-1                                        |     response = _Session.request(self, *args, **kwargs)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
worker-1                                        |     resp = self.send(prep, **send_kwargs)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
worker-1                                        |     r = adapter.send(request, **kwargs)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
worker-1                                        |     raise ConnectionError(e, request=request)
worker-1                                        | requests.exceptions.ConnectionError: HTTPConnectionPool(host='symbolicator', port=3021): Max retries exceeded with url: /symbolicate?timeout=5&scope=5 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f02314cd900>: Failed to resolve 'symbolicator' ([Errno -3] Temporary failure in name resolution)"))
worker-1                                        | 10:04:56 [ERROR] sentry.lang.native.symbolicator: Failed to contact symbolicator
worker-1                                        | Traceback (most recent call last):
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
worker-1                                        |     sock = connection.create_connection(
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
worker-1                                        |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
worker-1                                        |   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
worker-1                                        |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
worker-1                                        | socket.gaierror: [Errno -3] Temporary failure in name resolution
worker-1                                        | 
worker-1                                        | The above exception was the direct cause of the following exception:
worker-1                                        | 
worker-1                                        | Traceback (most recent call last):
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
worker-1                                        |     response = self._make_request(
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
worker-1                                        |     conn.request(
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
worker-1                                        |     self.endheaders()
worker-1                                        |   File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
worker-1                                        |     self._send_output(message_body, encode_chunked=encode_chunked)
worker-1                                        |   File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
worker-1                                        |     self.send(msg)
worker-1                                        |   File "/usr/local/lib/python3.10/http/client.py", line 976, in send
worker-1                                        |     self.connect()
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
worker-1                                        |     self.sock = self._new_conn()
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
worker-1                                        |     raise NameResolutionError(self.host, self, e) from e
worker-1                                        | urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7f02314cd900>: Failed to resolve 'symbolicator' ([Errno -3] Temporary failure in name resolution)
worker-1                                        | 
worker-1                                        | The above exception was the direct cause of the following exception:
worker-1                                        | 
worker-1                                        | Traceback (most recent call last):
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
worker-1                                        |     resp = conn.urlopen(
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
worker-1                                        |     retries = retries.increment(
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
worker-1                                        |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
worker-1                                        | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='symbolicator', port=3021): Max retries exceeded with url: /symbolicate?timeout=5&scope=5 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f02314cd900>: Failed to resolve 'symbolicator' ([Errno -3] Temporary failure in name resolution)"))
worker-1                                        | 
worker-1                                        | During handling of the above exception, another exception occurred:
worker-1                                        | 
worker-1                                        | Traceback (most recent call last):
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/sentry/tasks/symbolication.py", line 249, in _do_symbolicate_event
worker-1                                        |     symbolicated_data = symbolication_function(symbolicator, data)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/sentry/lang/native/processing.py", line 406, in process_native_stacktraces
worker-1                                        |     response = symbolicator.process_payload(stacktraces=stacktraces, modules=modules, signal=signal)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/sentry/lang/native/symbolicator.py", line 190, in process_payload
worker-1                                        |     res = self._process("symbolicate_stacktraces", "symbolicate", json=json)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/sentry/lang/native/symbolicator.py", line 105, in _process
worker-1                                        |     json_response = session.create_task(path, **kwargs)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/sentry/lang/native/symbolicator.py", line 359, in create_task
worker-1                                        |     return self._request(method="post", path=path, params=params, **kwargs)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/sentry/lang/native/symbolicator.py", line 293, in _request
worker-1                                        |     response = self.session.request(method, url, timeout=self.timeout + 1, **kwargs)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/sentry/net/http.py", line 189, in request
worker-1                                        |     response = _Session.request(self, *args, **kwargs)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
worker-1                                        |     resp = self.send(prep, **send_kwargs)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
worker-1                                        |     r = adapter.send(request, **kwargs)
worker-1                                        |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
worker-1                                        |     raise ConnectionError(e, request=request)
worker-1                                        | requests.exceptions.ConnectionError: HTTPConnectionPool(host='symbolicator', port=3021): Max retries exceeded with url: /symbolicate?timeout=5&scope=5 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f02314cd900>: Failed to resolve 'symbolicator' ([Errno -3] Temporary failure in name resolution)"))
worker-1                                        | 10:04:57 [ERROR] sentry.errors.events: tasks.store.symbolicate_event.symbolication
```

**Comment by barisyild** [comment]
The problem resolved itself but I still don't know why.

Re-installing with ./install.sh did not solve the problem.

**Comment by hubertdeng123** [comment]
`Temporary failure in name resolution` indicates to me that your web container is having problems connecting with symbolicator. I'm guessing that was fixed, which then solved your issue. I'm glad the problem resolved itself, and if it comes up again feel free to reopen the issue.
