### ISSUE TITLE
While attempting to reinstall Sentry I'm getting an error saying that container zookeeper is unhealthy and dependency failed to start.

### ISSUE THREAD

**Issue by edgariscoding** [getsentry/self-hosted#2881]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

Not sure if this is related at all: I relocated the docker /var/lib/docker directory to a mounted drive since this directory was taking up too much space. I added the new location on /etc/docker/daemon.json with docker-root.

Everything was working fine after relocating the directory, starting docker, and deleting the old directory. 

Hours later we had a spike in error logs and it caused Sentry to crash, i assume because it was not receiving any more events. I attempted rebooting the server and Sentry would no longer load. It would just show 502 Bad Gateway.

I attempted reinstalling but i got the following error:

```
Docker images built.

▶ Downloading and installing wal2json ...

▶ Bootstrapping and migrating Snuba ...
 Network sentry-self-hosted_default  Creating
 Network sentry-self-hosted_default  Created
 Container sentry-self-hosted-redis-1  Creating
 Container sentry-self-hosted-clickhouse-1  Creating
 Container sentry-self-hosted-zookeeper-1  Creating
 Container sentry-self-hosted-clickhouse-1  Created
 Container sentry-self-hosted-redis-1  Created
 Container sentry-self-hosted-zookeeper-1  Created
 Container sentry-self-hosted-kafka-1  Creating
 Container sentry-self-hosted-kafka-1  Created
 Container sentry-self-hosted-zookeeper-1  Starting
 Container sentry-self-hosted-clickhouse-1  Starting
 Container sentry-self-hosted-redis-1  Starting
 Container sentry-self-hosted-zookeeper-1  Started
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Started
 Container sentry-self-hosted-redis-1  Started
 Container sentry-self-hosted-zookeeper-1  Error
dependency failed to start: container sentry-self-hosted-zookeeper-1 is unhealthy
Error in install/bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:32
--> install/bootstrap-snuba.sh:source:3

Cleaning up...
```

Looking at the `docker logs sentry-self-hosted-zookeeper-1`:
```
sentryroot@CC-AZURE-SENTRY:~/sentry$ docker logs sentry-self-hosted-zookeeper-1
===> User
uid=0(root) gid=0(root) groups=0(root)
===> Configuring ...
===> Running preflight checks ... 
===> Check if /var/lib/zookeeper/data is writable ...
===> Check if /var/lib/zookeeper/log is writable ...
===> Launching ... 
===> Launching zookeeper ... 
[2024-03-11 20:49:01,534] WARN Either no config or no quorum defined in config, running  in standalone mode (org.apache.zookeeper.server.quorum.QuorumPeerMain)
[2024-03-11 20:49:01,664] WARN o.e.j.s.ServletContextHandler@33f88ab{/,null,STOPPED} contextPath ends with /* (org.eclipse.jetty.server.handler.ContextHandler)
[2024-03-11 20:49:01,664] WARN Empty contextPath (org.eclipse.jetty.server.handler.ContextHandler)
[2024-03-11 20:49:01,718] WARN ServletContext@o.e.j.s.ServletContextHandler@33f88ab{/,null,STARTING} has uncovered http methods for path: /* (org.eclipse.jetty.security.SecurityHandler)
[2024-03-11 20:49:01,760] ERROR Unexpected exception, exiting abnormally (org.apache.zookeeper.server.ZooKeeperServerMain)
java.io.IOException: No snapshot found, but there are log entries. Something is broken!
        at org.apache.zookeeper.server.persistence.FileTxnSnapLog.restore(FileTxnSnapLog.java:240)
        at org.apache.zookeeper.server.ZKDatabase.loadDataBase(ZKDatabase.java:240)
        at org.apache.zookeeper.server.ZooKeeperServer.loadData(ZooKeeperServer.java:305)
        at org.apache.zookeeper.server.ZooKeeperServer.startdata(ZooKeeperServer.java:465)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.startup(NIOServerCnxnFactory.java:764)
        at org.apache.zookeeper.server.ServerCnxnFactory.startup(ServerCnxnFactory.java:98)
        at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:145)
        at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:107)
        at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:65)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:128)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
```

Any suggestions?

### Expected Result

For ./install.sh to succeed.

### Actual Result

error logs listed above

**Comment by aldy505** [comment]
"No snapshot found" might be resolved if you recreate your Zookeeper volume. You might want to do this (but please backup your entire VM first -- also you'll lost the last 24 hours of unprocessed events):
1. `sudo docker compose down`
2. `sudo docker volume rm sentry-zookeeper`
3. `sudo docker volume rm sentry-kafka` -- Kafka will be problematic if the Zookeeper entry is missing or broken.. the usual stuff, one stuff leads to another.
4. `sudo ./install.sh`
5. `sudo docker compose up -d` (or `sudo docker compose --env-file .env.custom up -d` if you're using custom env file)

**Comment by dar6k6night** [comment]
> "No snapshot found" might be resolved if you recreate your Zookeeper volume. You might want to do this (but please backup your entire VM first -- also you'll lost the last 24 hours of unprocessed events):
> 
> 1. `sudo docker compose down`
> 2. `sudo docker volume rm sentry-zookeeper`
> 3. `sudo docker volume rm sentry-kafka` -- Kafka will be problematic if the Zookeeper entry is missing or broken.. the usual stuff, one stuff leads to another.
> 4. `sudo ./install.sh`
> 5. `sudo docker compose up -d` (or `sudo docker compose --env-file .env.custom up -d` if you're using custom env file)
I have the same problem, these steps do not help with fixing it, at step 4 it occurs again
