### ISSUE TITLE
Snuba consumes high cpu

### ISSUE THREAD

**Issue by samir34ml** [getsentry/self-hosted#2911]
### Self-Hosted Version

24.3.0

### CPU Architecture

x86_x64

### Docker Version

25.0.4

### Docker Compose Version

2.24.7

### Steps to Reproduce

I have installed sentry self hosted on an aws EC2. The only different that I have made is the following.
In the process of creating the EC2, I attached a new HDD disk to the server and mounted it. I used HDD disk to mount 2 volumes sentry-kafka and sentry-postgres. I edited the following file install/create-docker-volumes.sh (attached to the issue).
[create-docker-volumes.txt](https://github.com/getsentry/self-hosted/files/14665978/create-docker-volumes.txt)
So, now I can mount all the docker volumes data and storage of both sentry-kafka and sentry-postgres to the HDD disk.

The reason why I did this is to save some money and use huge disk of HDD instead of SSD because these volumes consume huge amount of disk space.

### Expected Result

normal behavior and events receiving and issue monitoring.

### Actual Result

no events no issues high cpu utilization even after uninstalling sentry completely and installing it again.

It worked for a while around day or day and half, then sentry stops to report. No new events or issues or transactions.
I had to reset it and re-install it from the beginning but now even before adding any project cpu is very high above 90%. 
![image](https://github.com/getsentry/self-hosted/assets/134782004/49c07718-b535-4530-8058-f026a028956b)

![image](https://github.com/getsentry/self-hosted/assets/134782004/958a1784-92c3-4155-80cc-36fbcd7a43b9)

I tried to add some logs from the docker compose logs command output.
[logs.txt](https://github.com/getsentry/self-hosted/files/14666617/logs.txt)

So any idea regrading what to do next?

Thanks,

**Comment by hubertdeng123** [comment]
Thanks for writing in. Could you answer these questions before proceeding?
1. What is your even throughput into your instance? 
2. How much CPU are you using?

**Comment by samir34ml** [comment]
Hello @hubertdeng123 

for question 1, I hope the attached screenshot answers your question.
![image](https://github.com/getsentry/self-hosted/assets/134782004/848015d5-65d5-47bb-ae0b-e06edc229d7e)

And for question 2, I am using t3a.xlarge as EC2 from aws, which has 4 vCPU and 16 GB of memory.

Thanks,

**Comment by csvan** [comment]
As somebody who also deploys Sentry on AWS, I would _strongly_ advice against using t3a instances. Their baseline performance is too low, and the burst performance does not scale well with how Sentry operates.

Look into using m7i instances, at least, or m7i-flex if minimising costs is a concern.

**Comment by chris-laack** [comment]
we use r6a.large instances in the aws. They work very well for us. 

<img width="1439" alt="Bildschirmfoto 2024-03-26 um 08 13 03" src="https://github.com/getsentry/self-hosted/assets/152288991/e3299522-8918-481d-980c-a5ea0f0eee66">

**Comment by levani** [comment]
Having the same issue on digitalocean droplet after upgrading to 24.3.0

**Comment by azaslavsky** [comment]
Can you see if the solution suggested [here](https://github.com/getsentry/snuba/issues/5707#issuecomment-2027710056) helps in this case as well?

**Comment by rihards-simanovics** [comment]
hey just updated to 24.4.1, my CPU is constantly pegged to 100%, snuba seems to be the cause.

<img width="1919" alt="image" src="https://github.com/getsentry/self-hosted/assets/52106095/8a3c134b-2145-47d5-896a-b67f0ab9ef7e">

**Comment by azaslavsky** [comment]
Can you try the advice posted [here](https://github.com/getsentry/self-hosted/issues/2931#issuecomment-2040854990)?

**Comment by rihards-simanovics** [comment]
> Can you try the advice posted [here](https://github.com/getsentry/self-hosted/issues/2931#issuecomment-2040854990)?

hmm actually runs worse without the rust, can see an extra 20% on top for the CPU utilisation from both sentry and arrouns 5% for snuba. have run the `docker compose logs -f` and it does look like everything is running as expected other than periodical tracebacks from `sentry-self-hosted-post-process-forwarder-errors-1`, `sentry-self-hosted-metrics-consumer-1` and `sentry-self-hosted-generic-metrics-consumer-1`, in case it helps here are the specific logs:

<details>
  <summary>sentry-self-hosted-post-process-forwarder-errors-1 traces</summary>

```
sentry-self-hosted-post-process-forwarder-errors-1                 | Traceback (most recent call last):
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/bin/sentry", line 8, in <module>
sentry-self-hosted-post-process-forwarder-errors-1                 |     sys.exit(main())
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
sentry-self-hosted-post-process-forwarder-errors-1                 |     func(**kwargs)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
sentry-self-hosted-post-process-forwarder-errors-1                 |     return self.main(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
sentry-self-hosted-post-process-forwarder-errors-1                 |     rv = self.invoke(ctx)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-post-process-forwarder-errors-1                 |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-post-process-forwarder-errors-1                 |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
sentry-self-hosted-post-process-forwarder-errors-1                 |     return ctx.invoke(self.callback, **ctx.params)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-errors-1                 |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-post-process-forwarder-errors-1                 |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
sentry-self-hosted-post-process-forwarder-errors-1                 |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-errors-1                 |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-post-process-forwarder-errors-1                 |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
sentry-self-hosted-post-process-forwarder-errors-1                 |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-post-process-forwarder-errors-1                 |     return __callback(*args, **kwargs)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 730, in basic_consumer
sentry-self-hosted-post-process-forwarder-errors-1                 |     run_processor_with_signals(processor)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/kafka.py", line 13, in run_processor_with_signals
sentry-self-hosted-post-process-forwarder-errors-1                 |     processor.run()
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
sentry-self-hosted-post-process-forwarder-errors-1                 |     self._run_once()
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 355, in _run_once
sentry-self-hosted-post-process-forwarder-errors-1                 |     self.__message = self.__consumer.poll(timeout=1.0)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/sentry/consumers/synchronized.py", line 245, in poll
sentry-self-hosted-post-process-forwarder-errors-1                 |     message = self.__consumer.poll(timeout)
sentry-self-hosted-post-process-forwarder-errors-1                 |   File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 414, in poll
sentry-self-hosted-post-process-forwarder-errors-1                 |     raise OffsetOutOfRange(str(error))
sentry-self-hosted-post-process-forwarder-errors-1                 | arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
```
</details>



<details>
  <summary>sentry-self-hosted-metrics-consumer-1 traces</summary>

```log
sentry-self-hosted-metrics-consumer-1                              | 07:11:58 [ERROR] arroyo.processing.processor: Caught exception, shutting down...
sentry-self-hosted-metrics-consumer-1                              | 07:11:58 [INFO] arroyo.processing.processor: Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f46df62f220>...
sentry-self-hosted-metrics-consumer-1                              | 07:11:58 [INFO] arroyo.processing.processor: Processor terminated
sentry-self-hosted-metrics-consumer-1                              | Traceback (most recent call last):
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/bin/sentry", line 8, in <module>
sentry-self-hosted-metrics-consumer-1                              |     sys.exit(main())
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
sentry-self-hosted-metrics-consumer-1                              |     func(**kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
sentry-self-hosted-metrics-consumer-1                              |     return self.main(*args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
sentry-self-hosted-metrics-consumer-1                              |     rv = self.invoke(ctx)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-metrics-consumer-1                              |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-metrics-consumer-1                              |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
sentry-self-hosted-metrics-consumer-1                              |     return ctx.invoke(self.callback, **ctx.params)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-metrics-consumer-1                              |     return __callback(*args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-metrics-consumer-1                              |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
sentry-self-hosted-metrics-consumer-1                              |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-metrics-consumer-1                              |     return __callback(*args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-metrics-consumer-1                              |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
sentry-self-hosted-metrics-consumer-1                              |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-metrics-consumer-1                              |     return __callback(*args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 730, in basic_consumer
sentry-self-hosted-metrics-consumer-1                              |     run_processor_with_signals(processor)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/kafka.py", line 13, in run_processor_with_signals
sentry-self-hosted-metrics-consumer-1                              |     processor.run()
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
sentry-self-hosted-metrics-consumer-1                              |     self._run_once()
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 355, in _run_once
sentry-self-hosted-metrics-consumer-1                              |     self.__message = self.__consumer.poll(timeout=1.0)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 416, in poll
sentry-self-hosted-metrics-consumer-1                              |     raise ConsumerError(str(error))
sentry-self-hosted-metrics-consumer-1                              | arroyo.errors.ConsumerError: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: ingest-metrics: Broker: Unknown topic or partition"}
sentry-self-hosted-metrics-consumer-1                              | Updating certificates in /etc/ssl/certs...
sentry-self-hosted-metrics-consumer-1                              | 0 added, 0 removed; done.
sentry-self-hosted-metrics-consumer-1                              | Running hooks in /etc/ca-certificates/update.d...
sentry-self-hosted-metrics-consumer-1                              | done.
sentry-self-hosted-metrics-consumer-1                              | Traceback (most recent call last):
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
sentry-self-hosted-metrics-consumer-1                              |     self._run_once()
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 355, in _run_once
sentry-self-hosted-metrics-consumer-1                              |     self.__message = self.__consumer.poll(timeout=1.0)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 416, in poll
sentry-self-hosted-metrics-consumer-1                              |     raise ConsumerError(str(error))
sentry-self-hosted-metrics-consumer-1                              | arroyo.errors.ConsumerError: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: ingest-metrics: Broker: Unknown topic or partition"}
sentry-self-hosted-metrics-consumer-1                              | 07:12:36 [ERROR] arroyo.processing.processor: Caught exception, shutting down...
sentry-self-hosted-metrics-consumer-1                              | 07:12:36 [INFO] arroyo.processing.processor: Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7f099ef585b0>...
sentry-self-hosted-metrics-consumer-1                              | 07:12:36 [INFO] arroyo.processing.processor: Processor terminated
sentry-self-hosted-metrics-consumer-1                              | Traceback (most recent call last):
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/bin/sentry", line 8, in <module>
sentry-self-hosted-metrics-consumer-1                              |     sys.exit(main())
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
sentry-self-hosted-metrics-consumer-1                              |     func(**kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
sentry-self-hosted-metrics-consumer-1                              |     return self.main(*args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
sentry-self-hosted-metrics-consumer-1                              |     rv = self.invoke(ctx)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-metrics-consumer-1                              |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-metrics-consumer-1                              |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
sentry-self-hosted-metrics-consumer-1                              |     return ctx.invoke(self.callback, **ctx.params)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-metrics-consumer-1                              |     return __callback(*args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-metrics-consumer-1                              |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
sentry-self-hosted-metrics-consumer-1                              |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-metrics-consumer-1                              |     return __callback(*args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-metrics-consumer-1                              |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
sentry-self-hosted-metrics-consumer-1                              |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-metrics-consumer-1                              |     return __callback(*args, **kwargs)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 730, in basic_consumer
sentry-self-hosted-metrics-consumer-1                              |     run_processor_with_signals(processor)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/kafka.py", line 13, in run_processor_with_signals
sentry-self-hosted-metrics-consumer-1                              |     processor.run()
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
sentry-self-hosted-metrics-consumer-1                              |     self._run_once()
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 355, in _run_once
sentry-self-hosted-metrics-consumer-1                              |     self.__message = self.__consumer.poll(timeout=1.0)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 416, in poll
sentry-self-hosted-metrics-consumer-1                              |     raise ConsumerError(str(error))
sentry-self-hosted-metrics-consumer-1                              | arroyo.errors.ConsumerError: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: ingest-metrics: Broker: Unknown topic or partition"}
sentry-self-hosted-metrics-consumer-1                              | Updating certificates in /etc/ssl/certs...
sentry-self-hosted-metrics-consumer-1                              | 0 added, 0 removed; done.
sentry-self-hosted-metrics-consumer-1                              | Running hooks in /etc/ca-certificates/update.d...
sentry-self-hosted-metrics-consumer-1                              | done.
sentry-self-hosted-metrics-consumer-1                              | Traceback (most recent call last):
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
sentry-self-hosted-metrics-consumer-1                              |     self._run_once()
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 355, in _run_once
sentry-self-hosted-metrics-consumer-1                              |     self.__message = self.__consumer.poll(timeout=1.0)
sentry-self-hosted-metrics-consumer-1                              |   File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 416, in poll
sentry-self-hosted-metrics-consumer-1                              |     raise ConsumerError(str(error))
sentry-self-hosted-metrics-consumer-1                              | arroyo.errors.ConsumerError: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: ingest-metrics: Broker: Unknown topic or partition"}
sentry-self-hosted-metrics-consumer-1                              | 07:13:14 [ERROR] arroyo.processing.processor: Caught exception, shutting down...
```
</details>


<details>
  <summary>sentry-self-hosted-generic-metrics-consumer-1 traces</summary>

```log
sentry-self-hosted-generic-metrics-consumer-1                      | 07:59:24 [ERROR] arroyo.processing.processor: Caught exception, shutting down...
sentry-self-hosted-generic-metrics-consumer-1                      | 07:59:24 [INFO] arroyo.processing.processor: Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7fc73d1035e0>...
sentry-self-hosted-generic-metrics-consumer-1                      | 07:59:24 [INFO] arroyo.processing.processor: Processor terminated
sentry-self-hosted-generic-metrics-consumer-1                      | Traceback (most recent call last):
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/bin/sentry", line 8, in <module>
sentry-self-hosted-generic-metrics-consumer-1                      |     sys.exit(main())
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
sentry-self-hosted-generic-metrics-consumer-1                      |     func(**kwargs)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
sentry-self-hosted-generic-metrics-consumer-1                      |     return self.main(*args, **kwargs)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
sentry-self-hosted-generic-metrics-consumer-1                      |     rv = self.invoke(ctx)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-generic-metrics-consumer-1                      |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
sentry-self-hosted-generic-metrics-consumer-1                      |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
sentry-self-hosted-generic-metrics-consumer-1                      |     return ctx.invoke(self.callback, **ctx.params)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-generic-metrics-consumer-1                      |     return __callback(*args, **kwargs)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-generic-metrics-consumer-1                      |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
sentry-self-hosted-generic-metrics-consumer-1                      |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-generic-metrics-consumer-1                      |     return __callback(*args, **kwargs)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
sentry-self-hosted-generic-metrics-consumer-1                      |     return f(get_current_context(), *args, **kwargs)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
sentry-self-hosted-generic-metrics-consumer-1                      |     return ctx.invoke(f, *args, **kwargs)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
sentry-self-hosted-generic-metrics-consumer-1                      |     return __callback(*args, **kwargs)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 730, in basic_consumer
sentry-self-hosted-generic-metrics-consumer-1                      |     run_processor_with_signals(processor)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/kafka.py", line 13, in run_processor_with_signals
sentry-self-hosted-generic-metrics-consumer-1                      |     processor.run()
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
sentry-self-hosted-generic-metrics-consumer-1                      |     self._run_once()
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 355, in _run_once
sentry-self-hosted-generic-metrics-consumer-1                      |     self.__message = self.__consumer.poll(timeout=1.0)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 416, in poll
sentry-self-hosted-generic-metrics-consumer-1                      |     raise ConsumerError(str(error))
sentry-self-hosted-generic-metrics-consumer-1                      | arroyo.errors.ConsumerError: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: ingest-performance-metrics: Broker: Unknown topic or partition"}
sentry-self-hosted-generic-metrics-consumer-1                      | Updating certificates in /etc/ssl/certs...
sentry-self-hosted-generic-metrics-consumer-1                      | 0 added, 0 removed; done.
sentry-self-hosted-generic-metrics-consumer-1                      | Running hooks in /etc/ca-certificates/update.d...
sentry-self-hosted-generic-metrics-consumer-1                      | done.
sentry-self-hosted-generic-metrics-consumer-1                      | Traceback (most recent call last):
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 288, in run
sentry-self-hosted-generic-metrics-consumer-1                      |     self._run_once()
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 355, in _run_once
sentry-self-hosted-generic-metrics-consumer-1                      |     self.__message = self.__consumer.poll(timeout=1.0)
sentry-self-hosted-generic-metrics-consumer-1                      |   File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 416, in poll
sentry-self-hosted-generic-metrics-consumer-1                      |     raise ConsumerError(str(error))
sentry-self-hosted-generic-metrics-consumer-1                      | arroyo.errors.ConsumerError: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: ingest-performance-metrics: Broker: Unknown topic or partition"}
sentry-self-hosted-generic-metrics-consumer-1                      | 07:59:53 [ERROR] arroyo.processing.processor: Caught exception, shutting down...
```
</details>
