### ISSUE TITLE
Upgrade issue when run ./scripts/restore.sh 

### ISSUE THREAD

**Issue by akshayoo007** [getsentry/self-hosted#2926]
### Self-Hosted Version

21.6.3

### CPU Architecture

x86_64

### Docker Version

26.0.0

### Docker Compose Version

2.25.0

### Steps to Reproduce

wget https://github.com/getsentry/self-hosted/archive/refs/tags/23.11.1.zip
unzip 23.11.1.zip
cd self-hosted-23.11.1 
./install.sh
docker compose uo -d
docker compose down
save backup.json in /sentry/backup.json
./scripts/resotre.sh

### Expected Result

Should migrate backup.json to Database 

### Actual Result

`Running hooks in /etc/ca-certificates/update.d...
done.
RpcImportError(
    kind: DeserializationFailed,
    on: InstanceID(model: 'sentry.user'),
    reason: The submitted JSON could not be deserialized into Django model instances
)
RpcImportError(
    kind: DeserializationFailed,
    on: InstanceID(model: 'sentry.user'),
    reason: The submitted JSON could not be deserialized into Django model instances
)
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 195, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/backup.py", line 637, in import_global
    import_in_global_scope(
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 446, in import_in_global_scope
    return _import(
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 329, in _import
    do_writes(pk_map)
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 305, in do_writes
    do_write(import_write_context, pk_map, model_name, json_data)
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 245, in do_write
    raise ImportingError(result)
sentry.backup.imports.ImportingError: is_err=True kind='DeserializationFailed' on=InstanceID(model='sentry.user', ordinal=None) left_pk=None right_pk=None reason='The submitted JSON could not be deserialized into Django model instances'
Error in scripts/_lib.sh:69.
'$dc run --rm -T web import global /etc/sentry/backup.json' exited with status 1
-> ./scripts/restore.sh:main:4
--> scripts/_lib.sh:restore:69`

**Comment by azaslavsky** [comment]
This script was basically nonfunctional on old versions, prior to 23.11.1. I'd recommend using the approach specified [here](https://develop.sentry.dev/self-hosted/backup/#full-backup) for your version instead. Conversely, you can upgrade to >=23.11.1, at which point *new* backups generated post-upgrade will be able to be restored properly (however, this backup, which was made using an old version, will still fail). Sorry, this wasn't a great experience before we revamped it in 23.11.1, so the options for old versions aren't great!
