### ISSUE TITLE
Errors on clean install

### ISSUE THREAD

**Issue by mrPsycho** [getsentry/self-hosted#2945]
### Self-Hosted Version

24.3.0

### CPU Architecture

x86_64

### Docker Version

26.0.0

### Docker Compose Version

2.25.0

### Steps to Reproduce

Follow https://develop.sentry.dev/self-hosted/

### Expected Result

No errors

### Actual Result

At some point this appears:
```
2024-04-08 16:29:15,914 Failed to create topic snuba-dead-letter-metrics
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/utils/manage_topics.py", line 31, in create_topics
    future.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=INVALID_CONFIG,val=40,str="Unknown topic config name: log.retention.minutes"}
2024-04-08 16:29:15,928 Failed to create topic snuba-dead-letter-generic-metrics
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/utils/manage_topics.py", line 31, in create_topics
    future.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=INVALID_CONFIG,val=40,str="Unknown topic config name: log.retention.minutes"}
2024-04-08 16:29:15,935 Failed to create topic snuba-dead-letter-replays
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/utils/manage_topics.py", line 31, in create_topics
    future.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=INVALID_CONFIG,val=40,str="Unknown topic config name: log.retention.minutes"}
2024-04-08 16:29:15,943 Failed to create topic snuba-dead-letter-querylog
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/utils/manage_topics.py", line 31, in create_topics
    future.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=INVALID_CONFIG,val=40,str="Unknown topic config name: log.retention.minutes"}
2024-04-08 16:29:15,949 Failed to create topic snuba-dead-letter-group-attributes
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/utils/manage_topics.py", line 31, in create_topics
    future.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
cimpl.KafkaException: KafkaError{code=INVALID_CONFIG,val=40,str="Unknown topic config name: log.retention.minutes"}
```

and then it looks like passed, but stil not expected

**Comment by mrPsycho** [comment]
ok. it may be due to low resources issue.
reinstalling works

**Comment by mrPsycho** [comment]
and additionally: 
on DO 4 shared cores and 8gb ram is not enough.
