### ISSUE TITLE
Not able to send invite emails

### ISSUE THREAD

**Issue by rohitdhas** [getsentry/self-hosted#3037]
### Self-Hosted Version

24.1.0

### CPU Architecture

x86_64

### Docker Version

26.1.1

### Docker Compose Version

v2.27.0

### Steps to Reproduce

We did a clean install and followed https://develop.sentry.dev/self-hosted/email/ this doc to setup outbound emails. We have hosted this on a linode server (16GB RAM and 8CPU). After this If I try to invite someone using email, I see a log saying the email is `queued` but not sent.

<img width="1001" alt="Screenshot 2024-05-10 at 4 39 16 PM" src="https://github.com/getsentry/self-hosted/assets/53969450/3110615b-9cdf-4d92-af01-44988dc10b99">

this is our mail server configuration in `config.yml`:
```
mail.host: 'smtp.sendgrid.net'
mail.port: 587
mail.username: 'sendgrid-username'
mail.password: 'sendgrid-password'
mail.use-tls: true
mail.backend: 'smtp'
mail.use-ssl: false
mail.from: 'sentry@bot.space'
mail.list-namespace: 'bot.space'
```

### Expected Result

An invite email should go through.

### Actual Result

Invite email is not being sent

**Comment by aldy505** [comment]
The mail would be queued from the `web` container, but it's actually sent from the `worker` container. Unless, you're executing it from the "send test email" button, then it's not queued and it's directly sent from the `web` container.

Your configuration looks right, have you check on the Sendgrid configuration itself that it's allowing the SMTP sending from some specific IP address or specific `from` sender?

**Comment by rohitdhas** [comment]
just checked `sentry-self-hosted-worker-1` container logs and I found these errors:

```
14:02:58 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[378f2c44-c2dc-4139-99d9-c15a6d6735cb] raised unexpected: SMTPServerDisconnected('Connection unexpectedly closed') (data={'hostname': 'celery@6b73afd5201f', 'id': '378f2c44-c2dc-4139-99d9-c15a6d6735cb', 'name': 'sentry.tasks.email.send_email', 'exc': "SMTPServerDisconnected('Connection unexpectedly closed')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 306, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 115, in reraise\n    raise value\n  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 301, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/sentry/silo/base.py", line 145, in override\n    return original_method(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/sentry/tasks/base.py", line 117, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/sentry/tasks/email.py", line 55, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.10/site-packages/sentry/utils/email/send.py", line 17, in send_messages\n    sent = connection.send_messages(messages)\n  File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 69, in open\n    self.connection.login(self.username, self.password)\n  File "/usr/local/lib/python3.10/smtplib.py", line 739, in login\n    (code, resp) = self.auth(\n  File "/usr/local/lib/python3.10/smtplib.py", line 642, in auth\n    (code, resp) = self.docmd("AUTH", mechanism + " " + response)\n  File "/usr/local/lib/python3.10/smtplib.py", line 432, in docmd\n    return self.getreply()\n  File "/usr/local/lib/python3.10/smtplib.py", line 405, in getreply\n    raise SMTPServerDisconnected("Connection unexpectedly closed")\nsmtplib.SMTPServerDisconnected: Connection unexpectedly closed\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f5f9a62f8e0>, '__start_time': 1715349778.017939}", 'description': 'raised unexpected', 'internal': False})
  File "/usr/local/lib/python3.10/site-packages/sentry/tasks/email.py", line 55, in send_email
  File "/usr/local/lib/python3.10/site-packages/sentry/utils/email/send.py", line 17, in send_messages
  File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
  File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 69, in open
12:22:38 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[62a66b70-96b7-4b6c-ba01-dc5681b1e594] raised unexpected: SMTPServerDisconnected('Connection unexpectedly closed') (data={'hostname': 'celery@6b73afd5201f', 'id': '62a66b70-96b7-4b6c-ba01-dc5681b1e594', 'name': 'sentry.tasks.email.send_email', 'exc': "SMTPServerDisconnected('Connection unexpectedly closed')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 306, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 115, in reraise\n    raise value\n  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 301, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/sentry/silo/base.py", line 145, in override\n    return original_method(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/sentry/tasks/base.py", line 117, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/sentry/tasks/email.py", line 55, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.10/site-packages/sentry/utils/email/send.py", line 17, in send_messages\n    sent = connection.send_messages(messages)\n  File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 69, in open\n    self.connection.login(self.username, self.password)\n  File "/usr/local/lib/python3.10/smtplib.py", line 739, in login\n    (code, resp) = self.auth(\n  File "/usr/local/lib/python3.10/smtplib.py", line 642, in auth\n    (code, resp) = self.docmd("AUTH", mechanism + " " + response)\n  File "/usr/local/lib/python3.10/smtplib.py", line 432, in docmd\n    return self.getreply()\n  File "/usr/local/lib/python3.10/smtplib.py", line 405, in getreply\n    raise SMTPServerDisconnected("Connection unexpectedly closed")\nsmtplib.SMTPServerDisconnected: Connection unexpectedly closed\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f5f8b47d4e0>, '__start_time': 1715430158.554215}", 'description': 'raised unexpected', 'internal': False})
```

**Comment by hubertdeng123** [comment]
As @aldy505 has mentioned above, have you checked the Sendgrid configuration itself?

**Comment by hubertdeng123** [comment]
Is your self-hosted instance TLS/SSL encrypted? Running out of ideas here...
