### ISSUE TITLE
Kafka and snuba error after upgrade to 24.5.0

### ISSUE THREAD

**Issue by K-Jean** [getsentry/self-hosted#3045]
### Self-Hosted Version

24.5.0.dev0

### CPU Architecture

x86_64

### Docker Version

25.0.3

### Docker Compose Version

2.0.1

### Steps to Reproduce

Launch ./install.sh everything went fine, but after running `docker compose up -d` kafka has an error and all snuba process is restarting. clickhouse has also some warnings but I don't know if this is linked.

### Expected Result

No error in snuba / kafka / clickhouse

### Actual Result

kafka logs 

```
sentry-self-hosted-kafka-1  | ===> User
sentry-self-hosted-kafka-1  | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
sentry-self-hosted-kafka-1  | ===> Configuring ...
sentry-self-hosted-kafka-1  | Running in Zookeeper mode...
sentry-self-hosted-kafka-1  | ===> Running preflight checks ... 
sentry-self-hosted-kafka-1  | ===> Check if /var/lib/kafka/data is writable ...
sentry-self-hosted-kafka-1  | ===> Check if Zookeeper is healthy ...
sentry-self-hosted-kafka-1  | Using log4j config /etc/kafka/log4j.properties
sentry-self-hosted-kafka-1  | ===> Launching ... 
sentry-self-hosted-kafka-1  | ===> Launching kafka ... 
sentry-self-hosted-kafka-1  | [2024-05-11 22:28:42,652] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
sentry-self-hosted-kafka-1  | [2024-05-11 22:28:43,453] INFO Starting the log cleaner (kafka.log.LogCleaner)
sentry-self-hosted-kafka-1  | [2024-05-11 22:28:43,672] INFO Updated connection-accept-rate max connection creation rate to 2147483647 (kafka.network.ConnectionQuotas)
sentry-self-hosted-kafka-1  | [2024-05-11 22:28:43,684] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1001] Created data-plane acceptor and processors for endpoint : ListenerName(PLAINTEXT) (kafka.network.SocketServer)
sentry-self-hosted-kafka-1  | [2024-05-11 22:28:43,737] INFO Creating /brokers/ids/1001 (is it secure? false) (kafka.zk.KafkaZkClient)
sentry-self-hosted-kafka-1  | [2024-05-11 22:28:43,751] INFO Stat of the created znode at /brokers/ids/1001 is: 363,363,1715466523745,1715466523745,1,0,0,72738539869634561,194,0,363
sentry-self-hosted-kafka-1  |  (kafka.zk.KafkaZkClient)
sentry-self-hosted-kafka-1  | [2024-05-11 22:28:43,752] INFO Registered broker 1001 at path /brokers/ids/1001 with addresses: PLAINTEXT://kafka:9092, czxid (broker epoch): 363 (kafka.zk.KafkaZkClient)
sentry-self-hosted-kafka-1  | [2024-05-11 22:28:43,889] INFO [/config/changes-event-process-thread]: Starting (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
sentry-self-hosted-kafka-1  | [2024-05-11 22:28:43,899] WARN [Controller id=1001, targetBrokerId=1001] Connection to node 1001 (kafka/172.19.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
sentry-self-hosted-kafka-1  | [2024-05-11 22:28:43,900] WARN [RequestSendThread controllerId=1001] Controller 1001's connection to broker kafka:9092 (id: 1001 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
sentry-self-hosted-kafka-1  | java.io.IOException: Connection to kafka:9092 (id: 1001 rack: null) failed.
sentry-self-hosted-kafka-1  | 	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
sentry-self-hosted-kafka-1  | 	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:298)
sentry-self-hosted-kafka-1  | 	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:251)
sentry-self-hosted-kafka-1  | 	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:130)
sentry-self-hosted-kafka-1  | [2024-05-11 22:28:43,944] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1001] Enabling request processing. (kafka.network.SocketServer)
sentry-self-hosted-kafka-1  | [2024-05-11 22:28:43,946] INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.DataPlaneAcceptor)
sentry-self-hosted-kafka-1  | [2024-05-11 22:30:01,520] INFO Creating topic monitors-clock-tick with configuration {} and initial partition assignment HashMap(0 -> ArrayBuffer(1001)) (kafka.zk.AdminZkClient)
```

One snuba logs : 
```
sentry-self-hosted-snuba-generic-metrics-sets-consumer-1  | Error: No such option: --no-skip-write
sentry-self-hosted-snuba-generic-metrics-sets-consumer-1  | 2024-05-11 22:31:05,083 Initializing Snuba...
sentry-self-hosted-snuba-generic-metrics-sets-consumer-1  | 2024-05-11 22:31:06,934 Snuba initialization took 1.8511952236294746s
sentry-self-hosted-snuba-generic-metrics-sets-consumer-1  | 2024-05-11 22:31:07,342 Initializing Snuba...
sentry-self-hosted-snuba-generic-metrics-sets-consumer-1  | 2024-05-11 22:31:09,178 Snuba initialization took 1.8370566610246897s
sentry-self-hosted-snuba-generic-metrics-sets-consumer-1  | Usage: snuba rust-consumer [OPTIONS]
sentry-self-hosted-snuba-generic-metrics-sets-consumer-1  | Try 'snuba rust-consumer --help' for help.
```

clickhouse : 
```
sentry-self-hosted-clickhouse-1  | 2024.05.11 20:34:38.640331 [ 1 ] {} <Warning> Application: Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.8.11.29.altinitystable (altinity build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
sentry-self-hosted-clickhouse-1  | 2024.05.11 20:34:38.658626 [ 1 ] {} <Warning> Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.8.11.29.altinitystable (altinity build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
sentry-self-hosted-clickhouse-1  | 2024.05.11 20:34:38.658735 [ 1 ] {} <Warning> Application: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.8.11.29.altinitystable (altinity build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
sentry-self-hosted-clickhouse-1  | 2024.05.11 20:34:38.658820 [ 1 ] {} <Warning> Application: Listen [::]:9004 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.8.11.29.altinitystable (altinity build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
sentry-self-hosted-clickhouse-1  | 2024.05.11 20:34:38.658897 [ 1 ] {} <Warning> Application: Listen [::]:9005 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.8.11.29.altinitystable (altinity build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
```

**Comment by hubertdeng123** [comment]
This should now be fixed here: https://github.com/getsentry/self-hosted/pull/3041
