### ISSUE TITLE
Active Directory SAML Login Stopped Working

### ISSUE THREAD

**Issue by edgariscoding** [getsentry/self-hosted#3066]
### Self-Hosted Version

24.4.2

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

Sentry had been working fine for the past couple of weeks. 
SAML with AD has been working flawlessly.

Today, when I attempted to access the Sentry site I was presented with the login page which asks me to log in with Active Directory.

I clicked the "Login with Active Directory" button, which redirected me to the Microsoft AD login page, it successfully authenticated and then redirected me back to Sentry.

### Expected Result

Normally when the redirect happens i'm able to successfully access the Sentry dashboard.

### Actual Result

This time it failed and this is what was displayed in Sentry:

![image](https://github.com/getsentry/self-hosted/assets/12093243/3d89f895-5eba-45bb-bc43-817572287a94)

How can i figure out what the issue is?

Running `docker compose logs` results in a LOT of logs. How can i filter these logs so i can share something useful and relevant?

I was able to find this, is this related?

```
sentry-self-hosted-web-1  | 10:19:01 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.18.0.45' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.013975143432617188 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
```

```
sentry-self-hosted-web-1  | 13:43:44 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.18.0.45' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.015113115310668945 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-web-1  | Traceback (most recent call last):
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.11/site-packages/sentry/utils/metrics.py", line 86, in worker
sentry-self-hosted-web-1  |     tsdb.backend.incr(TSDBModel.internal, full_key, count=amount)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.11/site-packages/sentry/tsdb/redissnuba.py", line 89, in method
sentry-self-hosted-web-1  |     return getattr(self.backends[backend], key)(*a, **kw)
sentry-self-hosted-web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.11/site-packages/sentry/tsdb/redis.py", line 236, in incr
sentry-self-hosted-web-1  |     self.incr_multi([(model, key)], timestamp, count, environment_id)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.11/site-packages/sentry/tsdb/redis.py", line 269, in incr_multi
sentry-self-hosted-web-1  |     with manager as client:
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.11/site-packages/rb/clients.py", line 637, in __exit__
sentry-self-hosted-web-1  |     self.mapping_client.join(timeout=timeout)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.11/site-packages/rb/clients.py", line 418, in join
sentry-self-hosted-web-1  |     command_buffer.wait_for_responses(self)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.11/site-packages/rb/clients.py", line 229, in wait_for_responses
sentry-self-hosted-web-1  |     value = client.parse_response(self.connection, command_name, **options)
sentry-self-hosted-web-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 892, in parse_response
sentry-self-hosted-web-1  |     response = connection.read_response()
sentry-self-hosted-web-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 752, in read_response
sentry-self-hosted-web-1  |     raise response
sentry-self-hosted-web-1  | redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

**Comment by azaslavsky** [comment]
Can you try increasing the `maxmemory` setting for your redis config? This may alleviate the problem.

**Comment by edgariscoding** [comment]
Issue was due to sentry-postgres maxing out the storage on the virtual machine. Had to truncate a Postgres table to make more space until we figure out why space is maxing out.
