### ISSUE TITLE
huge problem with sentry replay

### ISSUE THREAD

**Issue by qkfrksvl** [getsentry/self-hosted#3082]
### Self-Hosted Version

24.5.0

### CPU Architecture

x86_64

### Docker Version

k8s

### Docker Compose Version

k8s

### Steps to Reproduce

after upgrade sentry 24.5.0 (either 24.4.2), sentry replays menu shown the error.

### Expected Result

sentry replay data shown.

### Actual Result

![image (4)](https://github.com/getsentry/self-hosted/assets/86870268/0da9eeb6-04a0-4680-9e77-be9971640fd8)
![image (5)](https://github.com/getsentry/self-hosted/assets/86870268/cba5dad5-c5ab-4ff9-b340-684012fa31b4)
![image (6)](https://github.com/getsentry/self-hosted/assets/86870268/b70eef4b-74b7-4310-b065-d6438c796f2b)
![image (7)](https://github.com/getsentry/self-hosted/assets/86870268/ee88053b-d373-488f-b1c8-0726f0a9aa42)

sentry-web logs shown below
```
  File "/usr/local/lib/python3.11/site-packages/sentry/utils/snuba.py", line 1036, in _bulk_snuba_query
    raise clickhouse_error_codes_map.get(error["code"], QueryExecutionError)(
sentry.utils.snuba.QueryMissingColumn: DB::Exception: Unknown expression identifier '_snuba_error_id_no_dashes' in scope error_id_no_dashes -> _snuba_error_id_no_dashes. Maybe you meant: ['error_id_no_dashes']. Stack trace:
```

**Comment by qkfrksvl** [comment]
```
07:09:14 [ERROR] django.request: Internal Server Error: /api/0/organizations/sentry/replays/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/sentry/replays/?fields=activity&fields=browser&fields=count_dead_clicks&fields=count_errors&fields=count_rage_clicks&fields=duration&fields=finished_at&fields=has_viewed&fields=id&fields=is_archived&fields=os&fields=project_id&fields=started_at&fields=user&per_page=50&project=1&query=dead.selector%3A%22button%5Brole%3D%5C%22%5C%22%5D%5Baria-label%3D%5C%22%5C%22%5D%5Bdata-test-id%3D%5C%22%5C%22%5D%5Balt%3D%5C%22%5C%22%5D%5Btitle%3D%5C%22%5C%22%5D%5Bdata-sentry-component%3D%5C%22%5C%22%5D%22&queryReferrer=replayList&sort=-started_at'>)
07:09:15 [INFO] sentry.superuser: superuser.request (url='http://sentry-infra.tossinvest.bz/api/0/organizations/sentry/replays/c7bba4c98c18412cb685b7f73526da9b/' method='GET' ip_address='172.16.100.10' user_id=1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/snuba/referrer.py", line 875, in validate_referrer
    raise Exception(error_message)
Exception: referrer replays.query.details_query is not part of Referrer Enum
07:09:15 [WARNING] sentry.snuba.referrer: referrer replays.query.details_query is not part of Referrer Enum
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/api/base.py", line 306, in handle_exception
    response = super().handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/sentry/api/base.py", line 439, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/replays/endpoints/organization_replay_details.py", line 73, in get
    snuba_response = query_replay_instance(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/replays/query.py", line 91, in query_replay_instance
    return execute_query(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/replays/usecases/query/__init__.py", line 329, in execute_query
    return raw_snql_query(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/utils/snuba.py", line 860, in raw_snql_query
    return bulk_snuba_queries([request], referrer, use_cache)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/utils/snuba.py", line 884, in bulk_snuba_queries
    return _apply_cache_and_build_results(params, referrer=referrer, use_cache=use_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/utils/snuba.py", line 947, in _apply_cache_and_build_results
    query_results = _bulk_snuba_query([item[1] for item in to_query], headers)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/utils/snuba.py", line 1036, in _bulk_snuba_query
    raise clickhouse_error_codes_map.get(error["code"], QueryExecutionError)(
sentry.utils.snuba.QueryMissingColumn: DB::Exception: Unknown expression identifier '_snuba_error_id_no_dashes' in scope error_id_no_dashes -> _snuba_error_id_no_dashes. Maybe you meant: ['error_id_no_dashes']. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c9a449b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000780b9ac
2. DB::(anonymous namespace)::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&, bool, bool) @ 0x0000000010a87c5a
3. DB::(anonymous namespace)::QueryAnalyzer::resolveLambda(std::shared_ptr<DB::IQueryTreeNode> const&, std::shared_ptr<DB::IQueryTreeNode> const&, std::vector<std::shared_ptr<DB::IQueryTreeNode>, std::allocator<std::shared_ptr<DB::IQueryTreeNode>>> const&, DB::(anonymous namespace)::IdentifierResolveScope&) @ 0x0000000010aaa12f
4. DB::(anonymous namespace)::QueryAnalyzer::resolveFunction(std::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&) @ 0x0000000010aa1245
5. DB::(anonymous namespace)::QueryAnalyzer::resolveExpressionNode(std::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&, bool, bool) @ 0x0000000010a841bc
6. DB::(anonymous namespace)::QueryAnalyzer::resolveExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&, bool, bool) @ 0x0000000010a831ed
7. DB::(anonymous namespace)::QueryAnalyzer::resolveProjectionExpressionNodeList(std::shared_ptr<DB::IQueryTreeNode>&, DB::(anonymous namespace)::IdentifierResolveScope&) @ 0x0000000010a8e4e7
8. DB::(anonymous namespace)::QueryAnalyzer::resolveQuery(std::shared_ptr<DB::IQueryTreeNode> const&, DB::(anonymous namespace)::IdentifierResolveScope&) @ 0x0000000010a7a5f8
9. DB::QueryAnalysisPass::run(std::shared_ptr<DB::IQueryTreeNode>&, std::shared_ptr<DB::Context const>) @ 0x0000000010a780c5
10. DB::QueryTreePassManager::run(std::shared_ptr<DB::IQueryTreeNode>) @ 0x0000000010a76983
11. DB::(anonymous namespace)::buildQueryTreeAndRunPasses(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&) (.llvm.9862110563685019565) @ 0x0000000010d0aafd
12. DB::InterpreterSelectQueryAnalyzer::InterpreterSelectQueryAnalyzer(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, DB::SelectQueryOptions const&) @ 0x0000000010d09899
13. std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> std::__function::__policy_invoker<std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>::__call_impl<std::__function::__default_alloc_func<DB::registerInterpreterSelectQueryAnalyzer(DB::InterpreterFactory&)::$_0, std::unique_ptr<DB::IInterpreter, std::default_delete<DB::IInterpreter>> (DB::InterpreterFactory::Arguments const&)>>(std::__function::__policy_storage const*, DB::InterpreterFactory::Arguments const&) (.llvm.9862110563685019565) @ 0x0000000010d0c86c
14. DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x0000000010c9ec79
15. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001111a030
16. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000111169ba
17. DB::TCPHandler::runImpl() @ 0x00000000122a59c4
18. DB::TCPHandler::run() @ 0x00000000122c1fb9
19. Poco::Net::TCPServerConnection::start() @ 0x0000000014c105b2
20. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014c113f9
21. Poco::PooledThread::run() @ 0x0000000014d09a61
22. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014d07ffd
23. ? @ 0x00007fd7e8946134
24. ? @ 0x00007fd7e89c5a40




07:09:11 [ERROR] django.request: Internal Server Error: /api/0/organizations/sentry/replays/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/sentry/replays/?fields=activity&fields=browser&fields=count_dead_clicks&fields=count_errors&fields=count_rage_clicks&fields=duration&fields=finished_at&fields=has_viewed&fields=id&fields=is_archived&fields=os&fields=project_id&fields=started_at&fields=user&per_page=50&project=1&query=dead.selector%3A%22button%5Brole%3D%5C%22%5C%22%5D%5Baria-label%3D%5C%22%5C%22%5D%5Bdata-test-id%3D%5C%22%5C%22%5D%5Balt%3D%5C%22%5C%22%5D%5Btitle%3D%5C%22%5C%22%5D%5Bdata-sentry-component%3D%5C%22%5C%22%5D%22&queryReferrer=replayList&sort=-started_at'>)
07:09:13 [INFO] sentry.superuser: superuser.request (url='http://sentry-infra.tossinvest.bz/api/0/organizations/sentry/replays/?fields=activity&fields=browser&fields=count_dead_clicks&fields=count_errors&fields=count_rage_clicks&fields=duration&fields=finished_at&fields=has_viewed&fields=id&fields=is_archived&fields=os&fields=project_id&fields=started_at&fields=user&per_page=50&project=1&query=dead.selector%3A%22button%5Brole%3D%5C%22%5C%22%5D%5Baria-label%3D%5C%22%5C%22%5D%5Bdata-test-id%3D%5C%22%5C%22%5D%5Balt%3D%5C%22%5C%22%5D%5Btitle%3D%5C%22%5C%22%5D%5Bdata-sentry-component%3D%5C%22%5C%22%5D%22&queryReferrer=replayList&sort=-started_at' method='GET' ip_address='172.16.100.10' user_id=1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/snuba/referrer.py", line 875, in validate_referrer
    raise Exception(error_message)
Exception: referrer replays.query.browse_aggregated_conditions_subquery is not part of Referrer Enum
07:09:13 [WARNING] sentry.snuba.referrer: referrer replays.query.browse_aggregated_conditions_subquery is not part of Referrer Enum
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/snuba/referrer.py", line 875, in validate_referrer
    raise Exception(error_message)
Exception: referrer replays.query.browse_query is not part of Referrer Enum
```

**Comment by hubertdeng123** [comment]
It looks like you are not using a supported version of self-hosted Sentry as you're using k8s. Unfortunately we won't be able to help you any further here and you'll have more luck filing in the repo of the setup you're using.
