### ISSUE TITLE
Redis "missing flush" blocks event ingestion

### ISSUE THREAD

**Issue by zifeo** [getsentry/self-hosted#3102]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Deploy Sentry using https://github.com/sentry-kubernetes/charts, pretty standard. We have been running it quite successfully and wanted to reset the whole installation (same configuration/setup).

### How are you getting stuck?

No event get recorded ever and the following keeps happening in the worker:

```
sentry-worker-d5db47bf8-8wx4r sentry-worker Traceback (most recent call last):
sentry-worker-d5db47bf8-8wx4r sentry-worker   File "/usr/local/lib/python3.11/site-packages/sentry/buffer/redis.py", line 74, in callback
sentry-worker-d5db47bf8-8wx4r sentry-worker     callback = self._registry[buffer_hook_event]
sentry-worker-d5db47bf8-8wx4r sentry-worker                ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
sentry-worker-d5db47bf8-8wx4r sentry-worker KeyError: <BufferHookEvent.FLUSH: 'flush'>
sentry-worker-d5db47bf8-8wx4r sentry-worker 18:02:00 [ERROR] sentry.buffer.redis: buffer_hook_event.missing
sentry-worker-d5db47bf8-8wx4r sentry-worker Traceback (most recent call last):
sentry-worker-d5db47bf8-8wx4r sentry-worker   File "/usr/local/lib/python3.11/site-packages/sentry/buffer/redis.py", line 313, in process_batch
sentry-worker-d5db47bf8-8wx4r sentry-worker     redis_buffer_registry.callback(BufferHookEvent.FLUSH, self)
sentry-worker-d5db47bf8-8wx4r sentry-worker   File "/usr/local/lib/python3.11/site-packages/sentry/buffer/redis.py", line 78, in callback
sentry-worker-d5db47bf8-8wx4r sentry-worker     return callback(data)
sentry-worker-d5db47bf8-8wx4r sentry-worker            ^^^^^^^^
sentry-worker-d5db47bf8-8wx4r sentry-worker UnboundLocalError: cannot access local variable 'callback' where it is not associated with a value
sentry-worker-d5db47bf8-8wx4r sentry-worker 18:02:00 [ERROR] sentry.buffer.redis: process_batch.error
```

Can you clarify what exactly happens with that `_registry`? I tried digging inside but it seems quite unexpected. How can enable more advanced logging?

### Where in the product are you?

Other

### Version

24.5.0

**Comment by azaslavsky** [comment]
We explicitly don't support k8s setups in this repository, only docker-compose. You are welcome to ask in the referenced repository for help with this unsupported workflow.

**Comment by serrrios** [comment]
Why? Is this a problem within the components?

**Comment by azaslavsky** [comment]
Because it isn't part of the product we release. Similar to how if you modify your car with aftermarket parts, the manufacturer might be hesitant to work on it.

We're a small team, and we already have our hands full maintaining docker-compose based installs, which are generally much simpler than k8s. Further, the explicit goal of this repository is to provide a bootstrap for relatively small Sentry installations. If you find yourself needing the cluster-management-level tooling provided by k8s, you're probably operating at a scale much larger than what this open source configuration is intended to support.

You're welcome to attempt to go that route on your own (the source is all available, after all), or via third party repositories like the one you referenced, but it is outside the scope of what we are reasonably able to support here.

**Comment by zifeo** [comment]
@azaslavsky The issue was open on the main Sentry repo (because the issue looks to be inside the internals) and transferred to that repo. Can you then transfer it where it should belong?

**Comment by azaslavsky** [comment]
sentry-kubernetes is an unaffiliated organization/user, so I can't transfer issues into their `charts` repository. You can re-open the issue there if you'd like.

It is difficult to deduce whether the issue is caused by how redis is configured in k8s or not, but since @ceorourke added the line being referenced here, I'll loop her in.

**Comment by zifeo** [comment]
@azaslavsky Thanks for pointing that out, I always believed that it was officially maintained... Curious to hear indeed more about that specific change.

**Comment by laygir** [comment]
I think I'm having the same issue using using docker compose with 24.5.0

This is my first time trying Sentry as self hosted, bumping into bunch of other issues, so not really sure if I have everything operating properly.

[sentry-self-hosted-worker-1.log](https://github.com/user-attachments/files/15680884/sentry-self-hosted-worker-1.log)

Could we reopen this issue?

**Comment by ceorourke** [comment]
Hello, I work on the product side and don't know a ton about running self hosted (besides developing on it) or running Docker, but I've since fixed the issue as far as I can tell (about 2 weeks ago), so perhaps this is in an outdated version or we haven't yet released a new version with the fix?

**Comment by azaslavsky** [comment]
@laygir 24.5.1 was released 2 days ago, and should include @ceorourke 's fix. Would be amenable to upgrading your Sentry install to see if it fixes things?

**Comment by laygir** [comment]
@azaslavsky I removed all images, containers, volumes, networks to start fresh and worker appears to be better now 🥳

I'm sorry in advance for dumping these logs here, let me know if I should create a different issue, just sharing so you can evaluate severity/necessity.

There are some exceptions and errors here and there. Worker also has some errors but I think that's due to not yet configured smtp `[ERROR] celery.app.trace: Task sentry.tasks.email.send_email`

Let me know if I'm missing some additional basic config or any other log. I'll continue testing this and report back if something unusual happens. For example with 24.5.0 "issue alerts" were not being populated, with 24.5.1 that's fine now, or fresh docker solved that.. 🤷‍♂️ 

Kafka (Same as 24.5.0)

```js
===> Launching ... 
===> Launching kafka ... 
[2024-06-06 23:11:21,983] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2024-06-06 23:11:23,702] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2024-06-06 23:11:24,362] INFO Updated connection-accept-rate max connection creation rate to 2147483647 (kafka.network.ConnectionQuotas)
[2024-06-06 23:11:24,383] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1001] Created data-plane acceptor and processors for endpoint : ListenerName(PLAINTEXT) (kafka.network.SocketServer)
[2024-06-06 23:11:24,497] INFO Creating /brokers/ids/1001 (is it secure? false) (kafka.zk.KafkaZkClient)
[2024-06-06 23:11:24,551] INFO Stat of the created znode at /brokers/ids/1001 is: 381,381,1717715484542,1717715484542,1,0,0,72082200696127489,194,0,381
 (kafka.zk.KafkaZkClient)
[2024-06-06 23:11:24,552] INFO Registered broker 1001 at path /brokers/ids/1001 with addresses: PLAINTEXT://kafka:9092, czxid (broker epoch): 381 (kafka.zk.KafkaZkClient)
[2024-06-06 23:11:24,842] INFO [/config/changes-event-process-thread]: Starting (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
[2024-06-06 23:11:24,949] WARN [Controller id=1001, targetBrokerId=1001] Connection to node 1001 (kafka/172.27.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-06-06 23:11:24,951] WARN [RequestSendThread controllerId=1001] Controller 1001's connection to broker kafka:9092 (id: 1001 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.io.IOException: Connection to kafka:9092 (id: 1001 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:298)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:251)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:130)
[2024-06-06 23:11:25,058] WARN [Controller id=1001, targetBrokerId=1001] Connection to node 1001 (kafka/172.27.0.2:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-06-06 23:11:25,058] WARN [RequestSendThread controllerId=1001] Controller 1001's connection to broker kafka:9092 (id: 1001 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.io.IOException: Connection to kafka:9092 (id: 1001 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:298)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:251)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:130)
[2024-06-06 23:11:25,065] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1001] Enabling request processing. (kafka.network.SocketServer)
[2024-06-06 23:11:25,069] INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.DataPlaneAcceptor)
```

ClickHouse (Same as 24.5.0, there is also IPv6 error but that goes away if I add `<listen_host>0.0.0.0</listen_host>` in config.xml)

```js
2024.06.06 22:54:36.657301 [ 48 ] {2f87800b-cb6a-45e4-a647-aace8e46fed0} <Error> TCPHandler: Code: 60. DB::Exception: Table default.migrations_local does not exist. (UNKNOWN_TABLE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c61ff37 in /usr/bin/clickhouse
1. DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x0000000007132547 in /usr/bin/clickhouse
2. DB::IDatabase::getTable(String const&, std::shared_ptr<DB::Context const>) const @ 0x00000000114add99 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::shared_ptr<DB::Context const>, std::optional<DB::Exception>*) const @ 0x00000000116dcf68 in /usr/bin/clickhouse
4. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::shared_ptr<DB::Context const>) const @ 0x00000000116e6709 in /usr/bin/clickhouse
5. DB::JoinedTables::getLeftTableStorage() @ 0x0000000011fb8c34 in /usr/bin/clickhouse
6. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x0000000011ec18c3 in /usr/bin/clickhouse
7. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x0000000011f74948 in /usr/bin/clickhouse
8. DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x0000000011e7b91e in /usr/bin/clickhouse
9. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000122bf58a in /usr/bin/clickhouse
10. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x00000000122bb5b5 in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x0000000013137519 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x00000000131498f9 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x0000000015b42834 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015b43a31 in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x0000000015c7a667 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015c7893c in /usr/bin/clickhouse
17. ? @ 0x000074a7ca95f609 in ?
18. ? @ 0x000074a7ca884353 in ?
```

Postgres

```js
PostgreSQL init process complete; ready for start up.

2024-06-06 22:55:18.091 UTC [1] LOG:  starting PostgreSQL 14.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
2024-06-06 22:55:18.091 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-06-06 22:55:18.091 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-06-06 22:55:18.093 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-06-06 22:55:18.096 UTC [66] LOG:  database system was shut down at 2024-06-06 22:55:17 UTC
2024-06-06 22:55:18.102 UTC [1] LOG:  database system is ready to accept connections
2024-06-06 22:55:54.591 UTC [87] ERROR:  relation "sentry_option" does not exist at character 149
2024-06-06 22:55:54.591 UTC [87] STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."last_updated", "sentry_option"."last_updated_by", "sentry_option"."value" FROM "sentry_option" WHERE "sentry_option"."key" = 'github.apps-install-url' LIMIT 21
2024-06-06 22:55:54.699 UTC [87] ERROR:  relation "sentry_option" does not exist at character 149
2024-06-06 22:55:54.699 UTC [87] STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."last_updated", "sentry_option"."last_updated_by", "sentry_option"."value" FROM "sentry_option" WHERE "sentry_option"."key" = 'github-enterprise-app.alert-rule-action' LIMIT 21
2024-06-06 22:55:54.796 UTC [87] ERROR:  relation "sentry_option" does not exist at character 149
2024-06-06 22:55:54.796 UTC [87] STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."last_updated", "sentry_option"."last_updated_by", "sentry_option"."value" FROM "sentry_option" WHERE "sentry_option"."key" = 'vercel.integration-slug' LIMIT 21
2024-06-06 22:55:54.821 UTC [87] ERROR:  relation "sentry_option" does not exist at character 149
2024-06-06 22:55:54.821 UTC [87] STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."last_updated", "sentry_option"."last_updated_by", "sentry_option"."value" FROM "sentry_option" WHERE "sentry_option"."key" = 'msteams.app-id' LIMIT 21
2024-06-06 22:55:54.888 UTC [87] ERROR:  relation "sentry_option" does not exist at character 149
2024-06-06 22:55:54.888 UTC [87] STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."last_updated", "sentry_option"."last_updated_by", "sentry_option"."value" FROM "sentry_option" WHERE "sentry_option"."key" = 'discord.application-id' LIMIT 21
2024-06-06 22:55:54.891 UTC [87] ERROR:  relation "sentry_option" does not exist at character 149
2024-06-06 22:55:54.891 UTC [87] STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."last_updated", "sentry_option"."last_updated_by", "sentry_option"."value" FROM "sentry_option" WHERE "sentry_option"."key" = 'discord.public-key' LIMIT 21
2024-06-06 22:55:54.893 UTC [87] ERROR:  relation "sentry_option" does not exist at character 149
2024-06-06 22:55:54.893 UTC [87] STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."last_updated", "sentry_option"."last_updated_by", "sentry_option"."value" FROM "sentry_option" WHERE "sentry_option"."key" = 'discord.bot-token' LIMIT 21
2024-06-06 22:55:54.896 UTC [87] ERROR:  relation "sentry_option" does not exist at character 149
2024-06-06 22:55:54.896 UTC [87] STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."last_updated", "sentry_option"."last_updated_by", "sentry_option"."value" FROM "sentry_option" WHERE "sentry_option"."key" = 'discord.client-secret' LIMIT 21
2024-06-06 22:55:54.899 UTC [87] ERROR:  relation "sentry_projectkey" does not exist at character 403
2024-06-06 22:55:54.899 UTC [87] STATEMENT:  SELECT "sentry_projectkey"."id", "sentry_projectkey"."project_id", "sentry_projectkey"."label", "sentry_projectkey"."public_key", "sentry_projectkey"."secret_key", "sentry_projectkey"."roles", "sentry_projectkey"."status", "sentry_projectkey"."date_added", "sentry_projectkey"."rate_limit_count", "sentry_projectkey"."rate_limit_window", "sentry_projectkey"."data", "sentry_projectkey"."use_case" FROM "sentry_projectkey" WHERE ("sentry_projectkey"."project_id" = 1 AND "sentry_projectkey"."roles" = ("sentry_projectkey"."roles" | 1) AND "sentry_projectkey"."status" = 0) ORDER BY "sentry_projectkey"."id" ASC LIMIT 1
2024-06-06 22:55:54.906 UTC [87] ERROR:  relation "sentry_option" does not exist at character 149
2024-06-06 22:55:54.906 UTC [87] STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."last_updated", "sentry_option"."last_updated_by", "sentry_option"."value" FROM "sentry_option" WHERE "sentry_option"."key" = 'delightful_metrics.enable_code_locations' LIMIT 21
2024-06-06 22:56:07.741 UTC [88] ERROR:  relation "sentry_projectkey" does not exist at character 403
2024-06-06 22:56:07.741 UTC [88] STATEMENT:  SELECT "sentry_projectkey"."id", "sentry_projectkey"."project_id", "sentry_projectkey"."label", "sentry_projectkey"."public_key", "sentry_projectkey"."secret_key", "sentry_projectkey"."roles", "sentry_projectkey"."status", "sentry_projectkey"."date_added", "sentry_projectkey"."rate_limit_count", "sentry_projectkey"."rate_limit_window", "sentry_projectkey"."data", "sentry_projectkey"."use_case" FROM "sentry_projectkey" WHERE ("sentry_projectkey"."project_id" = 1 AND "sentry_projectkey"."roles" = ("sentry_projectkey"."roles" | 1) AND "sentry_projectkey"."status" = 0) ORDER BY "sentry_projectkey"."id" ASC LIMIT 1
2024-06-06 22:56:07.819 UTC [88] ERROR:  relation "django_migrations" does not exist at character 22
2024-06-06 22:56:07.819 UTC [88] STATEMENT:  SELECT COUNT(*) FROM django_migrations
2024-06-06 23:09:20.649 UTC [1] LOG:  received fast shutdown request
2024-06-06 23:09:20.650 UTC [1] LOG:  aborting any active transactions
2024-06-06 23:09:20.655 UTC [1] LOG:  background worker "logical replication launcher" (PID 72) exited with exit code 1
2024-06-06 23:09:20.667 UTC [67] LOG:  shutting down
2024-06-06 23:09:20.701 UTC [1] LOG:  database system is shut down
Setting up Change Data Capture
Replication config already present in pg_hba. Not changing anything.

PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-06-06 23:10:44.387 UTC [1] LOG:  starting PostgreSQL 14.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
2024-06-06 23:10:44.387 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-06-06 23:10:44.387 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-06-06 23:10:44.390 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-06-06 23:10:44.395 UTC [26] LOG:  database system was shut down at 2024-06-06 23:09:20 UTC
2024-06-06 23:10:44.402 UTC [1] LOG:  database system is ready to accept connections
2024-06-06 23:23:44.771 UTC [735] ERROR:  could not obtain lock on row in relation "sentry_controloutbox"
2024-06-06 23:23:44.771 UTC [735] STATEMENT:  SELECT "sentry_controloutbox"."id", "sentry_controloutbox"."shard_scope", "sentry_controloutbox"."shard_identifier", "sentry_controloutbox"."category", "sentry_controloutbox"."object_identifier", "sentry_controloutbox"."payload", "sentry_controloutbox"."scheduled_from", "sentry_controloutbox"."scheduled_for", "sentry_controloutbox"."date_added", "sentry_controloutbox"."region_name" FROM "sentry_controloutbox" WHERE ("sentry_controloutbox"."region_name" = '--monolith--' AND "sentry_controloutbox"."shard_identifier" = 1 AND "sentry_controloutbox"."shard_scope" = 1) ORDER BY "sentry_controloutbox"."id" ASC LIMIT 1 FOR UPDATE NOWAIT

2024-06-06 23:39:52.378 UTC [1984] ERROR:  duplicate key value violates unique constraint "sentry_featureadoption_organization_id_feature_id_8ca58f61_uniq"
2024-06-06 23:39:52.378 UTC [1984] DETAIL:  Key (organization_id, feature_id)=(1, 48) already exists.
2024-06-06 23:39:52.378 UTC [1984] STATEMENT:  INSERT INTO "sentry_featureadoption" ("organization_id", "feature_id", "date_completed", "complete", "applicable", "data") VALUES (1, 48, '2024-06-06T23:39:52.346083+00:00'::timestamptz, true, true, '{}'), (1, 2, '2024-06-06T23:39:52.346644+00:00'::timestamptz, true, true, '{}'), (1, 43, '2024-06-06T23:39:52.346717+00:00'::timestamptz, true, true, '{}'), (1, 44, '2024-06-06T23:39:52.346757+00:00'::timestamptz, true, true, '{}') RETURNING "sentry_featureadoption"."id"
2024-06-06 23:39:52.378 UTC [1986] ERROR:  duplicate key value violates unique constraint "sentry_featureadoption_organization_id_feature_id_8ca58f61_uniq"
2024-06-06 23:39:52.378 UTC [1986] DETAIL:  Key (organization_id, feature_id)=(1, 48) already exists.
2024-06-06 23:39:52.378 UTC [1986] STATEMENT:  INSERT INTO "sentry_featureadoption" ("organization_id", "feature_id", "date_completed", "complete", "applicable", "data") VALUES (1, 48, '2024-06-06T23:39:52.354850+00:00'::timestamptz, true, true, '{}'), (1, 2, '2024-06-06T23:39:52.354990+00:00'::timestamptz, true, true, '{}'), (1, 43, '2024-06-06T23:39:52.355049+00:00'::timestamptz, true, true, '{}'), (1, 44, '2024-06-06T23:39:52.355084+00:00'::timestamptz, true, true, '{}') RETURNING "sentry_featureadoption"."id"
2024-06-06 23:39:52.391 UTC [1986] ERROR:  duplicate key value violates unique constraint "sentry_organizationonboa_organization_id_task_e08c2f3d_uniq"
2024-06-06 23:39:52.391 UTC [1986] DETAIL:  Key (organization_id, task)=(1, 5) already exists.
2024-06-06 23:39:52.391 UTC [1986] STATEMENT:  INSERT INTO "sentry_organizationonboardingtask" ("organization_id", "user_id", "status", "completion_seen", "date_completed", "project_id", "data", "task") VALUES (1, NULL, 1, NULL, '2024-06-06T23:39:52.384405+00:00'::timestamptz, 2, '{}', 5) RETURNING "sentry_organizationonboardingtask"."id"
2024-06-06 23:39:52.393 UTC [1984] ERROR:  duplicate key value violates unique constraint "sentry_organizationonboa_organization_id_task_e08c2f3d_uniq"
2024-06-06 23:39:52.393 UTC [1984] DETAIL:  Key (organization_id, task)=(1, 5) already exists.
2024-06-06 23:39:52.393 UTC [1984] STATEMENT:  INSERT INTO "sentry_organizationonboardingtask" ("organization_id", "user_id", "status", "completion_seen", "date_completed", "project_id", "data", "task") VALUES (1, NULL, 1, NULL, '2024-06-06T23:39:52.387838+00:00'::timestamptz, 2, '{}', 5) RETURNING "sentry_organizationonboardingtask"."id"
```
