### ISSUE TITLE
Sentry 23.3.1 Jira Integration Failing 

### ISSUE THREAD

**Issue by cah-michel-bitar** [getsentry/self-hosted#3143]
### Self-Hosted Version

23.3.1

### CPU Architecture

x86_64

### Docker Version

20.10.18

### Docker Compose Version

1.29.2

### Steps to Reproduce

After an upgrade all the way from 21.8.0 where Jira integration was functioning normally to 23.3.1, Jira Cloud integration stopped working.

We tried reconfiguring everything multiple times and the integration was still failing.

### Expected Result

We expect to be able to create Jira tickets through Sentry

### Actual Result

It is actually failing with the following error:
![image](https://github.com/getsentry/self-hosted/assets/167771263/44784209-479c-4eac-b8b6-e5e4dba953d5)

And the only indicative log I was able to find was the following:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 188, in handle_exception
    response = super().handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 305, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/api/endpoints/group_integration_details.py", line 116, in get
    config = installation.get_create_issue_config(
  File "/usr/local/lib/python3.8/site-packages/sentry/integrations/jira_server/integration.py", line 721, in get_create_issue_config
    (choice["id"], choice["name"]) for choice in issue_type_choices["values"]
KeyError: 'values'
```

**Comment by azaslavsky** [comment]
Is there any reason you are not upgrading all the way to the latest release? The one you upgraded to is over a year old, and the offending line of code has already been removed, so upgrading further could resolve the issue.

**Comment by cah-michel-bitar** [comment]
@azaslavsky The upgrade is quite complicated in our setup and not really straightforward. It could take us some time.
Are you confirming however that this is indeed an issue within the code that cannot be fixed without an upgrade?

**Comment by hubertdeng123** [comment]
This may be an issue that has been ongoing actually. I'm going to transfer this over to sentry and see what they have to say 

https://github.com/getsentry/self-hosted/issues/2153
