### ISSUE TITLE
When using GitLab as a single sign-on solution, an error message is displayed on the page.

### ISSUE THREAD

**Issue by CoderX-Aaron** [getsentry/self-hosted#3192]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

I'm currently using the sentry-auth-gitlab-v2 plugin to implement single sign-on (SSO) functionality with Sentry. However,After completing the authorization on GitLab and returning to the Sentry page to log in, the page displays the following error message：
```Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

If you're daring, you may want to try the following:

Give it a few seconds and reload the page.
If all else fails, [contact us](https://github.com/getsentry/sentry/issues/new/choose) with more details.```
The current URL displayed on the Sentry page is "http://10.19.40.239:9000/auth/sso/?code=2861efe80576a1dcd592f1ceeda36576fb41f5029208163b23c093033faa82d1&state=0a1a2034f4a7d2274a6b002548e6a16b22e9053d12924a9b7bff802f227fd12f".

### Expected Result

using the sentry-auth-gitlab-v2 plugin to implement single sign-on (SSO) functionality with Sentry

### Actual Result

```Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

If you're daring, you may want to try the following:

Give it a few seconds and reload the page.
If all else fails, [contact us](https://github.com/getsentry/sentry/issues/new/choose) with more details.
```

error log：
```
02:20:27 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.24.0.53' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.01817774772644043 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
02:20:30 [INFO] sentry.superuser: superuser.request (url='http://10.19.40.239/auth/sso/?code=2861efe80576a1dcd592f1ceeda36576fb41f5029208163b23c093033faa82d1&state=0a1a2034f4a7d2274a6b002548e6a16b22e9053d12924a9b7bff802f227fd12f' method='GET' ip_address='10.2.129.112' user_id=1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/../sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/silo/base.py", line 146, in override
    return original_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/web/frontend/base.py", line 407, in dispatch
    return self.handle(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/web/frontend/auth_provider_login.py", line 28, in handle
    return helper.current_step()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/pipeline/base.py", line 188, in current_step
    return self.dispatch_to(step)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/auth/helper.py", line 756, in dispatch_to
    return step.dispatch(request=self.request, helper=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/web/frontend/base.py", line 407, in dispatch
    return self.handle(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/auth_gitlab/views.py", line 8, in handle
    user = client.get_user()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/auth_gitlab/client.py", line 41, in get_user
    return self._request("/user")
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/auth_gitlab/client.py", line 38, in _request
    return json.loads(req.content)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/utils/json.py", line 142, in loads
    return _default_decoder.decode(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/../simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/../simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
02:20:30 [ERROR] django.request: Internal Server Error: /auth/sso/ (status_code=500 request=<WSGIRequest: GET '/auth/sso/?code=2861efe80576a1dcd592f1ceeda36576fb41f5029208163b23c093033faa82d1&state=0a1a2034f4a7d2274a6b002548e6a16b22e9053d12924a9b7bff802f227fd12f'>)
```

### Product Area

Sign In

### Version

24.4.1

**Comment by hubertdeng123** [comment]
sentry-auth-gitlab-v2 is not something that we officially own, looks like? Is this what you're referring to?
https://pypi.org/project/sentry-auth-gitlab-v2/

If so, you may want to bring this up with the owners/maintainers of the project
