### ISSUE TITLE
install/set-up-and-migrate-database.sh:source:13 error

### ISSUE THREAD

**Issue by ripesensor** [getsentry/self-hosted#3202]
### Self-Hosted Version

24.6.0

### CPU Architecture

x86_64

### Docker Version

27.0.3

### Docker Compose Version

2.28.1

### Steps to Reproduce

When running `./install.sh` on an RHEL9 host I receive an error:
```
-> ./install.sh:main:38
--> install/set-up-and-migrate-database.sh:source:13
```

### Expected Result

Successful install. With the exact same config and version I can get the install to pass when using an Ubuntu 20.04 image, but cannot get the same to install on an RHEL9 image. 

### Actual Result

```
Traceback (most recent call last):
  File "/.venv/bin/sentry", line 4, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File "/usr/src/sentry/src/sentry/runner/main.py", line 148, in main
    func(**kwargs)
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/runner/main.py", line 97, in inner
    ctx.forward(django)
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 804, in forward
    return __self.invoke(__cmd, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/runner/decorators.py", line 34, in inner
    configure()
  File "/usr/src/sentry/src/sentry/runner/__init__.py", line 33, in configure
    _configure(ctx, py, yaml, skip_service_validation)
  File "/usr/src/sentry/src/sentry/runner/settings.py", line 121, in configure
    initialize_app(
  File "/usr/src/sentry/src/sentry/runner/initializer.py", line 366, in initialize_app
    django.setup()
  File "/.venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/.venv/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/.venv/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/sentry/src/sentry/plugins/sentry_interface_types/models.py", line 2, in <module>
    from sentry.plugins.bases.tag import TagPlugin
  File "/usr/src/sentry/src/sentry/plugins/bases/__init__.py", line 1, in <module>
    from .issue import IssueTrackingPlugin  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/plugins/bases/issue.py", line 10, in <module>
    from sentry.plugins.base.v1 import Plugin
  File "/usr/src/sentry/src/sentry/plugins/base/__init__.py", line 1, in <module>
    from .binding_manager import BindingManager
  File "/usr/src/sentry/src/sentry/plugins/base/binding_manager.py", line 5, in <module>
    from sentry.plugins.providers import IntegrationRepositoryProvider, RepositoryProvider
  File "/usr/src/sentry/src/sentry/plugins/providers/__init__.py", line 7, in <module>
    from .base import ProviderMixin
  File "/usr/src/sentry/src/sentry/plugins/providers/base.py", line 9, in <module>
    from sentry.services.hybrid_cloud.integration import integration_service
  File "/usr/src/sentry/src/sentry/services/hybrid_cloud/integration/__init__.py", line 1, in <module>
    from .model import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/services/hybrid_cloud/integration/model.py", line 10, in <module>
    from sentry.integrations.base import (
  File "/usr/src/sentry/src/sentry/integrations/base.py", line 18, in <module>
    from sentry.integrations.notify_disable import notify_disable
  File "/usr/src/sentry/src/sentry/integrations/notify_disable.py", line 4, in <module>
    from sentry.utils.email import MessageBuilder
  File "/usr/src/sentry/src/sentry/utils/email/__init__.py", line 25, in <module>
    from .address import email_to_group_id, group_id_to_email, parse_email, parse_user_name
  File "/usr/src/sentry/src/sentry/utils/email/address.py", line 19, in <module>
    signer = _CaseInsensitiveSigner()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/email/signer.py", line 26, in __init__
    super().__init__(*args, **kwargs)
  File "/.venv/lib/python3.11/site-packages/django/core/signing.py", line 193, in __init__
    self.key = key or settings.SECRET_KEY
                      ^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Error in install/set-up-and-migrate-database.sh:13.
'$dcr web shell -c "
from django.db import connection

with connection.cursor() as cursor:
  cursor.execute('ALTER TABLE IF EXISTS sentry_groupedmessage DROP CONSTRAINT IF EXISTS sentry_groupedmessage_project_id_id_515aaa7e_uniq;')
  cursor.execute('DROP INDEX IF EXISTS sentry_groupedmessage_project_id_id_515aaa7e_uniq;')
"' exited with status 1
-> ./install.sh:main:38
--> install/set-up-and-migrate-database.sh:source:13

Cleaning up...
```

**Comment by dericdesta** [comment]
Thanks, this also fixed it for me. Just for future reference: I use Doppler for SecOps and `doppler secrets substitute --output config.yml config.yml` produces a file with 600 file permissions. Anyways, thanks again for the fix.
