### ISSUE TITLE
Alert not working

### ISSUE THREAD

**Issue by xuweixi10** [getsentry/self-hosted#3219]
### Self-Hosted Version

24.7.0

### CPU Architecture

x86_64

### Docker Version

27.0.3

### Docker Compose Version

2.28.1

### Steps to Reproduce

1. select a transaction and create alert.
2. it's show status is ok, but in fact should trigger an alert

![Image](https://github.com/user-attachments/assets/e715b243-e647-4d31-8ee0-6fbd75629105)

![Image](https://github.com/user-attachments/assets/0ab3b078-c113-4d46-90c9-3c2fb875de61)

### Expected Result

trigger an alert

### Actual Result

nothing happned

**Comment by hubertdeng123** [comment]
Are there any logs in your web container that may be showing errors occurring? Otherwise, I wonder if there might be some kafka offset lag going on here. Can you try triggering another alert to see if this goes through?

**Comment by xuweixi11** [comment]
i get warning
```
Traceback (most recent call last):
  File "/usr/src/sentry/src/sentry/snuba/referrer.py", line 914, in validate_referrer
    raise Exception(error_message)
Exception: referrer api.metrics.series is not part of Referrer Enum
09:55:47 [WARNING] sentry.snuba.referrer: referrer api.metrics.series is not part of Referrer Enum
```

**Comment by xuweixi11** [comment]
i aslo get error in snuba
```
2024-07-25 16:15:55,933 New partitions assigned: {Partition(topic=Topic(name='snuba-metrics-commit-log'), index=0): 37, Partition(topic=Topic(name='snuba-metrics-commit-log'), index=1): 13673, Partition(topic=Topic(name='snuba-metrics-commit-log'), index=2): 27867, Partition(topic=Topic(name='snuba-metrics-commit-log'), index=3): 14012, Partition(topic=Topic(name='snuba-metrics-commit-log'), index=4): 6, Partition(topic=Topic(name='snuba-metrics-commit-log'), index=5): 13909, Partition(topic=Topic(name='snuba-metrics-commit-log'), index=6): 0, Partition(topic=Topic(name='snuba-metrics-commit-log'), index=7): 13762, Partition(topic=Topic(name='snuba-metrics-commit-log'), index=8): 100997, Partition(topic=Topic(name='snuba-metrics-commit-log'), index=9): 13795, Partition(topic=Topic(name='snuba-metrics-commit-log'), index=10): 13791, Partition(topic=Topic(name='snuba-metrics-commit-log'), index=11): 13805}
2024-07-25 16:15:55,933 Initialized processing strategy: <snuba.subscriptions.scheduler_processing_strategy.TickBuffer object at 0x7f2702488e50>
2024-07-25 16:16:03,405 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 322, in run
    self._run_once()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 410, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 275, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
                                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 2
2024-07-25 16:16:03,409 Terminating <snuba.subscriptions.scheduler_processing_strategy.TickBuffer object at 0x7f2702488e50>...
2024-07-25 16:16:03,409 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f2702248410>...
2024-07-25 16:16:03,410 Partitions to revoke: [Partition(topic=Topic(name='snuba-metrics-commit-log'), index=0), Partition(topic=Topic(name='snuba-metrics-commit-log'), index=1), Partition(topic=Topic(name='snuba-metrics-commit-log'), index=2), Partition(topic=Topic(name='snuba-metrics-commit-log'), index=3), Partition(topic=Topic(name='snuba-metrics-commit-log'), index=4), Partition(topic=Topic(name='snuba-metrics-commit-log'), index=5), Partition(topic=Topic(name='snuba-metrics-commit-log'), index=6), Partition(topic=Topic(name='snuba-metrics-commit-log'), index=7), Partition(topic=Topic(name='snuba-metrics-commit-log'), index=8), Partition(topic=Topic(name='snuba-metrics-commit-log'), index=9), Partition(topic=Topic(name='snuba-metrics-commit-log'), index=10), Partition(topic=Topic(name='snuba-metrics-commit-log'), index=11)]
2024-07-25 16:16:03,410 Partition revocation complete.
2024-07-25 16:16:03,413 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 322, in run
    self._run_once()
  File "/usr/local/lib/python3.11/site-packages/arroyo/processing/processor.py", line 410, in _run_once
    self.__processing_strategy.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 275, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
                                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 2
```

**Comment by xuweixi11** [comment]
after i fix snuba error, still no alert trigger

**Comment by xuweixi11** [comment]
after i fix Exception: referrer api.metrics.series is not part of Referrer Enum, still no alert trigger

**Comment by IanWoodard** [comment]
Could you provide some more context? What do your logs look like for Snuba?

**Comment by xuweixi11** [comment]
i think Snuba is ok
after i check the database find the table sentry_alertruleactivationcondition is empty, it's correct ?

**Comment by xuweixi10** [comment]
after i excute `sentry queues list` show queues count is zero, it's correct

**Comment by xuweixi10** [comment]
> Are there any logs in your web container that may be showing errors occurring? Otherwise, I wonder if there might be some kafka offset lag going on here. Can you try triggering another alert to see if this goes through?

i think so but there are too many topics and consumers, i check some maybe about metrics
Topic: metrics-subscription-results no producer no consumer
Topic: generic-metrics-subscription-results: no producer no consumer traffic but have consumer count?
![Image](https://github.com/user-attachments/assets/5e301779-8928-45f2-b368-7733e39e7857)

i also find the snuba-generic-metrics have too many messges is this normal?
![Image](https://github.com/user-attachments/assets/6cd55d57-0c51-4b3e-b0d5-7cc0852c18d9)

**Comment by xuweixi10** [comment]
after i check the alert code in sentry, maybe the problem is the topic metrics-subscription-results never have a message, it's produce from snuba
`snuba rust-consumer --storage metrics_raw --consumer-group snuba-metrics-consumers --auto-offset-reset=latest --max-batch-time-ms 750 --no-strict-offset-reset`
maybe i need start more sunba shell?

**Comment by xuweixi10** [comment]
after i check the code , i find in scheduler_consumer.py __synchronization_timestamp use received_p99 but the topic snuba-transactions-commit-log only have orig_message_ts value for example `{"offset":30338,"orig_message_ts":1722783407.593,"received_p99":null}` after i change the config it works

![Image](https://github.com/user-attachments/assets/b631b54c-cd0d-499b-9c69-1c8dcfbdbed1)
 so i'm confused why received_p99 is null

**Comment by hubertdeng123** [comment]
@getsentry/owners-snuba Do you have more context on why this is happening?

**Comment by nomarek** [comment]
I ran into the same problem when defining alerts. There are no errors in the snuba container logs and Kafka events are being processed correctly. Do you have any idea what could be causing the problem and how to fix it? Interestingly, the alert rules defined on "Number of Errors" seem to work fine for me, but I am not able to use "Transaction duration" and "Apdex" alerts.

**Comment by Kitsunees** [comment]
@nomarek Happened the same to us. Did you try to replace all occurrences of `rust-consumer` in **docker-compose.yml** file to just `consumer`. Then re-run **./install.sh** script.

You can use this as temporal fix to get alerts. We found this on another [github issue](https://github.com/getsentry/self-hosted/issues/2931#issuecomment-2040854990) and it worked.

**Comment by nomarek** [comment]
Thank you! This workaround worked.
