### ISSUE TITLE
sentry-snuba-subscription-consumer-events&sentry-snuba-subscription-consumer-transactions always restart because I lost clickhouse data

### ISSUE THREAD

**Issue by Arensi9801** [getsentry/self-hosted#3236]
### Body

Sentry Version(helm chart):22.11.0

**At first I lost all clickhouse data, then I re-initialized snuba through this command:**
` snuba bootstrap --no-migrate --force `
**And run this command：**
`snuba migrations migrate --force`

Then my clickhouse looks normal, but snuba-subscription-consumer-events & snuba-subscription-consumer-transactions always restart with the following error message For sentry-snuba-subscription-consumer-events：
`2024-07-31 08:13:35,949 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 190, Partition(topic=Topic(name='snuba-commit-log'), index=1): 0, Partition(topic=Topic(name='snuba-commit-log'), index=2): 0}
2024-07-31 08:13:46,772 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 227, in _run_once
    self.__processing_strategy.submit(self.__message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 255, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 1
2024-07-31 08:13:46,773 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f5e09ad51f0>...
2024-07-31 08:13:46,773 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0), Partition(topic=Topic(name='snuba-commit-log'), index=1), Partition(topic=Topic(name='snuba-commit-log'), index=2)]
2024-07-31 08:13:46,776 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 227, in _run_once
    self.__processing_strategy.submit(self.__message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 255, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 1`

 **For sentry-snuba-subscription-consumer-transactions：**
`2024-07-31 08:15:31,919 Snuba initialization took 1.8651850149035454s
2024-07-31 08:15:31,946 New partitions assigned: {Partition(topic=Topic(name='snuba-transactions-commit-log'), index=0): 0, Partition(topic=Topic(name='snuba-transactions-commit-log'), index=1): 0, Partition(topic=Topic(name='snuba-transactions-commit-log'), index=2): 0}
2024-07-31 08:15:31,984 Caught exception, shutting down...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 227, in _run_once
    self.__processing_strategy.submit(self.__message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 255, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 1
2024-07-31 08:15:31,985 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f99c0a961f0>...
2024-07-31 08:15:31,986 Partitions revoked: [Partition(topic=Topic(name='snuba-transactions-commit-log'), index=0), Partition(topic=Topic(name='snuba-transactions-commit-log'), index=1), Partition(topic=Topic(name='snuba-transactions-commit-log'), index=2)]
2024-07-31 08:15:31,988 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 227, in _run_once
    self.__processing_strategy.submit(self.__message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 255, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 1`
**What can I do to make it work properly?**

**Comment by Arensi9801** [comment]
I have tried recreating the snuba-transaction-commit-log and snuba-commit-log topics, but it doesn't seem to work.

**Comment by xuweixi10** [comment]
maybe you should check kafka topic partitions

![Image](https://github.com/user-attachments/assets/8681ad12-00fb-4b16-a67c-4dd4edbbad7e)

**Comment by Arensi9801** [comment]
My config for kafka topic partitions just like this:
    TOPIC_PARTITION_COUNTS = {
        "snuba-transactions-commit-log": 3,
        "snuba-sessions-commit-log": 3,
        "snuba-commit-log": 3,
      }

**Comment by Arensi9801** [comment]
> maybe you should check kafka topic partitions
> 
> ![Image](https://github.com/user-attachments/assets/8681ad12-00fb-4b16-a67c-4dd4edbbad7e)

My config for kafka topic partitions just like this:
```
TOPIC_PARTITION_COUNTS = {
"snuba-transactions-commit-log": 3,
"snuba-sessions-commit-log": 3,
"snuba-commit-log": 3,
}
```

**Comment by xuweixi10** [comment]
In fact, you should set more topic partitions count in config. try add transactions, snuba-metrics, events partitions count in TOPIC_PARTITION_COUNTS

**Comment by Arensi9801** [comment]
> events

I increased the number of partitions for these topics to 12 as you suggested, but it didn't seem to work, so I kept restarting
2024-08-02 08:36:56,824 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f7a06d81430>...
2024-08-02 08:36:56,824 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0), Partition(topic=Topic(name='snuba-commit-log'), index=1), Partition(topic=Topic(name='snuba-commit-log'), index=2)]
2024-08-02 08:36:56,825 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 227, in _run_once
    self.__processing_strategy.submit(self.__message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 255, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 1


this is my config for TOPIC partions:
TOPIC_PARTITION_COUNTS = {
    "snuba-transactions-commit-log": 3,
    "snuba-sessions-commit-log": 3,
    "snuba-commit-log": 3,
    "transactions": 12,
    "snuba-metrics": 12,
    "events": 12,
  }

**Comment by Arensi9801** [comment]
> events

I increased the number of partitions for these topics to 12 as you suggested, but it didn't seem to work, so I kept restarting
2024-08-02 08:36:56,824 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f7a06d81430>...
2024-08-02 08:36:56,824 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0), Partition(topic=Topic(name='snuba-commit-log'), index=1), Partition(topic=Topic(name='snuba-commit-log'), index=2)]
2024-08-02 08:36:56,825 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 153, in subscriptions_scheduler_executor
    processor.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 180, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 227, in _run_once
    self.__processing_strategy.submit(self.__message)
  File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
    self.__next_step.submit(message)
  File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 255, in submit
    tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
KeyError: 1


this is my config for TOPIC partions:
TOPIC_PARTITION_COUNTS = {
    "snuba-transactions-commit-log": 3,
    "snuba-sessions-commit-log": 3,
    "snuba-commit-log": 3,
    "transactions": 12,
    "snuba-metrics": 12,
    "events": 12,
  }

**Comment by xuweixi10** [comment]
sounds like it's a datetime problem, are you run snuba on UTC timezone?

**Comment by hubertdeng123** [comment]
Looks like you're using helm charts version of self-hosted, which is unsupported here. Closing this as this is not an issue with the docker compose version of self-hosted
