### ISSUE TITLE
User feedback page sometimes crashes

### ISSUE THREAD

**Issue by TheDevMinerTV** [getsentry/self-hosted#3240]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Make your browser window bigger than the mobile breakpoint (it won't work otherwise because the right side doesn't load)
2. Go to the user feedback page using the sidebar (reloading doesn't trigger the error)

### Expected Result

The page doesn't crash

### Actual Result

Stack trace from console:
```
TypeError: Cannot read properties of undefined (reading 'filter')
    at Xe (feedbackActivitySection.tsx:102:50)
    at eu (react-dom.production.min.js:167:137)
    at Ya (react-dom.production.min.js:290:337)
    at Rd (react-dom.production.min.js:280:389)
    at Pf (react-dom.production.min.js:280:320)
    at Mo (react-dom.production.min.js:280:180)
    at Ls (react-dom.production.min.js:271:88)
    at An (react-dom.production.min.js:273:300)
    at ti (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273Caused by: 
    at Xe (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_components_events_interfaces_crashContent_stackTrace_rawContent_tsx-app_views_feedback_fe-c90b4c.8f6e51467549fbf3c98a.js:14:13816)
    at section
    at https://bugs.devminer.xyz/_static/dist/sentry/chunks/vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--a96064.a0b8260c403fb42514bb.js:1:14521
    at oe (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_components_events_interfaces_crashContent_stackTrace_rawContent_tsx-app_views_feedback_fe-c90b4c.8f6e51467549fbf3c98a.js:15:12062)
    at div
    at https://bugs.devminer.xyz/_static/dist/sentry/chunks/vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--a96064.a0b8260c403fb42514bb.js:1:14521
    at jt (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_components_events_interfaces_crashContent_stackTrace_rawContent_tsx-app_views_feedback_fe-c90b4c.8f6e51467549fbf3c98a.js:15:28105)
    at Mn (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_components_events_interfaces_crashContent_stackTrace_rawContent_tsx-app_views_feedback_fe-c90b4c.8f6e51467549fbf3c98a.js:15:32837)
    at div
    at https://bugs.devminer.xyz/_static/dist/sentry/chunks/vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--a96064.a0b8260c403fb42514bb.js:1:14521
    at div
    at https://bugs.devminer.xyz/_static/dist/sentry/chunks/vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--a96064.a0b8260c403fb42514bb.js:1:14521
    at g (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:21:13935)
    at d (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:134:1801)
    at ve (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_components_events_interfaces_crashContent_stackTrace_rawContent_tsx-app_views_feedback_fe-c90b4c.8f6e51467549fbf3c98a.js:14:11633)
    at div
    at https://bugs.devminer.xyz/_static/dist/sentry/chunks/vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--a96064.a0b8260c403fb42514bb.js:1:14521
    at g (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_utils_withProject_tsx-app_views_settings_components_text_textBlock_tsx.218254a14e9375a2be76.js:1:16575)
    at _t (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_components_events_interfaces_crashContent_stackTrace_rawContent_tsx-app_views_feedback_fe-c90b4c.8f6e51467549fbf3c98a.js:15:62932)
    at Suspense
    at m (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:32:26583)
    at S (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:32:26136)
    at c (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:1:63377)
    at O
    at se (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:82:97356)
    at F (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_components_acl_feature_tsx-app_components_acl_featureDisabled_tsx.a56c6543df2a6b4783bb.js:1:1011)
    at c (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_components_acl_feature_tsx-app_components_acl_featureDisabled_tsx.a56c6543df2a6b4783bb.js:6:2388)
    at u (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_utils_withProject_tsx-app_views_settings_components_text_textBlock_tsx.218254a14e9375a2be76.js:1:23083)
    at E (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_utils_withProject_tsx-app_views_settings_components_text_textBlock_tsx.218254a14e9375a2be76.js:1:22505)
    at s (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_views_feedback_index_tsx.c4941c0b5bf752554233.js:1:533)
    at Suspense
    at m (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:32:26583)
    at S (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:32:26136)
    at c (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:1:63377)
    at O
    at https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:1:64567
    at g (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:21:13935)
    at Ii (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:1:268497)
    at div
    at m (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:311:33329)
    at g (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_utils_withProject_tsx-app_views_settings_components_text_textBlock_tsx.218254a14e9375a2be76.js:1:16575)
    at Pi (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:1:268960)
    at c (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:1:63377)
    at g (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:21:13935)
    at div
    at https://bugs.devminer.xyz/_static/dist/sentry/chunks/vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--a96064.a0b8260c403fb42514bb.js:1:14521
    at R (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_components_charts_barChart_tsx-app_components_lazyRender_tsx-app_components_timeRangeSele-2ad577.762d5c56b5280bfcb9a2.js:20:27506)
    at b (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:32:9187)
    at b (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_components_dropdownMenu_index_tsx-app_components_feedback_widget_useFeedbackWidget_tsx.db04a38f16395dfb6ad3.js:1:12524)
    at I (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:311:34975)
    at pt (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:1:73641)
    at c (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:1:63377)
    at w (https://bugs.devminer.xyz/_static/dist/sentry/chunks/vendors-node_modules_emotion_styled_base_dist_emotion-styled-base_browser_esm_js-node_modules-6cc63f.4f25a09fdb99c37ff4ce.js:12:29264)
    at M (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_actionCreators_discoverSavedQueries_tsx-app_components_charts_utils_tsx-app_components_gr-9f2511.4abb42669dd9c1993141.js:171:192456)
    at w (https://bugs.devminer.xyz/_static/dist/sentry/chunks/vendors-node_modules_emotion_styled_base_dist_emotion-styled-base_browser_esm_js-node_modules-6cc63f.4f25a09fdb99c37ff4ce.js:12:29264)
    at u (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_bootstrap_initializeApp_tsx-app_components_charts_components_tooltip_tsx-app_components_e-f44ccf.010f1956a29cca8a823e.js:130:1703)
    at q (https://bugs.devminer.xyz/_static/dist/sentry/chunks/vendors-node_modules_sentry_release-parser_lib_parser_js-node_modules_echarts_lib_component_m-309b6a.027ddf8b332990e3a089.js:541:28294)
    at j (https://bugs.devminer.xyz/_static/dist/sentry/chunks/vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--a96064.a0b8260c403fb42514bb.js:1:14927)
    at g (https://bugs.devminer.xyz/_static/dist/sentry/chunks/app_actionCreators_redirectToProject_tsx-app_actionCreators_sudoModal_tsx-app_bootstrap_commo-59afc0.75099e6db71d9400c480.js:121:11177)
    at Main
```
The stacktrace points to this line in `master`: https://github.com/getsentry/sentry/blob/77666108d432bec4c3c5ff951ce4f9b75f87afac/static/app/components/feedback/feedbackItem/feedbackActivitySection.tsx#L106

The JS debugger shows that the value trying to get filtered sometimes just has a wrong value inside of it:
![Chrome debugger](https://github.com/user-attachments/assets/f10d069a-2be1-47bf-84e0-6c95bfb8a868)

Usually `feedbackItem` would contain something like this:
![Image](https://github.com/user-attachments/assets/c093a52c-a6de-404e-8472-d337b1bf633b)

### Product Area

User Feedback

### Version

24.7.1

**Comment by asottile-sentry** [comment]
@getsentry/product-owners-user-feedback

**Comment by TheDevMinerTV** [comment]
I don't think this is related to selfhosted :/

**Comment by bruno-garcia** [comment]
There was a PR with changes to enable it here:
* https://github.com/getsentry/self-hosted/pull/3193

But I see that [you engaged there too](https://github.com/getsentry/self-hosted/pull/3193#pullrequestreview-2212594764) so I assume nothing done there that can help here.

@ryan953 @aliu39 any idea what could be going on?

> The stacktrace points to this line in master: https://github.com/getsentry/sentry/blob/77666108d432bec4c3c5ff951ce4f9b75f87afac/static/app/components/feedback/feedbackItem/feedbackActivitySection.tsx#L106

This is the latest code we have live on SaaS

**Comment by aliu39** [comment]
Related: https://github.com/getsentry/sentry/pull/74218. See the changes in FeedbackItemLoader and FeedbackItem

**Comment by bruno-garcia** [comment]
@aliu39 I don't follow. That PR was merged 3 weeks ago, so if folks run `master` on self hosted, the issue should be resolved?

**Comment by bruno-garcia** [comment]
While there's some context on: https://github.com/getsentry/sentry/pull/74218 the issue is related to data migration from User Feedbacks ingested before updating Sentry. And the new UI built to load user feedback.

Do you experience this issue with new feedbacks? Say, if you filter by last 14 days?

**Comment by TheDevMinerTV** [comment]
> Do you experience this issue with new feedbacks? Say, if you filter by last 14 days?

yep

> so if folks run master on self hosted, the issue should be resolved?

I guess I can try snapshotting and upgrading to nightly when I have time.

**Comment by bruno-garcia** [comment]
> I guess I can try snapshotting and upgrading to nightly when I have time.

Thanks!
Please let us know how it goes

**Comment by TheDevMinerTV** [comment]
Seems to be fixed by https://github.com/getsentry/sentry/issues/67412
