### ISSUE TITLE
Issue upgrading from v23.3.1-1 to v24.7.1-2

### ISSUE THREAD

**Issue by swade1987** [getsentry/self-hosted#3360]
### Self-Hosted Version

Sentry 23.3.1 0787c74

### CPU Architecture

x86_64

### Docker Version

Kubernetes 1.30

### Docker Compose Version

N/A

### Steps to Reproduce

1. Standup Postgres using `bitnami/postgresql:16.4.0-debian-12-r11`
2. Migrate data from the existing RDS cluster to the new Postgres instance using `pgdump`
3. Deploy a new instance of sentry using https://github.com/sentry-kubernetes/charts/tree/sentry-v25.9.0 (version 25.9.0)

Note: Version v25.9.0 of the helm chart deploys `v24.7.1-2` of Sentry.

### Expected Result

The `sentry-db-init` script should run successfully.

### Actual Result

```
Running migrations for default
Operations to perform:
Apply all migrations: auth, contenttypes, feedback, hybridcloud, nodestore, remote_subscriptions, replays, sentry, sessions, sites, social_auth, uptime
Traceback (most recent call last):
File "/.venv/bin/sentry", line 4, in
raise SystemExit(main())
^^^^^^
File "/usr/src/sentry/src/sentry/runner/main.py", line 149, in main
func(**kwargs)
File "/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in call
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/.venv/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
return f(get_current_context(), *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/sentry/src/sentry/runner/decorators.py", line 35, in inner
return ctx.invoke(f, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/sentry/src/sentry/runner/commands/upgrade.py", line 148, in upgrade
_upgrade(
File "/usr/src/sentry/src/sentry/runner/commands/upgrade.py", line 64, in _upgrade
dj_call_command(
File "/.venv/lib/python3.11/site-packages/django/core/management/init.py", line 194, in call_command
return command.execute(*args, **defaults)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
output = self.handle(*args, **options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 107, in wrapper
res = handle_func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/.venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 302, in handle
pre_migrate_apps = pre_migrate_state.apps
^^^^^^^^^^^^^^^^^^^^^^
File "/.venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in get
res = instance.dict[self.name] = self.func(instance)
^^^^^^^^^^^^^^^^^^^
File "/.venv/lib/python3.11/site-packages/django/db/migrations/state.py", line 566, in apps
return StateApps(self.real_apps, self.models)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/.venv/lib/python3.11/site-packages/django/db/migrations/state.py", line 637, in init
raise ValueError("\n".join(error.msg for error in errors))
ValueError: The field social_auth.UserSocialAuth.user was declared with a lazy reference to 'sentry.user', but app 'sentry' isn't installed.
```

**Comment by aldy505** [comment]
We can't really help with the helm chart since that's not a supported workflow. You should re-open the issue at the helm-chart repository instead.
