### ISSUE TITLE
There was an error loading data. --> SSLContext(PROTOCOL_TLS_CLIENT) (web container)

### ISSUE THREAD

**Issue by klemen-df** [getsentry/self-hosted#3364]
### Self-Hosted Version

24.9.0

### CPU Architecture

x86_64

### Docker Version

27.3.1

### Docker Compose Version

2.29.7

### Steps to Reproduce

1. Azure Virtual Machine with a public IP, 80 and 443 open for all
2. Ubuntu 20.04.6 LTS, latest patches
3. Docker Engine - Community, Version:           27.3.1
4. Upgraded 23.12.0 --> 23.12.1 --> 24.8.0 --> 24.9.0
5. nginx as a frontend web proxy, ssl termination (letsencrypt)

### Expected Result

Page should open.

### Actual Result

-  When I login to sentry I get : There was an error loading data.
- When I check the web container, I see:

```
Traceback (most recent call last):
  File "/usr/src/sentry/src/sentry/options/manager.py", line 217, in lookup_key
    return self.registry[key]
18:58:29 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_projects.OrganizationProjectsEndpoint' response=200 user_id='6' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/projects/' caller_ip='178.235.219.23' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.18260645866394043 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
18:58:29 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_teams.OrganizationTeamsEndpoint' response=200 user_id='6' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/teams/' caller_ip='178.235.219.23' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.16320085525512695 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
/usr/src/sentry/src/sentry/dynamic_sampling/tasks/common.py:428: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  Condition(Column("timestamp"), Op.GTE, datetime.utcnow() - self.time_interval),
/usr/src/sentry/src/sentry/dynamic_sampling/tasks/common.py:429: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  Condition(Column("timestamp"), Op.LT, datetime.utcnow()),
Traceback (most recent call last):
  File "/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 398, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8bf84aef60>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 1309, in _snuba_query
    _raw_snql_query(request, headers),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 1370, in _raw_snql_query
    return _snuba_pool.urlopen(
           ^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 487, in increment
    return super().increment(
           ^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=1218): Max retries exceeded with url: /generic_metrics/snql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8bf84aef60>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/sentry/src/sentry/api/serializers/base.py", line 108, in _serialize
    return self.serialize(obj, attrs, user, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/api/serializers/models/organization.py", line 639, in serialize
    org_volume = get_organization_volume(obj.id, timedelta(hours=24))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/dynamic_sampling/tasks/common.py", line 593, in get_organization_volume
    for org_volumes in GetActiveOrgsVolumes(
  File "/usr/src/sentry/src/sentry/dynamic_sampling/tasks/common.py", line 461, in __next__
    data = raw_snql_query(
           ^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 932, in raw_snql_query
    return bulk_snuba_queries(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 951, in bulk_snuba_queries
    return bulk_snuba_queries_with_referrers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 993, in bulk_snuba_queries_with_referrers
    return _apply_cache_and_build_results(snuba_requests, use_cache=use_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 1068, in _apply_cache_and_build_results
    query_results = _bulk_snuba_query([item[1] for item in to_query])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 1114, in _bulk_snuba_query
    _snuba_query(
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 1314, in _snuba_query
    raise SnubaError(err)
sentry.utils.snuba.SnubaError: HTTPConnectionPool(host='127.0.0.1', port=1218): Max retries exceeded with url: /generic_metrics/snql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8bf84aef60>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

```
18:58:44 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_index.OrganizationIndexEndpoint' response=200 user_id='6' is_app='False' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/api/0/organizations/' caller_ip='178.235.219.23' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.04429984092712402 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
Traceback (most recent call last):
  File "/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 398, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8bf82ced20>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 1309, in _snuba_query
    _raw_snql_query(request, headers),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 1370, in _raw_snql_query
    return _snuba_pool.urlopen(
           ^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 487, in increment
    return super().increment(
           ^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=1218): Max retries exceeded with url: /generic_metrics/snql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8bf82ced20>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/sentry/src/sentry/api/serializers/base.py", line 108, in _serialize
    return self.serialize(obj, attrs, user, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/api/serializers/models/organization.py", line 639, in serialize
    org_volume = get_organization_volume(obj.id, timedelta(hours=24))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/dynamic_sampling/tasks/common.py", line 593, in get_organization_volume
    for org_volumes in GetActiveOrgsVolumes(
  File "/usr/src/sentry/src/sentry/dynamic_sampling/tasks/common.py", line 461, in __next__
    data = raw_snql_query(
           ^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 932, in raw_snql_query
    return bulk_snuba_queries(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 951, in bulk_snuba_queries
    return bulk_snuba_queries_with_referrers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 993, in bulk_snuba_queries_with_referrers
    return _apply_cache_and_build_results(snuba_requests, use_cache=use_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 1068, in _apply_cache_and_build_results
    query_results = _bulk_snuba_query([item[1] for item in to_query])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 1114, in _bulk_snuba_query
    _snuba_query(
  File "/usr/src/sentry/src/sentry/utils/snuba.py", line 1314, in _snuba_query
    raise SnubaError(err)
sentry.utils.snuba.SnubaError: HTTPConnectionPool(host='127.0.0.1', port=1218): Max retries exceeded with url: /generic_metrics/snql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8bf82ced20>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Found this in KAFKA

```

[2024-10-04 19:05:49,640] ERROR Encountered metadata publishing fault: Error deleting stray partitions during startup (org.apache.kafka.server.fault.LoggingFaultHandler)
java.lang.RuntimeException: The log dir Log(dir=/var/lib/kafka/data/snuba-dead-letter-metrics-distributions-0, topic=snuba-dead-letter-metrics-distributions, partition=0, highWatermark=0, lastStableOffset=0, logStartOffset=0, logEndOffset=0) does not have a topic ID, which is not allowed when running in KRaft mode.
        at kafka.server.metadata.BrokerMetadataPublisher$.$anonfun$findStrayPartitions$2(BrokerMetadataPublisher.scala:76)
        at scala.Option.getOrElse(Option.scala:201)
        at kafka.server.metadata.BrokerMetadataPublisher$.$anonfun$findStrayPartitions$1(BrokerMetadataPublisher.scala:75)
        at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
        at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
        at scala.collection.mutable.ArrayBuffer.flatMap(ArrayBuffer.scala:43)
        at kafka.server.metadata.BrokerMetadataPublisher$.findStrayPartitions(BrokerMetadataPublisher.scala:73)
        at kafka.server.metadata.BrokerMetadataPublisher.finishInitializingReplicaManager(BrokerMetadataPublisher.scala:353)
        at kafka.server.metadata.BrokerMetadataPublisher.onMetadataUpdate(BrokerMetadataPublisher.scala:246)
        at org.apache.kafka.image.loader.MetadataLoader.initializeNewPublishers(MetadataLoader.java:309)
        at org.apache.kafka.image.loader.MetadataLoader.lambda$scheduleInitializeNewPublishers$0(MetadataLoader.java:266)
        at org.apache.kafka.queue.KafkaEventQueue$EventContext.run(KafkaEventQueue.java:127)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.handleEvents(KafkaEventQueue.java:210)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:181)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Found this in CLICKHOUSE

```
0. Poco::Net::SocketImpl::error(int, String const&) @ 0x0000000015b3dbf2 in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::peerAddress() @ 0x0000000015b40376 in /usr/bin/clickhouse
2. DB::HTTPServerRequest::HTTPServerRequest(std::shared_ptr<DB::IHTTPContext>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x0000000013154417 in /usr/bin/clickhouse
3. DB::HTTPServerConnection::run() @ 0x0000000013152ba4 in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x0000000015b42834 in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015b43a31 in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x0000000015c7a667 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015c7893c in /usr/bin/clickhouse
8. ? @ 0x00007f1844e14609 in ?
9. ? @ 0x00007f1844d39353 in ?
 (version 23.8.11.29.altinitystable (altinity build))
2024.10.04 19:23:14.569966 [ 674 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):
```

**Comment by klemen-df** [comment]
snuba-api looks ok

```
docker logs -f sentry-self-hosted-snuba-api-1
2024-10-04 19:06:05,659 Initializing Snuba...
2024-10-04 19:06:10,897 Snuba initialization took 5.239005207000446s
2024-10-04 19:06:11,515 Initializing Snuba...
2024-10-04 19:06:22,480 Snuba initialization took 10.96676636399934s
*** Starting uWSGI 2.0.23 (64bit) on [Fri Oct  4 19:06:22 2024] ***
compiled with version: 10.2.1 20210130 (Red Hat 10.2.1-11) on 07 November 2023 19:10:56
os: Linux-5.15.0-1073-azure #82~20.04.1-Ubuntu SMP Tue Sep 3 12:27:43 UTC 2024
nodename: 23000ef7a488
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /usr/src/snuba
detected binary path: /usr/local/bin/python
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 0.0.0.0:1218 fd 3
Python version: 3.11.8 (main, Mar 12 2024, 11:52:02) [GCC 12.2.0]
--- Python VM already initialized ---
Python main interpreter initialized at 0x7f596a83d218
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
initialized 38 metrics
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 8, cores: 1)
metrics collector thread started
2024-10-04 19:06:26,708 Initializing Snuba...
WSGI app 0 (mountpoint='') ready in 27 seconds on interpreter 0x7f596a83d218 pid: 8 (default app)
```

**Comment by aldy505** [comment]
```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=1218): Max retries exceeded with url: /generic_metrics/snql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8bf82ced20>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

This error indicates it's trying to call to Snuba but for some reason it uses `127.0.0.1` as the host instead of `snuba`. See this specific line that should be respected: https://github.com/getsentry/self-hosted/blob/8887a82a86153d0c9696463c0525976cf8e3f136/docker-compose.yml#L46

Did you configure it in a different way rather than what's defined in the repository?

**Comment by klemen-df** [comment]
> ```
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=1218): Max retries exceeded with url: /generic_metrics/snql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8bf82ced20>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ```
> 
> This error indicates it's trying to call to Snuba but for some reason it uses `127.0.0.1` as the host instead of `snuba-api`. See this specific line that should be respected:
> 
> [self-hosted/docker-compose.yml](https://github.com/getsentry/self-hosted/blob/8887a82a86153d0c9696463c0525976cf8e3f136/docker-compose.yml#L46)
> 
> Line 46 in [8887a82](/getsentry/self-hosted/commit/8887a82a86153d0c9696463c0525976cf8e3f136)
> 
>  SNUBA: "http://snuba-api:1218" 
> Did you configure it in a different way rather than what's defined in the repository?

hi @aldy505 , sadly no

grep SNUBA docker-compose.yml
    SNUBA: "http://snuba-api:1218"
  image: "$SNUBA_IMAGE"
    SNUBA_SETTINGS: self_hosted
      SENTRY_SNUBA_HOST: "http://snuba-api:1218"

Standard repo for 24.9.0

**Comment by klemen-df** [comment]
uh, I had some issues and I set this in web container - of course it then didn't use variables from sentry_defaults

```
    environment:
      SENTRY_LOG_LEVEL: "DEBUG"
```

Thank you!
